ITK: itk::DefaultConvertPixelTraits< PixelType > Class Template Reference
itk::DefaultConvertPixelTraits< PixelType > Class Template Reference
Group Core » Module ITKCommon
#include <itkDefaultConvertPixelTraits.h>
Public Types
using ComponentType = typename PixelType::ComponentType
Static Public Member Functions
static ComponentType GetNthComponent (int c, const PixelType &pixel)
static unsigned int GetNumberOfComponents ()
static unsigned int GetNumberOfComponents (const PixelType)
static void SetNthComponent (int c, PixelType &pixel, const ComponentType &v)
static ComponentType GetScalarValue (const PixelType &pixel)
Detailed Description
template<typename PixelType>
class itk::DefaultConvertPixelTraits< PixelType >
Traits class used to by ConvertPixels to convert blocks of pixels.
TOutputPixelType is the destination type. The input type is inferred by the templated static function Convert.
This implementation, does a simple assignment operator, so if you are going from from a higher bit representation to a lower bit one (int to char), you may want to specialize and add some sort of transfer function.
Definition at line 41 of file itkDefaultConvertPixelTraits.h.
Member Typedef Documentation
ComponentType
template<typename PixelType > using itk::DefaultConvertPixelTraits< PixelType >::ComponentType = typename PixelType::ComponentType
Determine the pixel data type.
Definition at line 45 of file itkDefaultConvertPixelTraits.h.
Member Function Documentation
GetNthComponent()
template<typename PixelType > static ComponentType itk::DefaultConvertPixelTraits< PixelType >::GetNthComponent (int c, const PixelType & pixel) inline static
Return the nth component of the pixel.
Definition at line 62 of file itkDefaultConvertPixelTraits.h.
Referenced by itk::NthElementPixelAccessor< T, TContainer >::Get(), and itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >::TransformOutputPixel().
GetNumberOfComponents() [1/2]
template<typename PixelType > static unsigned int itk::DefaultConvertPixelTraits< PixelType >::GetNumberOfComponents () inline static
Return the number of components per pixel.
Definition at line 49 of file itkDefaultConvertPixelTraits.h.
GetNumberOfComponents() [2/2]
template<typename PixelType > static unsigned int itk::DefaultConvertPixelTraits< PixelType >::GetNumberOfComponents (const PixelType) inline static
Definition at line 55 of file itkDefaultConvertPixelTraits.h.
GetScalarValue()
template<typename PixelType > static ComponentType itk::DefaultConvertPixelTraits< PixelType >::GetScalarValue (const PixelType & pixel) inline static
Return a single scalar value from this pixel.
Definition at line 76 of file itkDefaultConvertPixelTraits.h.
SetNthComponent()
template<typename PixelType > static void itk::DefaultConvertPixelTraits< PixelType >::SetNthComponent (int c, PixelType & pixel, const ComponentType & v) inline static
Set the nth component of the pixel.
Definition at line 69 of file itkDefaultConvertPixelTraits.h.
Referenced by itk::NthElementPixelAccessor< T, TContainer >::Set(), and itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >::TransformOutputPixel().
The documentation for this class was generated from the following file:
itkDefaultConvertPixelTraits.h