ITK: itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput > Class Template Reference
itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput > Class Template Reference
#include <itkSymmetricEigenAnalysisImageFilter.h>
Public Types
using CalculatorType = SymmetricEigenAnalysis< TInput, TOutput >
using RealValueType = typename TInput::RealValueType
Public Member Functions
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (SymmetricEigenAnalysisFunction)
TOutput operator() (const TInput &x) const
bool operator== (const SymmetricEigenAnalysisFunction &) const
SymmetricEigenAnalysisFunction ()=default
~SymmetricEigenAnalysisFunction ()=default
void SetDimension (unsigned int n)
unsigned int GetDimension () const
void OrderEigenValuesBy (EigenValueOrderEnum order)
void SetOrderEigenValuesBy (EigenValueOrderEnum order)
EigenValueOrderEnum GetOrderEigenValuesBy () const
Private Attributes
CalculatorType m_Calculator
Detailed Description
template<typename TInput, typename TOutput>
class itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >
Definition at line 43 of file itkSymmetricEigenAnalysisImageFilter.h.
Member Typedef Documentation
CalculatorType
template<typename TInput , typename TOutput > using itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::CalculatorType = SymmetricEigenAnalysis<TInput, TOutput>
Definition at line 49 of file itkSymmetricEigenAnalysisImageFilter.h.
RealValueType
template<typename TInput , typename TOutput > using itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::RealValueType = typename TInput::RealValueType
Definition at line 46 of file itkSymmetricEigenAnalysisImageFilter.h.
Constructor & Destructor Documentation
SymmetricEigenAnalysisFunction()
template<typename TInput , typename TOutput > itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::SymmetricEigenAnalysisFunction () default
~SymmetricEigenAnalysisFunction()
template<typename TInput , typename TOutput > itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::~SymmetricEigenAnalysisFunction () default
Member Function Documentation
GetDimension()
template<typename TInput , typename TOutput > unsigned int itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::GetDimension () const inline
Method to explicitly set the dimension of the matrix
Definition at line 74 of file itkSymmetricEigenAnalysisImageFilter.h.
Referenced by itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >::GetDimension().
GetOrderEigenValuesBy()
template<typename TInput , typename TOutput > EigenValueOrderEnum itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::GetOrderEigenValuesBy () const inline
Order eigen values. Default is to OrderByValue: lambda_1 < lambda_2 < ....
Definition at line 112 of file itkSymmetricEigenAnalysisImageFilter.h.
Referenced by itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >::GetOrderEigenValuesBy().
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TInput , typename TOutput > itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (SymmetricEigenAnalysisFunction< TInput, TOutput >)
operator()()
template<typename TInput , typename TOutput > TOutput itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::operator() (const TInput & x) const inline
Definition at line 59 of file itkSymmetricEigenAnalysisImageFilter.h.
operator==()
template<typename TInput , typename TOutput > bool itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::operator== (const SymmetricEigenAnalysisFunction< TInput, TOutput > &) const inline
Definition at line 51 of file itkSymmetricEigenAnalysisImageFilter.h.
OrderEigenValuesBy()
template<typename TInput , typename TOutput > void itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::OrderEigenValuesBy (EigenValueOrderEnum order) inline
Order eigen values. Default is to OrderByValue: lambda_1 < lambda_2 < ....
Definition at line 95 of file itkSymmetricEigenAnalysisImageFilter.h.
Referenced by itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >::OrderEigenValuesBy(), and itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::SetOrderEigenValuesBy().
SetDimension()
template<typename TInput , typename TOutput > void itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::SetDimension (unsigned int n) inline
Method to explicitly set the dimension of the matrix
Definition at line 69 of file itkSymmetricEigenAnalysisImageFilter.h.
Referenced by itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >::SetDimension().
SetOrderEigenValuesBy()
template<typename TInput , typename TOutput > void itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::SetOrderEigenValuesBy (EigenValueOrderEnum order) inline
Order eigen values. Default is to OrderByValue: lambda_1 < lambda_2 < ....
Definition at line 107 of file itkSymmetricEigenAnalysisImageFilter.h.
Member Data Documentation
m_Calculator
template<typename TInput , typename TOutput > CalculatorType itk::Functor::SymmetricEigenAnalysisFunction< TInput, TOutput >::m_Calculator private
Definition at line 128 of file itkSymmetricEigenAnalysisImageFilter.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::GetDimension(), itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::GetOrderEigenValuesBy(), itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::operator()(), itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::OrderEigenValuesBy(), and itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::SetDimension().
The documentation for this class was generated from the following file:
itkSymmetricEigenAnalysisImageFilter.h