ITK: itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor Class Reference
itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor Class Reference
Group Core » Module ITKMesh
#include <itkSimplexMeshToTriangleMeshFilter.h>
Public Member Functions
PointMapPointer GetCenterMap ()
void SetMesh (const InputMeshType *mesh)
SimplexCellVisitor ()
virtual ~SimplexCellVisitor ()=default
void Visit (CellIdentifier cellId, SimplexPolygonType *poly)
Protected Attributes
PointMapPointer m_CenterMap
InputMeshConstPointer m_Mesh
Detailed Description
template<typename TInputMesh, typename TOutputMesh>
class itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor
This class provides methods for visiting each simplex cell of a simplex mesh It computes the center of each visited cell.
Definition at line 94 of file itkSimplexMeshToTriangleMeshFilter.h.
Constructor & Destructor Documentation
SimplexCellVisitor()
template<typename TInputMesh , typename TOutputMesh > itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::SimplexCellVisitor () inline
default constructor
Definition at line 100 of file itkSimplexMeshToTriangleMeshFilter.h.
References New().
~SimplexCellVisitor()
template<typename TInputMesh , typename TOutputMesh > virtual itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::~SimplexCellVisitor () virtual default
default destructor
Member Function Documentation
GetCenterMap()
template<typename TInputMesh , typename TOutputMesh > PointMapPointer itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetCenterMap () inline
Definition at line 137 of file itkSimplexMeshToTriangleMeshFilter.h.
SetMesh()
template<typename TInputMesh , typename TOutputMesh > void itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::SetMesh (const InputMeshType * mesh) inline
Definition at line 143 of file itkSimplexMeshToTriangleMeshFilter.h.
Visit()
template<typename TInputMesh , typename TOutputMesh > void itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::Visit (CellIdentifier cellId, SimplexPolygonType * poly) inline
visits all polygon cells and compute the cell centers
Definition at line 111 of file itkSimplexMeshToTriangleMeshFilter.h.
References itk::PolygonCell< TCellInterface >::GetNumberOfPoints(), itk::PolygonCell< TCellInterface >::PointIdsBegin(), and itk::PolygonCell< TCellInterface >::PointIdsEnd().
Member Data Documentation
m_CenterMap
template<typename TInputMesh , typename TOutputMesh > PointMapPointer itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::m_CenterMap protected
Definition at line 150 of file itkSimplexMeshToTriangleMeshFilter.h.
m_Mesh
template<typename TInputMesh , typename TOutputMesh > InputMeshConstPointer itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::m_Mesh protected
Definition at line 149 of file itkSimplexMeshToTriangleMeshFilter.h.
The documentation for this class was generated from the following file:
itkSimplexMeshToTriangleMeshFilter.h