ITK: itk::NumericTraits< CovariantVector< T, D > > Class Template Reference
itk::NumericTraits< CovariantVector< T, D > > Class Template Reference
Data Representation ObjectsGroup Core » | Module ITKCommon
#include <itkNumericTraitsCovariantVectorPixel.h>
Public Types
using AbsType = CovariantVector< ElementAbsType, D >
using AccumulateType = CovariantVector< ElementAccumulateType, D >
using FloatType = CovariantVector< ElementFloatType, D >
using MeasurementVectorType = Self
using PrintType = CovariantVector< ElementPrintType, D >
using RealType = CovariantVector< ElementRealType, D >
using ScalarRealType = ElementRealType
using Self = CovariantVector< T, D >
using ValueType = T
Static Public Member Functions
static void AssignToArray (const Self &v, MeasurementVectorType &mv)
template<typename TArray >
static void AssignToArray (const Self &v, TArray &mv)
static unsigned int GetLength ()
static unsigned int GetLength (const CovariantVector< T, D > &)
static const Self max ()
static const Self max (const Self &)
static const Self min ()
static const Self min (const Self &)
static const Self NonpositiveMin ()
static const Self NonpositiveMin (const Self &)
static const Self OneValue ()
static const Self OneValue (const Self &)
static const Self ZeroValue ()
static const Self ZeroValue (const Self &)
static void SetLength (CovariantVector< T, D > &m, const unsigned int s)
Static Public Attributes
static constexpr bool IsComplex = NumericTraits<ValueType>::IsComplex
static constexpr bool IsInteger = std::is_integral<ValueType>::value
static constexpr bool IsSigned = std::is_signed<ValueType>::value
static const Self ITKCommon_EXPORT One
static const Self ITKCommon_EXPORT Zero
Private Types
using ElementAbsType = typename NumericTraits< T >::AbsType
using ElementAccumulateType = typename NumericTraits< T >::AccumulateType
using ElementFloatType = typename NumericTraits< T >::FloatType
using ElementPrintType = typename NumericTraits< T >::PrintType
using ElementRealType = typename NumericTraits< T >::RealType
Detailed Description
template<typename T, unsigned int D>
class itk::NumericTraits< CovariantVector< T, D > >
Define numeric traits for CovariantVector.
Template Parameters
T Component type of CovariantVector
D Dimension of the CovariantVector
We provide here a generic implementation based on creating types of CovariantVector whose components are the types of the NumericTraits from the original CovariantVector components. This implementation require support for partial specializations, since it is based on the concept that: NumericTraits<CovariantVector<T,D>> is defined piecewise by CovariantVector<NumericTraits<T>>
See also
NumericTraits
Definition at line 44 of file itkNumericTraitsCovariantVectorPixel.h.
Member Typedef Documentation
AbsType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::AbsType = CovariantVector<ElementAbsType, D>
Unsigned component type
Definition at line 60 of file itkNumericTraitsCovariantVectorPixel.h.
AccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::AccumulateType = CovariantVector<ElementAccumulateType, D>
Accumulation of addition and multiplication.
Definition at line 63 of file itkNumericTraitsCovariantVectorPixel.h.
ElementAbsType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::ElementAbsType = typename NumericTraits<T>::AbsType private
Definition at line 47 of file itkNumericTraitsCovariantVectorPixel.h.
ElementAccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::ElementAccumulateType = typename NumericTraits<T>::AccumulateType private
Definition at line 48 of file itkNumericTraitsCovariantVectorPixel.h.
ElementFloatType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::ElementFloatType = typename NumericTraits<T>::FloatType private
Definition at line 49 of file itkNumericTraitsCovariantVectorPixel.h.
ElementPrintType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::ElementPrintType = typename NumericTraits<T>::PrintType private
Definition at line 50 of file itkNumericTraitsCovariantVectorPixel.h.
ElementRealType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::ElementRealType = typename NumericTraits<T>::RealType private
Definition at line 51 of file itkNumericTraitsCovariantVectorPixel.h.
FloatType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::FloatType = CovariantVector<ElementFloatType, D>
Typedef for operations that use floating point instead of real precision
Definition at line 67 of file itkNumericTraitsCovariantVectorPixel.h.
MeasurementVectorType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::MeasurementVectorType = Self
Measurement vector type
Definition at line 79 of file itkNumericTraitsCovariantVectorPixel.h.
PrintType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::PrintType = CovariantVector<ElementPrintType, D>
Return the type that can be printed.
Definition at line 70 of file itkNumericTraitsCovariantVectorPixel.h.
RealType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::RealType = CovariantVector<ElementRealType, D>
Type for real-valued scalar operations.
Definition at line 73 of file itkNumericTraitsCovariantVectorPixel.h.
ScalarRealType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::ScalarRealType = ElementRealType
Type for real-valued scalar operations.
Definition at line 76 of file itkNumericTraitsCovariantVectorPixel.h.
Self
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::Self = CovariantVector<T, D>
Definition at line 57 of file itkNumericTraitsCovariantVectorPixel.h.
ValueType
template<typename T , unsigned int D> using itk::NumericTraits< CovariantVector< T, D > >::ValueType = T
Return the type of the native component type.
Definition at line 55 of file itkNumericTraitsCovariantVectorPixel.h.
Member Function Documentation
AssignToArray() [1/2]
template<typename T , unsigned int D> static void itk::NumericTraits< CovariantVector< T, D > >::AssignToArray (const Self & v, MeasurementVectorType & mv) inline static
Definition at line 179 of file itkNumericTraitsCovariantVectorPixel.h.
AssignToArray() [2/2]
template<typename T , unsigned int D> template<typename TArray > static void itk::NumericTraits< CovariantVector< T, D > >::AssignToArray (const Self & v, TArray & mv) inline static
Definition at line 186 of file itkNumericTraitsCovariantVectorPixel.h.
GetLength() [1/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< CovariantVector< T, D > >::GetLength () inline static
Return the length of the vector.
Definition at line 173 of file itkNumericTraitsCovariantVectorPixel.h.
GetLength() [2/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< CovariantVector< T, D > >::GetLength (const CovariantVector< T, D > &) inline static
Return the length of the vector.
Definition at line 166 of file itkNumericTraitsCovariantVectorPixel.h.
max() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::max () inline static
Definition at line 99 of file itkNumericTraitsCovariantVectorPixel.h.
max() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::max (const Self &) inline static
Component wise defined element
Note
minimum value for floating pointer types is defined as minimum positive normalize value.
Definition at line 87 of file itkNumericTraitsCovariantVectorPixel.h.
min() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::min () inline static
Definition at line 105 of file itkNumericTraitsCovariantVectorPixel.h.
min() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::min (const Self &) inline static
Definition at line 93 of file itkNumericTraitsCovariantVectorPixel.h.
NonpositiveMin() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::NonpositiveMin () inline static
Definition at line 111 of file itkNumericTraitsCovariantVectorPixel.h.
NonpositiveMin() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::NonpositiveMin (const Self &) inline static
Definition at line 129 of file itkNumericTraitsCovariantVectorPixel.h.
References itk::NumericTraits< T >::NonpositiveMin().
OneValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::OneValue () inline static
Definition at line 123 of file itkNumericTraitsCovariantVectorPixel.h.
OneValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::OneValue (const Self &) inline static
Definition at line 141 of file itkNumericTraitsCovariantVectorPixel.h.
References itk::NumericTraits< T >::OneValue().
SetLength()
template<typename T , unsigned int D> static void itk::NumericTraits< CovariantVector< T, D > >::SetLength (CovariantVector< T, D > & m, const unsigned int s) inline static
Fixed length vectors cannot be resized, so an exception will be thrown if the input size is not valid. If the size is valid the vector will be filled with zeros.
Definition at line 154 of file itkNumericTraitsCovariantVectorPixel.h.
References itk::FixedArray< T, 3 >::Fill().
ZeroValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::ZeroValue () inline static
Definition at line 117 of file itkNumericTraitsCovariantVectorPixel.h.
ZeroValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< CovariantVector< T, D > >::ZeroValue (const Self &) inline static
Definition at line 135 of file itkNumericTraitsCovariantVectorPixel.h.
References itk::NumericTraits< T >::ZeroValue().
Member Data Documentation
IsComplex
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< CovariantVector< T, D > >::IsComplex = NumericTraits<ValueType>::IsComplex static constexpr
Definition at line 148 of file itkNumericTraitsCovariantVectorPixel.h.
IsInteger
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< CovariantVector< T, D > >::IsInteger = std::is_integral<ValueType>::value static constexpr
Definition at line 147 of file itkNumericTraitsCovariantVectorPixel.h.
IsSigned
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< CovariantVector< T, D > >::IsSigned = std::is_signed<ValueType>::value static constexpr
Definition at line 146 of file itkNumericTraitsCovariantVectorPixel.h.
One
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< CovariantVector< T, D > >::One static
Definition at line 198 of file itkNumericTraitsCovariantVectorPixel.h.
Zero
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< CovariantVector< T, D > >::Zero static
Note
: the functions are preferred over the member variables as they are defined for all partial specialization
Definition at line 197 of file itkNumericTraitsCovariantVectorPixel.h.
The documentation for this class was generated from the following file:
itkNumericTraitsCovariantVectorPixel.h