ITK: itk::BYUMeshIO Class Reference
itk::BYUMeshIO Class Reference
Data Processing Objects » Filters » Input and Output FiltersGroup IO » | Module ITKIOMeshBYU
#include <itkBYUMeshIO.h>
Public Types
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = BYUMeshIO
using SizeValueType = Superclass::SizeValueType
using StreamOffsetType = Superclass::StreamOffsetType
using Superclass = MeshIOBase
Public Types inherited from itk::MeshIOBase
using ArrayOfExtensionsType = std::vector< std::string >
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = MeshIOBase
using SizeValueType = IdentifierType
using StreamOffsetType = std::streamoff
using Superclass = LightProcessObject
Public Types inherited from itk::LightProcessObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightProcessObject
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
bool CanReadFile (const char *fileName) override
bool CanWriteFile (const char *fileName) override
virtual const char * GetNameOfClass () const
void ReadCellData (void *buffer) override
void ReadCells (void *buffer) override
void ReadMeshInformation () override
void ReadPointData (void *buffer) override
void ReadPoints (void *buffer) override
void Write () override
void WriteCellData (void *buffer) override
void WriteCells (void *buffer) override
void WriteMeshInformation () override
void WritePointData (void *buffer) override
void WritePoints (void *buffer) override
Public Member Functions inherited from itk::MeshIOBase
std::string GetByteOrderAsString (IOByteOrderEnum) const
unsigned int GetComponentSize (IOComponentEnum componentType) const
std::string GetComponentTypeAsString (IOComponentEnum) const
std::string GetFileTypeAsString (IOFileEnum) const
std::string GetPixelTypeAsString (IOPixelEnum) const
const ArrayOfExtensionsType & GetSupportedReadExtensions () const
const ArrayOfExtensionsType & GetSupportedWriteExtensions () const
void SetByteOrderToBigEndian ()
void SetByteOrderToLittleEndian ()
void SetFileTypeToASCII ()
void SetFileTypeToBinary ()
template<typename T >
void SetPixelType (const Array< T > &array, bool UsePointPixel=true)
template<typename T , unsigned int VLength>
void SetPixelType (const CovariantVector< T, VLength > &, bool UsePointPixel=true)
template<typename T >
void SetPixelType (const DiffusionTensor3D< T > &, bool UsePointPixel=true)
template<typename T , unsigned int VLength>
void SetPixelType (const FixedArray< T, VLength > &, bool UsePointPixel=true)
template<typename T , unsigned int VRows, unsigned int VColumns>
void SetPixelType (const Matrix< T, VRows, VColumns > &, bool UsePointPixel=true)
template<typename T >
void SetPixelType (const RGBAPixel< T > &, bool UsePointPixel=true)
template<typename T >
void SetPixelType (const RGBPixel< T > &, bool UsePointPixel=true)
template<typename T >
void SetPixelType (const std::complex< T > &, bool UsePointPixel=true)
template<typename T , unsigned int VLength>
void SetPixelType (const SymmetricSecondRankTensor< T, VLength >, bool UsePointPixel=true)
template<typename T >
void SetPixelType (const T &, bool UsePointPixel=true)
template<typename T >
void SetPixelType (const VariableLengthVector< T > &vector, bool UsePointPixel=true)
template<typename T >
void SetPixelType (const VariableSizeMatrix< T > &matrix, bool UsePointPixel=true)
template<typename T , unsigned int VLength>
void SetPixelType (const Vector< T, VLength > &, bool UsePointPixel=true)
virtual void SetFileName (const char *_arg)
virtual const char * GetFileName () const
virtual void SetPointPixelType (const itk::CommonEnums::IOPixel _arg)
virtual itk::CommonEnums::IOPixel GetPointPixelType () const
virtual void SetCellPixelType (const itk::CommonEnums::IOPixel _arg)
virtual itk::CommonEnums::IOPixel GetCellPixelType () const
virtual void SetPointComponentType (const itk::CommonEnums::IOComponent _arg)
virtual itk::CommonEnums::IOComponent GetPointComponentType () const
virtual void SetCellComponentType (const itk::CommonEnums::IOComponent _arg)
virtual itk::CommonEnums::IOComponent GetCellComponentType () const
virtual void SetPointPixelComponentType (const itk::CommonEnums::IOComponent _arg)
virtual itk::CommonEnums::IOComponent GetPointPixelComponentType () const
virtual void SetCellPixelComponentType (const itk::CommonEnums::IOComponent _arg)
virtual itk::CommonEnums::IOComponent GetCellPixelComponentType () const
virtual void SetNumberOfPointPixelComponents (unsigned int _arg)
virtual unsigned int GetNumberOfPointPixelComponents () const
virtual void SetNumberOfCellPixelComponents (unsigned int _arg)
virtual unsigned int GetNumberOfCellPixelComponents () const
virtual void SetPointDimension (unsigned int _arg)
virtual unsigned int GetPointDimension () const
virtual void SetNumberOfPoints (SizeValueType _arg)
virtual SizeValueType GetNumberOfPoints () const
virtual void SetNumberOfCells (SizeValueType _arg)
virtual SizeValueType GetNumberOfCells () const
virtual void SetNumberOfPointPixels (SizeValueType _arg)
virtual SizeValueType GetNumberOfPointPixels () const
virtual void SetNumberOfCellPixels (SizeValueType _arg)
virtual SizeValueType GetNumberOfCellPixels () const
virtual void SetCellBufferSize (SizeValueType _arg)
virtual SizeValueType GetCellBufferSize () const
virtual void SetUpdatePoints (bool _arg)
virtual bool GetUpdatePoints () const
virtual void SetUpdateCells (bool _arg)
virtual bool GetUpdateCells () const
virtual void SetUpdatePointData (bool _arg)
virtual bool GetUpdatePointData () const
virtual void SetUpdateCellData (bool _arg)
virtual bool GetUpdateCellData () const
virtual void SetFileType (const IOFileEnum _arg)
virtual IOFileEnum GetFileType () const
virtual void SetByteOrder (const IOByteOrderEnum _arg)
virtual IOByteOrderEnum GetByteOrder () const
virtual void SetUseCompression (bool _arg)
virtual bool GetUseCompression () const
virtual void UseCompressionOn ()
Public Member Functions inherited from itk::LightProcessObject
virtual void AbortGenerateDataOn ()
virtual const bool & GetAbortGenerateData () const
virtual void SetAbortGenerateData (bool _arg)
virtual void UpdateOutputData ()
void UpdateProgress (float amount)
virtual void SetProgress (float _arg)
virtual const float & GetProgress () const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual void Delete ()
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::LightProcessObject
static Pointer New ()
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
BYUMeshIO ()
void PrintSelf (std::ostream &os, Indent indent) const override
template<typename T >
void WriteCells (T *buffer, std::ofstream &outputFile)
~BYUMeshIO () override
template<typename T >
void WritePoints (T *buffer, std::ofstream &outputFile)
Protected Member Functions inherited from itk::MeshIOBase
void AddSupportedReadExtension (const char *extension)
void AddSupportedWriteExtension (const char *extension)
MeshIOBase ()
template<typename T >
void ReadBufferAsBinary (T *buffer, std::ifstream &inputFile, SizeValueType numberOfComponents)
~MeshIOBase () override=default
template<typename T >
void ReadBufferAsAscii (T *buffer, std::ifstream &inputFile, SizeValueType numberOfComponents)
template<typename T >
void WriteBufferAsAscii (T *buffer, std::ofstream &outputFile, SizeValueType numberOfLines, SizeValueType numberOfComponents)
template<typename TOutput , typename TInput >
void WriteBufferAsBinary (TInput *buffer, std::ofstream &outputFile, SizeValueType numberOfComponents)
template<typename TInput , typename TOutput >
void ReadCellsBuffer (TInput *input, TOutput *output)
template<typename TInput , typename TOutput >
void ReadCellsBuffer (TInput *input, TOutput *output, CellGeometryEnum type)
template<typename TInput , typename TOutput >
void WriteCellsBuffer (TInput *input, TOutput *output, CellGeometryEnum cellType, unsigned int numberOfPoints, SizeValueType numberOfCells)
template<typename TInput , typename TOutput >
void WriteCellsBuffer (TInput *input, TOutput *output, CellGeometryEnum cellType, SizeValueType numberOfCells)
Protected Member Functions inherited from itk::LightProcessObject
virtual void GenerateData ()
LightProcessObject ()
~LightProcessObject () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Private Attributes
StreamOffsetType m_FilePosition { 0 }
SizeValueType m_FirstCellId
SizeValueType m_LastCellId
SizeValueType m_PartId
Additional Inherited Members
Protected Attributes inherited from itk::MeshIOBase
IOByteOrderEnum m_ByteOrder { IOByteOrderEnum::OrderNotApplicable }
SizeValueType m_CellBufferSize
IOComponentEnum m_CellComponentType { IOComponentEnum::UNKNOWNCOMPONENTTYPE }
IOComponentEnum m_CellPixelComponentType { IOComponentEnum::UNKNOWNCOMPONENTTYPE }
IOPixelEnum m_CellPixelType { IOPixelEnum::SCALAR }
std::string m_FileName
IOFileEnum m_FileType { IOFileEnum::ASCII }
unsigned int m_NumberOfCellPixelComponents { 0 }
SizeValueType m_NumberOfCellPixels
SizeValueType m_NumberOfCells
unsigned int m_NumberOfPointPixelComponents { 0 }
SizeValueType m_NumberOfPointPixels
SizeValueType m_NumberOfPoints
IOComponentEnum m_PointComponentType { IOComponentEnum::UNKNOWNCOMPONENTTYPE }
unsigned int m_PointDimension { 3 }
IOComponentEnum m_PointPixelComponentType { IOComponentEnum::UNKNOWNCOMPONENTTYPE }
IOPixelEnum m_PointPixelType { IOPixelEnum::SCALAR }
bool m_UpdateCellData { false }
bool m_UpdateCells { false }
bool m_UpdatePointData { false }
bool m_UpdatePoints { false }
bool m_UseCompression { false }
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Detailed Description
This class defines how to read and write BYU Geometry File Format.
Definition at line 38 of file itkBYUMeshIO.h.
Member Typedef Documentation
ConstPointer
using itk::BYUMeshIO::ConstPointer = SmartPointer<const Self>
Definition at line 46 of file itkBYUMeshIO.h.
Pointer
using itk::BYUMeshIO::Pointer = SmartPointer<Self>
Definition at line 47 of file itkBYUMeshIO.h.
Self
using itk::BYUMeshIO::Self = BYUMeshIO
Standard class type aliases.
Definition at line 44 of file itkBYUMeshIO.h.
SizeValueType
using itk::BYUMeshIO::SizeValueType = Superclass::SizeValueType
Definition at line 50 of file itkBYUMeshIO.h.
StreamOffsetType
using itk::BYUMeshIO::StreamOffsetType = Superclass::StreamOffsetType
Definition at line 49 of file itkBYUMeshIO.h.
Superclass
using itk::BYUMeshIO::Superclass = MeshIOBase
Definition at line 45 of file itkBYUMeshIO.h.
Constructor & Destructor Documentation
BYUMeshIO()
itk::BYUMeshIO::BYUMeshIO () protected
~BYUMeshIO()
itk::BYUMeshIO::~BYUMeshIO () override protected
Member Function Documentation
CanReadFile()
bool itk::BYUMeshIO::CanReadFile (const char * fileName) override virtual
Determine if the file can be read with this MeshIO implementation.
Parameters
FileNameToRead The name of the file to test for reading.
Postcondition
Sets classes MeshIOBase::m_FileName variable to be FileNameToWrite
Returns
Returns true if this MeshIO can read the file specified.
Implements itk::MeshIOBase.
CanWriteFile()
bool itk::BYUMeshIO::CanWriteFile (const char * fileName) override virtual
Determine if the file can be written with this MeshIO implementation.
Parameters
FileNameToWrite The name of the file to test for writing.
Postcondition
Sets classes MeshIOBase::m_FileName variable to be FileNameToWrite
Returns
Returns true if this MeshIO can write the file specified.
Implements itk::MeshIOBase.
GetNameOfClass()
virtual const char* itk::BYUMeshIO::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::MeshIOBase.
New()
static Pointer itk::BYUMeshIO::New () static
Method for creation through the object factory.
PrintSelf()
void itk::BYUMeshIO::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::MeshIOBase.
ReadCellData()
void itk::BYUMeshIO::ReadCellData (void * buffer) override virtual
Implements itk::MeshIOBase.
ReadCells()
void itk::BYUMeshIO::ReadCells (void * buffer) override virtual
Implements itk::MeshIOBase.
ReadMeshInformation()
void itk::BYUMeshIO::ReadMeshInformation () override virtual
Set the spacing and dimension information for the set filename.
Implements itk::MeshIOBase.
ReadPointData()
void itk::BYUMeshIO::ReadPointData (void * buffer) override virtual
Implements itk::MeshIOBase.
ReadPoints()
void itk::BYUMeshIO::ReadPoints (void * buffer) override virtual
Reads the data from disk into the memory buffer provided.
Implements itk::MeshIOBase.
Write()
void itk::BYUMeshIO::Write () override virtual
Implements itk::MeshIOBase.
WriteCellData()
void itk::BYUMeshIO::WriteCellData (void * buffer) override virtual
Implements itk::MeshIOBase.
WriteCells() [1/2]
template<typename T > void itk::BYUMeshIO::WriteCells (T * buffer, std::ofstream & outputFile) inline protected
Definition at line 138 of file itkBYUMeshIO.h.
References itk::NumericTraits< T >::ZeroValue().
WriteCells() [2/2]
void itk::BYUMeshIO::WriteCells (void * buffer) override virtual
Implements itk::MeshIOBase.
WriteMeshInformation()
void itk::BYUMeshIO::WriteMeshInformation () override virtual
Set the spacing and dimension information for the set filename.
Implements itk::MeshIOBase.
WritePointData()
void itk::BYUMeshIO::WritePointData (void * buffer) override virtual
Implements itk::MeshIOBase.
WritePoints() [1/2]
template<typename T > void itk::BYUMeshIO::WritePoints (T * buffer, std::ofstream & outputFile) inline protected
Write points to output stream
Definition at line 119 of file itkBYUMeshIO.h.
References itk::ConvertNumberToString(), and itk::NumericTraits< T >::ZeroValue().
WritePoints() [2/2]
void itk::BYUMeshIO::WritePoints (void * buffer) override virtual
Writes the data to disk from the memory buffer provided.
Implements itk::MeshIOBase.
Member Data Documentation
m_FilePosition
StreamOffsetType itk::BYUMeshIO::m_FilePosition { 0 } private
Definition at line 164 of file itkBYUMeshIO.h.
m_FirstCellId
SizeValueType itk::BYUMeshIO::m_FirstCellId private
Definition at line 166 of file itkBYUMeshIO.h.
m_LastCellId
SizeValueType itk::BYUMeshIO::m_LastCellId private
Definition at line 167 of file itkBYUMeshIO.h.
m_PartId
SizeValueType itk::BYUMeshIO::m_PartId private
Definition at line 165 of file itkBYUMeshIO.h.
The documentation for this class was generated from the following file:
itkBYUMeshIO.h