ITK: itk::NumericTraits< Point< T, D > > Class Template Reference
itk::NumericTraits< Point< T, D > > Class Template Reference
#include <itkNumericTraitsPointPixel.h>
Public Types
using AbsType = Point< ElementAbsType, D >
using AccumulateType = Point< ElementAccumulateType, D >
using FloatType = Point< ElementFloatType, D >
using MeasurementVectorType = Self
using PrintType = Point< ElementPrintType, D >
using RealType = Point< ElementRealType, D >
using ScalarRealType = ElementRealType
using Self = Point< T, D >
using ValueType = T
Static Public Member Functions
static void AssignToArray (const Self &v, MeasurementVectorType &mv)
template<typename TArray >
static void AssignToArray (const Self &v, TArray &mv)
static unsigned int GetLength ()
static unsigned int GetLength (const Point< T, D > &)
static const Self max ()
static const Self max (const Self &)
static const Self min ()
static const Self min (const Self &)
static const Self NonpositiveMin ()
static const Self NonpositiveMin (const Self &)
static const Self OneValue ()
static const Self OneValue (const Self &)
static const Self ZeroValue ()
static const Self ZeroValue (const Self &)
static void SetLength (Point< T, D > &m, const unsigned int s)
Static Public Attributes
static constexpr bool IsComplex = NumericTraits<ValueType>::IsComplex
static constexpr bool IsInteger = std::is_integral<ValueType>::value
static constexpr bool IsSigned = std::is_signed<ValueType>::value
static const Self ITKCommon_EXPORT One
static const Self ITKCommon_EXPORT Zero
Private Types
using ElementAbsType = typename NumericTraits< T >::AbsType
using ElementAccumulateType = typename NumericTraits< T >::AccumulateType
using ElementFloatType = typename NumericTraits< T >::FloatType
using ElementPrintType = typename NumericTraits< T >::PrintType
using ElementRealType = typename NumericTraits< T >::RealType
Detailed Description
template<typename T, unsigned int D>
class itk::NumericTraits< Point< T, D > >
NumericTraits for Point.
Template Parameters
T Component type for Point
D Dimension of the space
Definition at line 32 of file itkNumericTraitsPointPixel.h.
Member Typedef Documentation
AbsType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::AbsType = Point<ElementAbsType, D>
Unsigned component type
Definition at line 47 of file itkNumericTraitsPointPixel.h.
AccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::AccumulateType = Point<ElementAccumulateType, D>
Accumulation of addition and multiplication.
Definition at line 50 of file itkNumericTraitsPointPixel.h.
ElementAbsType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::ElementAbsType = typename NumericTraits<T>::AbsType private
Definition at line 35 of file itkNumericTraitsPointPixel.h.
ElementAccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::ElementAccumulateType = typename NumericTraits<T>::AccumulateType private
Definition at line 36 of file itkNumericTraitsPointPixel.h.
ElementFloatType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::ElementFloatType = typename NumericTraits<T>::FloatType private
Definition at line 37 of file itkNumericTraitsPointPixel.h.
ElementPrintType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::ElementPrintType = typename NumericTraits<T>::PrintType private
Definition at line 38 of file itkNumericTraitsPointPixel.h.
ElementRealType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::ElementRealType = typename NumericTraits<T>::RealType private
Definition at line 39 of file itkNumericTraitsPointPixel.h.
FloatType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::FloatType = Point<ElementFloatType, D>
Typedef for operations that use floating point instead of real precision
Definition at line 54 of file itkNumericTraitsPointPixel.h.
MeasurementVectorType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::MeasurementVectorType = Self
Measurement vector type
Definition at line 66 of file itkNumericTraitsPointPixel.h.
PrintType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::PrintType = Point<ElementPrintType, D>
Return the type that can be printed.
Definition at line 57 of file itkNumericTraitsPointPixel.h.
RealType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::RealType = Point<ElementRealType, D>
Type for real-valued scalar operations.
Definition at line 60 of file itkNumericTraitsPointPixel.h.
ScalarRealType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::ScalarRealType = ElementRealType
Type for real-valued scalar operations.
Definition at line 63 of file itkNumericTraitsPointPixel.h.
Self
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::Self = Point<T, D>
Definition at line 44 of file itkNumericTraitsPointPixel.h.
ValueType
template<typename T , unsigned int D> using itk::NumericTraits< Point< T, D > >::ValueType = T
Return the type of the native component type.
Definition at line 43 of file itkNumericTraitsPointPixel.h.
Member Function Documentation
AssignToArray() [1/2]
template<typename T , unsigned int D> static void itk::NumericTraits< Point< T, D > >::AssignToArray (const Self & v, MeasurementVectorType & mv) inline static
Definition at line 166 of file itkNumericTraitsPointPixel.h.
AssignToArray() [2/2]
template<typename T , unsigned int D> template<typename TArray > static void itk::NumericTraits< Point< T, D > >::AssignToArray (const Self & v, TArray & mv) inline static
Definition at line 173 of file itkNumericTraitsPointPixel.h.
GetLength() [1/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< Point< T, D > >::GetLength () inline static
Return the dimensionality of the point.
Definition at line 160 of file itkNumericTraitsPointPixel.h.
GetLength() [2/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< Point< T, D > >::GetLength (const Point< T, D > &) inline static
Return the dimensionality of the point.
Definition at line 153 of file itkNumericTraitsPointPixel.h.
max() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::max () inline static
Definition at line 86 of file itkNumericTraitsPointPixel.h.
max() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::max (const Self &) inline static
Component wise defined element
Note
minimum value for floating pointer types is defined as minimum positive normalize value.
Definition at line 74 of file itkNumericTraitsPointPixel.h.
min() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::min () inline static
Definition at line 92 of file itkNumericTraitsPointPixel.h.
min() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::min (const Self &) inline static
Definition at line 80 of file itkNumericTraitsPointPixel.h.
NonpositiveMin() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::NonpositiveMin () inline static
Definition at line 98 of file itkNumericTraitsPointPixel.h.
NonpositiveMin() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::NonpositiveMin (const Self &) inline static
Definition at line 116 of file itkNumericTraitsPointPixel.h.
References itk::NumericTraits< T >::NonpositiveMin().
OneValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::OneValue () inline static
Definition at line 110 of file itkNumericTraitsPointPixel.h.
OneValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::OneValue (const Self &) inline static
Definition at line 128 of file itkNumericTraitsPointPixel.h.
References itk::NumericTraits< T >::OneValue().
SetLength()
template<typename T , unsigned int D> static void itk::NumericTraits< Point< T, D > >::SetLength (Point< T, D > & m, const unsigned int s) inline static
Fixed length vectors cannot be resized, so an exception will be thrown if the input size is not valid. If the size is valid the vector will be filled with zeros.
Definition at line 141 of file itkNumericTraitsPointPixel.h.
References itk::FixedArray< TCoordRep, 3 >::Fill().
ZeroValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::ZeroValue () inline static
Definition at line 104 of file itkNumericTraitsPointPixel.h.
ZeroValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Point< T, D > >::ZeroValue (const Self &) inline static
Definition at line 122 of file itkNumericTraitsPointPixel.h.
References itk::NumericTraits< T >::ZeroValue().
Member Data Documentation
IsComplex
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< Point< T, D > >::IsComplex = NumericTraits<ValueType>::IsComplex static constexpr
Definition at line 135 of file itkNumericTraitsPointPixel.h.
IsInteger
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< Point< T, D > >::IsInteger = std::is_integral<ValueType>::value static constexpr
Definition at line 134 of file itkNumericTraitsPointPixel.h.
IsSigned
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< Point< T, D > >::IsSigned = std::is_signed<ValueType>::value static constexpr
Definition at line 133 of file itkNumericTraitsPointPixel.h.
One
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< Point< T, D > >::One static
Definition at line 185 of file itkNumericTraitsPointPixel.h.
Zero
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< Point< T, D > >::Zero static
Note
: the functions are preferred over the member variables as they are defined for all partial specialization
Definition at line 184 of file itkNumericTraitsPointPixel.h.
The documentation for this class was generated from the following file:
itkNumericTraitsPointPixel.h