ITK: itk::fftw::ComplexToComplexProxy< double > Class Reference
itk::fftw::ComplexToComplexProxy< double > Class Reference
#include <itkFFTWCommonExtended.h>
Public Types
using ComplexType = fftw_complex
using PixelType = double
using PlanType = fftw_plan
using Self = ComplexToComplexProxy< double >
Static Public Member Functions
static void DestroyPlan (PlanType p)
static void Execute (PlanType p)
static PlanType Plan_dft_1d (const int n, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r (int rank, const int *n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r_1d (int n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r_2d (int nx, int ny, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c (int rank, const int *n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c_1d (int n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c_2d (int nx, int ny, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
Detailed Description
Definition at line 193 of file itkFFTWCommonExtended.h.
Member Typedef Documentation
ComplexType
using itk::fftw::ComplexToComplexProxy< double >::ComplexType = fftw_complex
Definition at line 197 of file itkFFTWCommonExtended.h.
PixelType
using itk::fftw::ComplexToComplexProxy< double >::PixelType = double
Definition at line 196 of file itkFFTWCommonExtended.h.
PlanType
using itk::fftw::ComplexToComplexProxy< double >::PlanType = fftw_plan
Definition at line 198 of file itkFFTWCommonExtended.h.
Self
using itk::fftw::ComplexToComplexProxy< double >::Self = ComplexToComplexProxy<double>
Definition at line 199 of file itkFFTWCommonExtended.h.
Member Function Documentation
DestroyPlan()
static void itk::fftw::ComplexToComplexProxy< double >::DestroyPlan (PlanType p) inline static
Definition at line 320 of file itkFFTWCommonExtended.h.
Execute()
static void itk::fftw::ComplexToComplexProxy< double >::Execute (PlanType p) inline static
Definition at line 315 of file itkFFTWCommonExtended.h.
Plan_dft_1d()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_1d (const int n, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1) inline static
Definition at line 302 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_c2r (int rank, const int * n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 238 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r_1d()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_c2r_1d (int n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 202 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r_2d()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_c2r_2d (int nx, int ny, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 214 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r_3d()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 226 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_r2c (int rank, const int * n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 290 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c_1d()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_r2c_1d (int n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 251 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c_2d()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_r2c_2d (int nx, int ny, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 264 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c_3d()
static PlanType itk::fftw::ComplexToComplexProxy< double >::Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 277 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
The documentation for this class was generated from the following file:
itkFFTWCommonExtended.h