ITK: itk::Object Class Reference
itk::Object Class Reference
System Objects » ITK System Objects | Data Representation ObjectsGroup Core » | Module ITKCommon
#include <itkObject.h>
Inherits itk::LightObject.
Inherited by itk::BinaryImageToLevelSetImageAdaptorBase< TInput, MalcolmSparseLevelSetImage< TInput::ImageDimension > >, itk::BinaryImageToLevelSetImageAdaptorBase< TInput, ShiSparseLevelSetImage< TInput::ImageDimension > >, itk::BinaryImageToLevelSetImageAdaptorBase< TInput, TOutput >, itk::BinaryImageToLevelSetImageAdaptorBase< TInput, WhitakerSparseLevelSetImage< TOutput, TInput::ImageDimension > >, itk::BinaryImageToLevelSetImageAdaptorBase< TInputImage, LevelSetDenseImage< TLevelSetImage > >, itk::CenteredTransformInitializer< VersorRigid3DTransform< double >, TFixedImage, TMovingImage >, itk::Function::ConvergenceMonitoringFunction< double, double >, itk::CostFunctionTemplate< double >, itk::DomainThreader< itk::ThreadedIndexedContainerPartitioner, itk::GradientDescentOptimizerBasev4Template >, itk::DomainThreader< itk::ThreadedIndexedContainerPartitioner, itk::QuasiNewtonOptimizerv4Template >, itk::DomainThreader< TDomainPartitioner, TImageToImageMetricv4 >, itk::DomainThreader< TDomainPartitioner, TJointHistogramMetric >, itk::DomainThreader< ThreadedImageRegionPartitioner< TImage::ImageDimension >, TLevelSetEvolution >, itk::DomainThreader< ThreadedImageRegionPartitioner< TImageToImageMetricv4::VirtualImageDimension >, TImageToImageMetricv4 >, itk::DomainThreader< ThreadedImageRegionPartitioner< TJointHistogramMetric::VirtualImageDimension >, TJointHistogramMetric >, itk::DomainThreader< ThreadedIndexedContainerPartitioner, GradientDescentOptimizerBasev4Template< TInternalComputationValueType > >, itk::DomainThreader< ThreadedIndexedContainerPartitioner, QuasiNewtonOptimizerv4Template< TInternalComputationValueType > >, itk::DomainThreader< ThreadedIndexedContainerPartitioner, TImageToImageMetricv4 >, itk::DomainThreader< ThreadedIndexedContainerPartitioner, TJointHistogramMetric >, itk::DomainThreader< ThreadedIteratorRangePartitioner< TLevelSetEvolution::DomainMapImageFilterType::DomainMapType::const_iterator >, TLevelSetEvolution >, itk::DomainThreader< ThreadedIteratorRangePartitioner< WhitakerSparseLevelSetImage< TOutput, VDimension >::LayerConstIterator >, TLevelSetEvolution >, itk::FunctionBase< Array< double >, double >, itk::FunctionBase< ContinuousIndex< float, 2 >, FixedArray< double, Math::UnsignedPower(3+1, 2)> >, itk::FunctionBase< double, double >, itk::FunctionBase< float, double >, itk::FunctionBase< Point< double, 3 >, bool >, itk::FunctionBase< Point< double, 3 >, double >, itk::FunctionBase< Point< double, 3 >, TOutput >, itk::FunctionBase< Point< double, TImageType ::ImageDimension >, NumericTraits< TImageType ::PixelType >::RealType >, itk::FunctionBase< Point< double, TInputImage::ImageDimension >, NumericTraits< TInputImage::PixelType >::RealType >, itk::FunctionBase< Point< double, TInputImage::ImageDimension >, TInputImage::PixelType >, itk::FunctionBase< Point< double, TInputImage::ImageDimension >, Vector< double, TInputImage::ImageDimension > >, itk::FunctionBase< Point< float, TImageType ::ImageDimension >, NumericTraits< TImageType ::PixelType >::RealType >, itk::FunctionBase< Point< float, TInputImage::ImageDimension >, bool >, itk::FunctionBase< Point< float, TInputImage::ImageDimension >, CovariantVector< double, TInputImage::ImageDimension > >, itk::FunctionBase< Point< float, TInputImage::ImageDimension >, double >, itk::FunctionBase< Point< float, TInputImage::ImageDimension >, NumericTraits< TInputImage::PixelType >::RealType >, itk::FunctionBase< Point< float, TInputImage::ImageDimension >, TInputImage::PixelType >, itk::FunctionBase< Point< float, TInputImage::ImageDimension >, TOutput >, itk::FunctionBase< Point< float, TInputImage::ImageDimension >, vnl_matrix< NumericTraits< TInputImage::PixelType::ValueType >::RealType > >, itk::FunctionBase< Point< SpacePrecisionType, 3 >, double >, itk::FunctionBase< Point< TCoordRep, VSpaceDimension >, double >, itk::FunctionBase< Point< typename TInputImage::PixelType, TInputImage::ImageDimension >, NumericTraits< TInputImage::PixelType >::RealType >, itk::FunctionBase< TFunction::InputType, bool >, itk::FunctionBase< TInputPointSet::PointType, TOutput >, itk::FunctionBase< TMeasurementVector, double >, itk::FunctionBase< TMesh, TMesh::EdgeListPointerType >, itk::FunctionBase< TPointSet ::PointType, double >, itk::FunctionBase< TVector, double >, itk::GPUReduction< float >, itk::GPUReduction< int >, itk::HistogramAlgorithmBase< THistogram >, itk::ArchetypeSeriesFileNames, itk::BinaryImageToLevelSetImageAdaptorBase< TInputImage, TLevelSet >, itk::BoundingBox< TPointIdentifier, VPointDimension, TCoordRep, TPointsContainer >, itk::BSplineTransformInitializer< TTransform, TImage >, itk::BuildInformation, itk::ByteSwapper< T >, itk::CastSpatialObjectFilter< ObjectDimension >, itk::CenteredTransformInitializer< TTransform, TFixedImage, TMovingImage >, itk::ColorTable< TComponent >, itk::Command, itk::CostFunctionTemplate< TInternalComputationValueType >, itk::CreateObjectFunctionBase, itk::DataObject, itk::Directory, itk::DomainThreader< TDomainPartitioner, TAssociate >, itk::DOMNode, itk::DOMNodeXMLReader, itk::DOMNodeXMLWriter, itk::DOMReader< TOutput >, itk::DOMWriter< TInput >, itk::DynamicLoader, itk::FastMarchingImageToNodePairContainerAdaptor< TInput, TOutput, TImage >, itk::FFTWGlobalConfiguration, itk::Function::ColormapFunction< TScalar, TRGBPixel >, itk::Function::ConvergenceMonitoringFunction< TScalar, TEnergyValue >, itk::FunctionBase< TInput, TOutput >, itk::GPUDataManager, itk::GPUReduction< TElement >, itk::HistogramAlgorithmBase< TInputHistogram >, itk::ImageContainerInterface< TElementIdentifier, TElement >, itk::ImageDuplicator< TInputImage >, itk::ImageIOFactory, itk::ImageMomentsCalculator< TImage >, itk::ImagePCADecompositionCalculator< TInputImage, TBasisImage >, itk::ImageRegionSplitterBase, itk::ImportImageContainer< TElementIdentifier, TElement >, itk::IndexedContainerInterface< TElementIdentifier, TElement >, itk::KappaSigmaThresholdImageCalculator< TInputImage, TMaskImage >, itk::LandmarkBasedTransformInitializer< TTransform, TFixedImage, TMovingImage >, itk::LevelSetContainerBase< TIdentifier, TLevelSet >, itk::LevelSetDomainPartitionBase< TDomain >, itk::LevelSetEquationContainer< TTermContainer >, itk::LevelSetEquationTermBase< TInputImage, TLevelSetContainer >, itk::LevelSetEquationTermContainer< TInputImage, TLevelSetContainer >, itk::LevelSetEvolutionBase< TEquationContainer, TLevelSet >, itk::LightProcessObject, itk::LoggerBase, itk::LoggerManager, itk::LogOutput, itk::MapContainer< TElementIdentifier, TElement >, itk::MeshIOFactory, itk::MetaConverterBase< VDimension >, itk::MetaSceneConverter< VDimension, PixelType, TMeshTraits >, itk::MinimumMaximumImageCalculator< TInputImage >, itk::MRASlabIdentifier< TInputImage >, itk::MultiThreaderBase, itk::NumericSeriesFileNames, itk::ObjectFactoryBase, itk::ObjectStore< TObjectType >, itk::ObjectToObjectOptimizerBaseTemplate< TInternalComputationValueType >, itk::OctreeBase, itk::Optimizer, itk::OptimizerParameterScalesEstimatorTemplate< TInternalComputationValueType >, itk::OutputWindow, itk::PointsLocator< TPointsContainer >, itk::ProcessObject, itk::ProgressAccumulator, itk::QuadEdgeMeshDecimationCriterion< TMesh, TElement, TMeasure, TPriorityQueueWrapper >, itk::QuadEdgeMeshFunctionBase< TMesh, TOutput >, itk::QuadEdgeMeshTopologyChecker< TMesh >, itk::RealTimeClock, itk::RegularExpressionSeriesFileNames, itk::RingBuffer< TElement >, itk::SegmentationBorder, itk::SegmentationRegion, itk::SimplexMeshVolumeCalculator< TInputMesh >, itk::SparseFieldLayer< TNodeType >, itk::SpatialObjectDuplicator< TInputSpatialObject >, itk::SpatialObjectReader< VDimension, PixelType, TMeshTraits >, itk::SpatialObjectToImageStatisticsCalculator< TInputImage, TInputSpatialObject, TSampleDimension >, itk::SpatialObjectWriter< VDimension, PixelType, TMeshTraits >, itk::Statistics::DecisionRule, itk::Statistics::DenseFrequencyContainer2, itk::Statistics::ExpectationMaximizationMixtureModelEstimator< TSample >, itk::Statistics::KdTree< TSample >, itk::Statistics::KdTreeBasedKmeansEstimator< TKdTree >, itk::Statistics::KdTreeGenerator< TSample >, itk::Statistics::MixtureModelComponentBase< TSample >, itk::Statistics::ProbabilityDistribution, itk::Statistics::RandomVariateGeneratorBase, itk::Statistics::ScalarImageToHistogramGenerator< TImageType >, itk::Statistics::SparseFrequencyContainer2, itk::Statistics::SubsamplerBase< TSample >, itk::StoppingCriterionBase, itk::testhelper::ImageRegistrationMethodImageSource< TFixedPixelType, TMovingPixelType, VDimension >, itk::ThreadedDomainPartitioner< TDomain >, itk::ThreadPool, itk::TransformBaseTemplate< TParametersValueType >, itk::TransformIOFactoryTemplate< TParametersValueType >, itk::TransformParametersAdaptorBase< TTransform >, itk::TriangleMeshCurvatureCalculator< TInputMesh >, itk::UpdateMalcolmSparseLevelSet< VDimension, TEquationContainer >, itk::UpdateShiSparseLevelSet< VDimension, TEquationContainer >, itk::UpdateWhitakerSparseLevelSet< VDimension, TLevelSetValueType, TEquationContainer >, itk::ValarrayImageContainer< TElementIdentifier, TElement >, itk::VectorContainer< TElementIdentifier, TElement >, itk::Version, itk::VideoIOFactory, itk::VTKPolyDataWriter< TInputMesh >, itk::LevelSetContainerBase< TIdentifier, LevelSetDenseImage< TImage > >, itk::LevelSetDomainPartitionBase< TImage >, itk::LevelSetDomainPartitionBase< TMesh >, itk::LevelSetEquationTermBase< TInput, TLevelSetContainer >, itk::LevelSetEvolutionBase< TEquationContainer, LevelSetDenseImage< TImage > >, itk::LevelSetEvolutionBase< TEquationContainer, MalcolmSparseLevelSetImage< VDimension > >, itk::LevelSetEvolutionBase< TEquationContainer, ShiSparseLevelSetImage< VDimension > >, itk::LevelSetEvolutionBase< TEquationContainer, WhitakerSparseLevelSetImage< TOutput, VDimension > >, itk::MetaConverterBase< 3 >, itk::ObjectToObjectOptimizerBaseTemplate< double >, itk::OptimizerParameterScalesEstimatorTemplate< TMetric::ParametersValueType >, itk::QuadEdgeMeshFunctionBase< TMesh, TQEType * >, itk::QuadEdgeMeshFunctionBase< TMesh, TQEType::OriginRefType >, itk::ThreadedDomainPartitioner< ImageRegion< VDimension > >, itk::ThreadedDomainPartitioner< Index< 2 > >, itk::ThreadedDomainPartitioner< ThreadedIteratorRangePartitionerDomain< TIterator > >, itk::TransformBaseTemplate< double >, itk::TransformBaseTemplate< float >, itk::TransformParametersAdaptorBase< Transform< TTransform::ScalarType, TTransform::InputSpaceDimension, TTransform::OutputSpaceDimension > >, itk::VectorContainer< IdentifierType, TElementWrapper >, and itk::VTKPolyDataWriter< TMesh >.
Public Types
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual void Delete ()
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
Static Public Member Functions
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Private Member Functions
itkGetGlobalDeclarationMacro (bool, GlobalWarningDisplay)
Private Attributes
bool m_Debug { false }
MetaDataDictionary * m_MetaDataDictionary { nullptr }
TimeStamp m_MTime
std::string m_ObjectName
SubjectImplementation * m_SubjectImplementation { nullptr }
Static Private Attributes
static bool * m_GlobalWarningDisplay
Additional Inherited Members
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Detailed Description
Base class for most ITK classes.
Object is the second-highest level base class for most itk objects. It extends the base object functionality of LightObject by implementing callbacks (via object/observer), debug flags/methods, and modification time tracking. Most ITK classes should be a subclass of Object due to the need to keep track of modified time.
ITK Sphinx Examples:
All ITK Sphinx Examples
Copy Another
Definition at line 62 of file itkObject.h.
Member Typedef Documentation
ConstPointer
using itk::Object::ConstPointer = SmartPointer<const Self>
Definition at line 71 of file itkObject.h.
Pointer
using itk::Object::Pointer = SmartPointer<Self>
Definition at line 70 of file itkObject.h.
Self
using itk::Object::Self = Object
Smart pointer type alias support
Definition at line 68 of file itkObject.h.
Superclass
using itk::Object::Superclass = LightObject
Definition at line 69 of file itkObject.h.
Constructor & Destructor Documentation
Object()
itk::Object::Object () protected
~Object()
itk::Object::~Object () override protected
Member Function Documentation
AddObserver() [1/3]
unsigned long itk::Object::AddObserver (const EventObject & event, Command *)
Add an observer/command to this object invoked for event.
This is an implementation of the subject/observer design pattern. An observer is added by specifying an event to respond to and an itk::Command to execute. It returns an unsigned long tag which can be used later to remove the event or retrieve the command.
AddObserver() [2/3]
unsigned long itk::Object::AddObserver (const EventObject & event, Command *) const
AddObserver() [3/3]
unsigned long itk::Object::AddObserver (const EventObject & event, std::function< void(const EventObject &)> function) const
A convenient method to add an C++ lambda function as an observer.
A FunctionCommand object in implicitly create to hold function, and passed to this object as a standard observer. The command will be invoked for the specified event.
The function or lambda cannot captured this object as SmartPoint because a circular dependency is generated which causing memory leaks. Sample usage:
auto &objRef = *o.GetPointer();
o->AddObserver(itk::AnyEvent(), [&objRef](const itk::EventObject &event)
{ std::cout << "Object: " << objRef.GetNameOfClass() << " Event: " << event << std::endl; });
See also
FunctionCommand
CreateAnother()
LightObject::Pointer itk::Object::CreateAnother () const override virtual
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from itk::LightObject.
Reimplemented in itk::BSplineDeformableTransform< TParametersValueType, VDimension, VSplineOrder >.
DebugOff()
virtual void itk::Object::DebugOff () const virtual
Turn debugging output off.
DebugOn()
virtual void itk::Object::DebugOn () const virtual
Turn debugging output on.
GetCommand()
Command* itk::Object::GetCommand (unsigned long tag)
Get the command associated with the given tag. NOTE: This returns a pointer to a Command, but it is safe to assign this to a Command::Pointer. Since Command inherits from LightObject, at this point in the code, only a pointer or a reference to the Command can be used.
GetDebug()
bool itk::Object::GetDebug () const
Get the value of the debug flag.
GetGlobalWarningDisplay()
static bool itk::Object::GetGlobalWarningDisplay () static
GetMetaDataDictionary() [1/2]
MetaDataDictionary& itk::Object::GetMetaDataDictionary ()
Returns
A reference to this objects MetaDataDictionary.
Warning
This reference may be changed.
GetMetaDataDictionary() [2/2]
const MetaDataDictionary& itk::Object::GetMetaDataDictionary () const
Returns
A constant reference to this objects MetaDataDictionary.
GetMTime()
virtual ModifiedTimeType itk::Object::GetMTime () const virtual
Return this object's modified time.
Reimplemented in itk::ImageAdaptor< TImage, TAccessor >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::MultiResolutionImageRegistrationMethod< TFixedImage, TMovingImage >, itk::ImageRegistrationMethod< TFixedImage, TMovingImage >, itk::SpatialObject< VDimension >, itk::ImageToSpatialObjectRegistrationMethod< TFixedImage, TMovingSpatialObject >, itk::BoundingBox< TPointIdentifier, VPointDimension, TCoordRep, TPointsContainer >, itk::PointSetToImageRegistrationMethod< TFixedPointSet, TMovingImage >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::PointSetToPointSetRegistrationMethod< TFixedPointSet, TMovingPointSet >, itk::LandmarkDisplacementFieldSource< TOutputImage >, itk::DataObjectDecorator< T >, itk::ImageSpatialObject< TDimension, TPixelType >, and itk::MeshSpatialObject< TMesh >.
GetNameOfClass()
virtual const char* itk::Object::GetNameOfClass () const virtual
Standard part of all itk objects.
Reimplemented from itk::LightObject.
Reimplemented in itk::Statistics::KdTree< TSample >, itk::FunctionCommand, itk::LevelSetEvolution< TEquationContainer, MalcolmSparseLevelSetImage< VDimension > >, itk::CStyleCommand, itk::BinaryImageToLevelSetImageAdaptor< TInput, MalcolmSparseLevelSetImage< TInput::ImageDimension > >, itk::SymmetricEigenAnalysisFixedDimensionImageFilter< TMatrixDimension, TInputImage, TOutputImage >, itk::SimpleConstMemberCommand< T >, itk::LevelSetEvolution< TEquationContainer, ShiSparseLevelSetImage< VDimension > >, itk::DataObject, itk::BinaryImageToLevelSetImageAdaptor< TInput, ShiSparseLevelSetImage< TInput::ImageDimension > >, itk::WindowedSincInterpolateImageFunction< TInputImage, VRadius, TWindowFunction, TBoundaryCondition, TCoordRep >, itk::ParallelSparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >, itk::SparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::MovingHistogramMorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, itk::SimpleMemberCommand< T >, itk::MRIBiasFieldCorrectionFilter< TInputImage, TOutputImage, TMaskImage >, itk::GPUImageFactory, itk::JoinImageFilter< TInputImage1, TInputImage2 >, itk::PriorityQueueContainer< TElementWrapper, TElementWrapperInterface, TElementPriority, TElementIdentifier >, itk::FFTWGlobalConfiguration, itk::RawImageIOFactory< TPixel, VImageDimension >, itk::BinaryImageToLevelSetImageAdaptor< TInput, WhitakerSparseLevelSetImage< TOutput, TInput::ImageDimension > >, itk::LBFGS2Optimizerv4Template< TInternalComputationValueType >, itk::LevelSetEvolution< TEquationContainer, WhitakerSparseLevelSetImage< TOutput, VDimension > >, itk::ImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::ReceptorMemberCommand< T >, itk::GPUBinaryThresholdImageFilterFactory, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::GPUDemonsRegistrationFilterFactory, itk::KLMRegionGrowImageFilter< TInputImage, TOutputImage >, itk::WatershedImageFilter< TInputImage >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::SparseFieldLayer< TNodeType >, itk::RescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType, TOutputImage >, itk::LevelSetEvolutionComputeIterationThreader< WhitakerSparseLevelSetImage< TOutput, VDimension >, ThreadedIteratorRangePartitioner< WhitakerSparseLevelSetImage< TOutput, VDimension >::LayerConstIterator >, TLevelSetEvolution >, itk::MaskImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::IntensityWindowingImageFilter< TInputImage, TOutputImage >, itk::QuadEdgeMesh< TPixel, VDimension, TTraits >, itk::SigmoidImageFilter< TInputImage, TOutputImage >, itk::SparseFieldFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::VectorImageToImageAdaptor< TPixelType, Dimension >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, itk::ClampImageFilter< TInputImage, TOutputImage >, itk::DiffusionTensor3DReconstructionImageFilter< TReferenceImagePixelType, TGradientImagePixelType, TTensorPixelType, TMaskImageType >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::AutomaticTopologyMeshSource< TOutputMesh >, itk::AdaptImageFilter< TInputImage, TOutputImage, TAccessor >, itk::PatchBasedDenoisingBaseImageFilter< TInputImage, TOutputImage >, itk::CannySegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::DeformableSimplexMesh3DGradientConstraintForceFilter< TInputMesh, TOutputMesh >, itk::KLMSegmentationBorder, itk::MaskNegatedImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::BinaryThresholdImageFilter< TInputImage, TOutputImage >, itk::FastMarchingImageFilter< TLevelSet, TSpeedImage >, itk::ProcessObject, itk::ImageToImageMetricv4GetValueAndDerivativeThreader< ThreadedIndexedContainerPartitioner, TImageToImageMetricv4 >, itk::BSplineScatteredDataPointSetToImageFilter< TInputPointSet, TOutputImage >, itk::ImageKmeansModelEstimator< TInputImage, TMembershipFunction >, itk::BSplineDeformableTransform< TParametersValueType, VDimension, VSplineOrder >, itk::ScalarToRGBColormapImageFilter< TInputImage, TOutputImage >, itk::FiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::Statistics::HistogramToTextureFeaturesFilter< THistogram >, itk::Octree< TPixel, ColorTableSize, MappingFunctionType >, itk::Mesh< TPixelType, VDimension, TMeshTraits >, itk::WeightedAddImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::Statistics::MersenneTwisterRandomVariateGenerator, itk::STAPLEImageFilter< TInputImage, TOutputImage >, itk::SpatialObject< VDimension >, itk::ChangeLabelImageFilter< TInputImage, TOutputImage >, itk::ThresholdLabelerImageFilter< TInputImage, TOutputImage >, itk::GeodesicActiveContourShapePriorLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::AntiAliasBinaryImageFilter< TInputImage, TOutputImage >, itk::BinaryImageToSparseLevelSetImageAdaptorBase< TInput, TOutput >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ObjectByObjectLabelMapFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::MultiLabelSTAPLEImageFilter< TInputImage, TOutputImage, TWeights >, itk::watershed::Boundary< TScalar, TDimension >, itk::ExtractImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::MultiScaleHessianBasedMeasureImageFilter< TInputImage, THessianImage, TOutputImage >, itk::MattesMutualInformationImageToImageMetric< TFixedImage, TMovingImage >, itk::ContourExtractor2DImageFilter< TInputImage >, itk::LandweberDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::BinaryMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::DisplacementFieldJacobianDeterminantFilter< TInputImage, TRealType, TOutputImage >, itk::BorderQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::NarrowBandCurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::GPUMeanImageFilterFactory, itk::ParameterizationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::ThreadedIteratorRangePartitioner< TIterator >, itk::MergeLabelMapFilter< TImage >, itk::VectorConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::GeodesicActiveContourLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapeDetectionLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >, itk::LaplacianDeformationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::StandardDeviationProjectionImageFilter< TInputImage, TOutputImage, TAccumulate >, itk::RelabelComponentImageFilter< TInputImage, TOutputImage >, itk::ScalarConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::NaryMaximumImageFilter< TInputImage, TOutputImage >, itk::VectorRescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::ImageToSpatialObjectMetric< TFixedImage, TMovingSpatialObject >, itk::ObjectToObjectOptimizerBaseTemplate< TInternalComputationValueType >, itk::GDCMImageIO, itk::CurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::GPUBinaryThresholdImageFilter< TInputImage, TOutputImage >, itk::CastImageFilter< TInputImage, TOutputImage >, itk::HistogramToEntropyImageFilter< THistogram, TImage >, itk::Testing::ExtractSliceImageFilter< TInputImage, TOutputImage >, itk::LaplacianSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::MultiThreaderBase, itk::Statistics::ScalarImageToTextureFeaturesFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::ImageBase< VImageDimension >, itk::MatrixOffsetTransformBase< TParametersValueType, VInputDimension, VOutputDimension >, itk::NaryAddImageFilter< TInputImage, TOutputImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::MattesMutualInformationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::TransformGeometryImageFilter< TInputImage, TOutputImage >, itk::NiftiImageIO, itk::FFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage >, itk::RecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::LevelSetEvolutionComputeIterationThreader< LevelSetDenseImage< TImage >, ThreadedIteratorRangePartitioner< TLevelSetEvolution::DomainMapImageFilterType::DomainMapType::const_iterator >, TLevelSetEvolution >, itk::BSplineTransform< TParametersValueType, VDimension, VSplineOrder >, itk::HistogramToLogProbabilityImageFilter< THistogram, TImage >, itk::Statistics::ScalarImageToRunLengthMatrixFilter< TImageType, THistogramFrequencyContainer >, itk::CurvatureRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TImageForceFunction >, itk::ANTSNeighborhoodCorrelationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::FFTImageFilterFactory< TFFTImageFilter, TInput, TOutput >, itk::InvertIntensityImageFilter< TInputImage, TOutputImage >, itk::AffineTransform< TParametersValueType, VDimension >, itk::SimplexMesh< TPixelType, VDimension, TMeshTraits >, itk::BinaryThresholdProjectionImageFilter< TInputImage, TOutputImage >, itk::VectorThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::watershed::Segmenter< TInputImage >, itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >, itk::Statistics::HistogramToRunLengthFeaturesFilter< THistogram >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::ConstrainedValueAdditionImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::CurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::BinaryProjectionImageFilter< TInputImage, TOutputImage >, itk::ExpNegativeImageFilter< TInputImage, TOutputImage >, itk::JointHistogramMutualInformationComputeJointPDFThreader< ThreadedIndexedContainerPartitioner, TJointHistogramMetric >, itk::PhasedArray3DSpecialCoordinatesImage< TPixel >, itk::SpecialCoordinatesImage< TPixel, VImageDimension >, itk::Statistics::JointDomainImageToListSampleAdaptor< TImage >, itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HistogramToProbabilityImageFilter< THistogram, TImage >, itk::VectorIndexSelectionCastImageFilter< TInputImage, TOutputImage >, itk::HessianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::NarrowBandThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShotNoiseImageFilter< TInputImage, TOutputImage >, itk::ObjectToObjectMultiMetricv4< TFixedDimension, TMovingDimension, TVirtualImage, TInternalComputationValueType >, itk::TimeVaryingBSplineVelocityFieldImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::MagnitudeAndPhaseToComplexImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, TFunction1, TFunction2 >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::MutualInformationImageToImageMetric< TFixedImage, TMovingImage >, itk::LevelSetContainer< TIdentifier, LevelSetDenseImage< TImage > >, itk::Statistics::NormalVariateGenerator, itk::Statistics::ScalarImageToCooccurrenceMatrixFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::ContourSpatialObject< TDimension >, itk::AbsoluteValueDifferenceImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::N4BiasFieldCorrectionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::KLMSegmentationRegion, itk::TimeVaryingVelocityFieldImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::MeanProjectionImageFilter< TInputImage, TOutputImage, TAccumulate >, itk::LevelSetMotionRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::CommandIterationUpdatev4< TOptimizer >, itk::MovingHistogramImageFilterBase< TInputImage, TOutputImage, TKernel >, itk::Statistics::ScalarImageToRunLengthFeaturesFilter< TImageType, THistogramFrequencyContainer >, itk::ConstrainedValueDifferenceImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::ThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::LBFGSOptimizerv4, itk::VectorContainer< TElementIdentifier, TElement >, itk::AzimuthElevationToCartesianTransform< TParametersValueType, VDimension >, itk::ConnectedComponentFunctorImageFilter< TInputImage, TOutputImage, TFunctor, TMaskImage >, itk::SquaredDifferenceImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::Hessian3DToVesselnessMeasureImageFilter< TPixel >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::HDF5TransformIOTemplate< TParametersValueType >, itk::NormalQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::MemberCommand< T >, itk::Image< TPixel, VImageDimension >, itk::MovingHistogramImageFilter< TInputImage, TOutputImage, TKernel, THistogram >, itk::BSplineDownsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::WarpVectorImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::SumProjectionImageFilter< TInputImage, TOutputImage >, itk::MatrixIndexSelectionImageFilter< TInputImage, TOutputImage >, itk::BinaryNotImageFilter< TImage >, itk::ZeroCrossingBasedEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, itk::ObjectToObjectMetric< TFixedDimension, TMovingDimension, TVirtualImage, TParametersValueType >, itk::ImageFileWriter< TInputImage >, itk::BinaryMagnitudeImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::ReconstructionByDilationImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::LandmarkBasedTransformInitializer< TTransform, TFixedImage, TMovingImage >, itk::ObjectToObjectMetricBaseTemplate< TInternalComputationValueType >, itk::GrayscaleGeodesicErodeImageFilter< TInputImage, TOutputImage >, itk::PolygonGroupSpatialObjectXMLFileWriter, itk::ComplexToImaginaryImageAdaptor< TImage, TOutputPixelType >, itk::WarpImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::AdaptiveHistogramEqualizationImageFilter< TImageType, TKernel >, itk::MaximumImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::GrayscaleGeodesicDilateImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGrindPeakImageFilter< TInputImage, TOutputImage >, itk::ReconstructionByErosionImageFilter< TInputImage, TOutputImage >, itk::BinaryErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::BayesianClassifierImageFilter< TInputVectorImage, TLabelsType, TPosteriorsPrecisionType, TPriorsPrecisionType >, itk::ImageSeriesWriter< TInputImage, TOutputImage >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, TCompare >, itk::LaplacianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::LBFGSOptimizer, itk::BayesianClassifierInitializationImageFilter< TInputImage, TProbabilityPrecisionType >, itk::CommandIterationUpdate< TOptimizer >, itk::ObjectStore< TObjectType >, itk::MinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::CompositeTransform< TParametersValueType, VDimension >, itk::SliceBySliceImageFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::MeshIOBase, itk::BinaryDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::ExhaustiveOptimizer, itk::DisplacementFieldTransform< TParametersValueType, VDimension >, itk::ImageToSpatialObjectRegistrationMethod< TFixedImage, TMovingSpatialObject >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::HDF5ImageIO, itk::BinaryMinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::ComplexToModulusImageAdaptor< TImage, TOutputPixelType >, itk::ComplexToRealImageAdaptor< TImage, TOutputPixelType >, itk::HistogramToIntensityImageFilter< THistogram, TImage >, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::ChangeInformationImageFilter< TInputImage >, itk::MedianProjectionImageFilter< TInputImage, TOutputImage >, itk::Atan2ImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::AnisotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::PointSet< TPixelType, VDimension, TMeshTraits >, itk::RGBToLuminanceImageAdaptor< TImage, TOutputPixelType >, itk::BSplineL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::MaximumProjectionImageFilter< TInputImage, TOutputImage >, itk::AcosImageFilter< TInputImage, TOutputImage >, itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::FFTDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::ClassifierBase< TDataContainer >, itk::GPUCastImageFilter< TInputImage, TOutputImage >, itk::CommandVnlIterationUpdate< TOptimizer >, itk::RegionGrowImageFilter< TInputImage, TOutputImage >, itk::ComplexToPhaseImageAdaptor< TImage, TOutputPixelType >, itk::ExpNegativeImageAdaptor< TImage, TOutputPixelType >, itk::TanImageAdaptor< TImage, TOutputPixelType >, itk::Statistics::ExpectationMaximizationMixtureModelEstimator< TSample >, itk::Transform< TParametersValueType, VInputDimension, VOutputDimension >, itk::BSplineCenteredL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::ComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::TriangleMeshToBinaryImageFilter< TInputMesh, TOutputImage >, itk::MeshFileReader< TOutputMesh, ConvertPointPixelTraits, ConvertCellPixelTraits >, itk::MinimumProjectionImageFilter< TInputImage, TOutputImage >, itk::AsinImageFilter< TInputImage, TOutputImage >, itk::BinaryReconstructionByDilationImageFilter< TInputImage >, itk::BinaryReconstructionByErosionImageFilter< TInputImage >, itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >, itk::WienerDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::DeformableSimplexMesh3DFilter< TInputMesh, TOutputMesh >, itk::ExhaustiveOptimizerv4< TInternalComputationValueType >, itk::AcosImageAdaptor< TImage, TOutputPixelType >, itk::CosImageAdaptor< TImage, TOutputPixelType >, itk::ExpImageAdaptor< TImage, TOutputPixelType >, itk::Log10ImageAdaptor< TImage, TOutputPixelType >, itk::SinImageAdaptor< TImage, TOutputPixelType >, itk::SqrtImageAdaptor< TImage, TOutputPixelType >, itk::BSplineInterpolateImageFunction< TImageType, TCoordRep, TCoefficientType >, itk::BSplineResampleImageFilterBase< TInputImage, TOutputImage >, itk::InPlaceLabelMapFilter< TInputImage >, itk::SignedMaurerDistanceMapImageFilter< TInputImage, TOutputImage >, itk::TensorFractionalAnisotropyImageFilter< TInputImage, TOutputImage >, itk::TensorRelativeAnisotropyImageFilter< TInputImage, TOutputImage >, itk::CSVArray2DFileReader< TData >, itk::CorrelationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::AbsImageAdaptor< TImage, TOutputPixelType >, itk::QuadEdgeMeshToQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::CosImageFilter< TInputImage, TOutputImage >, itk::DiffeomorphicDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::Bruker2dseqImageIO, itk::DelaunayConformingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::AtanImageAdaptor< TImage, TOutputPixelType >, itk::Statistics::ScalarImageToCooccurrenceListSampleFilter< TImage >, itk::MinimumImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::NormalizeToConstantImageFilter< TInputImage, TOutputImage >, itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::RegistrationParameterScalesEstimator< TMetric >, itk::TemporalDataObject, itk::AsinImageAdaptor< TImage, TOutputPixelType >, itk::LogImageAdaptor< TImage, TOutputPixelType >, itk::Statistics::Histogram< TMeasurement, TFrequencyContainer >, itk::InterpolateImagePointsFilter< TInputImage, TOutputImage, TCoordType, InterpolatorType >, itk::AtanImageFilter< TInputImage, TOutputImage >, itk::LabelShapeKeepNObjectsImageFilter< TInputImage >, itk::MaskedRankImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel >, itk::RankImageFilter< TInputImage, TOutputImage, TKernel >, itk::GaussianImageSource< TOutputImage >, itk::GradientImageFilter< TInputImage, TOperatorValueType, TOutputValueType, TOutputImageType >, itk::ZeroCrossingImageFilter< TInputImage, TOutputImage >, itk::GradientDescentOptimizerv4Template< TInternalComputationValueType >, itk::ValarrayImageContainer< TElementIdentifier, TElement >, itk::CentralDifferenceImageFunction< TInputImage, TCoordRep, TOutputType >, itk::PipelineMonitorImageFilter< TImageType >, itk::ImagePCAShapeModelEstimator< TInputImage, TOutputImage >, itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::LaplacianImageFilter< TInputImage, TOutputImage >, itk::ImageGaussianModelEstimator< TInputImage, TMembershipFunction, TTrainingImage >, itk::ParametricBlindLeastSquaresDeconvolutionImageFilter< TInputImage, TKernelSource, TOutputImage >, itk::RichardsonLucyDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::LabelVotingImageFilter< TInputImage, TOutputImage >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::PointSetToPointSetMetricWithIndexv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::LoggerBase, itk::HistogramMatchingImageFilter< TInputImage, TOutputImage, THistogramMeasurement >, itk::BinaryShapeKeepNObjectsImageFilter< TInputImage >, itk::BinaryShapeOpeningImageFilter< TInputImage >, itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >, itk::ThresholdMaximumConnectedComponentsImageFilter< TInputImage, TOutputImage >, itk::BlackTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::BilateralImageFilter< TInputImage, TOutputImage >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::VideoIOBase, itk::InPlaceImageFilter< TInputImage, TOutputImage >, itk::FFTWComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::ImageFileReader< TOutputImage, ConvertPixelTraits >, itk::ImageIOBase, itk::TernaryMagnitudeImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::TernaryMagnitudeSquaredImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::LabelSelectionLabelMapFilter< TImage >, itk::ShapeLabelMapFilter< TImage, TLabelImage >, itk::OpeningByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::DirectedHausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::InitializationBiasedParticleSwarmOptimizer, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::FastSymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::GPUDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::TernaryOperatorImageFilter< TMask, TImage >, itk::LabelShapeOpeningImageFilter< TInputImage >, itk::HMaximaImageFilter< TInputImage, TOutputImage >, itk::WhiteTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::ApproximateSignedDistanceMapImageFilter< TInputImage, TOutputImage >, itk::HessianToObjectnessMeasureImageFilter< TInputImage, TOutputImage >, itk::SobelEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::IsotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::KullbackLeiblerCompareHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::LBFGSOptimizerBasev4< TInternalVnlOptimizerType >, itk::JensenHavrdaCharvatTsallisPointSetToPointSetMetricv4< TPointSet, TInternalComputationValueType >, itk::ImageSource< TOutputImage >, itk::LightProcessObject, itk::Statistics::KdTreeBasedKmeansEstimator< TKdTree >, itk::TransformBaseTemplate< TParametersValueType >, itk::ForwardFFTImageFilter< TInputImage, TOutputImage >, itk::TriangleMeshCurvatureCalculator< TInputMesh >, itk::SubtractImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::VectorMagnitudeImageFilter< TInputImage, TOutputImage >, itk::LabelMap< TLabelObject >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::ShapeRelabelImageFilter< TInputImage >, itk::ClosingByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleFillholeImageFilter< TInputImage, TOutputImage >, itk::ObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ContourMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::GradientDescentOptimizer, itk::ImplicitManifoldNormalVectorFilter< TInputImage, TSparseOutputImage >, itk::ScalarImageKmeansImageFilter< TInputImage, TOutputImage >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::MultiResolutionImageRegistrationMethod< TFixedImage, TMovingImage >, itk::IsolatedConnectedImageFilter< TInputImage, TOutputImage >, itk::DataObjectDecorator< T >, itk::BSplineDecompositionImageFilter< TInputImage, TOutputImage >, itk::LabelImageGaussianInterpolateImageFunction< TInputImage, TCoordRep, TPixelCompare >, itk::AnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::FFTWForwardFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::BinaryMask3DMeshSource< TInputImage, TOutputMesh >, itk::SinImageFilter< TInputImage, TOutputImage >, itk::ThresholdImageFilter< TImage >, itk::HardConnectedComponentImageFilter< TInputImage, TOutputImage >, itk::HMinimaImageFilter< TInputImage, TOutputImage >, itk::FRPROptimizer, itk::ImageClassifierBase< TInputImage, TClassifiedImage >, itk::SymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::MorphologicalWatershedImageFilter< TInputImage, TOutputImage >, itk::TobogganImageFilter< TInputImage, TOutputImage >, itk::LBFGSBOptimizerv4, itk::VideoStream< TFrameType >, itk::RegularExpressionSeriesFileNames, itk::BoundedReciprocalImageFilter< TInputImage, TOutputImage >, itk::RegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::ImageRegistrationMethod< TFixedImage, TMovingImage >, itk::MINCImageIO, itk::SimpleDataObjectDecorator< T >, itk::DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::Statistics::ProbabilityDistribution, itk::ShrinkImageFilter< TInputImage, TOutputImage >, itk::VectorCurvatureAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::AbsImageFilter< TInputImage, TOutputImage >, itk::ExpImageFilter< TInputImage, TOutputImage >, itk::AttributeSelectionLabelMapFilter< TImage, TAttributeAccessor >, itk::MorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ValuedRegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::OnePlusOneEvolutionaryOptimizer, itk::OnePlusOneEvolutionaryOptimizerv4< TInternalComputationValueType >, itk::DomainThreader< TDomainPartitioner, TAssociate >, itk::SparseImage< TNode, VImageDimension >, itk::Statistics::KdTreeGenerator< TSample >, itk::PadImageFilter< TInputImage, TOutputImage >, itk::PadImageFilterBase< TInputImage, TOutputImage >, itk::FFTWHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::GDCMSeriesFileNames, itk::Log10ImageFilter< TInputImage, TOutputImage >, itk::SqrtImageFilter< TInputImage, TOutputImage >, itk::TanImageFilter< TInputImage, TOutputImage >, itk::RegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::LabelOverlayImageFilter< TInputImage, TLabelImage, TOutputImage >, itk::SaltAndPepperNoiseImageFilter< TInputImage, TOutputImage >, itk::ConnectedThresholdImageFilter< TInputImage, TOutputImage >, itk::BoundingBox< TPointIdentifier, VPointDimension, TCoordRep, TPointsContainer >, itk::FFTWInverseFFTImageFilter< TInputImage, TOutputImage >, itk::ArchetypeSeriesFileNames, itk::Testing::HashImageFilter< TImageType >, itk::RoundImageFilter< TInputImage, TOutputImage >, itk::LabelMapToAttributeImageFilter< TInputImage, TOutputImage, TAttributeAccessor >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, TCompare1, TCompare2 >, itk::NarrowBandImageFilterBase< TInputImage, TOutputImage >, itk::AmoebaOptimizer, itk::MatchCardinalityImageToImageMetric< TFixedImage, TMovingImage >, itk::PointSetToImageRegistrationMethod< TFixedPointSet, TMovingImage >, itk::TimeVaryingBSplineVelocityFieldTransformParametersAdaptor< TTransform >, itk::PointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::BuildInformation, itk::ComplexConjugateImageAdaptor< TImage >, itk::FFTPadImageFilter< TInputImage, TOutputImage >, itk::FFTShiftImageFilter< TInputImage, TOutputImage >, itk::QuadEdgeMeshEulerOperatorFlipEdgeFunction< TMesh, TQEType >, itk::EdgePotentialImageFilter< TInputImage, TOutputImage >, itk::LogImageFilter< TInputImage, TOutputImage >, itk::RGBToLuminanceImageFilter< TInputImage, TOutputImage >, itk::ShiftScaleImageFilter< TInputImage, TOutputImage >, itk::BinaryReconstructionLabelMapFilter< TImage, TMarkerImage, TAttributeAccessor >, itk::LaplacianSharpeningImageFilter< TInputImage, TOutputImage >, itk::PCAShapeSignedDistanceFunction< TCoordRep, VSpaceDimension, TImage >, itk::UnsharpMaskLevelSetImageFilter< TInputImage, TOutputImage >, itk::TimeVaryingBSplineVelocityFieldTransform< TParametersValueType, VDimension >, itk::PointSetToPointSetRegistrationMethod< TFixedPointSet, TMovingPointSet >, itk::LabelMapToRGBImageFilter< TInputImage, TOutputImage >, itk::AutoPointerDataObjectDecorator< T >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::SquareImageFilter< TInputImage, TOutputImage >, itk::AttributeUniqueLabelMapFilter< TImage, TAttributeAccessor >, itk::LabelMapToLabelImageFilter< TInputImage, TOutputImage >, itk::ValuedRegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::FastIncrementalBinaryDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::ConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage >, itk::DerivativeImageFilter< TInputImage, TOutputImage >, itk::SPSAOptimizer, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::PatchBasedDenoisingImageFilter< TInputImage, TOutputImage >, itk::ConstantVelocityFieldTransformParametersAdaptor< TTransform >, itk::RecursiveMultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::TimeVaryingVelocityFieldTransformParametersAdaptor< TTransform >, itk::TemporalProcessObject, itk::VideoIOFactory, itk::Statistics::WeightedCentroidKdTreeGenerator< TSample >, itk::RayCastInterpolateImageFunction< TInputImage, TCoordRep >, itk::ExpandImageFilter< TInputImage, TOutputImage >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::ParametricPath< VDimension >, itk::NotImageFilter< TInputImage, TOutputImage >, itk::LabelContourImageFilter< TInputImage, TOutputImage >, itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >, itk::ContourDirectedMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::ProjectedLandweberDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::BSplineTransformParametersAdaptor< TTransform >, itk::DisplacementFieldTransformParametersAdaptor< TTransform >, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::ConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::FiniteDifferenceSparseImageFilter< TInputImageType, TSparseOutputImageType >, itk::BSplineCenteredResampleImageFilterBase< TInputImage, TOutputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::ConnectedRegionsMeshFilter< TInputMesh, TOutputMesh >, itk::DivideImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::ConvertLabelMapFilter< TInputImage, TOutputImage >, itk::LabelUniqueLabelMapFilter< TImage >, itk::GrayscaleConnectedOpeningImageFilter< TInputImage, TOutputImage >, itk::HausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::MaskFeaturePointSelectionFilter< TImage, TMask, TFeatures >, itk::LBFGSBOptimizer, itk::MRASlabIdentifier< TInputImage >, itk::Similarity2DTransform< TParametersValueType >, itk::ZeroFluxNeumannPadImageFilter< TInputImage, TOutputImage >, itk::VectorGradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >, itk::MinimumMaximumImageFilter< TInputImage >, itk::BinaryFillholeImageFilter< TInputImage >, itk::BinaryGrindPeakImageFilter< TInputImage >, itk::ShapeOpeningLabelMapFilter< TImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::GrayscaleConnectedClosingImageFilter< TInputImage, TOutputImage >, itk::BinaryThinningImageFilter< TInputImage, TOutputImage >, itk::MedianImageFilter< TInputImage, TOutputImage >, itk::PowellOptimizer, itk::ExponentialDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::CSVFileReaderBase, itk::CSVNumericObjectFileWriter< TValue, VRows, VColumns >, itk::DOMNodeXMLReader, itk::DOMNodeXMLWriter, itk::LabelToRGBImageFilter< TLabelImage, TOutputImage >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::QuasiNewtonOptimizerv4Template< TInternalComputationValueType >, itk::DemonsImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::FrustumSpatialFunction< VDimension, TInput >, itk::v3::Rigid3DTransform< TParametersValueType >, itk::FullToHalfHermitianImageFilter< TInputImage >, itk::HalfToFullHermitianImageFilter< TInputImage >, itk::ComplexToImaginaryImageFilter< TInputImage, TOutputImage >, itk::AttributeOpeningLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributePositionLabelMapFilter< TImage, TAttributeAccessor, VPhysicalPosition >, itk::RelabelLabelMapFilter< TImage >, itk::StatisticsLabelMapFilter< TImage, TFeatureImage >, itk::OtsuMultipleThresholdsImageFilter< TInputImage, TOutputImage >, itk::HConcaveImageFilter< TInputImage, TOutputImage >, itk::HConvexImageFilter< TInputImage, TOutputImage >, itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::FastMarchingUpwindGradientImageFilter< TLevelSet, TSpeedImage >, itk::SimilarityIndexImageFilter< TInputImage1, TInputImage2 >, itk::FFTConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::SimpleContourExtractorImageFilter< TInputImage, TOutputImage >, itk::CollidingFrontsImageFilter< TInputImage, TOutputImage >, itk::ImageModelEstimatorBase< TInputImage, TMembershipFunction >, itk::CenteredTransformInitializer< TTransform, TFixedImage, TMovingImage >, itk::IPLCommonImageIO, itk::DOMWriter< TInput >, itk::StimulateImageIO, itk::UnaryFrequencyDomainFilter< TImageType, TFrequencyIterator >, itk::watershed::BoundaryResolver< TPixelType, TDimension >, itk::AmoebaOptimizerv4, itk::SLICImageFilter< TInputImage, TOutputImage, TDistancePixel >, itk::VideoToVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::VideoFileReader< TOutputVideoStream >, itk::ImageAdaptor< TImage, TAccessor >, itk::HistogramToImageFilter< THistogram, TImage, TFunction >, itk::MultiTransform< TParametersValueType, VDimension, VSubDimensions >, itk::VnlHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::ImageMomentsCalculator< TImage >, itk::ComplexToPhaseImageFilter< TInputImage, TOutputImage >, itk::AttributeRelabelLabelMapFilter< TImage, TAttributeAccessor >, itk::ChangeLabelLabelMapFilter< TImage >, itk::MeanImageFilter< TInputImage, TOutputImage >, itk::ParticleSwarmOptimizer, itk::InverseDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::VotingBinaryIterativeHoleFillingImageFilter< TImage >, itk::VectorConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::BinaryImageToLevelSetImageAdaptor< TInputImage, LevelSetDenseImage< TLevelSetImage > >, itk::ObjectFactoryBase, itk::NoiseImageFilter< TInputImage, TOutputImage >, itk::Statistics::Sample< TMeasurementVector >, itk::BinShrinkImageFilter< TInputImage, TOutputImage >, itk::CoxDeBoorBSplineKernelFunction< VSplineOrder, TRealValueType >, itk::MirrorPadImageFilter< TInputImage, TOutputImage >, itk::CurvatureAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::InteriorExteriorMeshFilter< TInputMesh, TOutputMesh, TSpatialFunction >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, TBinaryPriorImage >, itk::BlobSpatialObject< TDimension >, itk::ImagePCADecompositionCalculator< TInputImage, TBasisImage >, itk::ComplexToRealImageFilter< TInputImage, TOutputImage >, itk::OrImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::XorImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::AttributeKeepNObjectsLabelMapFilter< TImage, TAttributeAccessor >, itk::OtsuMultipleThresholdsCalculator< TInputHistogram >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::BinaryMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryPruningImageFilter< TInputImage, TOutputImage >, itk::IsoContourDistanceImageFilter< TInputImage, TOutputImage >, itk::FastMarchingExtensionImageFilter< TLevelSet, TAuxValue, VAuxDimension, TSpeedImage >, itk::DiscreteGaussianDerivativeImageFilter< TInputImage, TOutputImage >, itk::GradientDifferenceImageToImageMetric< TFixedImage, TMovingImage >, itk::DOMReader< TOutput >, itk::LaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::GradientDescentLineSearchOptimizerv4Template< TInternalComputationValueType >, itk::PowellOptimizerv4< TInternalComputationValueType >, itk::ConicShellInteriorExteriorSpatialFunction< VDimension, TInput >, itk::ImageRegionSplitterMultidimensional, itk::VectorNeighborhoodOperatorImageFilter< TInputImage, TOutputImage >, itk::Statistics::GaussianDistribution, itk::Statistics::MahalanobisDistanceMembershipFunction< TVector >, itk::KernelTransform< TParametersValueType, VDimension >, itk::BSplineControlPointImageFilter< TInputImage, TOutputImage >, itk::BSplineControlPointImageFunction< TInputImage, TCoordRep >, itk::SimplexMeshVolumeCalculator< TInputMesh >, itk::RandomImageSource< TOutputImage >, itk::ImageMaskSpatialObject< TDimension, TPixel >, itk::AndImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::ComplexToModulusImageFilter< TInputImage, TOutputImage >, itk::BinaryContourImageFilter< TInputImage, TOutputImage >, itk::ShapeRelabelLabelMapFilter< TImage >, itk::ShapeUniqueLabelMapFilter< TImage >, itk::StatisticsKeepNObjectsLabelMapFilter< TImage >, itk::StatisticsOpeningLabelMapFilter< TImage >, itk::NormalizedCorrelationImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::RegularStepGradientDescentBaseOptimizer, itk::TransformToDisplacementFieldFilter< TOutputImage, TParametersValueType >, itk::GE4ImageIO, itk::BinaryMedianImageFilter< TInputImage, TOutputImage >, itk::LevelSetEquationContainer< TTermContainer >, itk::Rigid3DTransform< TParametersValueType >, itk::ImageFunction< TInputImage, TOutput, TCoordRep >, itk::PasteImageFilter< TInputImage, TSourceImage, TOutputImage >, itk::ComposeImageFilter< TInputImage, TOutputImage >, itk::ProjectionImageFilter< TInputImage, TOutputImage, TAccumulator >, itk::ShapeKeepNObjectsLabelMapFilter< TImage >, itk::StatisticsRelabelLabelMapFilter< TImage >, itk::LiThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::LevelSetNeighborhoodExtractor< TLevelSet >, itk::DeformableSimplexMesh3DBalloonForceFilter< TInputMesh, TOutputMesh >, itk::JPEG2000ImageIOFactory, itk::MRCImageIO, itk::LaplacianDeformationQuadEdgeMeshFilterWithHardConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::Version, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::MaskNeighborhoodOperatorImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::Statistics::TDistribution, itk::BSplineResampleImageFunction< TImageType, TCoordRep >, itk::SliceImageFilter< TInputImage, TOutputImage >, itk::FFTWForward1DFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWInverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::InverseFFTImageFilter< TInputImage, TOutputImage >, itk::VnlInverseFFTImageFilter< TInputImage, TOutputImage >, itk::WarpMeshFilter< TInputMesh, TOutputMesh, TDisplacementField >, itk::QuadEdgeMeshEulerOperatorJoinVertexFunction< TMesh, TQEType >, itk::FourierSeriesPath< VDimension >, itk::StatisticsPositionLabelMapFilter< TImage >, itk::IntermodesThresholdCalculator< THistogram, TOutput >, itk::LiThresholdCalculator< THistogram, TOutput >, itk::OtsuThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::YenThresholdCalculator< THistogram, TOutput >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::FastChamferDistanceImageFilter< TInputImage, TOutputImage >, itk::GenerateImageSource< TOutputImage >, itk::ParametricImageSource< TOutputImage >, itk::BinaryMaskToNarrowBandPointSetFilter< TInputImage, TOutputMesh >, itk::VTKImageImport< TOutputImage >, itk::ImageToImageMetricv4GetValueAndDerivativeThreader< ThreadedImageRegionPartitioner< TImageToImageMetricv4::VirtualImageDimension >, TImageToImageMetricv4 >, itk::JointHistogramMutualInformationComputeJointPDFThreader< ThreadedImageRegionPartitioner< TJointHistogramMetric::VirtualImageDimension >, TJointHistogramMetric >, itk::LabeledPointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::PointSetFunction< TInputPointSet, TOutput, TCoordRep >, itk::VideoSource< TOutputVideoStream >, itk::ImageRegionSplitterBase, itk::UnaryGeneratorImageFilter< TInputImage, TOutputImage >, itk::NthElementImageAdaptor< TImage, TOutputPixelType >, itk::Statistics::ChiSquareDistribution, itk::Statistics::ImageToListSampleAdaptor< TImage >, itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >, itk::Statistics::MaximumRatioDecisionRule, itk::Statistics::MembershipFunctionBase< TVector >, itk::CenteredSimilarity2DTransform< TParametersValueType >, itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< TInputImage, TCoordRep >, itk::RegionOfInterestImageFilter< TInputImage, TOutputImage >, itk::VnlRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::ParametricSpaceToImageSpaceMeshFilter< TInputMesh, TOutputMesh >, itk::LineSpatialObject< TDimension >, itk::TubeSpatialObject< TDimension, TSpatialObjectPointType >, itk::StatisticsImageFilter< TInputImage >, itk::AggregateLabelMapFilter< TImage >, itk::StatisticsUniqueLabelMapFilter< TImage >, itk::GaborImageSource< TOutputImage >, itk::GridImageSource< TOutputImage >, itk::FFTDiscreteGaussianImageFilterFactory, itk::ReinitializeLevelSetImageFilter< TLevelSet >, itk::TikhonovDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::TimeVaryingVelocityFieldIntegrationImageFilter< TTimeVaryingVelocityField, TDisplacementField >, itk::TransformParametersAdaptor< TTransform >, itk::MRCImageIOFactory, itk::SpeckleNoiseImageFilter< TInputImage, TOutputImage >, itk::BSplineSyNImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ImageDuplicator< TInputImage >, itk::TernaryGeneratorImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::Statistics::MembershipSample< TSample >, itk::ScaleSkewVersor3DTransform< TParametersValueType >, itk::WrapPadImageFilter< TInputImage, TOutputImage >, itk::FFTWComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::VoronoiSegmentationImageFilter< TInputImage, TOutputImage, TBinaryPriorImage >, itk::DTITubeSpatialObject< TDimension >, itk::AccumulateImageFilter< TInputImage, TOutputImage >, itk::OrthogonalSwath2DPathFilter< TFourierSeriesPath, TSwathMeritImage >, itk::Path< TInput, TOutput, VDimension >, itk::PolyLineParametricPath< VDimension >, itk::NormalizeImageFilter< TInputImage, TOutputImage >, itk::LabelMapFilter< TInputImage, TOutputImage >, itk::ShiftScaleLabelMapFilter< TImage >, itk::IsoDataThresholdCalculator< THistogram, TOutput >, itk::DoubleThresholdImageFilter< TInputImage, TOutputImage >, itk::GrayscaleDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::ConvolutionImageFilterBase< TInputImage, TKernelImage, TOutputImage >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::GradientVectorFlowImageFilter< TInputImage, TOutputImage, TInternalPixel >, itk::LevelSetVelocityNeighborhoodExtractor< TLevelSet, TAuxValue, VAuxDimension >, itk::BSplineExponentialDiffeomorphicTransform< TParametersValueType, VDimension >, itk::GaussianExponentialDiffeomorphicTransform< TParametersValueType, VDimension >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::CompareHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::ImageToImageMetric< TFixedImage, TMovingImage >, itk::KappaStatisticImageToImageMetric< TFixedImage, TMovingImage >, itk::AdditiveGaussianNoiseImageFilter< TInputImage, TOutputImage >, itk::SmoothingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::LevelSetEvolution< TEquationContainer, LevelSetDenseImage< TImage > >, itk::HeavisideStepFunction< TInput, TOutput >, itk::BinaryFunctorImageFilter< TInputImage1, TInputImage2, TOutputImage, TFunction >, itk::Statistics::GaussianMembershipFunction< TMeasurementVector >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::ComposeScaleSkewVersor3DTransform< TParametersValueType >, itk::Rigid2DTransform< TParametersValueType >, itk::VectorInterpolateImageFunction< TInputImage, TCoordRep >, itk::FlipImageFilter< TImage >, itk::NumericSeriesFileNames, itk::TransformMeshFilter< TInputMesh, TOutputMesh, TTransform >, itk::SurfaceSpatialObject< TDimension, TSpatialObjectPointType >, itk::AutoCropLabelMapFilter< TInputImage >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::HuangThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::IntermodesThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::IsoDataThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::KittlerIllingworthThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::MaximumEntropyThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::MomentsThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::RenyiEntropyThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ShanbhagThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::TriangleThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::GrayscaleMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::CumulativeGaussianOptimizer, itk::ParticleSwarmOptimizerBase, itk::IterativeInverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::LandmarkDisplacementFieldSource< TOutputImage >, itk::NormalizedMutualInformationHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::PointSetToSpatialObjectDemonsRegistration< TFixedPointSet, TMovingSpatialObject >, itk::GPUDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::DOMNode, itk::FrequencyBandImageFilter< TImageType, TFrequencyIterator >, itk::VTKImageExport< TInputImage >, itk::BSplineInterpolationWeightFunction< TCoordRep, VSpaceDimension, VSplineOrder >, itk::ImageSink< TInputImage >, itk::ThreadPool, itk::Statistics::DistanceMetric< TVector >, itk::Statistics::MixtureModelComponentBase< TSample >, itk::Statistics::RegionConstrainedSubsampler< TSample, TRegion >, itk::CenteredRigid2DTransform< TParametersValueType >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::VnlForwardFFTImageFilter< TInputImage, TOutputImage >, itk::QuadEdgeMeshFunctionBase< TMesh, TOutput >, itk::VoronoiDiagram2D< TCoordType >, itk::VoronoiSegmentationRGBImageFilter< TInputImage, TOutputImage >, itk::MeshFileWriter< TInputMesh >, itk::CastSpatialObjectFilter< ObjectDimension >, itk::ImageSpatialObject< TDimension, TPixelType >, itk::ChainCodePath2D, itk::CropLabelMapFilter< TInputImage >, itk::PadLabelMapFilter< TInputImage >, itk::ShapePositionLabelMapFilter< TImage >, itk::HuangThresholdCalculator< THistogram, TOutput >, itk::KappaSigmaThresholdImageCalculator< TInputImage, TMaskImage >, itk::MaximumEntropyThresholdCalculator< THistogram, TOutput >, itk::TriangleThresholdCalculator< THistogram, TOutput >, itk::YenThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::GrayscaleMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::CheckerBoardImageFilter< TImage >, itk::QuaternionRigidTransformGradientDescentOptimizer, itk::VersorTransformOptimizer, itk::ShapeSignedDistanceFunction< TCoordRep, VSpaceDimension >, itk::TimeVaryingVelocityFieldTransform< TParametersValueType, VDimension >, itk::GPUNeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType, TParentImageFilter >, itk::TransformParametersAdaptorBase< TTransform >, itk::TransformIOBaseTemplate< TParametersValueType >, itk::DiscreteGaussianCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::LevelSetEquationAdvectionTerm< TInput, TLevelSetContainer >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType >, itk::Statistics::CovarianceSampleFilter< TSample >, itk::GaussianDerivativeImageFunction< TInputImage, TOutput >, itk::GaussianInterpolateImageFunction< TInputImage, TCoordRep >, itk::PermuteAxesImageFilter< TImage >, itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >, itk::JoinSeriesImageFilter< TInputImage, TOutputImage >, itk::ChainCodePath< VDimension >, itk::HilbertPath< TIndexValue, VDimension >, itk::ModulusImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::RegionFromReferenceLabelMapFilter< TInputImage >, itk::KittlerIllingworthThresholdCalculator< THistogram, TOutput >, itk::RenyiEntropyThresholdCalculator< THistogram, TOutput >, itk::GrayscaleFunctionDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleFunctionErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::MorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, itk::VersorRigid3DTransformOptimizer, itk::DiscreteMeanCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::LevelSetEquationChanAndVeseExternalTerm< TInput, TLevelSetContainer >, itk::JointHistogramMutualInformationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::ByteSwapper< T >, itk::ImportImageFilter< TPixel, VImageDimension >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, TFunction >, itk::IdentityTransform< TParametersValueType, VDimension >, itk::NeighborhoodOperatorImageFunction< TInputImage, TOutput >, itk::VTKPolyDataMeshIO, itk::TIFFImageIO, itk::VTKImageIO, itk::SpatialObjectToImageFilter< TInputSpatialObject, TOutputImage >, itk::DivideOrZeroOutImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::BinaryClosingByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryOpeningByReconstructionImageFilter< TInputImage, TKernel >, itk::FastMarchingImageToNodePairContainerAdaptor< TInput, TOutput, TImage >, itk::GaborKernelFunction< TRealValueType >, itk::ExtensionVelocitiesImageFilter< TLevelSet, TAuxValue, VAuxDimension >, itk::ShapePriorMAPCostFunction< TFeatureImage, TOutputPixel >, itk::BSplineSmoothingOnUpdateDisplacementFieldTransform< TParametersValueType, VDimension >, itk::GPUGradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::BioRadImageIO, itk::GE5ImageIO, itk::SiemensVisionImageIO, itk::VotingBinaryHoleFillingImageFilter< TInputImage, TOutputImage >, itk::ImportImageContainer< TElementIdentifier, TElement >, itk::XMLFileOutputWindow, itk::RecursiveSeparableImageFilter< TInputImage, TOutputImage >, itk::Statistics::SpatialNeighborSubsampler< TSample, TRegion >, itk::CovarianceImageFunction< TInputImage, TCoordRep >, itk::MeanImageFunction< TInputImage, TCoordRep >, itk::ScatterMatrixImageFunction< TInputImage, TCoordRep >, itk::ConstantPadImageFilter< TInputImage, TOutputImage >, itk::VnlComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::MeshSource< TOutputMesh >, itk::TriangleMeshToSimplexMeshFilter< TInputMesh, TOutputMesh >, itk::QuadEdgeMeshTopologyChecker< TMesh >, itk::VoronoiDiagram2DGenerator< TCoordType >, itk::VTKImageIOFactory, itk::LandmarkSpatialObject< TDimension >, itk::PolylineMask2DImageFilter< TInputImage, TPolyline, TOutputImage >, itk::KappaSigmaThresholdImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::DilateObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::EuclideanDistancePointMetric< TFixedPointSet, TMovingPointSet, TDistanceMap >, itk::BioRadImageIOFactory, itk::GEAdwImageIO, itk::LSMImageIOFactory, itk::RGBGibbsPriorFilter< TInputImage, TClassifiedImage >, itk::DiscreteCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::LevelSetEquationChanAndVeseInternalTerm< TInput, TLevelSetContainer >, itk::RingBuffer< TElement >, itk::VideoFileWriter< TInputVideoStream >, itk::AtanRegularizedHeavisideStepFunction< TInput, TOutput >, itk::ImageContainerInterface< TElementIdentifier, TElement >, itk::IndexedContainerInterface< TElementIdentifier, TElement >, itk::Statistics::ListSample< TMeasurementVector >, itk::Statistics::StandardDeviationPerComponentSampleFilter< TSample >, itk::QuaternionRigidTransform< TParametersValueType >, itk::ScaleVersor3DTransform< TParametersValueType >, itk::MedianImageFunction< TInputImage, TCoordRep >, itk::StreamingImageIOBase, itk::EllipseSpatialObject< TDimension >, itk::MeshSpatialObject< TMesh >, itk::GetAverageSliceImageFilter< TInputImage, TOutputImage >, itk::MomentsThresholdCalculator< THistogram, TOutput >, itk::ShanbhagThresholdCalculator< THistogram, TOutput >, itk::BasicDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::ErodeObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::DifferenceOfGaussiansGradientImageFilter< TInputImage, TDataType >, itk::PointSetToImageMetric< TFixedPointSet, TMovingImage >, itk::MINCImageIOFactory, itk::RawImageIO< TPixel, VImageDimension >, itk::StimulateImageIOFactory, itk::SegmentationRegion, itk::VotingBinaryImageFilter< TInputImage, TOutputImage >, itk::DiscreteMaximumCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteMinimumCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscretePrincipalCurvaturesQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::LevelSetEquationCurvatureTerm< TInput, TLevelSetContainer, TCurvatureImage >, itk::LevelSetEquationOverlapPenaltyTerm< TInput, TLevelSetContainer >, itk::LevelSetEquationPropagationTerm< TInput, TLevelSetContainer, TPropagationImage >, itk::SingleValuedCostFunctionv4Template< TInternalComputationValueType >, itk::ExpectationBasedPointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::MeanSquaresImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::HeavisideStepFunctionBase< TInput, TOutput >, itk::OutputWindow, itk::SinRegularizedHeavisideStepFunction< TInput, TOutput >, itk::Statistics::GaussianRandomSpatialNeighborSubsampler< TSample, TRegion >, itk::Statistics::ImageToHistogramFilter< TImage >, itk::Statistics::MeanSampleFilter< TSample >, itk::Statistics::SubsamplerBase< TSample >, itk::Statistics::UniformRandomSpatialNeighborSubsampler< TSample, TRegion >, itk::Euler3DTransform< TParametersValueType >, itk::Similarity3DTransform< TParametersValueType >, itk::LinearInterpolateImageFunction< TInputImage, TCoordRep >, itk::MahalanobisDistanceThresholdImageFunction< TInputImage, TCoordRep >, itk::SumOfSquaresImageFunction< TInputImage, TCoordRep >, itk::Forward1DFFTImageFilter< TInputImage, TOutputImage >, itk::MeshToMeshFilter< TInputMesh, TOutputMesh >, itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >, itk::GiftiMeshIO, itk::GaussianSpatialObject< TDimension >, itk::SpatialObjectFactoryBase, itk::MultiplyImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::MeanReciprocalSquareDifferenceImageToImageMetric< TFixedImage, TMovingImage >, itk::MeanReciprocalSquareDifferencePointSetToImageMetric< TFixedPointSet, TMovingImage >, itk::GPUMeanImageFilter< TInputImage, TOutputImage >, itk::CSVArray2DDataObject< TData >, itk::LSMImageIO, itk::TransformFileWriterTemplate< TParametersValueType >, itk::SegmentationBorder, itk::LevelSetDenseImage< TImage >, itk::LevelSetEvolutionComputeIterationThreader< LevelSetDenseImage< TImage >, ThreadedImageRegionPartitioner< TImage::ImageDimension >, TLevelSetEvolution >, itk::ImageFilterToVideoFilterWrapper< TImageToImageFilter >, itk::Directory, itk::ImageRegionSplitterSlowDimension, itk::InteriorExteriorSpatialFunction< VDimension, TInput >, itk::Statistics::GaussianMixtureModelComponent< TSample >, itk::Statistics::ImageClassifierFilter< TSample, TInputImage, TOutputImage >, itk::VersorRigid3DTransform< TParametersValueType >, itk::GaussianBlurImageFunction< TInputImage, TOutput >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::ImageToParametricSpaceFilter< TInputImage, TOutputMesh >, itk::VTKPolyDataWriter< TInputMesh >, itk::Testing::StretchIntensityImageFilter< TInputImage, TOutputImage >, itk::MetaSceneConverter< VDimension, PixelType, TMeshTraits >, itk::PointBasedSpatialObject< TDimension, TSpatialObjectPointType >, itk::TernaryAddImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::HistogramThresholdCalculator< THistogram, TOutput >, itk::BasicErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::PhysicalPointImageSource< TOutputImage >, itk::CumulativeGaussianCostFunction, itk::NormalizedCorrelationImageToImageMetric< TFixedImage, TMovingImage >, itk::Bruker2dseqImageIOFactory, itk::SpatialObjectWriter< VDimension, PixelType, TMeshTraits >, itk::TransformFileReaderTemplate< TParametersValueType >, itk::LevelSetEquationLaplacianTerm< TInput, TLevelSetContainer >, itk::LevelSetEquationTermBase< TInputImage, TLevelSetContainer >, itk::ConjugateGradientLineSearchOptimizerv4Template< TInternalComputationValueType >, itk::LoggerOutput, itk::PoolMultiThreader, itk::ThreadedImageRegionPartitioner< VDimension >, itk::ThreadedIndexedContainerPartitioner, itk::Statistics::DecisionRule, itk::InterpolateImageFunction< TInputImage, TCoordRep >, itk::VectorMeanImageFunction< TInputImage, TCoordRep >, itk::InterpolateImageFilter< TInputImage, TOutputImage >, itk::VnlComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::JPEGImageIOFactory, itk::VTKPolyDataReader< TOutputMesh >, itk::PNGImageIOFactory, itk::TIFFImageIOFactory, itk::ImageShapeModelEstimatorBase< TInputImage, TOutputImage >, itk::LabelOverlapMeasuresImageFilter< TLabelImage >, itk::PathSource< TOutputPath >, itk::OtsuThresholdCalculator< THistogram, TOutput >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, THistogram >, itk::ShapePriorMAPCostFunctionBase< TFeatureImage, TOutputPixel >, itk::MRIBiasEnergyFunction< TImage, TImageMask, TBiasField >, itk::GPUImageDataManager< ImageType >, itk::NormalizedCorrelationPointSetToImageMetric< TFixedPointSet, TMovingImage >, itk::PointSetToPointSetMetric< TFixedPointSet, TMovingPointSet >, itk::SpatialObjectReader< VDimension, PixelType, TMeshTraits >, itk::watershed::SegmentTable< TScalar >, itk::MultiGradientOptimizerv4Template< TInternalComputationValueType >, itk::RegularStepGradientDescentOptimizerv4< TInternalComputationValueType >, itk::EuclideanDistancePointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::FrameDifferenceVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::GaussianSpatialFunction< TOutput, VImageDimension, TInput >, itk::MapContainer< TElementIdentifier, TElement >, itk::MinimumMaximumImageCalculator< TInputImage >, itk::StreamingImageFilter< TInputImage, TOutputImage >, itk::ThreadedDomainPartitioner< TDomain >, itk::Statistics::PointSetToListSampleAdaptor< TPointSet >, itk::Rigid3DPerspectiveTransform< TParametersValueType >, itk::VersorTransform< TParametersValueType >, itk::VectorLinearInterpolateImageFunction< TInputImage, TCoordRep >, itk::VectorNearestNeighborInterpolateImageFunction< TInputImage, TCoordRep >, itk::CropImageFilter< TInputImage, TOutputImage >, itk::VnlInverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::ImageSeriesReader< TOutputImage >, itk::QuadEdgeMeshBoundaryEdgesMeshFunction< TMesh >, itk::SpatialObjectToPointSetFilter< TPointBasedSpatialObject, TOutputPointSet >, itk::ChainCodeToFourierSeriesPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >, itk::BinomialBlurImageFilter< TInputImage, TOutputImage >, itk::GaussianSmoothingOnUpdateDisplacementFieldTransform< TParametersValueType, VDimension >, itk::GPUGradientAnisotropicDiffusionImageFilterFactory, itk::GPUBoxImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::TransformFactoryBase, itk::watershed::SegmentTree< TScalar >, itk::LevelSetEvolutionUpdateLevelSetsThreader< LevelSetDenseImage< TImage >, ThreadedImageRegionPartitioner< TImage::ImageDimension >, TLevelSetEvolution >, itk::FrameAverageVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::BSplineDerivativeKernelFunction< VSplineOrder, TRealValueType >, itk::BSplineKernelFunction< VSplineOrder, TRealValueType >, itk::DynamicLoader, itk::ProgressAccumulator, itk::TernaryFunctorImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage, TFunction >, itk::Statistics::MaskedImageToHistogramFilter< TImage, TMaskImage >, itk::Statistics::SampleToSubsampleFilter< TSample >, itk::Statistics::VectorContainerToListSampleAdaptor< TVectorContainer >, itk::TranslationTransform< TParametersValueType, VDimension >, itk::ExtrapolateImageFunction< TInputImage, TCoordRep >, itk::VarianceImageFunction< TInputImage, TCoordRep >, itk::NrrdImageIO, itk::Testing::ComparisonImageFilter< TInputImage, TOutputImage >, itk::NaryFunctorImageFilter< TInputImage, TOutputImage, TFunction >, itk::DisplacementFieldToBSplineImageFilter< TInputImage, TInputPointSet, TOutputImage >, itk::SpatialFunctionImageEvaluatorFilter< TSpatialFunction, TInputImage, TOutputImage >, itk::OneWayEquivalencyTable, itk::LevelSetEquationBinaryMaskTerm< TInput, TLevelSetContainer >, itk::Command, itk::FileOutputWindow, itk::GaussianDerivativeSpatialFunction< TOutput, VImageDimension, TInput >, itk::SpatialFunction< TOutput, VImageDimension, TInput >, itk::KernelImageFilter< TInputImage, TOutputImage, TKernel >, itk::Statistics::DistanceToCentroidMembershipFunction< TVector >, itk::Statistics::MahalanobisDistanceMetric< TVector >, itk::Statistics::SampleClassifierFilter< TSample >, itk::ScaleTransform< TParametersValueType, VDimension >, itk::VnlForward1DFFTImageFilter< TInputImage, TOutputImage >, itk::MeshIOFactory, itk::MetaImageIO, itk::PolygonSpatialObject< TDimension >, itk::OrthogonallyCorrected2DParametricPath, itk::BoxMeanImageFilter< TInputImage, TOutputImage >, itk::GradientMagnitudeImageFilter< TInputImage, TOutputImage >, itk::SphereSignedDistanceFunction< TCoordRep, VSpaceDimension >, itk::CenteredVersorTransformInitializer< TFixedImage, TMovingImage >, itk::PointsLocator< TPointsContainer >, itk::HDF5ImageIOFactory, itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >, itk::UpdateWhitakerSparseLevelSet< VDimension, TLevelSetValueType, TEquationContainer >, itk::RegistrationParameterScalesFromJacobian< TMetric >, itk::RegistrationParameterScalesFromShiftBase< TMetric >, itk::DecimateFramesVideoFilter< TVideoStream >, itk::BinaryThresholdSpatialFunction< TFunction >, itk::FunctionBase< TInput, TOutput >, itk::GaussianKernelFunction< TRealValueType >, itk::SymmetricEllipsoidInteriorExteriorSpatialFunction< VDimension, TInput >, itk::Statistics::NeighborhoodSampler< TSample >, itk::Statistics::WeightedCovarianceSampleFilter< TSample >, itk::BSplineTransformInitializer< TTransform, TImage >, itk::Euler2DTransform< TParametersValueType >, itk::BinaryThresholdImageFunction< TInputImage, TCoordRep >, itk::Inverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::BMPImageIO, itk::RegularSphereMeshSource< TOutputMesh >, itk::BYUMeshIO, itk::FreeSurferBinaryMeshIO, itk::PNGImageIO, itk::ArrowSpatialObject< TDimension >, itk::Function::ColormapFunction< TScalar, TRGBPixel >, itk::EigenAnalysis2DImageFilter< TInputImage, TEigenValueImage, TEigenVectorImage >, itk::GPUDataManager, itk::GPUUnaryFunctorImageFilter< TInputImage, TOutputImage, TFunction, TParentImageFilter >, itk::MeanSquaresPointSetToImageMetric< TFixedPointSet, TMovingImage >, itk::LevelSetDomainMapImageFilter< TInputImage, TOutputImage >, itk::LevelSetEquationTermContainer< TInputImage, TLevelSetContainer >, itk::UpdateMalcolmSparseLevelSet< VDimension, TEquationContainer >, itk::UpdateShiSparseLevelSet< VDimension, TEquationContainer >, itk::ImageToImageMetricv4GetValueAndDerivativeThreaderBase< TDomainPartitioner, TImageToImageMetricv4 >, itk::ColorTable< TComponent >, itk::EquivalencyTable, itk::KernelFunctionBase< TRealValueType >, itk::BoxImageFilter< TInputImage, TOutputImage >, itk::Statistics::DenseFrequencyContainer2, itk::Statistics::WeightedMeanSampleFilter< TSample >, itk::NeighborhoodBinaryThresholdImageFunction< TInputImage, TCoordRep >, itk::NiftiImageIOFactory, itk::BoxSpatialObject< TDimension >, itk::MetaImageConverter< VDimension, TPixel, TSpatialObjectType >, itk::ImageAndPathToImageFilter< TInputImage, TInputPath, TOutputImage >, itk::ImageToPathFilter< TInputImage, TOutputPath >, itk::BoxSigmaImageFilter< TInputImage, TOutputImage >, itk::InvertDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUReduction< TElement >, itk::CorrelationCoefficientHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::MeanSquaresHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::GE4ImageIOFactory, itk::GE5ImageIOFactory, itk::GEAdwImageIOFactory, itk::SiemensVisionImageIOFactory, itk::DOMTextNode, itk::MalcolmSparseLevelSetImage< VDimension >, itk::WhitakerSparseLevelSetImage< TOutput, VDimension >, itk::MultiStartOptimizerv4Template< TInternalComputationValueType >, itk::FileListVideoIO, itk::FileListVideoIOFactory, itk::PointSetToImageFilter< TInputPointSet, TOutputImage >, itk::StdStreamLogOutput, itk::RGBToVectorImageAdaptor< TImage >, itk::Statistics::SparseFrequencyContainer2, itk::NearestNeighborExtrapolateImageFunction< TInputImage, TCoordRep >, itk::BMPImageIOFactory, itk::GDCMImageIOFactory, itk::GiplImageIO, itk::GiplImageIOFactory, itk::BYUMeshIOFactory, itk::OBJMeshIOFactory, itk::OFFMeshIO, itk::OFFMeshIOFactory, itk::VTKPolyDataMeshIOFactory, itk::MetaImageIOFactory, itk::NrrdImageIOFactory, itk::GroupSpatialObject< TDimension >, itk::PathAndImageToPathFilter< TInputPath, TInputImage, TOutputPath >, itk::PathToChainCodePathFilter< TInputPath, TOutputChainCodePath >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::testhelper::ImageRegistrationMethodImageSource< TFixedPixelType, TMovingPixelType, VDimension >, itk::MeanSquaresImageToImageMetric< TFixedImage, TMovingImage >, itk::MutualInformationHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::HDF5TransformIOFactory, itk::MatlabTransformIOFactory, itk::LevelSetBase< TInput, VDimension, TOutput, TDomain >, itk::LevelSetEvolutionBase< TEquationContainer, TLevelSet >, itk::LevelSetQuadEdgeMesh< TMesh >, itk::Function::ConvergenceMonitoringFunction< TScalar, TEnergyValue >, itk::TBBMultiThreader, itk::TorusInteriorExteriorSpatialFunction< VDimension, TInput >, itk::AddImageAdaptor< TImage >, itk::VectorToRGBImageAdaptor< TImage >, itk::Statistics::ManhattanDistanceMetric< TVector >, itk::ElasticBodySplineKernelTransform< TParametersValueType, VDimension >, itk::ThinPlateR2LogRSplineKernelTransform< TParametersValueType, VDimension >, itk::JPEGImageIO, itk::QuadEdgeMeshEulerOperatorSplitVertexFunction< TMesh, TQEType >, itk::FreeSurferAsciiMeshIO, itk::FreeSurferAsciiMeshIOFactory, itk::FreeSurferBinaryMeshIOFactory, itk::GiftiMeshIOFactory, itk::OBJMeshIO, itk::MetaConverterBase< VDimension >, itk::MetaImageMaskConverter< VDimension >, itk::PathToPathFilter< TInputPath, TOutputPath >, itk::PolylineMaskImageFilter< TInputImage, TPolyline, TVector, TOutputImage >, itk::MultipleValuedNonLinearOptimizer, itk::Optimizer, itk::GPUImage< TPixel, VImageDimension >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::TxtTransformIOFactory, itk::NoiseBaseImageFilter< TInputImage, TOutputImage >, itk::LevelSetContainerBase< TIdentifier, TLevelSet >, itk::LevelSetSparseImage< TOutput, VDimension >, itk::GradientDescentOptimizerBasev4Template< TInternalComputationValueType >, itk::Function::WindowConvergenceMonitoringFunction< TScalar >, itk::EllipsoidInteriorExteriorSpatialFunction< VDimension, TInput >, itk::MatrixResizeableDataObject< TItemType >, itk::MultipleLogOutput, itk::StreamingProcessObject, itk::Statistics::EuclideanDistanceMetric< TVector >, itk::CenteredEuler3DTransform< TParametersValueType >, itk::ElasticBodyReciprocalSplineKernelTransform< TParametersValueType, VDimension >, itk::NearestNeighborInterpolateImageFunction< TInputImage, TCoordRep >, itk::MetaMeshConverter< VDimension, PixelType, TMeshTraits >, itk::SpatialObjectToImageStatisticsCalculator< TInputImage, TInputSpatialObject, TSampleDimension >, itk::PathToImageFilter< TInputPath, TOutputImage >, itk::VanHerkGilWermanErodeImageFilter< TImage, TKernel >, itk::LevenbergMarquardtOptimizer, itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< TParametersValueType, VDimension >, itk::PolygonGroupSpatialObjectXMLFileReader, itk::TransformIOFactoryTemplate< TParametersValueType >, itk::EdgeDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::NeighborhoodConnectedImageFilter< TInputImage, TOutputImage >, itk::LevelSetContainer< TIdentifier, TLevelSet >, itk::LevelSetImage< TInput, VDimension, TOutput >, itk::FiniteCylinderSpatialFunction< VDimension, TInput >, itk::LoggerManager, itk::UnaryCorrespondenceMatrix< TItemType >, itk::Statistics::EuclideanSquareDistanceMetric< TVector >, itk::Statistics::MaximumDecisionRule, itk::MetaContourConverter< VDimension >, itk::NonLinearOptimizer, itk::GPUAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::HistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::ShiSparseLevelSetImage< VDimension >, itk::GradientDescentOptimizerBasev4ModifyGradientByLearningRateThreaderTemplate< TInternalComputationValueType >, itk::GradientDescentOptimizerBasev4ModifyGradientByScalesThreaderTemplate< TInternalComputationValueType >, itk::OptimizerParameterScalesEstimatorTemplate< TInternalComputationValueType >, itk::RegistrationParameterScalesFromIndexShift< TMetric >, itk::RegistrationParameterScalesFromPhysicalShift< TMetric >, itk::SphereSpatialFunction< VImageDimension, TInput >, itk::ThreadLogger, itk::ScaleLogarithmicTransform< TParametersValueType, VDimension >, itk::ThinPlateSplineKernelTransform< TParametersValueType, VDimension >, itk::VolumeSplineKernelTransform< TParametersValueType, VDimension >, itk::MetaArrowConverter< VDimension >, itk::MetaBlobConverter< VDimension >, itk::MetaDTITubeConverter< VDimension >, itk::MetaEllipseConverter< VDimension >, itk::MetaGaussianConverter< VDimension >, itk::MetaGroupConverter< VDimension >, itk::MetaLandmarkConverter< VDimension >, itk::MetaLineConverter< VDimension >, itk::MetaSurfaceConverter< VDimension >, itk::MetaTubeConverter< VDimension >, itk::MetaVesselTubeConverter< VDimension >, itk::VanHerkGilWermanDilateImageFilter< TImage, TKernel >, itk::ConjugateGradientOptimizer, itk::SingleValuedNonLinearOptimizer, itk::BSplineExponentialDiffeomorphicTransformParametersAdaptor< TTransform >, itk::BSplineSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor< TTransform >, itk::GaussianExponentialDiffeomorphicTransformParametersAdaptor< TTransform >, itk::GaussianSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor< TTransform >, itk::VTKImageExportBase, itk::LevelSetDomainPartitionImageWithKdTree< TImage >, itk::SingleValuedNonLinearVnlOptimizerv4, itk::ImageRegionSplitterDirection, itk::Statistics::ScalarImageToHistogramGenerator< TImageType >, itk::QuadEdgeMeshEulerOperatorSplitFacetFunction< TMesh, TQEType >, itk::VoronoiPartitioningImageFilter< TInputImage, TOutputImage >, itk::MultipleValuedNonLinearVnlOptimizer, itk::SingleValuedNonLinearVnlOptimizer, itk::ConstantVelocityFieldTransform< TParametersValueType, VDimension >, itk::TxtTransformIOTemplate< TParametersValueType >, itk::DiscreteLevelSetImage< TOutput, VDimension >, itk::QuasiNewtonOptimizerv4EstimateNewtonStepThreaderTemplate< TInternalComputationValueType >, itk::RealTimeClock, itk::StoppingCriterionBase, itk::Statistics::MinimumDecisionRule, itk::FixedCenterOfRotationAffineTransform< TParametersValueType, VDimension >, itk::ImageToMeshFilter< TInputImage, TOutputMesh >, itk::QuadEdgeMeshEulerOperatorDeleteCenterVertexFunction< TMesh, TQEType >, itk::QuadEdgeMeshEulerOperatorSplitEdgeFunction< TMesh, TQEType >, itk::QuadEdgeMeshScalarDataVTKPolyDataWriter< TMesh >, itk::QuadEdgeMeshZipMeshFunction< TMesh, TQEType >, itk::CostFunctionTemplate< TInternalComputationValueType >, itk::RegularStepGradientDescentOptimizer, itk::VelocityFieldTransform< TParametersValueType, VDimension >, itk::LevelSetDomainPartition< TImage >, itk::LevelSetDomainPartitionImage< TImage >, itk::JointHistogramMutualInformationComputeJointPDFThreaderBase< TDomainPartitioner, TJointHistogramMetric >, itk::Logger, itk::QuadEdgeMeshEulerOperatorCreateCenterVertexFunction< TMesh, TQEType >, itk::SpatialObjectDuplicator< TInputSpatialObject >, itk::HistogramAlgorithmBase< TInputHistogram >, itk::MultipleValuedCostFunction, itk::CleanQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::QuadEdgeMeshDecimationCriterion< TMesh, TElement, TMeasure, TPriorityQueueWrapper >, itk::BSplineBaseTransform< TParametersValueType, VDimension, VSplineOrder >, itk::CenteredAffineTransform< TParametersValueType, VDimension >, itk::ScalableAffineTransform< TParametersValueType, VDimension >, itk::ImageIOFactory, itk::QuadEdgeMeshEulerOperatorJoinFacetFunction< TMesh, TQEType >, itk::SingleValuedCostFunction, itk::MatlabTransformIOTemplate< ParametersValueType >, itk::DiscreteCurvatureTensorQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::LevelSetDomainPartitionBase< TDomain >, itk::LevelSetDomainPartitionMesh< TMesh >, itk::MetaArrayWriter, itk::QuadricDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::LevelSetEvolutionStoppingCriterion< TLevelSetContainer >, itk::Statistics::RandomVariateGeneratorBase, itk::MetaArrayReader, itk::DecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::SquaredEdgeLengthDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::BinaryImageToLevelSetImageAdaptorBase< TInputImage, TLevelSet >, itk::WatershedMiniPipelineProgressCommand, itk::AnchorDilateImageFilter< TImage, TKernel >, itk::TextOutput, and itk::AnchorErodeImageFilter< TImage, TKernel >.
GetObjectName()
virtual const std::string& itk::Object::GetObjectName () const virtual
A facility to help application programmers set a human identifiable name for a given object. This has no inherent use in ITK, but is a convenience to allow developers to provide a name for this object.
GetTimeStamp()
virtual const TimeStamp& itk::Object::GetTimeStamp () const virtual
Return this object's time stamp.
Reimplemented in itk::RealTimeClock.
GlobalWarningDisplayOff()
static void itk::Object::GlobalWarningDisplayOff () inline static
Definition at line 143 of file itkObject.h.
GlobalWarningDisplayOn()
static void itk::Object::GlobalWarningDisplayOn () inline static
Definition at line 138 of file itkObject.h.
HasObserver()
bool itk::Object::HasObserver (const EventObject & event) const
Return true if an observer is registered for this event.
InvokeEvent() [1/2]
void itk::Object::InvokeEvent (const EventObject &)
Call Execute on all the Commands observing this event id.
InvokeEvent() [2/2]
void itk::Object::InvokeEvent (const EventObject &) const
Call Execute on all the Commands observing this event id. The actions triggered by this call doesn't modify this object.
itkGetGlobalDeclarationMacro()
itk::Object::itkGetGlobalDeclarationMacro (bool , GlobalWarningDisplay) private
Only used to synchronize the global variable across static libraries.
Modified()
virtual void itk::Object::Modified () const virtual
Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data.
Reimplemented in itk::ImageAdaptor< TImage, TAccessor >, itk::GrayscaleDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::MorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, and itk::NormalizeImageFilter< TInputImage, TOutputImage >.
Referenced by itk::Function::ConvergenceMonitoringFunction< double, double >::AddEnergyValue(), itk::Function::ConvergenceMonitoringFunction< double, double >::ClearEnergyValues(), itk::AdaptImageFilter< TInputImage, TOutputImage, TAccessor >::SetAccessor(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetAlpha(), itk::NotImageFilter< TInputImage, TOutputImage >::SetBackgroundValue(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetBeta(), itk::ExpNegativeImageFilter< TInputImage, TOutputImage >::SetFactor(), itk::NotImageFilter< TInputImage, TOutputImage >::SetForegroundValue(), itk::VectorIndexSelectionCastImageFilter< TInputImage, TOutputImage >::SetIndex(), itk::MatrixIndexSelectionImageFilter< TInputImage, TOutputImage >::SetIndices(), itk::Statistics::Sample< ImageJointDomainTraits< TImage >::MeasurementVectorType >::SetMeasurementVectorSize(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetOutputMaximum(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetOutputMinimum(), and itk::TransformParametersAdaptor< TTransform >::SetRequiredFixedParameters().
New()
static Pointer itk::Object::New () static
Method for creation through the object factory.
PrintObservers()
bool itk::Object::PrintObservers (std::ostream & os, Indent indent) const protected
PrintSelf()
void itk::Object::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::LightObject.
Reimplemented in itk::RegularSphereMeshSource< TOutputMesh >, itk::ImageBase< TLabelObject::ImageDimension >, itk::ImageBase< VectorImage< TPixelType, Dimension > ::ImageDimension >, itk::ImageBase< TImage::ImageDimension >, itk::ImageBase< 2 >, itk::Statistics::KdTree< TSample >, itk::ImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::ImageToImageMetricv4< TFixedImage, TMovingImage, TFixedImage, double, DefaultImageToImageMetricTraitsv4< TFixedImage, TMovingImage, TFixedImage, double > >, itk::ImageIOBase, itk::SpatialObject< VDimension >, itk::SpatialObject< 3 >, itk::SpatialObject< TDimension >, itk::SpatialObject< Mesh< int > ::PointDimension >, itk::MeshIOBase, itk::Mesh< TPixelType, VDimension, TMeshTraits >, itk::Mesh< TPixelType, 3, DefaultStaticMeshTraits< TPixelType, 3, 3, TPixelType, TPixelType, TPixelType > >, itk::Mesh< TPixel, VDimension, QuadEdgeMeshTraits< TPixel, VDimension, bool, bool > >, itk::Mesh< TCoordType, 2, DefaultDynamicMeshTraits< TCoordType, 2, 2, TCoordType > >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TimeVaryingBSplineVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, DisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ProcessObject, itk::MatrixOffsetTransformBase< TParametersValueType, VInputDimension, VOutputDimension >, itk::MRIBiasFieldCorrectionFilter< TInputImage, TOutputImage, TMaskImage >, itk::MatrixOffsetTransformBase< double, VDimension, VDimension >, itk::MatrixOffsetTransformBase< double, 2, 2 >, itk::MatrixOffsetTransformBase< double, 3, 3 >, itk::MatrixOffsetTransformBase< float, VDimension, VDimension >, itk::MatrixOffsetTransformBase< float, 3, 3 >, itk::ImageAdaptor< TImage, TAccessor >, itk::ImageAdaptor< TImage, Accessor::AsinPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::SqrtPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::VectorToRGBPixelAccessor< TImage::PixelType::ValueType > >, itk::ImageAdaptor< TImage, Accessor::CosPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::TanPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::AbsPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::ComplexToModulusPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::RGBToVectorPixelAccessor< TImage::PixelType::ComponentType > >, itk::ImageAdaptor< TImage, Accessor::SinPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::LogPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::ComplexToPhasePixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< VectorImage< TPixelType, Dimension >, Accessor::VectorImageToImagePixelAccessor< TPixelType > >, itk::ImageAdaptor< TImage, Accessor::Log10PixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::AtanPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::ComplexToRealPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::ComplexToImaginaryPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::ComplexConjugatePixelAccessor< TImage::PixelType > >, itk::ImageAdaptor< TImage, Accessor::ExpNegativePixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::AcosPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::AddPixelAccessor< TImage::PixelType > >, itk::ImageAdaptor< TImage, Accessor::RGBToLuminancePixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::ImageAdaptor< TImage, Accessor::ExpPixelAccessor< TImage::PixelType, TOutputPixelType > >, itk::LabelMap< TLabelObject >, itk::LBFGS2Optimizerv4Template< TInternalComputationValueType >, itk::DisplacementFieldTransform< TParametersValueType, VDimension >, itk::CompositeTransform< TParametersValueType, VDimension >, itk::PhasedArray3DSpecialCoordinatesImage< TPixel >, itk::FastMarchingImageFilter< TLevelSet, TSpeedImage >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType, TOutputImage >, itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, float, Image< float, TInputImage::ImageDimension > >, itk::ImageSource< VectorImage< float, TInputImage::ImageDimension > >, itk::ImageSource< TSparseOutputImage >, itk::ImageSource< TLevelSet >, itk::ImageSource< Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageSource< Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageSource< Image< float, TInputImage::ImageDimension > >, itk::ImageSource< ImageType >, itk::ImageSource< Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< TInputImage >, itk::ImageSource< itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageSource< Image< double, TInputImage::ImageDimension > >, itk::ImageSource< Image< DiffusionTensor3D< double >, 3 > >, itk::ImageSource< Image< SizeValueType, 3 > >, itk::ImageSource< TImage >, itk::ImageSource< Image< TOutputPixelType, 2 > >, itk::ImageSource< Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageSource< Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageSource< TClassifiedImage >, itk::ImageSource< TImageType >, itk::ImageSource< Image< TPixel, 2 > >, itk::ImageSource< TInputImage1 >, itk::ImageSource< Image< TPixel, 3 > >, itk::ImageSource< Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageSource< TDisplacementField >, itk::ImageSource< TLabelImage >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageSource< Image< double, 3 > >, itk::ImageSource< VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< TSparseOutputImageType >, itk::ImageSource< Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageSource< Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageSource< Image< float, 3 > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageSource< TEigenValueImage >, itk::ImageSource< Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::N4BiasFieldCorrectionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::Image< TPixel, 2 >, itk::Image< double, TInputImage::ImageDimension >, itk::Image< TNode *, 2 >, itk::Image< unsigned char, TInputImage::ImageDimension >, itk::SymmetricEigenAnalysisFixedDimensionImageFilter< TMatrixDimension, TInputImage, TOutputImage >, itk::GDCMImageIO, itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >, itk::BSplineInterpolateImageFunction< TImageType, TCoordRep, TCoefficientType >, itk::BSplineInterpolateImageFunction< TImageType, float, TImageType::PixelType >, itk::BSplineInterpolateImageFunction< TInputImage, typename TInputImage::PixelType >, itk::ParallelSparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::SparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TInputImage >, itk::SparseFieldLevelSetImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageMetric< TFixedImage, TMovingImage >, itk::VideoStream< TFrameType >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, itk::BSplineBaseTransform< TParametersValueType, VDimension, VSplineOrder >, itk::BSplineBaseTransform< double, 3, 3 >, itk::Statistics::Histogram< TMeasurement, TFrequencyContainer >, itk::WindowedSincInterpolateImageFunction< TInputImage, VRadius, TWindowFunction, TBoundaryCondition, TCoordRep >, itk::Statistics::JointDomainImageToListSampleAdaptor< TImage >, itk::SpecialCoordinatesImage< TPixel, VImageDimension >, itk::ObjectToObjectMetric< TFixedDimension, TMovingDimension, TVirtualImage, TParametersValueType >, itk::SpecialCoordinatesImage< TPixel, 3 >, itk::ObjectToObjectMetric< TFixedDimension, TMovingDimension, Image< double, TFixedDimension >, double >, itk::ObjectToObjectMetric< TFixedPointSet::PointDimension, TFixedPointSet ::PointDimension, Image< double, TFixedPointSet::PointDimension >, double >, itk::ObjectToObjectMetric< TFixedImage::ImageDimension, TMovingImage::ImageDimension, TFixedImage, double >, itk::ObjectToObjectMetric< TPointSet ::PointDimension, TPointSet ::PointDimension, Image< double, TPointSet ::PointDimension >, double >, itk::PatchBasedDenoisingBaseImageFilter< TInputImage, TOutputImage >, itk::PointSetToPointSetMetricWithIndexv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::PointSetToPointSetMetricWithIndexv4< TPointSet, TPointSet, double >, itk::PointSetToPointSetMetricWithIndexv4< TFixedPointSet, TFixedPointSet, double >, itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >, itk::BSplineDeformableTransform< TParametersValueType, VDimension, VSplineOrder >, itk::VoronoiDiagram2D< TCoordType >, itk::ShapeUniqueLabelMapFilter< TImage >, itk::MultiTransform< TParametersValueType, VDimension, VSubDimensions >, itk::MultiTransform< double, 3, 3 >, itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >, itk::Statistics::MembershipSample< TSample >, itk::Statistics::ImageToListSampleAdaptor< TImage >, itk::DiffusionTensor3DReconstructionImageFilter< TReferenceImagePixelType, TGradientImagePixelType, TTensorPixelType, TMaskImageType >, itk::ObjectToObjectOptimizerBaseTemplate< TInternalComputationValueType >, itk::ObjectToObjectOptimizerBaseTemplate< double >, itk::KLMRegionGrowImageFilter< TInputImage, TOutputImage >, itk::SparseFieldLayer< TNodeType >, itk::BSplineScatteredDataPointSetToImageFilter< TInputPointSet, TOutputImage >, itk::BSplineTransform< TParametersValueType, VDimension, VSplineOrder >, itk::SimplexMesh< TPixelType, VDimension, TMeshTraits >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::DisplacementFieldToBSplineImageFilter< TInputImage, TInputPointSet, TOutputImage >, itk::AffineTransform< TParametersValueType, VDimension >, itk::AffineTransform< double, 3 >, itk::AffineTransform< double, VDimension >, itk::BSplineControlPointImageFunction< TInputImage, TCoordRep >, itk::SparseFieldFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::Statistics::ListSample< TMeasurementVector >, itk::Statistics::ListSample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >, itk::Statistics::ListSample< TVectorContainer::Element >, itk::Statistics::ListSample< MeasurementVectorPixelTraits< TImage::PixelType >::MeasurementVectorType >, itk::Statistics::ListSample< TPointSet::PointType >, itk::Statistics::ListSample< ImageJointDomainTraits< TImage >::MeasurementVectorType >, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >, itk::SPSAOptimizer, itk::RelabelComponentImageFilter< TInputImage, TOutputImage >, itk::Statistics::GaussianDistribution, itk::Testing::ExtractSliceImageFilter< TInputImage, TOutputImage >, itk::Rigid2DTransform< TParametersValueType >, itk::Rigid2DTransform< double >, itk::watershed::Boundary< TScalar, TDimension >, itk::WatershedImageFilter< TInputImage >, itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >, itk::MattesMutualInformationImageToImageMetric< TFixedImage, TMovingImage >, itk::PointSet< TPixelType, VDimension, TMeshTraits >, itk::Statistics::PointSetToListSampleAdaptor< TPointSet >, itk::PointSet< TPixelType, VDimension, DefaultStaticMeshTraits< TPixelType, 3, 3, TPixelType, TPixelType, TPixelType > >, itk::PointSet< TPixel, VDimension, QuadEdgeMeshTraits< TPixel, VDimension, bool, bool > >, itk::PointSet< TPixelType, 3, DefaultStaticMeshTraits< TPixelType, 3, 3 > >, itk::PointSet< TCoordType, VDimension, DefaultDynamicMeshTraits< TCoordType, 2, 2, TCoordType > >, itk::Statistics::VectorContainerToListSampleAdaptor< TVectorContainer >, itk::ConnectedRegionsMeshFilter< TInputMesh, TOutputMesh >, itk::Statistics::HistogramToTextureFeaturesFilter< THistogram >, itk::ObjectToObjectMetricBaseTemplate< TInternalComputationValueType >, itk::ObjectToObjectMetricBaseTemplate< double >, itk::TriangleMeshToBinaryImageFilter< TInputMesh, TOutputImage >, itk::MetaArrayReader, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage >, itk::Rigid3DPerspectiveTransform< TParametersValueType >, itk::TranslationTransform< TParametersValueType, VDimension >, itk::KernelTransform< TParametersValueType, VDimension >, itk::KernelTransform< TParametersValueType, 3 >, itk::KernelTransform< double, 3 >, itk::ObjectFactoryBase, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LaplacianDeformationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::AzimuthElevationToCartesianTransform< TParametersValueType, VDimension >, itk::Statistics::ScalarImageToRunLengthMatrixFilter< TImageType, THistogramFrequencyContainer >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, Image< unsigned char, 2 > >, itk::FiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::WarpImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::MaskImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::DisplacementFieldJacobianDeterminantFilter< TInputImage, TRealType, TOutputImage >, itk::FiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::FiniteDifferenceImageFilter< TInputImage, TSparseOutputImage >, itk::FiniteDifferenceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::FiniteDifferenceImageFilter< TInputImageType, TSparseOutputImageType >, itk::LabelOverlapMeasuresImageFilter< TLabelImage >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, itk::KLMSegmentationRegion, itk::ChangeInformationImageFilter< TInputImage >, itk::MultiResolutionImageRegistrationMethod< TFixedImage, TMovingImage >, itk::Statistics::HistogramToRunLengthFeaturesFilter< THistogram >, itk::NarrowBandImageFilterBase< TInputImage, TOutputImage >, itk::NarrowBandImageFilterBase< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::Statistics::ChiSquareDistribution, itk::Statistics::TDistribution, itk::JensenHavrdaCharvatTsallisPointSetToPointSetMetricv4< TPointSet, TInternalComputationValueType >, itk::GradientDescentOptimizerv4Template< TInternalComputationValueType >, itk::GradientDescentOptimizerv4Template< double >, itk::Similarity2DTransform< TParametersValueType >, itk::Similarity2DTransform< double >, itk::CastSpatialObjectFilter< ObjectDimension >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::ObjectToObjectMultiMetricv4< TFixedDimension, TMovingDimension, TVirtualImage, TInternalComputationValueType >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< FeatureImageType, ImageType >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< ImageType, ImageType >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::WarpVectorImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::ImageSeriesWriter< TInputImage, TOutputImage >, itk::MaskNegatedImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::FastMarchingUpwindGradientImageFilter< TLevelSet, TSpeedImage >, itk::PatchBasedDenoisingImageFilter< TInputImage, TOutputImage >, itk::MattesMutualInformationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::ImageFileWriter< TInputImage >, itk::BinaryThresholdImageFilter< TInputImage, TOutputImage >, itk::Statistics::ScalarImageToTextureFeaturesFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::NarrowBandThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::watershed::SegmentTree< TScalar >, itk::VoronoiSegmentationRGBImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::ParticleSwarmOptimizerBase, itk::ImageKmeansModelEstimator< TInputImage, TMembershipFunction >, itk::CannyEdgeDetectionImageFilter< ImageType, ImageType >, itk::PipelineMonitorImageFilter< TImageType >, itk::SpatialObjectToImageFilter< TInputSpatialObject, TOutputImage >, itk::ImageMomentsCalculator< TImage >, itk::HistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::MultiScaleHessianBasedMeasureImageFilter< TInputImage, THessianImage, TOutputImage >, itk::PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::ImageFunction< TInputImage, TOutput, TCoordRep >, itk::ImageFunction< TInputImage, bool, float >, itk::ImageFunction< TInputImage, CovariantVector< double, TInputImage::ImageDimension >, float >, itk::ImageFunction< TInputImage, Vector< double, TInputImage::ImageDimension >, double >, itk::ImageFunction< TInputImage, NumericTraits< TInputImage::PixelType >::RealType, double >, itk::ImageFunction< TImageType, NumericTraits< TImageType ::PixelType >::RealType, float >, itk::ImageFunction< TInputImage, double >, itk::ImageFunction< TInputImage, TInputImage::PixelType, float >, itk::ImageFunction< TImageType, NumericTraits< TImageType ::PixelType >::RealType, double >, itk::ImageFunction< TInputImage, TInputImage::PixelType, double >, itk::ImageFunction< TInputImage, vnl_matrix< NumericTraits< TInputImage::PixelType::ValueType >::RealType >, float >, itk::ImageFunction< TInputImage, NumericTraits< TInputImage::PixelType >::RealType, float >, itk::ImageFunction< TInputImage, NumericTraits< TInputImage::PixelType >::RealType, typename TInputImage::PixelType >, itk::ImageFunction< TInputImage, TOutput >, itk::TimeVaryingBSplineVelocityFieldImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ImageRegistrationMethod< TFixedImage, TMovingImage >, itk::JointHistogramMutualInformationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::ThresholdLabelerImageFilter< TInputImage, TOutputImage >, itk::ScaleTransform< TParametersValueType, VDimension >, itk::ObjectByObjectLabelMapFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::ScaleTransform< float, 3 >, itk::DeformableSimplexMesh3DFilter< TInputMesh, TOutputMesh >, itk::GradientDescentOptimizerBasev4Template< TInternalComputationValueType >, itk::GradientDescentOptimizerBasev4Template< double >, itk::IntensityWindowingImageFilter< TInputImage, TOutputImage >, itk::ThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::VelocityFieldTransform< TParametersValueType, VDimension >, itk::TimeVaryingBSplineVelocityFieldTransformParametersAdaptor< TTransform >, itk::Statistics::ExpectationMaximizationMixtureModelEstimator< TSample >, itk::Statistics::ScalarImageToRunLengthFeaturesFilter< TImageType, THistogramFrequencyContainer >, itk::CentralDifferenceImageFunction< TInputImage, TCoordRep, TOutputType >, itk::RecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::watershed::SegmentTreeGenerator< ScalarType >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::BSplineControlPointImageFilter< TInputImage, TOutputImage >, itk::FFTConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::DiscreteGaussianDerivativeImageFilter< TInputImage, TOutputImage >, itk::DeformableSimplexMesh3DGradientConstraintForceFilter< TInputMesh, TOutputMesh >, itk::FFTConvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage, double >, itk::FFTConvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::NiftiImageIO, itk::ContourExtractor2DImageFilter< TInputImage >, itk::OnePlusOneEvolutionaryOptimizer, itk::ScalarToRGBColormapImageFilter< TInputImage, TOutputImage >, itk::LBFGSBOptimizer, itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::RGBGibbsPriorFilter< TInputImage, TClassifiedImage >, itk::QuasiNewtonOptimizerv4Template< TInternalComputationValueType >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::BayesianClassifierImageFilter< TInputVectorImage, TLabelsType, TPosteriorsPrecisionType, TPriorsPrecisionType >, itk::RegistrationParameterScalesEstimator< TMetric >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TOutputImage >, itk::ContourSpatialObject< TDimension >, itk::RescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::OFFMeshIO, itk::TIFFImageIO, itk::ConstantVelocityFieldTransform< TParametersValueType, VDimension >, itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::GDCMSeriesFileNames, itk::HistogramMatchingImageFilter< TInputImage, TOutputImage, THistogramMeasurement >, itk::ANTSNeighborhoodCorrelationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::ImageToSpatialObjectRegistrationMethod< TFixedImage, TMovingSpatialObject >, itk::FrequencyBandImageFilter< TImageType, TFrequencyIterator >, itk::KLMSegmentationBorder, itk::DanielssonDistanceMapImageFilter< ImageType, ImageType >, itk::Statistics::ScalarImageToCooccurrenceMatrixFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::MutualInformationImageToImageMetric< TFixedImage, TMovingImage >, itk::FreeSurferBinaryMeshIO, itk::MetaImageIO, itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::TransformToDisplacementFieldFilter< TOutputImage, TParametersValueType >, itk::RayCastInterpolateImageFunction< TInputImage, TCoordRep >, itk::ObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ImageSeriesReader< TOutputImage >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::LevelSetMotionRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::BinaryMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::BilateralImageFilter< TInputImage, TOutputImage >, itk::UnaryFrequencyDomainFilter< TImageType, TFrequencyIterator >, itk::VideoSource< TOutputVideoStream >, itk::UnaryFrequencyDomainFilter< TImageType, FrequencyFFTLayoutImageRegionIteratorWithIndex< TImageType > >, itk::VideoSource< TVideoStream >, itk::VideoSource< itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::PasteImageFilter< TInputImage, TSourceImage, TOutputImage >, itk::PCAShapeSignedDistanceFunction< TCoordRep, VSpaceDimension, TImage >, itk::VTKImageImport< TOutputImage >, itk::PathSource< TOutputPath >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::TimeVaryingBSplineVelocityFieldTransform< TParametersValueType, VDimension >, itk::PathSource< PolyLineParametricPath< 2 > >, itk::PathSource< OrthogonallyCorrected2DParametricPath >, itk::PathSource< TOutputChainCodePath >, itk::PathSource< TOutputFourierSeriesPath >, itk::SimplexMeshVolumeCalculator< TInputMesh >, itk::ClampImageFilter< TInputImage, TOutputImage >, itk::BSplineSmoothingOnUpdateDisplacementFieldTransform< TParametersValueType, VDimension >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::LandmarkBasedTransformInitializer< TTransform, TFixedImage, TMovingImage >, itk::CurvatureRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TImageForceFunction >, itk::ManifoldParzenWindowsPointSetFunction< TPointSet, TOutput, TCoordRep >, itk::Statistics::Sample< TMeasurementVector >, itk::CSVFileReaderBase, itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >, itk::Statistics::Sample< TVectorContainer::Element >, itk::Statistics::Sample< MeasurementVectorPixelTraits< TImage::PixelType >::MeasurementVectorType >, itk::Statistics::Sample< TPointSet::PointType >, itk::Statistics::Sample< Array< float > >, itk::Statistics::Sample< ImageJointDomainTraits< TImage >::MeasurementVectorType >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType >, itk::CenteredSimilarity2DTransform< TParametersValueType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::PointSetToImageRegistrationMethod< TFixedPointSet, TMovingImage >, itk::OnePlusOneEvolutionaryOptimizerv4< TInternalComputationValueType >, itk::FileListVideoIO, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::ShapeKeepNObjectsLabelMapFilter< TImage >, itk::OBJMeshIO, itk::CorrelationImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::FreeSurferAsciiMeshIO, itk::CSVArray2DDataObject< TData >, itk::PointSetToImageFilter< TInputPointSet, TOutputImage >, itk::CenteredRigid2DTransform< TParametersValueType >, itk::ShapeRelabelLabelMapFilter< TImage >, itk::LBFGSOptimizer, itk::LBFGSBOptimizerv4, itk::AdaptiveHistogramEqualizationImageFilter< TImageType, TKernel >, itk::SliceBySliceImageFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::GradientDescentOptimizer, itk::GPUNeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType, TParentImageFilter >, itk::BorderQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::GaussianBlurImageFunction< TInputImage, TOutput >, itk::JPEG2000ImageIO, itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::PointSetToImageMetric< TFixedPointSet, TMovingImage >, itk::GaussianDerivativeImageFunction< TInputImage, TOutput >, itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::PointSetToPointSetRegistrationMethod< TFixedPointSet, TMovingPointSet >, itk::ObjectStore< TObjectType >, itk::ShapeOpeningLabelMapFilter< TImage >, itk::GradientImageFilter< TInputImage, TOperatorValueType, TOutputValueType, TOutputImageType >, itk::AntiAliasBinaryImageFilter< TInputImage, TOutputImage >, itk::SignedMaurerDistanceMapImageFilter< TInputImage, TOutputImage >, itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::AmoebaOptimizer, itk::VectorThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ImageToSpatialObjectMetric< TFixedImage, TMovingSpatialObject >, itk::RawImageIO< TPixel, VImageDimension >, itk::OneWayEquivalencyTable, itk::Statistics::KdTreeBasedKmeansEstimator< TKdTree >, itk::Rigid3DTransform< TParametersValueType >, itk::InterpolateImagePointsFilter< TInputImage, TOutputImage, TCoordType, InterpolatorType >, itk::HilbertPath< TIndexValue, VDimension >, itk::ChangeLabelImageFilter< TInputImage, TOutputImage >, itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >, itk::TimeVaryingVelocityFieldIntegrationImageFilter< TTimeVaryingVelocityField, TDisplacementField >, itk::MultiStartOptimizerv4Template< TInternalComputationValueType >, itk::SLICImageFilter< TInputImage, TOutputImage, TDistancePixel >, itk::Rigid3DTransform< double >, itk::GeodesicActiveContourShapePriorLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::DiffeomorphicDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::TimeVaryingVelocityFieldImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::GaussianInterpolateImageFunction< TInputImage, TCoordRep >, itk::BSplineResampleImageFilterBase< TInputImage, TOutputImage >, itk::BinaryThresholdProjectionImageFilter< TInputImage, TOutputImage >, itk::NormalizedCorrelationImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::GaussianInterpolateImageFunction< TInputImage, double >, itk::Statistics::ProbabilityDistribution, itk::MahalanobisDistanceThresholdImageFunction< TInputImage, TCoordRep >, itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >, itk::BinaryProjectionImageFilter< TInputImage, TOutputImage >, itk::ScaleSkewVersor3DTransform< TParametersValueType >, itk::VectorNeighborhoodOperatorImageFilter< TInputImage, TOutputImage >, itk::MeshFileReader< TOutputMesh, ConvertPointPixelTraits, ConvertCellPixelTraits >, itk::MergeLabelMapFilter< TImage >, itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TInputImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension >, Function::RankHistogram< TInputImage::PixelType > >, itk::ChainCodePath< VDimension >, itk::BinaryShapeOpeningImageFilter< TInputImage >, itk::ClassifierBase< TDataContainer >, itk::ChainCodePath< 2 >, itk::ClassifierBase< TInputImage >, itk::ComposeScaleSkewVersor3DTransform< TParametersValueType >, itk::BYUMeshIO, itk::ChainCodePath2D, itk::BinaryShapeKeepNObjectsImageFilter< TInputImage >, itk::ZeroCrossingBasedEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::VideoIOBase, itk::ValarrayImageContainer< TElementIdentifier, TElement >, itk::CurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::QuaternionRigidTransform< TParametersValueType >, itk::AttributeSelectionLabelMapFilter< TImage, TAttributeAccessor >, itk::PowellOptimizer, itk::NarrowBandCurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapePriorMAPCostFunctionBase< TFeatureImage, TOutputPixel >, itk::BayesianClassifierInitializationImageFilter< TInputImage, TProbabilityPrecisionType >, itk::NormalQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::TemporalProcessObject, itk::AttributeSelectionLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::watershed::Relabeler< ScalarType, Self::ImageDimension >, itk::InterpolateImageFunction< TInputImage, TCoordRep >, itk::MeshSource< TOutputMesh >, itk::MetaArrayWriter, itk::StatisticsLabelMapFilter< TImage, TFeatureImage >, itk::GeodesicActiveContourLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::TransformIOBaseTemplate< TParametersValueType >, itk::InterpolateImageFunction< TImageType, float >, itk::InterpolateImageFunction< TImageType, double >, itk::InterpolateImageFunction< TInputImage, double >, itk::InterpolateImageFunction< TInputImage, typename TInputImage::PixelType >, itk::MeshSource< PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::MeshSource< TOutputPointSet >, itk::MeshSource< TOutput >, itk::MeshSource< VoronoiDiagram2D< TCoordType > >, itk::MeshSource< TInputMesh >, itk::MeshSource< PointSet< Vector< typename PointSet< Matrix< SpacePrecisionType, TFixedImage::ImageDimension, TFixedImage::ImageDimension >, TFixedImage::ImageDimension > ::PointType::ValueType, PointSet< Matrix< SpacePrecisionType, TFixedImage::ImageDimension, TFixedImage::ImageDimension >, TFixedImage::ImageDimension > ::PointDimension >, PointSet< Matrix< SpacePrecisionType, TFixedImage::ImageDimension, TFixedImage::ImageDimension >, TFixedImage::ImageDimension > ::PointDimension > >, itk::TransformIOBaseTemplate< ParametersValueType >, itk::ThresholdMaximumConnectedComponentsImageFilter< TInputImage, TOutputImage >, itk::ScalarImageKmeansImageFilter< TInputImage, TOutputImage >, itk::watershed::BoundaryResolver< TPixelType, TDimension >, itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicErodeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicDilateImageFilter< TInputImage, TOutputImage >, itk::ShapePriorMAPCostFunction< TFeatureImage, TOutputPixel >, itk::LandmarkDisplacementFieldSource< TOutputImage >, itk::TemporalDataObject, itk::Statistics::ImageClassifierFilter< TSample, TInputImage, TOutputImage >, itk::ScalableAffineTransform< TParametersValueType, VDimension >, itk::BinaryMask3DMeshSource< TInputImage, TOutputMesh >, itk::IsoContourDistanceImageFilter< TInputImage, TOutputImage >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::CurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::LandweberDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::InvertDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::ExhaustiveOptimizerv4< TInternalComputationValueType >, itk::ScalableAffineTransform< double, 3 >, itk::LandweberDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::MaskNeighborhoodOperatorImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::VersorTransform< TParametersValueType >, itk::VersorTransform< double >, itk::KappaSigmaThresholdImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::MaskFeaturePointSelectionFilter< TImage, TMask, TFeatures >, itk::Statistics::KdTreeGenerator< TSample >, itk::Statistics::UniformRandomSpatialNeighborSubsampler< TSample, TRegion >, itk::BinaryThresholdImageFunction< TInputImage, TCoordRep >, itk::InPlaceLabelMapFilter< TInputImage >, itk::OtsuMultipleThresholdsImageFilter< TInputImage, TOutputImage >, itk::RegularStepGradientDescentBaseOptimizer, itk::AmoebaOptimizerv4, itk::BinaryThresholdImageFunction< TInputImage, float >, itk::InPlaceLabelMapFilter< TImage >, itk::SparseImage< TNode, VImageDimension >, itk::MeshFileWriter< TInputMesh >, itk::ShapeLabelMapFilter< TImage, TLabelImage >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::ShapeLabelMapFilter< TImage, Image< TImage::PixelType, TImage::ImageDimension > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::Statistics::ImageToHistogramFilter< TImage >, itk::VectorRescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::HessianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::CompareHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::FastSymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::ImageSink< TImage >, itk::Similarity3DTransform< TParametersValueType >, itk::DirectedHausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::FastChamferDistanceImageFilter< TInputImage, TOutputImage >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::LabelOverlayImageFilter< TInputImage, TLabelImage, TOutputImage >, itk::PowellOptimizerv4< TInternalComputationValueType >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::ScaleVersor3DTransform< TParametersValueType >, itk::ShrinkImageFilter< TInputImage, TOutputImage >, itk::RandomImageSource< TOutputImage >, itk::GradientDifferenceImageToImageMetric< TFixedImage, TMovingImage >, itk::HDF5ImageIO, itk::LBFGSOptimizerBasev4< TInternalVnlOptimizerType >, itk::LBFGSOptimizerBasev4< vnl_lbfgs >, itk::LBFGSOptimizerBasev4< vnl_lbfgsb >, itk::Statistics::MixtureModelComponentBase< TSample >, itk::AnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::BinaryReconstructionByDilationImageFilter< TInputImage >, itk::BinaryReconstructionByErosionImageFilter< TInputImage >, itk::LevelSetNeighborhoodExtractor< TLevelSet >, itk::MovingHistogramImageFilterBase< TInputImage, TOutputImage, TKernel >, itk::Euler3DTransform< TParametersValueType >, itk::ImagePCAShapeModelEstimator< TInputImage, TOutputImage >, itk::PolyLineParametricPath< VDimension >, itk::ReinitializeLevelSetImageFilter< TLevelSet >, itk::BSplineTransformParametersAdaptor< TTransform >, itk::CenteredTransformInitializer< TTransform, TFixedImage, TMovingImage >, itk::ShotNoiseImageFilter< TInputImage, TOutputImage >, itk::VotingBinaryIterativeHoleFillingImageFilter< TImage >, itk::MovingHistogramImageFilterBase< TImageType, TImageType, Neighborhood< bool, TImageType::ImageDimension > >, itk::MovingHistogramImageFilterBase< TInputImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension > >, itk::Euler3DTransform< double >, itk::CenteredTransformInitializer< VersorRigid3DTransform< double >, TFixedImage, TMovingImage >, itk::GiftiMeshIO, itk::ThresholdImageFilter< TImage >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, TFunction1, TFunction2 >, itk::ContourMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::ConvolutionImageFilterBase< TInputImage, TKernelImage, TOutputImage >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::GPUDataManager, itk::LBFGSOptimizerv4, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::greater< TInputImage::PixelType >, std::greater< TOutputImage::PixelType > >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::less< TInputImage::PixelType >, std::less< TOutputImage::PixelType > >, itk::ConvolutionImageFilterBase< TInputImage, TInputImage, TInputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::IterativeDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::FFTWComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::StatisticsImageFilter< TInputImage >, itk::LabelShapeKeepNObjectsImageFilter< TInputImage >, itk::HistogramToImageFilter< THistogram, TImage, TFunction >, itk::VectorInterpolateImageFunction< TInputImage, TCoordRep >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::GrayscaleDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, TCompare >, itk::FFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage >, itk::DerivativeImageFilter< TInputImage, TOutputImage >, itk::HistogramToImageFilter< THistogram, Image< SizeValueType, 3 >, Function::HistogramIntensityFunction< SizeValueType, Image< SizeValueType, 3 > ::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramEntropyFunction< SizeValueType, Image< double, 3 > ::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< float, 3 >, Function::HistogramProbabilityFunction< SizeValueType, Image< float, 3 > ::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramLogProbabilityFunction< SizeValueType, Image< double, 3 > ::PixelType > >, itk::VectorInterpolateImageFunction< TInputImage, double >, itk::VectorInterpolateImageFunction< TInputImage, float >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::greater< TOutputImage::PixelType > >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::less< TOutputImage::PixelType > >, itk::PointBasedSpatialObject< TDimension, TSpatialObjectPointType >, itk::ImagePCADecompositionCalculator< TInputImage, TBasisImage >, itk::IntermodesThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ApproximateSignedDistanceMapImageFilter< TInputImage, TOutputImage >, itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::ImageClassifierBase< TInputImage, TClassifiedImage >, itk::ImageModelEstimatorBase< TInputImage, TMembershipFunction >, itk::RegularStepGradientDescentOptimizerv4< TInternalComputationValueType >, itk::DemonsImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::PointBasedSpatialObject< 3, LineSpatialObjectPoint< 3 > >, itk::PointBasedSpatialObject< 3, TubeSpatialObjectPoint< 3 > >, itk::PointBasedSpatialObject< 3 >, itk::PointBasedSpatialObject< 3, ContourSpatialObjectPoint< 3 > >, itk::PointBasedSpatialObject< TDimension, DTITubeSpatialObjectPoint< 3 > >, itk::PointBasedSpatialObject< 3, SurfaceSpatialObjectPoint< 3 > >, itk::PointBasedSpatialObject< 3, SpatialObjectPoint< 3 > >, itk::MinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< TInputImage, TCoordRep >, itk::LabelShapeOpeningImageFilter< TInputImage >, itk::GaussianImageSource< TOutputImage >, itk::HessianToObjectnessMeasureImageFilter< TInputImage, TOutputImage >, itk::KullbackLeiblerCompareHistogramImageToImageMetric< TFixedImage, TMovingImage >, itk::VTKImageExportBase, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::ExpandImageFilter< TInputImage, TOutputImage >, itk::MorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::FastMarchingExtensionImageFilter< TLevelSet, TAuxValue, VAuxDimension, TSpeedImage >, itk::WienerDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::MatchCardinalityImageToImageMetric< TFixedImage, TMovingImage >, itk::IPLCommonImageIO, itk::Statistics::DistanceMetric< TVector >, itk::BinaryErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::RegionGrowImageFilter< TInputImage, TOutputImage >, itk::Statistics::DistanceMetric< Array< double > >, itk::Statistics::MembershipFunctionBase< TVector >, itk::Statistics::SampleClassifierFilter< TSample >, itk::ShapePositionLabelMapFilter< TImage >, itk::ShapeDetectionLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::MRASlabIdentifier< TInputImage >, itk::ComposeDisplacementFieldsImageFilter< TInputImage, TOutputImage >, itk::ParameterizationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::MultiGradientOptimizerv4Template< TInternalComputationValueType >, itk::Statistics::MembershipFunctionBase< TMeasurementVector >, itk::VersorRigid3DTransform< TParametersValueType >, itk::FFTWHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::PathToImageFilter< TInputPath, TOutputImage >, itk::GrayscaleMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::ContourDirectedMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::HausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::GenerateImageSource< TOutputImage >, itk::BinaryMaskToNarrowBandPointSetFilter< TInputImage, TOutputMesh >, itk::ImplicitManifoldNormalVectorFilter< TInputImage, TSparseOutputImage >, itk::VideoToVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::VersorRigid3DTransform< double >, itk::VideoToVideoFilter< itk::VideoStream< TImageToImageFilter::InputImageType >, itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::VideoToVideoFilter< TVideoStream, TVideoStream >, itk::NearestNeighborExtrapolateImageFunction< TInputImage, TCoordRep >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::GrayscaleMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::PointSetToPointSetMetric< TFixedPointSet, TMovingPointSet >, itk::GPUDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::Bruker2dseqImageIO, itk::BSplineDecompositionImageFilter< TInputImage, TOutputImage >, itk::SumOfSquaresImageFunction< TInputImage, TCoordRep >, itk::ImageSpatialObject< TDimension, TPixelType >, itk::DoubleThresholdImageFilter< TInputImage, TOutputImage >, itk::SimilarityIndexImageFilter< TInputImage1, TInputImage2 >, itk::LevelSetDomainMapImageFilter< TInputImage, TOutputImage >, itk::ImageSpatialObject< 3, unsigned char >, itk::Statistics::SubsamplerBase< TSample >, itk::SliceImageFilter< TInputImage, TOutputImage >, itk::Testing::HashImageFilter< TImageType >, itk::TubeSpatialObject< TDimension, TSpatialObjectPointType >, itk::PolylineMaskImageFilter< TInputImage, TPolyline, TVector, TOutputImage >, itk::BinaryContourImageFilter< TInputImage, TOutputImage >, itk::MaskedRankImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel >, itk::RankImageFilter< TInputImage, TOutputImage, TKernel >, itk::RegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::ExponentialDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::SymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::StimulateImageIO, itk::LabeledPointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::InPlaceImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::InPlaceImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::InPlaceImageFilter< TLabelImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage, TInputImage >, itk::InPlaceImageFilter< TDisplacementField, TDisplacementField >, itk::InPlaceImageFilter< TInputImage, TSparseOutputImage >, itk::InPlaceImageFilter< TInputImage1, TOutputImage >, itk::InPlaceImageFilter< FeatureImageType, ImageType >, itk::InPlaceImageFilter< TImageType, TImageType >, itk::InPlaceImageFilter< TInputImage1, TInputImage1 >, itk::InPlaceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::InPlaceImageFilter< TMask, TImage >, itk::InPlaceImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::InPlaceImageFilter< TInputImageType, TSparseOutputImageType >, itk::InPlaceImageFilter< TImage, TImage >, itk::TubeSpatialObject< 3, DTITubeSpatialObjectPoint< 3 > >, itk::OutputWindow, itk::Euler2DTransform< TParametersValueType >, itk::FFTWInverseFFTImageFilter< TInputImage, TOutputImage >, itk::ExhaustiveOptimizer, itk::LaplacianSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::CenteredEuler3DTransform< TParametersValueType >, itk::BinShrinkImageFilter< TInputImage, TOutputImage >, itk::VoronoiSegmentationImageFilter< TInputImage, TOutputImage, TBinaryPriorImage >, itk::GaussianSpatialObject< TDimension >, itk::RegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::Hessian3DToVesselnessMeasureImageFilter< TPixel >, itk::ZeroCrossingImageFilter< TInputImage, TOutputImage >, itk::KappaStatisticImageToImageMetric< TFixedImage, TMovingImage >, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::ExpectationBasedPointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::Statistics::MahalanobisDistanceMembershipFunction< TVector >, itk::FFTWForwardFFTImageFilter< TInputImage, TOutputImage >, itk::TriangleMeshCurvatureCalculator< TInputMesh >, itk::ShapeRelabelImageFilter< TInputImage >, itk::GridImageSource< TOutputImage >, itk::SimpleContourExtractorImageFilter< TInputImage, TOutputImage >, itk::CSVArray2DFileReader< TData >, itk::MINCImageIO, itk::SaltAndPepperNoiseImageFilter< TInputImage, TOutputImage >, itk::MeanImageFunction< TInputImage, TCoordRep >, itk::FFTWRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::ParametricPath< VDimension >, itk::BinaryPruningImageFilter< TInputImage, TOutputImage >, itk::SobelEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::ImageGaussianModelEstimator< TInputImage, TMembershipFunction, TTrainingImage >, itk::CSVNumericObjectFileWriter< TValue, VRows, VColumns >, itk::ParametricPath< 2 >, itk::Statistics::CovarianceSampleFilter< TSample >, itk::Statistics::RegionConstrainedSubsampler< TSample, TRegion >, itk::VTKPolyDataMeshIO, itk::BinaryNotImageFilter< TImage >, itk::BinaryReconstructionLabelMapFilter< TImage, TMarkerImage, TAttributeAccessor >, itk::RegionFromReferenceLabelMapFilter< TInputImage >, itk::DelaunayConformingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::GradientDescentLineSearchOptimizerv4Template< TInternalComputationValueType >, itk::BinaryMinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::InterpolateImageFilter< TInputImage, TOutputImage >, itk::MorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, itk::SingleValuedNonLinearVnlOptimizer, itk::LevelSetVelocityNeighborhoodExtractor< TLevelSet, TAuxValue, VAuxDimension >, itk::Statistics::GaussianMembershipFunction< TMeasurementVector >, itk::NeighborhoodOperatorImageFunction< TInputImage, TOutput >, itk::ImageFileReader< TOutputImage, ConvertPixelTraits >, itk::SpatialObjectToImageStatisticsCalculator< TInputImage, TInputSpatialObject, TSampleDimension >, itk::LabelContourImageFilter< TInputImage, TOutputImage >, itk::OpeningByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< TParametersValueType, VDimension >, itk::BSplineExponentialDiffeomorphicTransformParametersAdaptor< TTransform >, itk::BSplineSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor< TTransform >, itk::VotingBinaryImageFilter< TInputImage, TOutputImage >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::VoronoiDiagram2DGenerator< TCoordType >, itk::GradientVectorFlowImageFilter< TInputImage, TOutputImage, TInternalPixel >, itk::CleanQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::VideoFileWriter< TInputVideoStream >, itk::Statistics::NormalVariateGenerator, itk::Statistics::SpatialNeighborSubsampler< TSample, TRegion >, itk::FlipImageFilter< TImage >, itk::VTKImageIO, itk::CropLabelMapFilter< TInputImage >, itk::PadLabelMapFilter< TInputImage >, itk::ClosingByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::ParametricBlindLeastSquaresDeconvolutionImageFilter< TInputImage, TKernelSource, TOutputImage >, itk::EuclideanDistancePointMetric< TFixedPointSet, TMovingPointSet, TDistanceMap >, itk::BinaryMedianImageFilter< TInputImage, TOutputImage >, itk::Statistics::MahalanobisDistanceMetric< TVector >, itk::MedianImageFunction< TInputImage, TCoordRep >, itk::RegularExpressionSeriesFileNames, itk::MinimumMaximumImageFilter< TInputImage >, itk::FourierSeriesPath< VDimension >, itk::InvertIntensityImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGrindPeakImageFilter< TInputImage, TOutputImage >, itk::ShapeSignedDistanceFunction< TCoordRep, VSpaceDimension >, itk::ProgressAccumulator, itk::CovarianceImageFunction< TInputImage, TCoordRep >, itk::ScatterMatrixImageFunction< TInputImage, TCoordRep >, itk::Path< TInput, TOutput, VDimension >, itk::Path< unsigned int, Index< 3 >, 3 >, itk::Path< double, ContinuousIndex< SpacePrecisionType, VDimension >, VDimension >, itk::Path< unsigned int, Offset< VDimension >, VDimension >, itk::KappaSigmaThresholdImageCalculator< TInputImage, TMaskImage >, itk::HardConnectedComponentImageFilter< TInputImage, TOutputImage >, itk::VideoFileReader< TOutputVideoStream >, itk::TriangleMeshToSimplexMeshFilter< TInputMesh, TOutputMesh >, itk::OrthogonallyCorrected2DParametricPath, itk::HMaximaImageFilter< TInputImage, TOutputImage >, itk::LaplacianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::InitializationBiasedParticleSwarmOptimizer, itk::Function::ColormapFunction< TScalar, TRGBPixel >, itk::StreamingImageFilter< TInputImage, TOutputImage >, itk::ThreadLogger, itk::FiniteDifferenceSparseImageFilter< TInputImageType, TSparseOutputImageType >, itk::JPEGImageIO, itk::CumulativeGaussianCostFunction, itk::AnisotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::InverseDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::IterativeInverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::FiniteDifferenceSparseImageFilter< TInputImage, TSparseOutputImage >, itk::InverseDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::VectorMeanImageFunction< TInputImage, TCoordRep >, itk::HMinimaImageFilter< TInputImage, TOutputImage >, itk::SmoothingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::MorphologicalWatershedImageFilter< TInputImage, TOutputImage >, itk::DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::ScaleLogarithmicTransform< TParametersValueType, VDimension >, itk::CoxDeBoorBSplineKernelFunction< VSplineOrder, TRealValueType >, itk::GaborKernelFunction< TRealValueType >, itk::PointsLocator< TPointsContainer >, itk::TransformParametersAdaptor< TTransform >, itk::MRCImageIO, itk::DenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::Statistics::DenseFrequencyContainer2, itk::NeighborhoodBinaryThresholdImageFunction< TInputImage, TCoordRep >, itk::VarianceImageFunction< TInputImage, TCoordRep >, itk::LabelToRGBImageFilter< TLabelImage, TOutputImage >, itk::LinearInterpolateImageFunction< TInputImage, TCoordRep >, itk::VTKPolyDataWriter< TInputMesh >, itk::Testing::ComparisonImageFilter< TInputImage, TOutputImage >, itk::MeshSpatialObject< TMesh >, itk::TikhonovDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::SingleValuedNonLinearVnlOptimizerv4, itk::VTKPolyDataWriter< TMesh >, itk::ExtrapolateImageFunction< TInputImage, TCoordRep >, itk::PNGImageIO, itk::EllipseSpatialObject< TDimension >, itk::ImageMaskSpatialObject< TDimension, TPixel >, itk::AccumulateImageFilter< TInputImage, TOutputImage >, itk::AttributeOpeningLabelMapFilter< TImage, TAttributeAccessor >, itk::FRPROptimizer, itk::DecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::TobogganImageFilter< TInputImage, TOutputImage >, itk::ExtrapolateImageFunction< TInputImage, float >, itk::Statistics::ScalarImageToHistogramGenerator< TImageType >, itk::ConstantPadImageFilter< TInputImage, TOutputImage >, itk::SpatialObjectToPointSetFilter< TPointBasedSpatialObject, TOutputPointSet >, itk::BinaryGrindPeakImageFilter< TInputImage >, itk::ErodeObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::RecursiveMultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::TransformFileWriterTemplate< TParametersValueType >, itk::ArchetypeSeriesFileNames, itk::ShiftScaleImageFilter< TInputImage, TOutputImage >, itk::ChangeLabelLabelMapFilter< TImage >, itk::Statistics::GaussianRandomSpatialNeighborSubsampler< TSample, TRegion >, itk::PermuteAxesImageFilter< TImage >, itk::QuadEdgeMeshEulerOperatorFlipEdgeFunction< TMesh, TQEType >, itk::AttributeKeepNObjectsLabelMapFilter< TImage, TAttributeAccessor >, itk::OtsuMultipleThresholdsCalculator< TInputHistogram >, itk::BlackTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::GaussianSmoothingOnUpdateDisplacementFieldTransform< TParametersValueType, VDimension >, itk::PointSetFunction< TInputPointSet, TOutput, TCoordRep >, itk::OtsuMultipleThresholdsCalculator< THistogram >, itk::PointSetFunction< TPointSet, double, double >, itk::Statistics::MaximumRatioDecisionRule, itk::Statistics::MeanSampleFilter< TSample >, itk::Statistics::SparseFrequencyContainer2, itk::CropImageFilter< TInputImage, TOutputImage >, itk::NormalizeToConstantImageFilter< TInputImage, TOutputImage >, itk::AttributeUniqueLabelMapFilter< TImage, TAttributeAccessor >, itk::RingBuffer< TElement >, itk::AttributeUniqueLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::QuadEdgeMeshEulerOperatorJoinVertexFunction< TMesh, TQEType >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::GrayscaleFillholeImageFilter< TInputImage, TOutputImage >, itk::WhiteTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::IsotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::RichardsonLucyDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::BSplineTransformInitializer< TTransform, TImage >, itk::BSplineCenteredResampleImageFilterBase< TInputImage, TOutputImage >, itk::PadImageFilter< TInputImage, TOutputImage >, itk::ProjectionImageFilter< TInputImage, TOutputImage, TAccumulator >, itk::HConcaveImageFilter< TInputImage, TOutputImage >, itk::HConvexImageFilter< TInputImage, TOutputImage >, itk::MeanReciprocalSquareDifferenceImageToImageMetric< TFixedImage, TMovingImage >, itk::MeanSquaresImageToImageMetric< TFixedImage, TMovingImage >, itk::NormalizedCorrelationPointSetToImageMetric< TFixedPointSet, TMovingImage >, itk::GPUDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::AdditiveGaussianNoiseImageFilter< TInputImage, TOutputImage >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Function::BinaryThresholdAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MaximumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::BinaryAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MedianAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::SumAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MeanAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::StandardDeviationAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MinimumAccumulator< TInputImage::PixelType > >, itk::Statistics::ScalarImageToCooccurrenceListSampleFilter< TImage >, itk::VTKPolyDataReader< TOutputMesh >, itk::Testing::StretchIntensityImageFilter< TInputImage, TOutputImage >, itk::AutoCropLabelMapFilter< TInputImage >, itk::BinaryFillholeImageFilter< TInputImage >, itk::GrayscaleConnectedOpeningImageFilter< TInputImage, TOutputImage >, itk::BinomialBlurImageFilter< TInputImage, TOutputImage >, itk::MeanReciprocalSquareDifferencePointSetToImageMetric< TFixedPointSet, TMovingImage >, itk::RegistrationParameterScalesFromJacobian< TMetric >, itk::PoolMultiThreader, itk::SimpleDataObjectDecorator< T >, itk::Statistics::WeightedCovarianceSampleFilter< TSample >, itk::NumericSeriesFileNames, itk::GrayscaleConnectedClosingImageFilter< TInputImage, TOutputImage >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, THistogram >, itk::BinaryMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryOpeningByReconstructionImageFilter< TInputImage, TKernel >, itk::GaborImageSource< TOutputImage >, itk::NormalizedCorrelationImageToImageMetric< TFixedImage, TMovingImage >, itk::IsolatedConnectedImageFilter< TInputImage, TOutputImage >, itk::MeanSquaresImageToImageMetricv4< TFixedImage, TMovingImage, TVirtualImage, TInternalComputationValueType, TMetricTraits >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::less< TInputImage::PixelType > > >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::greater< TInputImage::PixelType > > >, itk::Statistics::DistanceToCentroidMembershipFunction< TVector >, itk::Statistics::StandardDeviationPerComponentSampleFilter< TSample >, itk::BSplineL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::FFTPadImageFilter< TInputImage, TOutputImage >, itk::ImageToParametricSpaceFilter< TInputImage, TOutputMesh >, itk::PolygonSpatialObject< TDimension >, itk::AttributeRelabelLabelMapFilter< TImage, TAttributeAccessor >, itk::GPUReduction< TElement >, itk::AttributeRelabelLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::GPUReduction< float >, itk::GPUReduction< int >, itk::RecursiveSeparableImageFilter< TInputImage, TOutputImage >, itk::BSplineCenteredL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::ArrowSpatialObject< TDimension >, itk::BinaryMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::SphereSignedDistanceFunction< TCoordRep, VSpaceDimension >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::RecursiveSeparableImageFilter< TInputImage, TInputImage >, itk::GPUDenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::KernelImageFilter< TInputImage, TOutputImage, TKernel >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::DeformableSimplexMesh3DBalloonForceFilter< TInputMesh, TOutputMesh >, itk::BioRadImageIO, itk::SpeckleNoiseImageFilter< TInputImage, TOutputImage >, itk::Function::ConvergenceMonitoringFunction< TScalar, TEnergyValue >, itk::KernelImageFilter< TInputImage, TInputImage, TKernel >, itk::KernelImageFilter< TImageType, TImageType, Neighborhood< bool, TImageType::ImageDimension > >, itk::KernelImageFilter< TInputImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension > >, itk::KernelImageFilter< TImage, TImage, TKernel >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TInputImage >, itk::Function::ConvergenceMonitoringFunction< double, double >, itk::VectorNearestNeighborInterpolateImageFunction< TInputImage, TCoordRep >, itk::UnsharpMaskLevelSetImageFilter< TInputImage, TOutputImage >, itk::TransformFileReaderTemplate< TParametersValueType >, itk::Statistics::WeightedMeanSampleFilter< TSample >, itk::NearestNeighborInterpolateImageFunction< TInputImage, TCoordRep >, itk::SpatialObjectDuplicator< TInputSpatialObject >, itk::BinaryClosingByReconstructionImageFilter< TInputImage, TKernel >, itk::CumulativeGaussianOptimizer, itk::TensorFractionalAnisotropyImageFilter< TInputImage, TOutputImage >, itk::TensorRelativeAnisotropyImageFilter< TInputImage, TOutputImage >, itk::RegionOfInterestImageFilter< TInputImage, TOutputImage >, itk::BMPImageIO, itk::JoinSeriesImageFilter< TInputImage, TOutputImage >, itk::ImageAndPathToImageFilter< TInputImage, TInputPath, TOutputImage >, itk::IntermodesThresholdCalculator< THistogram, TOutput >, itk::MultipleValuedNonLinearVnlOptimizer, itk::ParticleSwarmOptimizer, itk::LSMImageIO, itk::VotingBinaryHoleFillingImageFilter< TInputImage, TOutputImage >, itk::ImageAndPathToImageFilter< TImage, ParametricPath< 2 >, TImage >, itk::Statistics::WeightedCentroidKdTreeGenerator< TSample >, itk::ShiftScaleLabelMapFilter< TImage >, itk::ConnectedThresholdImageFilter< TInputImage, TOutputImage >, itk::SpatialFunctionImageEvaluatorFilter< TSpatialFunction, TInputImage, TOutputImage >, itk::NrrdImageIO, itk::Optimizer, itk::CenteredVersorTransformInitializer< TFixedImage, TMovingImage >, itk::VectorConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::Statistics::GaussianMixtureModelComponent< TSample >, itk::VectorLinearInterpolateImageFunction< TInputImage, TCoordRep >, itk::ConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::RegistrationParameterScalesFromShiftBase< TMetric >, itk::PadImageFilterBase< TInputImage, TOutputImage >, itk::StreamingImageIOBase, itk::VoronoiPartitioningImageFilter< TInputImage, TOutputImage >, itk::PathAndImageToPathFilter< TInputPath, TInputImage, TOutputPath >, itk::AttributePositionLabelMapFilter< TImage, TAttributeAccessor, VPhysicalPosition >, itk::LabelMapToAttributeImageFilter< TInputImage, TOutputImage, TAttributeAccessor >, itk::TransformParametersAdaptorBase< TTransform >, itk::EuclideanDistancePointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >, itk::PadImageFilterBase< TInputImage, TInputImage >, itk::PathAndImageToPathFilter< TFourierSeriesPath, TSwathMeritImage, OrthogonallyCorrected2DParametricPath >, itk::TransformParametersAdaptorBase< Transform< TTransform::ScalarType, TTransform::InputSpaceDimension, TTransform::OutputSpaceDimension > >, itk::FFTShiftImageFilter< TInputImage, TOutputImage >, itk::TBBMultiThreader, itk::XMLFileOutputWindow, itk::GPUImageToImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::ConjugateGradientLineSearchOptimizerv4Template< TInternalComputationValueType >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BoxImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TInputImage, InPlaceImageFilter< TInputImage, TInputImage > >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, MeanImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DiscreteGaussianImageFilter< TInputImage, TOutputImage > >, itk::BoxSpatialObject< TDimension >, itk::OrthogonalSwath2DPathFilter< TFourierSeriesPath, TSwathMeritImage >, itk::DilateObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::CheckerBoardImageFilter< TImage >, itk::ParametricImageSource< TOutputImage >, itk::RegistrationParameterScalesFromIndexShift< TMetric >, itk::BoxImageFilter< TInputImage, TOutputImage >, itk::ElasticBodySplineKernelTransform< TParametersValueType, VDimension >, itk::DifferenceOfGaussiansGradientImageFilter< TInputImage, TDataType >, itk::PointSetToSpatialObjectDemonsRegistration< TFixedPointSet, TMovingSpatialObject >, itk::BoxImageFilter< TInputImage, TInputImage >, itk::BoxImageFilter< TImageType, TImageType >, itk::BoxImageFilter< TImage, TImage >, itk::ElasticBodyReciprocalSplineKernelTransform< TParametersValueType, VDimension >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::VTKImageExport< TInputImage >, itk::GiplImageIO, itk::SurfaceSpatialObject< TDimension, TSpatialObjectPointType >, itk::SegmentationRegion, itk::Forward1DFFTImageFilter< TInputImage, TOutputImage >, itk::Forward1DFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::StdStreamLogOutput, itk::TorusInteriorExteriorSpatialFunction< VDimension, TInput >, itk::InteriorExteriorMeshFilter< TInputMesh, TOutputMesh, TSpatialFunction >, itk::HistogramAlgorithmBase< TInputHistogram >, itk::AggregateLabelMapFilter< TImage >, itk::OtsuThresholdCalculator< THistogram, TOutput >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, TCompare1, TCompare2 >, itk::HistogramAlgorithmBase< THistogram >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, std::greater< TImage::PixelType >, std::less< TImage::PixelType > >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, std::less< TImage::PixelType >, std::greater< TImage::PixelType > >, itk::Statistics::SampleToSubsampleFilter< TSample >, itk::GPUMeanImageFilter< TInputImage, TOutputImage >, itk::QuadEdgeMeshDecimationCriterion< TMesh, TElement, TMeasure, TPriorityQueueWrapper >, itk::Function::WindowConvergenceMonitoringFunction< TScalar >, itk::LineSpatialObject< TDimension >, itk::ImageToPathFilter< TInputImage, TOutputPath >, itk::LaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::ImageToPathFilter< TInputImage, PolyLineParametricPath< 2 > >, itk::WarpMeshFilter< TInputMesh, TOutputMesh, TDisplacementField >, itk::ChainCodeToFourierSeriesPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::HuangThresholdCalculator< THistogram, TOutput >, itk::RenyiEntropyThresholdCalculator< THistogram, TOutput >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, MinFunctor< TImage::PixelType > >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, MaxFunctor< TImage::PixelType > >, itk::QuadEdgeMeshTopologyChecker< TMesh >, itk::SymmetricEllipsoidInteriorExteriorSpatialFunction< VDimension, TInput >, itk::Inverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::SingleValuedNonLinearOptimizer, itk::OptimizerParameterScalesEstimatorTemplate< TInternalComputationValueType >, itk::Inverse1DFFTImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::OptimizerParameterScalesEstimatorTemplate< TMetric::ParametersValueType >, itk::StreamingProcessObject, itk::Statistics::NeighborhoodSampler< TSample >, itk::BlobSpatialObject< TDimension >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::WatershedMiniPipelineProgressCommand, itk::AnchorErodeDilateImageFilter< TImage, TKernel, std::greater< TImage::PixelType > >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, std::less< TImage::PixelType > >, itk::GPUBoxImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::SegmentationBorder, itk::GPUBoxImageFilter< TInputImage, TOutputImage, MeanImageFilter< TInputImage, TOutputImage > >, itk::InteriorExteriorSpatialFunction< 3, Point< double, 3 > >, itk::TransformMeshFilter< TInputMesh, TOutputMesh, TTransform >, itk::PathToPathFilter< TInputPath, TOutputPath >, itk::PathToPathFilter< TInputPath, TOutputChainCodePath >, itk::PathToPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::PathToPathFilter< TFourierSeriesPath, OrthogonallyCorrected2DParametricPath >, itk::RealTimeClock, itk::GaussianSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor< TTransform >, itk::XMLReaderBase, itk::LaplacianDeformationQuadEdgeMeshFilterWithHardConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >, itk::SpatialFunction< TOutput, VImageDimension, TInput >, itk::DTITubeSpatialObject< TDimension >, itk::MultipleValuedNonLinearOptimizer, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GaussianExponentialDiffeomorphicTransformParametersAdaptor< TTransform >, itk::FrameDifferenceVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::ImageFilterToVideoFilterWrapper< TImageToImageFilter >, itk::SpatialFunction< double, VSpaceDimension, Point< TCoordRep, VSpaceDimension > >, itk::SpatialFunction< bool, VDimension, Point< double, 3 > >, itk::SpatialFunction< bool, 3, Point< double, 3 > >, itk::SpatialFunction< bool, TFunction::ImageDimension, TFunction::InputType >, itk::SpatialFunction< double, 3, Point< double, 3 > >, itk::SpatialFunction< double, 3, Point< SpacePrecisionType, 3 > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::SphereSpatialFunction< VImageDimension, TInput >, itk::ParametricSpaceToImageSpaceMeshFilter< TInputMesh, TOutputMesh >, itk::PathToChainCodePathFilter< TInputPath, TOutputChainCodePath >, itk::FrameAverageVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::GetAverageSliceImageFilter< TInputImage, TOutputImage >, itk::RegistrationParameterScalesFromPhysicalShift< TMetric >, itk::DecimateFramesVideoFilter< TVideoStream >, itk::LandmarkSpatialObject< TDimension >, itk::HDF5ImageIOFactory, itk::GPUAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::NoiseBaseImageFilter< TInputImage, TOutputImage >, itk::GaussianKernelFunction< double >, itk::KernelFunctionBase< double >, itk::GPUAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::NoiseBaseImageFilter< TInputImage, TInputImage >, itk::BYUMeshIOFactory, itk::OBJMeshIOFactory, itk::OFFMeshIOFactory, itk::VTKPolyDataMeshIOFactory, itk::NiftiImageIOFactory, itk::ImageShapeModelEstimatorBase< TInputImage, TOutputImage >, itk::GE4ImageIOFactory, itk::GE5ImageIOFactory, itk::GEAdwImageIOFactory, itk::SiemensVisionImageIOFactory, itk::ImageShapeModelEstimatorBase< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::FreeSurferAsciiMeshIOFactory, itk::FreeSurferBinaryMeshIOFactory, itk::GiftiMeshIOFactory, itk::DivideOrZeroOutImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::HDF5TransformIOFactory, itk::MatlabTransformIOFactory, itk::TxtTransformIOFactory, itk::NeighborhoodConnectedImageFilter< TInputImage, TOutputImage >, itk::CostFunctionTemplate< TInternalComputationValueType >, itk::CostFunctionTemplate< double >, itk::GroupSpatialObject< TDimension >, itk::GroupSpatialObject< 3 >, itk::MultiLabelSTAPLEImageFilter< TInputImage, TOutputImage, TWeights >, itk::STAPLEImageFilter< TInputImage, TOutputImage >, itk::LabelVotingImageFilter< TInputImage, TOutputImage >, itk::BSplineExponentialDiffeomorphicTransform< TParametersValueType, VDimension >, itk::CollidingFrontsImageFilter< TInputImage, TOutputImage >, itk::GradientMagnitudeImageFilter< TInputImage, TOutputImage >, itk::LaplacianImageFilter< TInputImage, TOutputImage >, itk::GaussianExponentialDiffeomorphicTransform< TParametersValueType, VDimension >, and itk::LaplacianSharpeningImageFilter< TInputImage, TOutputImage >.
Referenced by itk::OptimizerParameterScalesEstimatorTemplate< TMetric::ParametersValueType >::PrintSelf(), itk::QuadEdgeMeshDecimationCriterion< TMesh, TElement, TMeasure, TPriorityQueueWrapper >::PrintSelf(), itk::TransformParametersAdaptorBase< Transform< TTransform::ScalarType, TTransform::InputSpaceDimension, TTransform::OutputSpaceDimension > >::PrintSelf(), itk::Function::ConvergenceMonitoringFunction< double, double >::PrintSelf(), itk::Function::ColormapFunction< TScalar, TRGBPixel >::PrintSelf(), and itk::ValarrayImageContainer< TElementIdentifier, TElement >::PrintSelf().
Register()
void itk::Object::Register () const override virtual
Increase the reference count (mark as used by another object).
Reimplemented from itk::LightObject.
Referenced by itk::ScanlineFilterCommon< TInputImage, TOutputImage >::Register().
RemoveAllObservers()
void itk::Object::RemoveAllObservers ()
Remove all observers .
RemoveObserver()
void itk::Object::RemoveObserver (unsigned long tag)
Remove the observer with this tag value.
SetDebug()
void itk::Object::SetDebug (bool debugFlag) const
Set the value of the debug flag. A non-zero value turns debugging on.
SetGlobalWarningDisplay()
static void itk::Object::SetGlobalWarningDisplay (bool val) static
This is a global flag that controls whether any debug, warning or error messages are displayed.
SetMetaDataDictionary() [1/2]
void itk::Object::SetMetaDataDictionary (const MetaDataDictionary & rhs)
Set the MetaDataDictionary
SetMetaDataDictionary() [2/2]
void itk::Object::SetMetaDataDictionary (MetaDataDictionary && rrhs)
Set the MetaDataDictionary
SetObjectName()
virtual void itk::Object::SetObjectName (std::string _arg) virtual
A facility to help application programmers set a human identifiable name for a given object. This has no inherent use in ITK, but is a convenience to allow developers to provide a name for this object.
SetReferenceCount()
void itk::Object::SetReferenceCount (int) override virtual
Sets the reference count (use with care)
Reimplemented from itk::LightObject.
SetTimeStamp()
virtual void itk::Object::SetTimeStamp (const TimeStamp & timeStamp) protected virtual
Set the time stamp of this object. This method must be used very carefully !!!. Most mortals will never need to call this method.
UnRegister()
void itk::Object::UnRegister () const override virtual noexcept
Decrease the reference count (release by another object).
Reimplemented from itk::LightObject.
Referenced by itk::ScanlineFilterCommon< TInputImage, TOutputImage >::UnRegister().
Member Data Documentation
m_Debug
bool itk::Object::m_Debug { false } mutable private
Enable/Disable debug messages.
Definition at line 268 of file itkObject.h.
m_GlobalWarningDisplay
bool* itk::Object::m_GlobalWarningDisplay static private
Global object debug flag.
Definition at line 274 of file itkObject.h.
m_MetaDataDictionary
MetaDataDictionary* itk::Object::m_MetaDataDictionary { nullptr } mutable private
Implementation for holding Object MetaData
See also
itk::MetaDataDictionary
itk::MetaDataObjectBase
itk::MetaDataObject This is only allocated if used.
Definition at line 287 of file itkObject.h.
m_MTime
TimeStamp itk::Object::m_MTime mutable private
Keep track of modification time.
Definition at line 271 of file itkObject.h.
m_ObjectName
std::string itk::Object::m_ObjectName private
Definition at line 289 of file itkObject.h.
m_SubjectImplementation
SubjectImplementation* itk::Object::m_SubjectImplementation { nullptr } private
Implementation class for Subject/Observer Pattern. This is only allocated if used.
Definition at line 278 of file itkObject.h.
The documentation for this class was generated from the following file:
itkObject.h