ITK: itk::NumericTraits< RGBAPixel< T > > Class Template Reference
itk::NumericTraits< RGBAPixel< T > > Class Template Reference
Data Representation ObjectsGroup Core » | Module ITKCommon
#include <itkNumericTraitsRGBAPixel.h>
Public Types
using AbsType = RGBAPixel< ElementAbsType >
using AccumulateType = RGBAPixel< ElementAccumulateType >
using FloatType = RGBAPixel< ElementFloatType >
using MeasurementVectorType = Self
using PrintType = RGBAPixel< ElementPrintType >
using RealType = RGBAPixel< ElementRealType >
using ScalarRealType = ElementRealType
using Self = RGBAPixel< T >
using ValueType = T
Static Public Member Functions
static void AssignToArray (const Self &v, MeasurementVectorType &mv)
template<typename TArray >
static void AssignToArray (const Self &v, TArray &mv)
static unsigned int GetLength ()
static unsigned int GetLength (const RGBAPixel< T > &)
static bool IsNegative (Self val)
static bool IsNonnegative (Self val)
static bool IsNonpositive (Self val)
static bool IsPositive (Self val)
static const Self max ()
static const Self max (const Self &)
static const Self min ()
static const Self min (const Self &)
static const Self NonpositiveMin ()
static const Self NonpositiveMin (const Self &)
static const Self OneValue ()
static const Self OneValue (const Self &)
static const Self ZeroValue ()
static const Self ZeroValue (const Self &)
static void SetLength (RGBAPixel< T > &m, const unsigned int s)
Static Public Attributes
static constexpr bool IsComplex = NumericTraits<ValueType>::IsComplex
static constexpr bool IsInteger = std::is_integral<ValueType>::value
static constexpr bool IsSigned = std::is_signed<ValueType>::value
static const Self ITKCommon_EXPORT One
static const Self ITKCommon_EXPORT Zero
Private Types
using ElementAbsType = typename NumericTraits< T >::AbsType
using ElementAccumulateType = typename NumericTraits< T >::AccumulateType
using ElementFloatType = typename NumericTraits< T >::FloatType
using ElementPrintType = typename NumericTraits< T >::PrintType
using ElementRealType = typename NumericTraits< T >::RealType
Detailed Description
template<typename T>
class itk::NumericTraits< RGBAPixel< T > >
Define numeric traits for RGBAPixel.
Template Parameters
T Component type of RBGAPixel
We provide here a generic implementation based on creating types of RGBAPixel whose components are the types of the NumericTraits from the original RGBAPixel components. This implementation require support for partial specializations, since it is based on the concept that: NumericTraits<RGBAPixel< T > > is defined piecewise by RGBAPixel< NumericTraits< T > >
See also
NumericTraits
Definition at line 43 of file itkNumericTraitsRGBAPixel.h.
Member Typedef Documentation
AbsType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::AbsType = RGBAPixel<ElementAbsType>
Unsigned component type
Definition at line 59 of file itkNumericTraitsRGBAPixel.h.
AccumulateType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::AccumulateType = RGBAPixel<ElementAccumulateType>
Accumulation of addition and multiplication.
Definition at line 62 of file itkNumericTraitsRGBAPixel.h.
ElementAbsType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::ElementAbsType = typename NumericTraits<T>::AbsType private
Definition at line 46 of file itkNumericTraitsRGBAPixel.h.
ElementAccumulateType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::ElementAccumulateType = typename NumericTraits<T>::AccumulateType private
Definition at line 47 of file itkNumericTraitsRGBAPixel.h.
ElementFloatType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::ElementFloatType = typename NumericTraits<T>::FloatType private
Definition at line 48 of file itkNumericTraitsRGBAPixel.h.
ElementPrintType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::ElementPrintType = typename NumericTraits<T>::PrintType private
Definition at line 49 of file itkNumericTraitsRGBAPixel.h.
ElementRealType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::ElementRealType = typename NumericTraits<T>::RealType private
Definition at line 50 of file itkNumericTraitsRGBAPixel.h.
FloatType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::FloatType = RGBAPixel<ElementFloatType>
Typedef for operations that use floating point instead of real precision
Definition at line 66 of file itkNumericTraitsRGBAPixel.h.
MeasurementVectorType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::MeasurementVectorType = Self
Measurement vector type
Definition at line 78 of file itkNumericTraitsRGBAPixel.h.
PrintType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::PrintType = RGBAPixel<ElementPrintType>
Return the type that can be printed.
Definition at line 69 of file itkNumericTraitsRGBAPixel.h.
RealType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::RealType = RGBAPixel<ElementRealType>
Type for real-valued scalar operations.
Definition at line 72 of file itkNumericTraitsRGBAPixel.h.
ScalarRealType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::ScalarRealType = ElementRealType
Type for real-valued scalar operations.
Definition at line 75 of file itkNumericTraitsRGBAPixel.h.
Self
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::Self = RGBAPixel<T>
Definition at line 56 of file itkNumericTraitsRGBAPixel.h.
ValueType
template<typename T > using itk::NumericTraits< RGBAPixel< T > >::ValueType = T
Return the type of the native component type.
Definition at line 54 of file itkNumericTraitsRGBAPixel.h.
Member Function Documentation
AssignToArray() [1/2]
template<typename T > static void itk::NumericTraits< RGBAPixel< T > >::AssignToArray (const Self & v, MeasurementVectorType & mv) inline static
Definition at line 207 of file itkNumericTraitsRGBAPixel.h.
AssignToArray() [2/2]
template<typename T > template<typename TArray > static void itk::NumericTraits< RGBAPixel< T > >::AssignToArray (const Self & v, TArray & mv) inline static
Definition at line 214 of file itkNumericTraitsRGBAPixel.h.
GetLength() [1/2]
template<typename T > static unsigned int itk::NumericTraits< RGBAPixel< T > >::GetLength () inline static
Return the dimensionality of the pixel. Always returns 4.
Definition at line 201 of file itkNumericTraitsRGBAPixel.h.
GetLength() [2/2]
template<typename T > static unsigned int itk::NumericTraits< RGBAPixel< T > >::GetLength (const RGBAPixel< T > &) inline static
Return the dimensionality of the pixel. Always returns 4.
Definition at line 194 of file itkNumericTraitsRGBAPixel.h.
IsNegative()
template<typename T > static bool itk::NumericTraits< RGBAPixel< T > >::IsNegative (Self val) inline static
Is a given value negative?
Definition at line 161 of file itkNumericTraitsRGBAPixel.h.
References itk::RGBAPixel< TComponent >::GetLuminance(), and itk::NumericTraits< T >::IsNegative().
IsNonnegative()
template<typename T > static bool itk::NumericTraits< RGBAPixel< T > >::IsNonnegative (Self val) inline static
Is a given value nonnegative?
Definition at line 168 of file itkNumericTraitsRGBAPixel.h.
References itk::RGBAPixel< TComponent >::GetLuminance(), and itk::NumericTraits< T >::IsNonnegative().
IsNonpositive()
template<typename T > static bool itk::NumericTraits< RGBAPixel< T > >::IsNonpositive (Self val) inline static
Is a given value nonpositive?
Definition at line 154 of file itkNumericTraitsRGBAPixel.h.
References itk::RGBAPixel< TComponent >::GetLuminance(), and itk::NumericTraits< T >::IsNonpositive().
IsPositive()
template<typename T > static bool itk::NumericTraits< RGBAPixel< T > >::IsPositive (Self val) inline static
Is a given value positive?
Definition at line 147 of file itkNumericTraitsRGBAPixel.h.
References itk::RGBAPixel< TComponent >::GetLuminance(), and itk::NumericTraits< T >::IsPositive().
max() [1/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::max () inline static
Definition at line 98 of file itkNumericTraitsRGBAPixel.h.
max() [2/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::max (const Self &) inline static
Component wise defined elements
Note
minimum value for floating pointer types is defined as minimum positive normalize value.
Definition at line 86 of file itkNumericTraitsRGBAPixel.h.
min() [1/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::min () inline static
Definition at line 104 of file itkNumericTraitsRGBAPixel.h.
min() [2/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::min (const Self &) inline static
Definition at line 92 of file itkNumericTraitsRGBAPixel.h.
NonpositiveMin() [1/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::NonpositiveMin () inline static
Definition at line 110 of file itkNumericTraitsRGBAPixel.h.
NonpositiveMin() [2/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::NonpositiveMin (const Self &) inline static
Definition at line 128 of file itkNumericTraitsRGBAPixel.h.
References itk::NumericTraits< T >::NonpositiveMin().
OneValue() [1/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::OneValue () inline static
Definition at line 122 of file itkNumericTraitsRGBAPixel.h.
OneValue() [2/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::OneValue (const Self &) inline static
Definition at line 140 of file itkNumericTraitsRGBAPixel.h.
References itk::NumericTraits< T >::OneValue().
SetLength()
template<typename T > static void itk::NumericTraits< RGBAPixel< T > >::SetLength (RGBAPixel< T > & m, const unsigned int s) inline static
RGBA pixels must have 4 components, so the size cannot be set to anything besides 4. If called with size of 4, this function will fill the pixel with zeros.
Definition at line 181 of file itkNumericTraitsRGBAPixel.h.
References itk::FixedArray< unsigned short, 4 >::Fill().
ZeroValue() [1/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::ZeroValue () inline static
Definition at line 116 of file itkNumericTraitsRGBAPixel.h.
ZeroValue() [2/2]
template<typename T > static const Self itk::NumericTraits< RGBAPixel< T > >::ZeroValue (const Self &) inline static
Definition at line 134 of file itkNumericTraitsRGBAPixel.h.
References itk::NumericTraits< T >::ZeroValue().
Member Data Documentation
IsComplex
template<typename T > constexpr bool itk::NumericTraits< RGBAPixel< T > >::IsComplex = NumericTraits<ValueType>::IsComplex static constexpr
Definition at line 175 of file itkNumericTraitsRGBAPixel.h.
IsInteger
template<typename T > constexpr bool itk::NumericTraits< RGBAPixel< T > >::IsInteger = std::is_integral<ValueType>::value static constexpr
Definition at line 174 of file itkNumericTraitsRGBAPixel.h.
IsSigned
template<typename T > constexpr bool itk::NumericTraits< RGBAPixel< T > >::IsSigned = std::is_signed<ValueType>::value static constexpr
Definition at line 173 of file itkNumericTraitsRGBAPixel.h.
One
template<typename T > const Self ITKCommon_EXPORT itk::NumericTraits< RGBAPixel< T > >::One static
Definition at line 226 of file itkNumericTraitsRGBAPixel.h.
Zero
template<typename T > const Self ITKCommon_EXPORT itk::NumericTraits< RGBAPixel< T > >::Zero static
Note
: the functions are preferred over the member variables as they are defined for all partial specialization
Definition at line 225 of file itkNumericTraitsRGBAPixel.h.
The documentation for this class was generated from the following file:
itkNumericTraitsRGBAPixel.h