ITK: itk::TriangleHelper< TPoint > Class Template Reference
itk::TriangleHelper< TPoint > Class Template Reference
Group Core » Module ITKCommon
#include <itkTriangleHelper.h>
Public Types
using CoordRepType = typename PointType::CoordRepType
using CrossVectorType = CrossHelper< VectorType >
using PointType = TPoint
using Self = TriangleHelper
using VectorType = typename PointType::VectorType
Static Public Member Functions
static CoordRepType ComputeAngle (const PointType &iP1, const PointType &iP2, const PointType &iP3)
static CoordRepType ComputeArea (const PointType &iP1, const PointType &iP2, const PointType &iP3)
static PointType ComputeBarycenter (const CoordRepType &iA1, const PointType &iP1, const CoordRepType &iA2, const PointType &iP2, const CoordRepType &iA3, const PointType &iP3)
static PointType ComputeCircumCenter (const PointType &iP1, const PointType &iP2, const PointType &iP3)
static PointType ComputeConstrainedCircumCenter (const PointType &iP1, const PointType &iP2, const PointType &iP3)
static PointType ComputeGravityCenter (const PointType &iP1, const PointType &iP2, const PointType &iP3)
static CoordRepType ComputeMixedArea (const PointType &iP1, const PointType &iP2, const PointType &iP3)
static VectorType ComputeNormal (const PointType &iA, const PointType &iB, const PointType &iC)
static CoordRepType Cotangent (const PointType &iA, const PointType &iB, const PointType &iC)
static bool IsObtuse (const PointType &iA, const PointType &iB, const PointType &iC)
Static Public Attributes
static constexpr unsigned int PointDimension = PointType::PointDimension
Detailed Description
template<typename TPoint>
class itk::TriangleHelper< TPoint >
A convenience class for computation of various triangle elements in 2D or 3D.
Definition at line 31 of file itkTriangleHelper.h.
Member Typedef Documentation
CoordRepType
template<typename TPoint > using itk::TriangleHelper< TPoint >::CoordRepType = typename PointType::CoordRepType
Definition at line 36 of file itkTriangleHelper.h.
CrossVectorType
template<typename TPoint > using itk::TriangleHelper< TPoint >::CrossVectorType = CrossHelper<VectorType>
Definition at line 38 of file itkTriangleHelper.h.
PointType
template<typename TPoint > using itk::TriangleHelper< TPoint >::PointType = TPoint
Definition at line 35 of file itkTriangleHelper.h.
Self
template<typename TPoint > using itk::TriangleHelper< TPoint >::Self = TriangleHelper
Definition at line 34 of file itkTriangleHelper.h.
VectorType
template<typename TPoint > using itk::TriangleHelper< TPoint >::VectorType = typename PointType::VectorType
Definition at line 37 of file itkTriangleHelper.h.
Member Function Documentation
ComputeAngle()
template<typename TPoint > static CoordRepType itk::TriangleHelper< TPoint >::ComputeAngle (const PointType & iP1, const PointType & iP2, const PointType & iP3) static
Compute angles (iA,iB,iC)
Referenced by itk::DiscretePrincipalCurvaturesQuadEdgeMeshFilter< TInputMesh, TInputMesh >::ComputeMeanAndGaussianCurvatures().
ComputeArea()
template<typename TPoint > static CoordRepType itk::TriangleHelper< TPoint >::ComputeArea (const PointType & iP1, const PointType & iP2, const PointType & iP3) static
Compute Area.
ComputeBarycenter()
template<typename TPoint > static PointType itk::TriangleHelper< TPoint >::ComputeBarycenter (const CoordRepType & iA1, const PointType & iP1, const CoordRepType & iA2, const PointType & iP2, const CoordRepType & iA3, const PointType & iP3) static
Compute barycenter, with given weights.
ComputeCircumCenter()
template<typename TPoint > static PointType itk::TriangleHelper< TPoint >::ComputeCircumCenter (const PointType & iP1, const PointType & iP2, const PointType & iP3) static
Compute circum center.
ComputeConstrainedCircumCenter()
template<typename TPoint > static PointType itk::TriangleHelper< TPoint >::ComputeConstrainedCircumCenter (const PointType & iP1, const PointType & iP2, const PointType & iP3) static
Compute circum center constrained to be inside the triangle.
ComputeGravityCenter()
template<typename TPoint > static PointType itk::TriangleHelper< TPoint >::ComputeGravityCenter (const PointType & iP1, const PointType & iP2, const PointType & iP3) static
Compute center of mass.
ComputeMixedArea()
template<typename TPoint > static CoordRepType itk::TriangleHelper< TPoint >::ComputeMixedArea (const PointType & iP1, const PointType & iP2, const PointType & iP3) static
ComputeNormal()
template<typename TPoint > static VectorType itk::TriangleHelper< TPoint >::ComputeNormal (const PointType & iA, const PointType & iB, const PointType & iC) static
Compute Normal vector to the triangle formed by (iA,iB,iC)
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::AddTriangle(), and itk::DiscretePrincipalCurvaturesQuadEdgeMeshFilter< TInputMesh, TInputMesh >::ComputeMeanAndGaussianCurvatures().
Cotangent()
template<typename TPoint > static CoordRepType itk::TriangleHelper< TPoint >::Cotangent (const PointType & iA, const PointType & iB, const PointType & iC) static
Compute cotangent(iA,iB,iC)
Referenced by itk::ConformalMatrixCoefficients< TInputMesh >::operator()(), and itk::AuthalicMatrixCoefficients< TInputMesh >::operator()().
IsObtuse()
template<typename TPoint > static bool itk::TriangleHelper< TPoint >::IsObtuse (const PointType & iA, const PointType & iB, const PointType & iC) static
return true if (iA,iB,iC) forms an Obtuse angle (above 90 degrees)
Member Data Documentation
PointDimension
template<typename TPoint > constexpr unsigned int itk::TriangleHelper< TPoint >::PointDimension = PointType::PointDimension static constexpr
Definition at line 40 of file itkTriangleHelper.h.
The documentation for this class was generated from the following file:
itkTriangleHelper.h