ITK: itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix > Class Template Reference
itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix > Class Template Reference
Group Core » Module ITKCommon
#include <itkSymmetricEigenAnalysis.h>
Public Types
using EigenMatrixType = TEigenMatrix
using EigenValueOrderEnum = itk::EigenValueOrderEnum
using MatrixType = TMatrix
using VectorType = TVector
Public Member Functions
unsigned int ComputeEigenValues (const TMatrix &A, TVector &D) const
unsigned int ComputeEigenValuesAndVectors (const TMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors) const
unsigned int GetDimension () const
unsigned int GetOrder () const
bool GetOrderEigenMagnitudes () const
bool GetOrderEigenValues () const
void SetOrder (const unsigned int n)
SymmetricEigenAnalysis ()=default
SymmetricEigenAnalysis (const unsigned int dimension)
~SymmetricEigenAnalysis ()=default
void SetOrderEigenValues (const bool b)
void SetOrderEigenMagnitudes (const bool b)
void SetDimension (const unsigned int n)
void SetUseEigenLibrary (const bool input)
void SetUseEigenLibraryOn ()
void SetUseEigenLibraryOff ()
bool GetUseEigenLibrary () const
Private Member Functions
unsigned int ComputeEigenValuesAndVectorsLegacy (const TMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors) const
unsigned int ComputeEigenValuesAndVectorsUsingQL (double *d, double *e, double *z) const
unsigned int ComputeEigenValuesAndVectorsWithEigenLibrary (const TMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors) const
template<typename QMatrix >
auto ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors, bool) const -> decltype(GetPointerToMatrixData(A), 1U)
template<typename QMatrix >
auto ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors, long) const -> decltype(1U)
unsigned int ComputeEigenValuesLegacy (const TMatrix &A, TVector &D) const
unsigned int ComputeEigenValuesUsingQL (double *d, double *e) const
unsigned int ComputeEigenValuesWithEigenLibrary (const TMatrix &A, TVector &EigenValues) const
template<typename QMatrix >
auto ComputeEigenValuesWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, bool) const -> decltype(GetPointerToMatrixData(A), 1U)
template<typename QMatrix >
auto ComputeEigenValuesWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, long) const -> decltype(1U)
template<typename QMatrix = TMatrix>
auto GetMatrixValueType (...) const -> typename QMatrix::ValueType
template<typename QMatrix = TMatrix>
auto GetMatrixValueType (bool) const -> typename QMatrix::element_type
void ReduceToTridiagonalMatrix (double *a, double *d, double *e, double *e2) const
void ReduceToTridiagonalMatrixAndGetTransformation (const double *a, double *d, double *e, double *z) const
Private Attributes
unsigned int m_Dimension { 0 }
unsigned int m_Order { 0 }
EigenValueOrderEnum m_OrderEigenValues { EigenValueOrderEnum::OrderByValue }
bool m_UseEigenLibrary { false }
Detailed Description
template<typename TMatrix, typename TVector, typename TEigenMatrix = TMatrix>
class itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >
Find Eigen values of a real 2D symmetric matrix. It serves as a thread-safe alternative to the class: vnl_symmetric_eigensystem, which uses netlib routines.
The class is templated over the input matrix (which is expected to provide access to its elements with the [][] operator), matrix to store eigen values (must provide write operations on its elements with the [] operator), and EigenMatrix to store eigen vectors (must provide write access to its elements with the [][] operator).
The SetOrderEigenValues() method can be used to order eigen values (and their corresponding eigen vectors if computed) in ascending order. This is the default ordering scheme. Eigen vectors and values can be obtained without ordering by calling SetOrderEigenValues(false).
The SetOrderEigenMagnitudes() method can be used to order eigen values (and their corresponding eigen vectors if computed) by magnitude in ascending order.
The user of this class is explicitly supposed to set the dimension of the 2D matrix using the SetDimension() method.
The class contains routines taken from netlib sources (www.netlib.org). netlib/tql1.c netlib/tql2.c netlib/tred1.c netlib/tred2.c
Reference: num. math. 11, 293-306(1968) by bowdler, martin, reinsch, and wilkinson. handbook for auto. comp., vol.ii-linear algebra, 227-240(1971).
Definition at line 204 of file itkSymmetricEigenAnalysis.h.
Member Typedef Documentation
EigenMatrixType
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> using itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::EigenMatrixType = TEigenMatrix
Definition at line 223 of file itkSymmetricEigenAnalysis.h.
EigenValueOrderEnum
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> using itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::EigenValueOrderEnum = itk::EigenValueOrderEnum
Definition at line 207 of file itkSymmetricEigenAnalysis.h.
MatrixType
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> using itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::MatrixType = TMatrix
Definition at line 222 of file itkSymmetricEigenAnalysis.h.
VectorType
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> using itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::VectorType = TVector
Definition at line 224 of file itkSymmetricEigenAnalysis.h.
Constructor & Destructor Documentation
SymmetricEigenAnalysis() [1/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SymmetricEigenAnalysis () default
SymmetricEigenAnalysis() [2/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SymmetricEigenAnalysis (const unsigned int dimension) inline
Definition at line 215 of file itkSymmetricEigenAnalysis.h.
~SymmetricEigenAnalysis()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::~SymmetricEigenAnalysis () default
Member Function Documentation
ComputeEigenValues()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValues (const TMatrix & A, TVector & D) const
Compute Eigen values of A A is any type that overloads the [][] operator and contains the symmetric matrix. In practice only the upper triangle of the matrix will be accessed. (Both itk::Matrix and vnl_matrix overload [][] operator.)
'EigenValues' is any type that overloads the [][] operator and will contain the eigen values.
No size checking is performed. A is expected to be a square matrix of size m_Dimension. 'EigenValues' is expected to be of length m_Dimension. The matrix is not checked to see if it is symmetric.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::operator()().
ComputeEigenValuesAndVectors()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectors (const TMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors) const
Compute Eigen values and vectors of A A is any type that overloads the [][] operator and contains the symmetric matrix. In practice only the upper triangle of the matrix will be accessed. (Both itk::Matrix and vnl_matrix overload [][] operator.)
'EigenValues' is any type that overloads the [] operator and will contain the eigen values.
'EigenVectors' is any type that provides access to its elements with the [][] operator. It is expected be of size m_Dimension * m_Dimension.
No size checking is performed. A is expected to be a square matrix of size m_Dimension. 'EigenValues' is expected to be of length m_Dimension. The matrix is not checked to see if it is symmetric.
Each row of the matrix 'EigenVectors' represents an eigen vector. (unlike MATLAB where the columns of the [EigenVectors, EigenValues] = eig(A) contains the eigenvectors).
ComputeEigenValuesAndVectorsLegacy()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsLegacy (const TMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors) const private
ComputeEigenValuesAndVectorsUsingQL()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsUsingQL (double * d, double * e, double * z) const private
Finds the eigenvalues and eigenvectors of a symmetric tridiagonal matrix by the ql method.
On input: 'd' contains the diagonal elements of the input matrix. 'e' contains the subdiagonal elements of the input matrix in its last n-1 positions. e(1) is arbitrary. 'z' contains the transformation matrix produced in the reduction by ReduceToTridiagonalMatrixAndGetTransformation(), if performed. If the eigenvectors of the tridiagonal matrix are desired, z must contain the identity matrix.
On Output: 'd' contains the eigenvalues. 'e' has been destroyed. 'z' contains orthonormal eigenvectors of the symmetric tridiagonal (or full) matrix.
Returns: zero for normal return, j if the j-th eigenvalue has not been determined after 1000 iterations.
Reference This subroutine is a translation of the algol procedure tql1, num. math. 11, 293-306(1968) by bowdler, martin, reinsch, and wilkinson. handbook for auto. comp., vol.ii-linear algebra, 227-240(1971).
Questions and comments should be directed to Burton s. Garbow, Mathematics and Computer Science Div., Argonne National Laboratory. This version dated august 1983.
Function Adapted from netlib/tql2.c. [Changed: remove static vars, enforce const correctness. Use vnl routines as necessary]
ComputeEigenValuesAndVectorsWithEigenLibrary()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibrary (const TMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors) const inline private
Definition at line 534 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesAndVectorsWithEigenLibraryImpl() [1/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors, bool) const -> decltype(GetPointerToMatrixData(A), 1U) inline private
Definition at line 615 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesAndVectorsWithEigenLibraryImpl() [2/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors, long) const -> decltype(1U) inline private
Definition at line 549 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesLegacy()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesLegacy (const TMatrix & A, TVector & D) const private
ComputeEigenValuesUsingQL()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesUsingQL (double * d, double * e) const private
Finds the eigenvalues of a symmetric tridiagonal matrix by the ql method.
On input: 'd' contains the diagonal elements of the input matrix. 'e' contains the subdiagonal elements of the input matrix in its last n-1 positions. e(1) is arbitrary. On Output: 'd' contains the eigenvalues. 'e' has been destroyed.
Returns: zero for normal return, j if the j-th eigenvalue has not been determined after 30 iterations.
Reference This subroutine is a translation of the algol procedure tql1, num. math. 11, 293-306(1968) by bowdler, martin, reinsch, and wilkinson. handbook for auto. comp., vol.ii-linear algebra, 227-240(1971).
Questions and comments should be directed to Burton s. Garbow, Mathematics and Computer Science Div., Argonne National Laboratory. This version dated august 1983.
Function Adapted from netlib/tql1.c. [Changed: remove static vars, enforce const correctness. Use vnl routines as necessary]
ComputeEigenValuesWithEigenLibrary()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibrary (const TMatrix & A, TVector & EigenValues) const inline private
Definition at line 666 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesWithEigenLibraryImpl() [1/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, bool) const -> decltype(GetPointerToMatrixData(A), 1U) inline private
Definition at line 718 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesWithEigenLibraryImpl() [2/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, long) const -> decltype(1U) inline private
Definition at line 679 of file itkSymmetricEigenAnalysis.h.
GetDimension()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetDimension () const inline
Get Matrix dimension, Will be 0 unless explicitly set by a call to SetDimension.
Definition at line 344 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::GetDimension(), and itk::operator<<().
GetMatrixValueType() [1/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix = TMatrix> auto itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetMatrixValueType (...) const -> typename QMatrix::ValueType inline private
Definition at line 527 of file itkSymmetricEigenAnalysis.h.
GetMatrixValueType() [2/2]
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix = TMatrix> auto itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetMatrixValueType (bool) const -> typename QMatrix::element_type inline private
Definition at line 521 of file itkSymmetricEigenAnalysis.h.
GetOrder()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetOrder () const inline
Get the Matrix order. Will be 0 unless explicitly set, or unless a call to SetDimension has been made in which case it will be the matrix dimension.
Definition at line 277 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::operator<<().
GetOrderEigenMagnitudes()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> bool itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetOrderEigenMagnitudes () const inline
Definition at line 323 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::GetOrderEigenValuesBy(), and itk::operator<<().
GetOrderEigenValues()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> bool itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetOrderEigenValues () const inline
Definition at line 300 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::GetOrderEigenValuesBy(), and itk::operator<<().
GetUseEigenLibrary()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> bool itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetUseEigenLibrary () const inline
Set/Get to use Eigen library instead of vnl/netlib.
Definition at line 366 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::operator<<().
ReduceToTridiagonalMatrix()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ReduceToTridiagonalMatrix (double * a, double * d, double * e, double * e2) const private
Reduces a real symmetric matrix to a symmetric tridiagonal matrix using orthogonal similarity transformations. 'inputMatrix' contains the real symmetric input matrix. Only the lower triangle of the matrix need be supplied. The upper triangle is unaltered. 'd' contains the diagonal elements of the tridiagonal matrix. 'e' contains the subdiagonal elements of the tridiagonal matrix in its last n-1 positions. e(1) is set to zero. 'e2' contains the squares of the corresponding elements of e. 'e2' may coincide with e if the squares are not needed. questions and comments should be directed to burton s. garbow. mathematics and computer science div, argonne national laboratory this version dated august 1983.
Function adapted from netlib/tred1.c. [Changed: remove static vars, enforce const correctness. Use vnl routines as necessary]. Reference: num. math. 11, 181-195(1968) by martin, reinsch, and wilkinson. handbook for auto. comp., vol.ii-linear algebra, 212-226(1971).
ReduceToTridiagonalMatrixAndGetTransformation()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ReduceToTridiagonalMatrixAndGetTransformation (const double * a, double * d, double * e, double * z) const private
Reduces a real symmetric matrix to a symmetric tridiagonal matrix using and accumulating orthogonal similarity transformations. 'inputMatrix' contains the real symmetric input matrix. Only the lower triangle of the matrix need be supplied. The upper triangle is unaltered. 'diagonalElements' will contains the diagonal elements of the tridiagonal matrix. 'subDiagonalElements' will contain the subdiagonal elements of the tridiagonal matrix in its last n-1 positions. subDiagonalElements(1) is set to zero. 'transformMatrix' contains the orthogonal transformation matrix produced in the reduction.
Questions and comments should be directed to Burton s. Garbow, Mathematics and Computer Science Div., Argonne National Laboratory. This version dated august 1983.
Function adapted from netlib/tred2.c. [Changed: remove static vars, enforce const correctness. Use vnl routines as necessary]. Reference: num. math. 11, 181-195(1968) by martin, reinsch, and wilkinson. handbook for auto. comp., vol.ii-linear algebra, 212-226(1971).
SetDimension()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SetDimension (const unsigned int n) inline
Set the dimension of the input matrix A. A is a square matrix of size m_Dimension.
Definition at line 331 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::SetDimension().
SetOrder()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SetOrder (const unsigned int n) inline
Matrix order. Defaults to matrix dimension if not set
Definition at line 268 of file itkSymmetricEigenAnalysis.h.
SetOrderEigenMagnitudes()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SetOrderEigenMagnitudes (const bool b) inline
Set/Get methods to order the eigen value magnitudes in ascending order. In other words, |lambda_1| < |lambda_2| < .....
Definition at line 309 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::OrderEigenValuesBy().
SetOrderEigenValues()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SetOrderEigenValues (const bool b) inline
Set/Get methods to order the eigen values in ascending order. This is the default. ie lambda_1 < lambda_2 < ....
Definition at line 286 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TInputImage ::PixelType >::OrderEigenValuesBy().
SetUseEigenLibrary()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SetUseEigenLibrary (const bool input) inline
Set/Get to use Eigen library instead of vnl/netlib.
Definition at line 351 of file itkSymmetricEigenAnalysis.h.
SetUseEigenLibraryOff()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SetUseEigenLibraryOff () inline
Set/Get to use Eigen library instead of vnl/netlib.
Definition at line 361 of file itkSymmetricEigenAnalysis.h.
SetUseEigenLibraryOn()
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::SetUseEigenLibraryOn () inline
Set/Get to use Eigen library instead of vnl/netlib.
Definition at line 356 of file itkSymmetricEigenAnalysis.h.
Member Data Documentation
m_Dimension
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::m_Dimension { 0 } private
Definition at line 374 of file itkSymmetricEigenAnalysis.h.
m_Order
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::m_Order { 0 } private
Definition at line 375 of file itkSymmetricEigenAnalysis.h.
m_OrderEigenValues
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> EigenValueOrderEnum itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::m_OrderEigenValues { EigenValueOrderEnum::OrderByValue } private
Definition at line 376 of file itkSymmetricEigenAnalysis.h.
m_UseEigenLibrary
template<typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> bool itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::m_UseEigenLibrary { false } private
Definition at line 373 of file itkSymmetricEigenAnalysis.h.
The documentation for this class was generated from the following file:
itkSymmetricEigenAnalysis.h