ITK: itk::Neighborhood< TPixel, VDimension, TAllocator > Class Template Reference
itk::Neighborhood< TPixel, VDimension, TAllocator > Class Template Reference
Data Processing Objects » OperatorsData Access Objects » Iterators » | Image IteratorsGroup Core » | Module ITKCommon
#include <itkNeighborhood.h>
Public Types
using AllocatorType = TAllocator
using ConstIterator = typename AllocatorType::const_iterator
using DimensionValueType = unsigned int
using Iterator = typename AllocatorType::iterator
using NeighborIndexType = SizeValueType
using OffsetType = Offset< VDimension >
using PixelType = TPixel
using RadiusType = itk::Size< VDimension >
using Self = Neighborhood
using SizeType = itk::Size< VDimension >
using SizeValueType = typename SizeType::SizeValueType
using SliceIteratorType = SliceIterator< TPixel, Self >
Public Member Functions
NeighborIndexType GetCenterNeighborhoodIndex () const
TPixel GetCenterValue () const
virtual NeighborIndexType GetNeighborhoodIndex (const OffsetType &) const
OffsetType GetOffset (NeighborIndexType i) const
const SizeType GetRadius () const
SizeValueType GetRadius (DimensionValueType n) const
SizeType GetSize () const
SizeValueType GetSize (DimensionValueType n) const
std::slice GetSlice (unsigned int) const
OffsetValueType GetStride (DimensionValueType axis) const
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
itkTypeMacroNoParent (Neighborhood)
Neighborhood ()=default
Neighborhood (const Self &)=default
Neighborhood (Self &&)=default
Self & operator= (const Self &)=default
Self & operator= (Self &&)=default
bool operator== (const Self &other) const
void Print (std::ostream &os) const
void SetRadius (const SizeType &)
void SetRadius (const SizeValueType)
NeighborIndexType Size () const
virtual ~Neighborhood ()=default
Iterator End ()
Iterator Begin ()
ConstIterator End () const
ConstIterator Begin () const
TPixel & operator[] (NeighborIndexType i)
const TPixel & operator[] (NeighborIndexType i) const
TPixel & GetElement (NeighborIndexType i)
void SetRadius (const SizeValueType *rad)
AllocatorType & GetBufferReference ()
const AllocatorType & GetBufferReference () const
TPixel & operator[] (const OffsetType &o)
const TPixel & operator[] (const OffsetType &o) const
Static Public Attributes
static constexpr unsigned int NeighborhoodDimension = VDimension
Protected Member Functions
virtual void Allocate (NeighborIndexType i)
virtual void ComputeNeighborhoodOffsetTable ()
virtual void ComputeNeighborhoodStrideTable ()
virtual void PrintSelf (std::ostream &, Indent) const
void SetSize ()
Private Attributes
AllocatorType m_DataBuffer
std::vector< OffsetType > m_OffsetTable
SizeType m_Radius { { 0 } }
SizeType m_Size { { 0 } }
OffsetValueType m_StrideTable [VDimension] { 0 }
Detailed Description
template<typename TPixel, unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>>
class itk::Neighborhood< TPixel, VDimension, TAllocator >
A light-weight container object for storing an N-dimensional neighborhood of values.
This class serves as the base class for several other Itk objects such as itk::NeighborhoodOperator and itk::NeighborhoodIterator. Its purpose is to store values and their relative spatial locations.
A Neighborhood has an N-dimensional radius. The radius is defined separately for each dimension as the number of pixels that the neighborhood extends outward from the center pixel. For example, a 2D Neighborhood object with a radius of 2x3 has sides of length 5x7. Neighborhood objects always have an unambiguous center because their side lengths are always odd.
See also
Neighborhood
NeighborhoodIterator
Definition at line 54 of file itkNeighborhood.h.
Member Typedef Documentation
AllocatorType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::AllocatorType = TAllocator
External support for allocator type.
Definition at line 61 of file itkNeighborhood.h.
ConstIterator
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::ConstIterator = typename AllocatorType::const_iterator
Definition at line 76 of file itkNeighborhood.h.
DimensionValueType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::DimensionValueType = unsigned int
Type used to refer to space dimensions
Definition at line 92 of file itkNeighborhood.h.
Iterator
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::Iterator = typename AllocatorType::iterator
Iterator type alias support Note the naming is intentional, i.e., AllocatorType::iterator and AllocatorType::const_iterator, because the allocator may be a vnl object or other type, which uses this form.
Definition at line 75 of file itkNeighborhood.h.
NeighborIndexType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::NeighborIndexType = SizeValueType
Type used to refer to the elements of the pixel list that are part of the neighborhood.
Definition at line 96 of file itkNeighborhood.h.
OffsetType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::OffsetType = Offset<VDimension>
Offset type used to reference neighbor locations
Definition at line 86 of file itkNeighborhood.h.
PixelType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::PixelType = TPixel
External support for pixel type.
Definition at line 70 of file itkNeighborhood.h.
RadiusType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::RadiusType = itk::Size<VDimension>
Radius type alias support
Definition at line 83 of file itkNeighborhood.h.
Self
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::Self = Neighborhood
Standard class type aliases.
Definition at line 58 of file itkNeighborhood.h.
SizeType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::SizeType = itk::Size<VDimension>
Size and value type alias support
Definition at line 79 of file itkNeighborhood.h.
SizeValueType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::SizeValueType = typename SizeType::SizeValueType
Definition at line 80 of file itkNeighborhood.h.
SliceIteratorType
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::SliceIteratorType = SliceIterator<TPixel, Self>
External slice iterator type type alias support
Definition at line 89 of file itkNeighborhood.h.
Constructor & Destructor Documentation
Neighborhood() [1/3]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> itk::Neighborhood< TPixel, VDimension, TAllocator >::Neighborhood () default
Default constructor.
~Neighborhood()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> virtual itk::Neighborhood< TPixel, VDimension, TAllocator >::~Neighborhood () virtual default
Default destructor.
Neighborhood() [2/3]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> itk::Neighborhood< TPixel, VDimension, TAllocator >::Neighborhood (const Self &) default
Copy constructor.
Neighborhood() [3/3]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> itk::Neighborhood< TPixel, VDimension, TAllocator >::Neighborhood (Self &&) default
Move-constructor.
Member Function Documentation
Allocate()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> virtual void itk::Neighborhood< TPixel, VDimension, TAllocator >::Allocate (NeighborIndexType i) inline protected virtual
Allocates the neighborhood's memory buffer.
Definition at line 294 of file itkNeighborhood.h.
Begin() [1/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> Iterator itk::Neighborhood< TPixel, VDimension, TAllocator >::Begin () inline
STL-style iterator support.
Definition at line 173 of file itkNeighborhood.h.
Begin() [2/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> ConstIterator itk::Neighborhood< TPixel, VDimension, TAllocator >::Begin () const inline
STL-style iterator support.
Definition at line 183 of file itkNeighborhood.h.
ComputeNeighborhoodOffsetTable()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> virtual void itk::Neighborhood< TPixel, VDimension, TAllocator >::ComputeNeighborhoodOffsetTable () protected virtual
Fills entries into the offset lookup table. Called once on initialization.
ComputeNeighborhoodStrideTable()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> virtual void itk::Neighborhood< TPixel, VDimension, TAllocator >::ComputeNeighborhoodStrideTable () protected virtual
Computes the entries for the stride table
End() [1/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> Iterator itk::Neighborhood< TPixel, VDimension, TAllocator >::End () inline
STL-style iterator support.
Definition at line 168 of file itkNeighborhood.h.
End() [2/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> ConstIterator itk::Neighborhood< TPixel, VDimension, TAllocator >::End () const inline
STL-style iterator support.
Definition at line 178 of file itkNeighborhood.h.
GetBufferReference() [1/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> AllocatorType& itk::Neighborhood< TPixel, VDimension, TAllocator >::GetBufferReference () inline
Returns a reference to the data buffer structure.
Definition at line 244 of file itkNeighborhood.h.
Referenced by itk::operator<<().
GetBufferReference() [2/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> const AllocatorType& itk::Neighborhood< TPixel, VDimension, TAllocator >::GetBufferReference () const inline
Returns a reference to the data buffer structure.
Definition at line 249 of file itkNeighborhood.h.
GetCenterNeighborhoodIndex()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> NeighborIndexType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetCenterNeighborhoodIndex () const inline
Definition at line 272 of file itkNeighborhood.h.
GetCenterValue()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> TPixel itk::Neighborhood< TPixel, VDimension, TAllocator >::GetCenterValue () const inline
Returns the element at the center of the neighborhood.
Definition at line 208 of file itkNeighborhood.h.
GetElement()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> TPixel& itk::Neighborhood< TPixel, VDimension, TAllocator >::GetElement (NeighborIndexType i) inline
Pass-through data access methods to the buffer.
Definition at line 200 of file itkNeighborhood.h.
GetNeighborhoodIndex()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> virtual NeighborIndexType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetNeighborhoodIndex (const OffsetType &) const virtual
GetOffset()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> OffsetType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetOffset (NeighborIndexType i) const inline
Returns the itk::Offset from the center of the Neighborhood to the requested neighbor index.
Definition at line 263 of file itkNeighborhood.h.
GetRadius() [1/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> const SizeType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetRadius () const inline
Returns the radius of the neighborhood.
Definition at line 129 of file itkNeighborhood.h.
Referenced by itk::operator<<().
GetRadius() [2/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> SizeValueType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetRadius (DimensionValueType n) const inline
Returns the radius of the neighborhood along a specified dimension.
Definition at line 137 of file itkNeighborhood.h.
GetSize() [1/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> SizeType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetSize () const inline
Returns the size (total length of sides) of the neighborhood.
Definition at line 152 of file itkNeighborhood.h.
GetSize() [2/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> SizeValueType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetSize (DimensionValueType n) const inline
Returns the size (total length) of the neighborhood along a specified dimension.
Definition at line 145 of file itkNeighborhood.h.
Referenced by itk::operator<<().
GetSlice()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> std::slice itk::Neighborhood< TPixel, VDimension, TAllocator >::GetSlice (unsigned int) const
GetStride()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> OffsetValueType itk::Neighborhood< TPixel, VDimension, TAllocator >::GetStride (DimensionValueType axis) const inline
Returns the stride length for the specified dimension. Stride length is the number of pixels between adjacent pixels along the given dimension.
Definition at line 161 of file itkNeighborhood.h.
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> itk::Neighborhood< TPixel, VDimension, TAllocator >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
itkTypeMacroNoParent()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> itk::Neighborhood< TPixel, VDimension, TAllocator >::itkTypeMacroNoParent (Neighborhood< TPixel, VDimension, TAllocator >)
Run-time type information (and related methods).
operator=() [1/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> Self& itk::Neighborhood< TPixel, VDimension, TAllocator >::operator= (const Self &) default
Assignment operator.
operator=() [2/2]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> Self& itk::Neighborhood< TPixel, VDimension, TAllocator >::operator= (Self &&) default
Move-assignment.
operator==()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> bool itk::Neighborhood< TPixel, VDimension, TAllocator >::operator== (const Self & other) const inline
Comparison operator.
Definition at line 120 of file itkNeighborhood.h.
operator[]() [1/4]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> TPixel& itk::Neighborhood< TPixel, VDimension, TAllocator >::operator[] (const OffsetType & o) inline
Get pixel value by offset
Definition at line 256 of file itkNeighborhood.h.
Referenced by itk::Neighborhood< char, TImage::ImageDimension >::operator[]().
operator[]() [2/4]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> const TPixel& itk::Neighborhood< TPixel, VDimension, TAllocator >::operator[] (const OffsetType & o) const inline
Get pixel value by offset
Definition at line 257 of file itkNeighborhood.h.
Referenced by itk::Neighborhood< char, TImage::ImageDimension >::operator[]().
operator[]() [3/4]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> TPixel& itk::Neighborhood< TPixel, VDimension, TAllocator >::operator[] (NeighborIndexType i) inline
Pass-through data access methods to the buffer.
Definition at line 197 of file itkNeighborhood.h.
operator[]() [4/4]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> const TPixel& itk::Neighborhood< TPixel, VDimension, TAllocator >::operator[] (NeighborIndexType i) const inline
Pass-through data access methods to the buffer.
Definition at line 198 of file itkNeighborhood.h.
Print()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> void itk::Neighborhood< TPixel, VDimension, TAllocator >::Print (std::ostream & os) const inline
Standard itk object method.
Definition at line 237 of file itkNeighborhood.h.
PrintSelf()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> virtual void itk::Neighborhood< TPixel, VDimension, TAllocator >::PrintSelf (std::ostream & , Indent) const protected virtual
Standard itk object method.
Reimplemented in itk::AnnulusOperator< TPixel, TDimension, TAllocator >, itk::GaussianDerivativeOperator< TPixel, VDimension, TAllocator >, itk::GaussianOperator< TPixel, VDimension, TAllocator >, itk::GaussianOperator< ScalarType, VDimension >, itk::GaussianOperator< ScalarType, Superclass::Dimension >, itk::NeighborhoodOperator< TPixel, VDimension, TAllocator >, itk::NeighborhoodOperator< MovedGradientPixelType, VDimension, NeighborhoodAllocator< MovedGradientPixelType > >, itk::NeighborhoodOperator< ScalarValueType, VDimension, NeighborhoodAllocator< ScalarValueType > >, itk::NeighborhoodOperator< FixedGradientPixelType, VDimension, NeighborhoodAllocator< FixedGradientPixelType > >, itk::NeighborhoodOperator< PixelType, VDimension, NeighborhoodAllocator< PixelType > >, itk::NeighborhoodOperator< TPixel, 2, NeighborhoodAllocator< TPixel > >, itk::NeighborhoodOperator< OutputImagePixelType, VDimension, NeighborhoodAllocator< OutputImagePixelType > >, itk::NeighborhoodOperator< ScalarType, VDimension, NeighborhoodAllocator< ScalarType > >, itk::SobelOperator< TPixel, VDimension, TAllocator >, itk::SobelOperator< FixedGradientPixelType, Self::FixedImageDimension >, itk::SobelOperator< MovedGradientPixelType, Self::MovedImageDimension >, itk::DerivativeOperator< TPixel, VDimension, TAllocator >, itk::DerivativeOperator< ScalarValueType, Self::ImageDimension >, itk::DerivativeOperator< PixelType, Self::ImageDimension >, itk::DerivativeOperator< OutputImagePixelType, Self::ImageDimension >, itk::LaplacianOperator< TPixel, VDimension, TAllocator >, itk::ImageKernelOperator< TPixel, VDimension, TAllocator >, itk::ConstShapedNeighborhoodIterator< TImage, TBoundaryCondition >, itk::ConstShapedNeighborhoodIterator< TImage, ZeroFluxNeumannBoundaryCondition< TImage > >, itk::ConstShapedNeighborhoodIterator< ImageType, ZeroFluxNeumannBoundaryCondition< ImageType > >, itk::NeighborhoodIterator< TImage, TBoundaryCondition >, itk::NeighborhoodIterator< TImage, ZeroFluxNeumannBoundaryCondition< TImage > >, itk::NeighborhoodIterator< ImageType, ZeroFluxNeumannBoundaryCondition< ImageType > >, itk::ShapedNeighborhoodIterator< TImage, TBoundaryCondition >, itk::ShapedNeighborhoodIterator< ImageType >, itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >, itk::ConstNeighborhoodIterator< TImage, ZeroFluxNeumannBoundaryCondition< TImage > >, itk::ConstNeighborhoodIterator< TImage >, itk::ConstNeighborhoodIterator< FixedImageType >, itk::ConstNeighborhoodIterator< TImageType >, itk::ConstNeighborhoodIterator< TDisplacementField >, itk::ConstNeighborhoodIterator< ImageType, ZeroFluxNeumannBoundaryCondition< ImageType > >, itk::ConstNeighborhoodIterator< TSparseImageType >, and itk::ConstNeighborhoodIteratorWithOnlyIndex< TImage >.
SetRadius() [1/3]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> void itk::Neighborhood< TPixel, VDimension, TAllocator >::SetRadius (const SizeType &)
Sets the radius for the neighborhood, calculates size from the radius, and allocates storage.
SetRadius() [2/3]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> void itk::Neighborhood< TPixel, VDimension, TAllocator >::SetRadius (const SizeValueType * rad) inline
Sets the radius for the neighborhood. Overloaded to support an unsigned long array.
Definition at line 221 of file itkNeighborhood.h.
SetRadius() [3/3]
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> void itk::Neighborhood< TPixel, VDimension, TAllocator >::SetRadius (const SizeValueType)
Overloads SetRadius to allow a single long integer argument that is used as the radius of all the dimensions of the Neighborhood (resulting in a "square" neighborhood).
SetSize()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> void itk::Neighborhood< TPixel, VDimension, TAllocator >::SetSize () inline protected
Sets the length along each dimension.
Definition at line 283 of file itkNeighborhood.h.
Size()
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> NeighborIndexType itk::Neighborhood< TPixel, VDimension, TAllocator >::Size () const inline
More STL-style support.
Definition at line 191 of file itkNeighborhood.h.
Referenced by itk::VectorNeighborhoodInnerProduct< ImageType >::operator()().
Member Data Documentation
m_DataBuffer
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> AllocatorType itk::Neighborhood< TPixel, VDimension, TAllocator >::m_DataBuffer private
The buffer in which data is stored.
Definition at line 322 of file itkNeighborhood.h.
Referenced by itk::Neighborhood< char, TImage::ImageDimension >::operator==().
m_OffsetTable
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> std::vector<OffsetType> itk::Neighborhood< TPixel, VDimension, TAllocator >::m_OffsetTable private
Definition at line 329 of file itkNeighborhood.h.
m_Radius
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> SizeType itk::Neighborhood< TPixel, VDimension, TAllocator >::m_Radius { { 0 } } private
Number of neighbors to include (symmetrically) along each axis. A neighborhood will always have odd-length axes (m_Radius[n]*2+1).
Definition at line 315 of file itkNeighborhood.h.
Referenced by itk::Neighborhood< char, TImage::ImageDimension >::operator==().
m_Size
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> SizeType itk::Neighborhood< TPixel, VDimension, TAllocator >::m_Size { { 0 } } private
Actual length of each dimension, calculated from m_Radius. A neighborhood will always have odd-length axes (m_Radius[n]*2+1).
Definition at line 319 of file itkNeighborhood.h.
Referenced by itk::Neighborhood< char, TImage::ImageDimension >::operator==().
m_StrideTable
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> OffsetValueType itk::Neighborhood< TPixel, VDimension, TAllocator >::m_StrideTable[VDimension] { 0 } private
A lookup table for keeping track of stride lengths in a neighborhood i.e. the memory offsets between pixels along each dimensional axis
Definition at line 326 of file itkNeighborhood.h.
NeighborhoodDimension
template<typename TPixel , unsigned int VDimension = 2, typename TAllocator = NeighborhoodAllocator<TPixel>> constexpr unsigned int itk::Neighborhood< TPixel, VDimension, TAllocator >::NeighborhoodDimension = VDimension static constexpr
External support for dimensionality.
Definition at line 64 of file itkNeighborhood.h.
The documentation for this class was generated from the following file:
itkNeighborhood.h