ITK: itk::SpatialObjectFactoryBase Class Reference
itk::SpatialObjectFactoryBase Class Reference
Group Core » Module ITKSpatialObjects
#include <itkSpatialObjectFactoryBase.h>
Public Types
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = SpatialObjectFactoryBase
using Superclass = ObjectFactoryBase
Public Types inherited from itk::ObjectFactoryBase
using ConstPointer = SmartPointer< const Self >
using InsertionPositionEnum = ObjectFactoryEnums::InsertionPosition
using Pointer = SmartPointer< Self >
using Self = ObjectFactoryBase
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
const char * GetDescription () const override
const char * GetITKSourceVersion () const override
virtual const char * GetNameOfClass () const
void RegisterSpatialObject (const char *classOverride, const char *overrideClassName, const char *description, bool enableFlag, CreateObjectFunctionBase *createFunction)
Public Member Functions inherited from itk::ObjectFactoryBase
virtual void Disable (const char *className)
virtual std::list< std::string > GetClassOverrideDescriptions ()
virtual std::list< std::string > GetClassOverrideNames ()
virtual std::list< std::string > GetClassOverrideWithNames ()
virtual bool GetEnableFlag (const char *className, const char *subclassName)
virtual std::list< bool > GetEnableFlags ()
const char * GetLibraryPath ()
virtual void SetEnableFlag (bool flag, const char *className, const char *subclassName)
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual void Delete ()
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
Static Public Member Functions
static Pointer New ()
static void RegisterDefaultSpatialObjects ()
static SpatialObjectFactoryBase * GetFactory ()
Static Public Member Functions inherited from itk::ObjectFactoryBase
static std::list< LightObject::Pointer > CreateAllInstance (const char *itkclassname)
static LightObject::Pointer CreateInstance (const char *itkclassname)
static std::list< ObjectFactoryBase * > GetRegisteredFactories ()
static void Initialize ()
static void RegisterFactoryInternal (ObjectFactoryBase *)
template<typename TFactory >
static void RegisterInternalFactoryOnce ()
static void ReHash ()
static void UnRegisterAllFactories ()
static void UnRegisterFactory (ObjectFactoryBase *)
static bool RegisterFactory (ObjectFactoryBase *, InsertionPositionEnum where=InsertionPositionEnum::INSERT_AT_BACK, vcl_size_t position=0)
static void SetStrictVersionChecking (bool)
static void StrictVersionCheckingOn ()
static void StrictVersionCheckingOff ()
static bool GetStrictVersionChecking ()
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
SpatialObjectFactoryBase ()
~SpatialObjectFactoryBase () override
Protected Member Functions inherited from itk::ObjectFactoryBase
virtual std::list< LightObject::Pointer > CreateAllObject (const char *itkclassname)
virtual LightObject::Pointer CreateObject (const char *itkclassname)
ObjectFactoryBase ()
void PrintSelf (std::ostream &os, Indent indent) const override
void RegisterOverride (const char *classOverride, const char *subclass, const char *description, bool enableFlag, CreateObjectFunctionBase *createFunction)
~ObjectFactoryBase () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Static Private Attributes
static SpatialObjectFactoryBase * m_Factory
Additional Inherited Members
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Detailed Description
Create instances of SpatialObjects.
Definition at line 43 of file itkSpatialObjectFactoryBase.h.
Member Typedef Documentation
ConstPointer
using itk::SpatialObjectFactoryBase::ConstPointer = SmartPointer<const Self>
Definition at line 52 of file itkSpatialObjectFactoryBase.h.
Pointer
using itk::SpatialObjectFactoryBase::Pointer = SmartPointer<Self>
Definition at line 51 of file itkSpatialObjectFactoryBase.h.
Self
using itk::SpatialObjectFactoryBase::Self = SpatialObjectFactoryBase
Standard class type aliases.
Definition at line 49 of file itkSpatialObjectFactoryBase.h.
Superclass
using itk::SpatialObjectFactoryBase::Superclass = ObjectFactoryBase
Definition at line 50 of file itkSpatialObjectFactoryBase.h.
Constructor & Destructor Documentation
SpatialObjectFactoryBase()
itk::SpatialObjectFactoryBase::SpatialObjectFactoryBase () protected
~SpatialObjectFactoryBase()
itk::SpatialObjectFactoryBase::~SpatialObjectFactoryBase () override protected
Member Function Documentation
GetDescription()
const char* itk::SpatialObjectFactoryBase::GetDescription () const override virtual
Return a descriptive string describing the factory.
Implements itk::ObjectFactoryBase.
GetFactory()
static SpatialObjectFactoryBase* itk::SpatialObjectFactoryBase::GetFactory () inline static
Register this SpatialObject
Definition at line 73 of file itkSpatialObjectFactoryBase.h.
References New(), and itk::ObjectFactoryBase::RegisterFactory().
Referenced by itk::SpatialObjectFactory< T >::RegisterSpatialObject().
GetITKSourceVersion()
const char* itk::SpatialObjectFactoryBase::GetITKSourceVersion () const override virtual
Class methods used to interface with the registered factories.
Implements itk::ObjectFactoryBase.
GetNameOfClass()
virtual const char* itk::SpatialObjectFactoryBase::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::ObjectFactoryBase.
New()
static Pointer itk::SpatialObjectFactoryBase::New () static
Method for class instantiation.
Referenced by GetFactory().
RegisterDefaultSpatialObjects()
static void itk::SpatialObjectFactoryBase::RegisterDefaultSpatialObjects () static
Register all builtin SpatialObjects
RegisterSpatialObject()
void itk::SpatialObjectFactoryBase::RegisterSpatialObject (const char * classOverride, const char * overrideClassName, const char * description, bool enableFlag, CreateObjectFunctionBase * createFunction) inline
Definition at line 88 of file itkSpatialObjectFactoryBase.h.
Member Data Documentation
m_Factory
SpatialObjectFactoryBase* itk::SpatialObjectFactoryBase::m_Factory static private
Definition at line 102 of file itkSpatialObjectFactoryBase.h.
The documentation for this class was generated from the following file:
itkSpatialObjectFactoryBase.h