ITK: itk::ImageRegionRange< TImage > Class Template Reference
itk::ImageRegionRange< TImage > Class Template Reference final
Data Access Objects » Iterators » Image IteratorsGroup Core » | Module ITKCommon
#include <itkImageRegionRange.h>
Classes
class QualifiedIterator
Public Types
using const_iterator = QualifiedIterator< true >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using iterator = QualifiedIterator< IsImageTypeConst >
using reverse_iterator = std::reverse_iterator< iterator >
Public Member Functions
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
ImageRegionRange () noexcept=default
ImageRegionRange (TImage &image)
~ImageRegionRange ()=default
ImageRegionRange (TImage &image, const RegionType &iterationRegion)
iterator begin () const noexcept
iterator end () const noexcept
reverse_iterator rbegin () const noexcept
reverse_iterator rend () const noexcept
vcl_size_t size () const noexcept
bool empty () const noexcept
Private Types
using BufferIteratorType = typename ImageBufferRange< TImage >::iterator
using ImageDimensionType = typename TImage::ImageDimensionType
using IndexType = typename RegionType::IndexType
using OffsetTableType = Offset< ImageDimension+1 >
using OffsetType = typename TImage::OffsetType
using PixelType = typename TImage::PixelType
using RegionType = typename TImage::RegionType
using Self = ImageRegionRange
using SizeType = typename TImage::SizeType
Static Private Member Functions
static OffsetValueType ComputeOffset (const OffsetTableType &offsetTable, const IndexType &bufferedRegionIndex, const IndexType &index)
Private Attributes
BufferIteratorType m_BufferBegin {}
IndexType m_BufferedRegionIndex { {} }
IndexType m_IterationRegionIndex { {} }
SizeType m_IterationRegionSize { {} }
OffsetTableType m_OffsetTable { {} }
Static Private Attributes
static constexpr ImageDimensionType ImageDimension = TImage::ImageDimension
static constexpr bool IsImageTypeConst = std::is_const<TImage>::value
Detailed Description
template<typename TImage>
class itk::ImageRegionRange< TImage >
Modern C++11 range to iterate over the pixels of an image region. Designed to conform to Standard C++ Iterator requirements, so that it can be used in range-based for loop, and passed to Standard C++ algorithms.
The following example adds 42 to each pixel, using a range-based for loop:
ImageRegionRange<ImageType> range{ *image, imageRegion };
for (auto&& pixel : range)
{
  pixel = pixel + 42;
}
The following example prints the values of the pixels:
for (const auto pixel : range)
{
  std::cout << pixel << std::endl;
}
Author
Niels Dekker, LKEB, Leiden University Medical Center
See also
ImageRegionIterator
ImageRegionIndexRange
ImageBufferRange
ShapedImageNeighborhoodRange
Definition at line 72 of file itkImageRegionRange.h.
Member Typedef Documentation
BufferIteratorType
template<typename TImage > using itk::ImageRegionRange< TImage >::BufferIteratorType = typename ImageBufferRange<TImage>::iterator private
Definition at line 82 of file itkImageRegionRange.h.
const_iterator
template<typename TImage > using itk::ImageRegionRange< TImage >::const_iterator = QualifiedIterator<true>
Definition at line 325 of file itkImageRegionRange.h.
const_reverse_iterator
template<typename TImage > using itk::ImageRegionRange< TImage >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 328 of file itkImageRegionRange.h.
ImageDimensionType
template<typename TImage > using itk::ImageRegionRange< TImage >::ImageDimensionType = typename TImage::ImageDimensionType private
Definition at line 76 of file itkImageRegionRange.h.
IndexType
template<typename TImage > using itk::ImageRegionRange< TImage >::IndexType = typename RegionType::IndexType private
Definition at line 87 of file itkImageRegionRange.h.
iterator
template<typename TImage > using itk::ImageRegionRange< TImage >::iterator = QualifiedIterator<IsImageTypeConst>
Definition at line 326 of file itkImageRegionRange.h.
OffsetTableType
template<typename TImage > using itk::ImageRegionRange< TImage >::OffsetTableType = Offset<ImageDimension + 1> private
Definition at line 86 of file itkImageRegionRange.h.
OffsetType
template<typename TImage > using itk::ImageRegionRange< TImage >::OffsetType = typename TImage::OffsetType private
Definition at line 85 of file itkImageRegionRange.h.
PixelType
template<typename TImage > using itk::ImageRegionRange< TImage >::PixelType = typename TImage::PixelType private
Definition at line 77 of file itkImageRegionRange.h.
RegionType
template<typename TImage > using itk::ImageRegionRange< TImage >::RegionType = typename TImage::RegionType private
Definition at line 83 of file itkImageRegionRange.h.
reverse_iterator
template<typename TImage > using itk::ImageRegionRange< TImage >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 327 of file itkImageRegionRange.h.
Self
template<typename TImage > using itk::ImageRegionRange< TImage >::Self = ImageRegionRange private
Definition at line 75 of file itkImageRegionRange.h.
SizeType
template<typename TImage > using itk::ImageRegionRange< TImage >::SizeType = typename TImage::SizeType private
Definition at line 84 of file itkImageRegionRange.h.
Constructor & Destructor Documentation
ImageRegionRange() [1/3]
template<typename TImage > itk::ImageRegionRange< TImage >::ImageRegionRange () default noexcept
Constructs an empty range
ImageRegionRange() [2/3]
template<typename TImage > itk::ImageRegionRange< TImage >::ImageRegionRange (TImage & image, const RegionType & iterationRegion) inline explicit
Constructs an object, representing the range of pixels of the specified region, within the specified image.
Definition at line 339 of file itkImageRegionRange.h.
ImageRegionRange() [3/3]
template<typename TImage > itk::ImageRegionRange< TImage >::ImageRegionRange (TImage & image) inline explicit
Constructs a range of the pixels of the requested region of an image.
Definition at line 371 of file itkImageRegionRange.h.
~ImageRegionRange()
template<typename TImage > itk::ImageRegionRange< TImage >::~ImageRegionRange () default
Explicitly-defaulted destructor.
Member Function Documentation
begin()
template<typename TImage > iterator itk::ImageRegionRange< TImage >::begin () const inline noexcept
Returns an iterator to the first pixel.
Definition at line 378 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::ComputeOffset(), itk::ImageRegionRange< TImage >::m_BufferBegin, itk::ImageRegionRange< TImage >::m_BufferedRegionIndex, itk::ImageRegionRange< TImage >::m_IterationRegionIndex, itk::ImageRegionRange< TImage >::m_IterationRegionSize, and itk::ImageRegionRange< TImage >::m_OffsetTable.
Referenced by itk::ImageRegionRange< TImage >::cbegin(), and itk::ImageRegionRange< TImage >::rend().
cbegin()
template<typename TImage > const_iterator itk::ImageRegionRange< TImage >::cbegin () const inline noexcept
Returns a const iterator to the first pixel. Provides only read-only access to the pixel data.
Definition at line 407 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::begin().
cend()
template<typename TImage > const_iterator itk::ImageRegionRange< TImage >::cend () const inline noexcept
Returns a const 'end iterator' for this range.
Definition at line 414 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::end().
ComputeOffset()
template<typename TImage > static OffsetValueType itk::ImageRegionRange< TImage >::ComputeOffset (const OffsetTableType & offsetTable, const IndexType & bufferedRegionIndex, const IndexType & index) inline static private
Definition at line 303 of file itkImageRegionRange.h.
References itk::ImageHelper< VImageDimension, VLoop >::ComputeOffset(), and itk::Offset< VDimension >::data().
Referenced by itk::ImageRegionRange< TImage >::begin(), and itk::ImageRegionRange< TImage >::end().
crbegin()
template<typename TImage > const_reverse_iterator itk::ImageRegionRange< TImage >::crbegin () const inline noexcept
Returns a const reverse 'begin iterator' for this range.
Definition at line 437 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::rbegin().
crend()
template<typename TImage > const_reverse_iterator itk::ImageRegionRange< TImage >::crend () const inline noexcept
Returns a const reverse 'end iterator' for this range.
Definition at line 444 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::rend().
empty()
template<typename TImage > bool itk::ImageRegionRange< TImage >::empty () const inline noexcept
Tells whether the range is empty.
Definition at line 462 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::m_IterationRegionSize.
end()
template<typename TImage > iterator itk::ImageRegionRange< TImage >::end () const inline noexcept
Returns an 'end iterator' for this range.
Definition at line 389 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::ComputeOffset(), itk::ImageRegionRange< TImage >::m_BufferBegin, itk::ImageRegionRange< TImage >::m_BufferedRegionIndex, itk::ImageRegionRange< TImage >::m_IterationRegionIndex, itk::ImageRegionRange< TImage >::m_IterationRegionSize, and itk::ImageRegionRange< TImage >::m_OffsetTable.
Referenced by itk::ImageRegionRange< TImage >::cend(), and itk::ImageRegionRange< TImage >::rbegin().
rbegin()
template<typename TImage > reverse_iterator itk::ImageRegionRange< TImage >::rbegin () const inline noexcept
Returns a reverse 'begin iterator' for this range.
Definition at line 421 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::end().
Referenced by itk::ImageRegionRange< TImage >::crbegin().
rend()
template<typename TImage > reverse_iterator itk::ImageRegionRange< TImage >::rend () const inline noexcept
Returns a reverse 'end iterator' for this range.
Definition at line 429 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::begin().
Referenced by itk::ImageRegionRange< TImage >::crend().
size()
template<typename TImage > vcl_size_t itk::ImageRegionRange< TImage >::size () const inline noexcept
Returns the size of the range, that is the number of pixels in the region.
Definition at line 452 of file itkImageRegionRange.h.
References itk::ImageRegionRange< TImage >::m_IterationRegionSize.
Member Data Documentation
ImageDimension
template<typename TImage > constexpr ImageDimensionType itk::ImageRegionRange< TImage >::ImageDimension = TImage::ImageDimension static constexpr private
Definition at line 80 of file itkImageRegionRange.h.
Referenced by itk::ImageRegionRange< TImage >::QualifiedIterator< VIsConst >::Decrement(), itk::ImageRegionRange< TImage >::QualifiedIterator< VIsConst >::Increment(), itk::ImageRegionRange< TImage >::QualifiedIterator< VIsConst >::operator++(), and itk::ImageRegionRange< TImage >::QualifiedIterator< VIsConst >::operator--().
IsImageTypeConst
template<typename TImage > constexpr bool itk::ImageRegionRange< TImage >::IsImageTypeConst = std::is_const<TImage>::value static constexpr private
Definition at line 79 of file itkImageRegionRange.h.
m_BufferBegin
template<typename TImage > BufferIteratorType itk::ImageRegionRange< TImage >::m_BufferBegin {} private
Definition at line 313 of file itkImageRegionRange.h.
Referenced by itk::ImageRegionRange< TImage >::begin(), and itk::ImageRegionRange< TImage >::end().
m_BufferedRegionIndex
template<typename TImage > IndexType itk::ImageRegionRange< TImage >::m_BufferedRegionIndex { {} } private
Definition at line 315 of file itkImageRegionRange.h.
Referenced by itk::ImageRegionRange< TImage >::begin(), and itk::ImageRegionRange< TImage >::end().
m_IterationRegionIndex
template<typename TImage > IndexType itk::ImageRegionRange< TImage >::m_IterationRegionIndex { {} } private
Definition at line 317 of file itkImageRegionRange.h.
Referenced by itk::ImageRegionRange< TImage >::begin(), and itk::ImageRegionRange< TImage >::end().
m_IterationRegionSize
template<typename TImage > SizeType itk::ImageRegionRange< TImage >::m_IterationRegionSize { {} } private
Definition at line 319 of file itkImageRegionRange.h.
Referenced by itk::ImageRegionRange< TImage >::begin(), itk::ImageRegionRange< TImage >::empty(), itk::ImageRegionRange< TImage >::end(), and itk::ImageRegionRange< TImage >::size().
m_OffsetTable
template<typename TImage > OffsetTableType itk::ImageRegionRange< TImage >::m_OffsetTable { {} } private
Definition at line 322 of file itkImageRegionRange.h.
Referenced by itk::ImageRegionRange< TImage >::begin(), and itk::ImageRegionRange< TImage >::end().
The documentation for this class was generated from the following file:
itkImageRegionRange.h