ITK: itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare > Class Template Reference
itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare > Class Template Reference
#include <itkMorphologyHistogram.h>
Public Member Functions
void AddBoundary ()
void AddPixel (const TInputPixel &p)
TInputPixel GetValue ()
TInputPixel GetValue (const TInputPixel &)
void RemoveBoundary ()
void RemovePixel (const TInputPixel &p)
void SetBoundary (const TInputPixel &val)
VectorMorphologyHistogram ()
Static Public Member Functions
static bool UseVectorBasedAlgorithm ()
Public Attributes
TInputPixel m_Boundary
TCompare m_Compare
TInputPixel m_CurrentValue
int m_Direction
TInputPixel m_InitValue
std::vector< IdentifierType > m_Vector
Detailed Description
template<typename TInputPixel, typename TCompare>
class itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >
Definition at line 119 of file itkMorphologyHistogram.h.
Constructor & Destructor Documentation
VectorMorphologyHistogram()
template<typename TInputPixel , typename TCompare > itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram () inline
Definition at line 122 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Boundary, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Compare, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_CurrentValue, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Direction, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_InitValue, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Vector, itk::NumericTraits< T >::max(), and itk::NumericTraits< T >::NonpositiveMin().
Member Function Documentation
AddBoundary()
template<typename TInputPixel , typename TCompare > void itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddBoundary () inline
Definition at line 142 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddPixel(), and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Boundary.
AddPixel()
template<typename TInputPixel , typename TCompare > void itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddPixel (const TInputPixel & p) inline
Definition at line 154 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Compare, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_CurrentValue, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Vector, and itk::NumericTraits< T >::NonpositiveMin().
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddBoundary().
GetValue() [1/2]
template<typename TInputPixel , typename TCompare > TInputPixel itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::GetValue () inline
Definition at line 175 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_CurrentValue.
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::GetValue().
GetValue() [2/2]
template<typename TInputPixel , typename TCompare > TInputPixel itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::GetValue (const TInputPixel &) inline
Definition at line 181 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::GetValue().
RemoveBoundary()
template<typename TInputPixel , typename TCompare > void itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemoveBoundary () inline
Definition at line 148 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Boundary, and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemovePixel().
RemovePixel()
template<typename TInputPixel , typename TCompare > void itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemovePixel (const TInputPixel & p) inline
Definition at line 164 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_CurrentValue, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Direction, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_InitValue, itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Vector, and itk::NumericTraits< T >::NonpositiveMin().
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemoveBoundary().
SetBoundary()
template<typename TInputPixel , typename TCompare > void itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::SetBoundary (const TInputPixel & val) inline
Definition at line 187 of file itkMorphologyHistogram.h.
References itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Boundary.
UseVectorBasedAlgorithm()
template<typename TInputPixel , typename TCompare > static bool itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::UseVectorBasedAlgorithm () inline static
Definition at line 193 of file itkMorphologyHistogram.h.
Member Data Documentation
m_Boundary
template<typename TInputPixel , typename TCompare > TInputPixel itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Boundary
Definition at line 203 of file itkMorphologyHistogram.h.
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddBoundary(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemoveBoundary(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::SetBoundary(), and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram().
m_Compare
template<typename TInputPixel , typename TCompare > TCompare itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Compare
Definition at line 201 of file itkMorphologyHistogram.h.
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddPixel(), and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram().
m_CurrentValue
template<typename TInputPixel , typename TCompare > TInputPixel itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_CurrentValue
Definition at line 200 of file itkMorphologyHistogram.h.
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddPixel(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::GetValue(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemovePixel(), and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram().
m_Direction
template<typename TInputPixel , typename TCompare > int itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Direction
Definition at line 202 of file itkMorphologyHistogram.h.
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemovePixel(), and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram().
m_InitValue
template<typename TInputPixel , typename TCompare > TInputPixel itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_InitValue
Definition at line 199 of file itkMorphologyHistogram.h.
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemovePixel(), and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram().
m_Vector
template<typename TInputPixel , typename TCompare > std::vector<IdentifierType> itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::m_Vector
Definition at line 198 of file itkMorphologyHistogram.h.
Referenced by itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddPixel(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemovePixel(), and itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram().
The documentation for this class was generated from the following file:
itkMorphologyHistogram.h