ITK: itk::ImageRegionSplitterBase Class Reference
itk::ImageRegionSplitterBase Class Reference abstract
System Objects » ITK System Objects | Data Processing ObjectsGroup Core » | Module ITKCommon
#include <itkImageRegionSplitterBase.h>
Public Types
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = ImageRegionSplitterBase
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
virtual const char * GetNameOfClass () const
unsigned int GetSplit (unsigned int i, unsigned int numberOfPieces, ImageIORegion &region) const
template<unsigned int VImageDimension>
unsigned int GetSplit (unsigned int i, unsigned int numberOfPieces, ImageRegion< VImageDimension > &region) const
template<unsigned int VImageDimension>
unsigned int GetNumberOfSplits (const ImageRegion< VImageDimension > &region, unsigned int requestedNumber) const
unsigned int GetNumberOfSplits (const ImageIORegion &region, unsigned int requestedNumber) const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual void Delete ()
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
Protected Member Functions
virtual unsigned int GetNumberOfSplitsInternal (unsigned int dim, const IndexValueType regionIndex[], const SizeValueType regionSize[], unsigned int requestedNumber) const =0
virtual unsigned int GetSplitInternal (unsigned int dim, unsigned int i, unsigned int numberOfPieces, IndexValueType regionIndex[], SizeValueType regionSize[]) const =0
ImageRegionSplitterBase ()
void PrintSelf (std::ostream &os, Indent indent) const override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Additional Inherited Members
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Detailed Description
Divide an image region into several pieces.
ImageRegionSplitterBase is an abstract interface to divide an ImageRegion into smaller regions. ImageRegionSplitterBase is used by the ImageSource, StreamingImageFilter, streaming ImageIO classes to divide a region into a series of smaller subregions.
This object has two basic methods: GetNumberOfSplits() and GetSplit().
GetNumberOfSplits() is used to determine how may subregions a given region can be divided. You call GetNumberOfSplits with an argument that is the number of subregions you want. If the image region can support that number of subregions, that number is returned. Otherwise, the maximum number of splits less then or equal to the argument be returned. For example, if a region splitter class only divides a region into horizontal slabs, then the maximum number of splits will be the number of rows in the region.
GetSplit() returns the ith of N subregions (as an ImageRegion object).
See also
ImageRegionSplitterDirection
ImageRegionSplitterSlowDimension
Definition at line 58 of file itkImageRegionSplitterBase.h.
Member Typedef Documentation
ConstPointer
using itk::ImageRegionSplitterBase::ConstPointer = SmartPointer<const Self>
Definition at line 67 of file itkImageRegionSplitterBase.h.
Pointer
using itk::ImageRegionSplitterBase::Pointer = SmartPointer<Self>
Definition at line 66 of file itkImageRegionSplitterBase.h.
Self
using itk::ImageRegionSplitterBase::Self = ImageRegionSplitterBase
Standard class type aliases.
Definition at line 64 of file itkImageRegionSplitterBase.h.
Superclass
using itk::ImageRegionSplitterBase::Superclass = Object
Definition at line 65 of file itkImageRegionSplitterBase.h.
Constructor & Destructor Documentation
ImageRegionSplitterBase()
itk::ImageRegionSplitterBase::ImageRegionSplitterBase () protected
Member Function Documentation
GetNameOfClass()
virtual const char* itk::ImageRegionSplitterBase::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::Object.
Reimplemented in itk::ImageRegionSplitterMultidimensional, itk::ImageRegionSplitterSlowDimension, and itk::ImageRegionSplitterDirection.
GetNumberOfSplits() [1/2]
unsigned int itk::ImageRegionSplitterBase::GetNumberOfSplits (const ImageIORegion & region, unsigned int requestedNumber) const inline
How many pieces can the specified region be split? A given region cannot always be divided into the requested number of pieces. For instance, if the numberOfPieces exceeds the number of pixels along a certain dimensions, then some splits will not be possible. This method returns a number less than or equal to the requested number of pieces.
Definition at line 86 of file itkImageRegionSplitterBase.h.
References itk::ImageIORegion::GetImageDimension(), itk::ImageIORegion::GetIndex(), and itk::ImageIORegion::GetSize().
GetNumberOfSplits() [2/2]
template<unsigned int VImageDimension> unsigned int itk::ImageRegionSplitterBase::GetNumberOfSplits (const ImageRegion< VImageDimension > & region, unsigned int requestedNumber) const inline
How many pieces can the specified region be split? A given region cannot always be divided into the requested number of pieces. For instance, if the numberOfPieces exceeds the number of pixels along a certain dimensions, then some splits will not be possible. This method returns a number less than or equal to the requested number of pieces.
Definition at line 80 of file itkImageRegionSplitterBase.h.
References itk::ImageRegion< VImageDimension >::GetIndex(), and itk::ImageRegion< VImageDimension >::GetSize().
GetNumberOfSplitsInternal()
virtual unsigned int itk::ImageRegionSplitterBase::GetNumberOfSplitsInternal (unsigned int dim, const IndexValueType regionIndex[], const SizeValueType regionSize[], unsigned int requestedNumber) const protected pure virtual
Templetless method to compute the number of possible splits for any number of dimensions.
Implemented in itk::ImageRegionSplitterMultidimensional, itk::ImageRegionSplitterSlowDimension, and itk::ImageRegionSplitterDirection.
GetSplit() [1/2]
unsigned int itk::ImageRegionSplitterBase::GetSplit (unsigned int i, unsigned int numberOfPieces, ImageIORegion & region) const inline
Definition at line 113 of file itkImageRegionSplitterBase.h.
References itk::ImageIORegion::GetImageDimension(), itk::ImageIORegion::GetModifiableIndex(), and itk::ImageIORegion::GetModifiableSize().
GetSplit() [2/2]
template<unsigned int VImageDimension> unsigned int itk::ImageRegionSplitterBase::GetSplit (unsigned int i, unsigned int numberOfPieces, ImageRegion< VImageDimension > & region) const inline
Get a region definition that represents the ith piece a specified region.
The numberOfPieces must be equal to what GetNumberOfSplits() returns. The return value is the maximum number of splits available. If i is greater than or equal to the return value the value of the region is undefined.
Definition at line 104 of file itkImageRegionSplitterBase.h.
References itk::ImageRegion< VImageDimension >::GetModifiableIndex(), and itk::ImageRegion< VImageDimension >::GetModifiableSize().
GetSplitInternal()
virtual unsigned int itk::ImageRegionSplitterBase::GetSplitInternal (unsigned int dim, unsigned int i, unsigned int numberOfPieces, IndexValueType regionIndex[], SizeValueType regionSize[]) const protected pure virtual
Templetless method to compute an actual split for any number of dimensions. dim is the size of the regionIndex and regionSize arrays.
Implemented in itk::ImageRegionSplitterMultidimensional, itk::ImageRegionSplitterSlowDimension, and itk::ImageRegionSplitterDirection.
PrintSelf()
void itk::ImageRegionSplitterBase::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::LightObject.
Reimplemented in itk::ImageRegionSplitterMultidimensional, and itk::ImageRegionSplitterDirection.
The documentation for this class was generated from the following file:
itkImageRegionSplitterBase.h