ITK: itk::RectangularImageNeighborhoodShape< VImageDimension > Class Template Reference
itk::RectangularImageNeighborhoodShape< VImageDimension > Class Template Reference
Data Access Objects » Iterators » Image IteratorsGroup Core » | Module ITKCommon
#include <itkRectangularImageNeighborhoodShape.h>
Public Member Functions
constexpr vcl_size_t GetNumberOfOffsets () const noexcept
constexpr RectangularImageNeighborhoodShape (const Size< ImageDimension > &radius) noexcept
void FillOffsets (Offset< ImageDimension > *const offsets) const noexcept
Static Public Attributes
static constexpr unsigned int ImageDimension = VImageDimension
Private Member Functions
constexpr vcl_size_t CalculateNumberOfOffsets (const unsigned int dimension) const noexcept
Private Attributes
vcl_size_t m_NumberOfOffsets
Size< ImageDimension > m_Radius
Detailed Description
template<unsigned int VImageDimension>
class itk::RectangularImageNeighborhoodShape< VImageDimension >
Rectangular (or hyperrectangular) image-neighborhood shape. Eases creating a sequence of offsets for ShapedImageNeighborhoodRange. Can also be used for ShapedNeighborhoodIterator.
The following example creates a 3 x 5 rectangular neighborhood around pixel location [10, 20], and generates the offsets for a neighborhood range:
const Index<> location = { 10, 20 };
const Size<> radius = { { 1, 2 } };
const RectangularImageNeighborhoodShape<2> shape{ radius };
const std::vector<Offset<>> offsets = GenerateImageNeighborhoodOffsets(shape);
ShapedImageNeighborhoodRange<ImageType> neighborhoodRange{ *image, location, offsets };
See also
ShapedNeighborhoodIterator
ShapedImageNeighborhoodRange
Definition at line 53 of file itkRectangularImageNeighborhoodShape.h.
Constructor & Destructor Documentation
RectangularImageNeighborhoodShape()
template<unsigned int VImageDimension> constexpr itk::RectangularImageNeighborhoodShape< VImageDimension >::RectangularImageNeighborhoodShape (const Size< ImageDimension > & radius) inline explicit constexpr noexcept
Constructs a hyperrectangular shape whose size is specified by the radius
Definition at line 60 of file itkRectangularImageNeighborhoodShape.h.
Member Function Documentation
CalculateNumberOfOffsets()
template<unsigned int VImageDimension> constexpr vcl_size_t itk::RectangularImageNeighborhoodShape< VImageDimension >::CalculateNumberOfOffsets (const unsigned int dimension) const inline constexpr private noexcept
Definition at line 119 of file itkRectangularImageNeighborhoodShape.h.
References itk::Size< VDimension >::m_InternalArray, and itk::RectangularImageNeighborhoodShape< VImageDimension >::m_Radius.
FillOffsets()
template<unsigned int VImageDimension> void itk::RectangularImageNeighborhoodShape< VImageDimension >::FillOffsets (Offset< ImageDimension > *const offsets) const inline noexcept
Fills the specified buffer with the offsets for a neighborhood of this shape.
Definition at line 76 of file itkRectangularImageNeighborhoodShape.h.
References itk::Size< VDimension >::begin(), itk::Offset< VDimension >::begin(), itk::Size< VDimension >::end(), itk::RectangularImageNeighborhoodShape< VImageDimension >::ImageDimension, itk::RectangularImageNeighborhoodShape< VImageDimension >::m_NumberOfOffsets, and itk::RectangularImageNeighborhoodShape< VImageDimension >::m_Radius.
GetNumberOfOffsets()
template<unsigned int VImageDimension> constexpr vcl_size_t itk::RectangularImageNeighborhoodShape< VImageDimension >::GetNumberOfOffsets () const inline constexpr noexcept
Returns the number of offsets needed to represent this shape.
Definition at line 68 of file itkRectangularImageNeighborhoodShape.h.
References itk::RectangularImageNeighborhoodShape< VImageDimension >::m_NumberOfOffsets.
Member Data Documentation
ImageDimension
template<unsigned int VImageDimension> constexpr unsigned int itk::RectangularImageNeighborhoodShape< VImageDimension >::ImageDimension = VImageDimension static constexpr
Definition at line 56 of file itkRectangularImageNeighborhoodShape.h.
Referenced by itk::RectangularImageNeighborhoodShape< VImageDimension >::FillOffsets().
m_NumberOfOffsets
template<unsigned int VImageDimension> vcl_size_t itk::RectangularImageNeighborhoodShape< VImageDimension >::m_NumberOfOffsets private
Definition at line 113 of file itkRectangularImageNeighborhoodShape.h.
Referenced by itk::RectangularImageNeighborhoodShape< VImageDimension >::FillOffsets(), and itk::RectangularImageNeighborhoodShape< VImageDimension >::GetNumberOfOffsets().
m_Radius
template<unsigned int VImageDimension> Size<ImageDimension> itk::RectangularImageNeighborhoodShape< VImageDimension >::m_Radius private
Definition at line 110 of file itkRectangularImageNeighborhoodShape.h.
Referenced by itk::RectangularImageNeighborhoodShape< VImageDimension >::CalculateNumberOfOffsets(), and itk::RectangularImageNeighborhoodShape< VImageDimension >::FillOffsets().
The documentation for this class was generated from the following file:
itkRectangularImageNeighborhoodShape.h