ITK: itk::Function::VectorMorphologicalGradientHistogram< TInputPixel > Class Template Reference
itk::Function::VectorMorphologicalGradientHistogram< TInputPixel > Class Template Reference
#include <itkMovingHistogramMorphologicalGradientImageFilter.h>
Public Member Functions
void AddBoundary ()
void AddPixel (const TInputPixel &p)
TInputPixel GetValue ()
TInputPixel GetValue (const TInputPixel &)
void RemoveBoundary ()
void RemovePixel (const TInputPixel &p)
VectorMorphologicalGradientHistogram ()
~VectorMorphologicalGradientHistogram ()=default
Static Public Member Functions
static bool UseVectorBasedAlgorithm ()
Public Attributes
SizeValueType m_Count
TInputPixel m_Max
TInputPixel m_Min
std::vector< SizeValueType > m_Vector
Detailed Description
template<typename TInputPixel>
class itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >
Definition at line 106 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Constructor & Destructor Documentation
VectorMorphologicalGradientHistogram()
template<typename TInputPixel > itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::VectorMorphologicalGradientHistogram () inline
Definition at line 109 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Count, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Max, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Min, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Vector, itk::NumericTraits< T >::max(), and itk::NumericTraits< T >::NonpositiveMin().
~VectorMorphologicalGradientHistogram()
template<typename TInputPixel > itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::~VectorMorphologicalGradientHistogram () default
Member Function Documentation
AddBoundary()
template<typename TInputPixel > void itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::AddBoundary () inline
Definition at line 121 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
AddPixel()
template<typename TInputPixel > void itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::AddPixel (const TInputPixel & p) inline
Definition at line 130 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Count, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Max, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Min, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Vector, and itk::NumericTraits< T >::NonpositiveMin().
GetValue() [1/2]
template<typename TInputPixel > TInputPixel itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue () inline
Definition at line 174 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Count, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Max, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Min, and itk::NumericTraits< T >::ZeroValue().
Referenced by itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue().
GetValue() [2/2]
template<typename TInputPixel > TInputPixel itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue (const TInputPixel &) inline
Definition at line 168 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue().
RemoveBoundary()
template<typename TInputPixel > void itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemoveBoundary () inline
Definition at line 125 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
RemovePixel()
template<typename TInputPixel > void itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemovePixel (const TInputPixel & p) inline
Definition at line 145 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Count, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Max, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Min, itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Vector, itk::NumericTraits< T >::max(), and itk::NumericTraits< T >::NonpositiveMin().
UseVectorBasedAlgorithm()
template<typename TInputPixel > static bool itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::UseVectorBasedAlgorithm () inline static
Definition at line 187 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Member Data Documentation
m_Count
template<typename TInputPixel > SizeValueType itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Count
Definition at line 195 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Referenced by itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::AddPixel(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemovePixel(), and itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::VectorMorphologicalGradientHistogram().
m_Max
template<typename TInputPixel > TInputPixel itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Max
Definition at line 194 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Referenced by itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::AddPixel(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemovePixel(), and itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::VectorMorphologicalGradientHistogram().
m_Min
template<typename TInputPixel > TInputPixel itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Min
Definition at line 193 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Referenced by itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::AddPixel(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemovePixel(), and itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::VectorMorphologicalGradientHistogram().
m_Vector
template<typename TInputPixel > std::vector<SizeValueType> itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::m_Vector
Definition at line 192 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Referenced by itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::AddPixel(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemovePixel(), and itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::VectorMorphologicalGradientHistogram().
The documentation for this class was generated from the following file:
itkMovingHistogramMorphologicalGradientImageFilter.h