ITK: itk::fftw::Proxy< float > Class Reference
itk::fftw::Proxy< float > Class Reference
#include <itkFFTWCommon.h>
Public Types
using ComplexType = fftwf_complex
using PixelType = float
using PlanType = fftwf_plan
using Self = Proxy< float >
Static Public Member Functions
static void DestroyPlan (PlanType p)
static void Execute (PlanType p)
static PlanType Plan_dft (int rank, const int *n, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_1d (int n, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_2d (int nx, int ny, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_3d (int nx, int ny, int nz, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r (int rank, const int *n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r_1d (int n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r_2d (int nx, int ny, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c (int rank, const int *n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c_1d (int n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c_2d (int nx, int ny, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
Static Public Attributes
static constexpr SizeValueType GREATEST_PRIME_FACTOR = 13
Detailed Description
Definition at line 66 of file itkFFTWCommon.h.
Member Typedef Documentation
ComplexType
using itk::fftw::Proxy< float >::ComplexType = fftwf_complex
Definition at line 70 of file itkFFTWCommon.h.
PixelType
using itk::fftw::Proxy< float >::PixelType = float
Definition at line 69 of file itkFFTWCommon.h.
PlanType
using itk::fftw::Proxy< float >::PlanType = fftwf_plan
Definition at line 71 of file itkFFTWCommon.h.
Self
using itk::fftw::Proxy< float >::Self = Proxy<float>
Definition at line 72 of file itkFFTWCommon.h.
Member Function Documentation
DestroyPlan()
static void itk::fftw::Proxy< float >::DestroyPlan (PlanType p) inline static
Definition at line 394 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Execute()
static void itk::fftw::Proxy< float >::Execute (PlanType p) inline static
Definition at line 389 of file itkFFTWCommon.h.
Plan_dft()
static PlanType itk::fftw::Proxy< float >::Plan_dft (int rank, const int * n, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 334 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex(), and itk::FFTWGlobalConfiguration::SetNewWisdomAvailable().
Plan_dft_1d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_1d (int n, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 284 of file itkFFTWCommon.h.
Plan_dft_2d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_2d (int nx, int ny, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 296 of file itkFFTWCommon.h.
Plan_dft_3d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_3d (int nx, int ny, int nz, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 314 of file itkFFTWCommon.h.
Plan_dft_c2r()
static PlanType itk::fftw::Proxy< float >::Plan_dft_c2r (int rank, const int * n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 129 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex(), and itk::FFTWGlobalConfiguration::SetNewWisdomAvailable().
Plan_dft_c2r_1d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_c2r_1d (int n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 82 of file itkFFTWCommon.h.
Plan_dft_c2r_2d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_c2r_2d (int nx, int ny, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 93 of file itkFFTWCommon.h.
Plan_dft_c2r_3d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 110 of file itkFFTWCommon.h.
Plan_dft_r2c()
static PlanType itk::fftw::Proxy< float >::Plan_dft_r2c (int rank, const int * n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 230 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex(), and itk::FFTWGlobalConfiguration::SetNewWisdomAvailable().
Plan_dft_r2c_1d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_r2c_1d (int n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 183 of file itkFFTWCommon.h.
Plan_dft_r2c_2d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_r2c_2d (int nx, int ny, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 194 of file itkFFTWCommon.h.
Plan_dft_r2c_3d()
static PlanType itk::fftw::Proxy< float >::Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 211 of file itkFFTWCommon.h.
Member Data Documentation
GREATEST_PRIME_FACTOR
constexpr SizeValueType itk::fftw::Proxy< float >::GREATEST_PRIME_FACTOR = 13 static constexpr
Definition at line 78 of file itkFFTWCommon.h.
The documentation for this class was generated from the following file:
itkFFTWCommon.h