ITK: itk::watershed::BoundaryResolver< TPixelType, TDimension > Class Template Reference
itk::watershed::BoundaryResolver< TPixelType, TDimension > Class Template Reference
Data Processing Objects » Filters » Image Filters » Image Segmentation Filters » Intensity-Based Image Segmentation Filters » Watershed-based Segmentation FiltersGroup Segmentation » | Module ITKWatersheds
#include <itkWatershedBoundaryResolver.h>
Public Types
using BoundaryType = Boundary< PixelType, TDimension >
using DataObjectPointer = DataObject::Pointer
using DataObjectPointerArraySizeType = ProcessObject::DataObjectPointerArraySizeType
using EquivalencyTableType = EquivalencyTable
using PixelType = TPixelType
using SegmenterType = Segmenter< Image< TPixelType, TDimension > >
Public Types inherited from itk::ProcessObject
using ConstPointer = SmartPointer< const Self >
using DataObjectIdentifierType = DataObject::DataObjectIdentifierType
using DataObjectPointer = DataObject::Pointer
using DataObjectPointerArray = std::vector< DataObjectPointer >
using DataObjectPointerArraySizeType = DataObjectPointerArray::size_type
using MultiThreaderType = MultiThreaderBase
using NameArray = std::vector< DataObjectIdentifierType >
using Pointer = SmartPointer< Self >
using Self = ProcessObject
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
void GenerateData () override
DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx) override
void SetBoundaryA (BoundaryType *bd)
BoundaryType::Pointer GetBoundaryA ()
void SetBoundaryB (BoundaryType *bd)
BoundaryType::Pointer GetBoundaryB ()
virtual void SetFace (unsigned short _arg)
virtual unsigned short GetFace () const
void SetEquivalencyTable (EquivalencyTableType::Pointer a)
EquivalencyTableType::Pointer GetEquivalencyTable ()
Public Member Functions inherited from itk::ProcessObject
virtual void AbortGenerateDataOn ()
virtual void EnlargeOutputRequestedRegion (DataObject *)
virtual const bool & GetAbortGenerateData () const
DataObjectPointerArray GetIndexedInputs ()
DataObjectPointerArray GetIndexedOutputs ()
NameArray GetInputNames () const
DataObjectPointerArray GetInputs ()
MultiThreaderType * GetMultiThreader () const
DataObjectPointerArraySizeType GetNumberOfIndexedInputs () const
DataObjectPointerArraySizeType GetNumberOfIndexedOutputs () const
DataObjectPointerArraySizeType GetNumberOfInputs () const
DataObjectPointerArraySizeType GetNumberOfOutputs () const
virtual DataObjectPointerArraySizeType GetNumberOfValidRequiredInputs () const
NameArray GetOutputNames () const
DataObjectPointerArray GetOutputs ()
virtual float GetProgress () const
NameArray GetRequiredInputNames () const
bool HasInput (const DataObjectIdentifierType &key) const
bool HasOutput (const DataObjectIdentifierType &key) const
void IncrementProgress (float increment)
virtual DataObjectPointer MakeOutput (const DataObjectIdentifierType &)
virtual void PrepareOutputs ()
virtual void PropagateRequestedRegion (DataObject *output)
virtual void ResetPipeline ()
virtual void SetAbortGenerateData (bool _arg)
void SetMultiThreader (MultiThreaderType *threader)
virtual void Update ()
virtual void UpdateLargestPossibleRegion ()
virtual void UpdateOutputData (DataObject *output)
virtual void UpdateOutputInformation ()
void UpdateProgress (float progress)
virtual void SetReleaseDataFlag (bool val)
virtual bool GetReleaseDataFlag () const
void ReleaseDataFlagOn ()
void ReleaseDataFlagOff ()
virtual void SetReleaseDataBeforeUpdateFlag (bool _arg)
virtual const bool & GetReleaseDataBeforeUpdateFlag () const
virtual void ReleaseDataBeforeUpdateFlagOn ()
virtual void SetNumberOfWorkUnits (ThreadIdType _arg)
virtual const ThreadIdType & GetNumberOfWorkUnits () const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual void Delete ()
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
Static Public Attributes
static constexpr unsigned int ImageDimension = TDimension
Protected Member Functions
BoundaryResolver ()
void GenerateOutputRequestedRegion (DataObject *output) override
void PrintSelf (std::ostream &os, Indent indent) const override
~BoundaryResolver () override=default
Protected Member Functions inherited from itk::ProcessObject
virtual void AddInput (DataObject *input)
void AddOptionalInputName (const DataObjectIdentifierType &)
void AddOptionalInputName (const DataObjectIdentifierType &, DataObjectPointerArraySizeType idx)
virtual void AddOutput (DataObject *output)
bool AddRequiredInputName (const DataObjectIdentifierType &)
bool AddRequiredInputName (const DataObjectIdentifierType &, DataObjectPointerArraySizeType idx)
virtual void CacheInputReleaseDataFlags ()
virtual void GenerateInputRequestedRegion ()
virtual void GenerateOutputInformation ()
DataObject * GetInput (const DataObjectIdentifierType &key)
const DataObject * GetInput (const DataObjectIdentifierType &key) const
virtual const DataObjectPointerArraySizeType & GetNumberOfRequiredInputs () const
virtual const DataObjectPointerArraySizeType & GetNumberOfRequiredOutputs () const
bool IsIndexedInputName (const DataObjectIdentifierType &) const
bool IsIndexedOutputName (const DataObjectIdentifierType &) const
bool IsRequiredInputName (const DataObjectIdentifierType &) const
DataObjectPointerArraySizeType MakeIndexFromInputName (const DataObjectIdentifierType &name) const
DataObjectPointerArraySizeType MakeIndexFromOutputName (const DataObjectIdentifierType &name) const
DataObjectIdentifierType MakeNameFromInputIndex (DataObjectPointerArraySizeType idx) const
DataObjectIdentifierType MakeNameFromOutputIndex (DataObjectPointerArraySizeType idx) const
virtual void PopBackInput ()
virtual void PopFrontInput ()
ProcessObject ()
virtual void PropagateResetPipeline ()
virtual void PushBackInput (const DataObject *input)
virtual void PushFrontInput (const DataObject *input)
virtual void ReleaseInputs ()
virtual void RemoveInput (const DataObjectIdentifierType &key)
virtual void RemoveInput (DataObjectPointerArraySizeType)
virtual void RemoveOutput (const DataObjectIdentifierType &key)
virtual void RemoveOutput (DataObjectPointerArraySizeType idx)
bool RemoveRequiredInputName (const DataObjectIdentifierType &)
virtual void RestoreInputReleaseDataFlags ()
virtual void SetInput (const DataObjectIdentifierType &key, DataObject *input)
virtual void SetNthInput (DataObjectPointerArraySizeType idx, DataObject *input)
virtual void SetNthOutput (DataObjectPointerArraySizeType idx, DataObject *output)
void SetNumberOfIndexedInputs (DataObjectPointerArraySizeType num)
void SetNumberOfIndexedOutputs (DataObjectPointerArraySizeType num)
virtual void SetNumberOfRequiredInputs (DataObjectPointerArraySizeType)
virtual void SetNumberOfRequiredOutputs (DataObjectPointerArraySizeType _arg)
virtual void SetOutput (const DataObjectIdentifierType &name, DataObject *output)
virtual void SetPrimaryInput (DataObject *object)
virtual void SetPrimaryOutput (DataObject *object)
void SetRequiredInputNames (const NameArray &)
virtual void VerifyInputInformation () ITKv5_CONST
virtual void VerifyPreconditions () ITKv5_CONST
~ProcessObject () override
DataObject * GetInput (DataObjectPointerArraySizeType idx)
const DataObject * GetInput (DataObjectPointerArraySizeType idx) const
DataObject * GetPrimaryInput ()
const DataObject * GetPrimaryInput () const
virtual void SetPrimaryInputName (const DataObjectIdentifierType &key)
virtual const char * GetPrimaryInputName () const
DataObject * GetOutput (const DataObjectIdentifierType &key)
const DataObject * GetOutput (const DataObjectIdentifierType &key) const
virtual void SetPrimaryOutputName (const DataObjectIdentifierType &key)
virtual const char * GetPrimaryOutputName () const
DataObject * GetOutput (DataObjectPointerArraySizeType i)
const DataObject * GetOutput (DataObjectPointerArraySizeType i) const
DataObject * GetPrimaryOutput ()
const DataObject * GetPrimaryOutput () const
virtual bool GetThreaderUpdateProgress () const
virtual void ThreaderUpdateProgressOn ()
virtual void SetThreaderUpdateProgress (bool arg)
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Protected Attributes
unsigned short m_Face { 0 }
Protected Attributes inherited from itk::ProcessObject
TimeStamp m_OutputInformationMTime
bool m_Updating
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
using Self = BoundaryResolver
using Superclass = ProcessObject
using Pointer = SmartPointer< Self >
using ConstPointer = SmartPointer< const Self >
static Pointer New ()
virtual const char * GetNameOfClass () const
Additional Inherited Members
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Static Protected Member Functions inherited from itk::ProcessObject
static constexpr float progressFixedToFloat (uint32_t fixed)
static uint32_t progressFloatToFixed (float f)
Detailed Description
template<typename TPixelType, unsigned int TDimension>
class itk::watershed::BoundaryResolver< TPixelType, TDimension >
This filter implements a piece of the streaming watershed segmentation algorithm. It takes in pairs of itk::watershed::Boundary objects and connects the labeling of pixels across image chunk boundaries. Read the documentation found in itk::WatershedImageFilter and the other watershed segmentation component objects for more information.
A note on terminology in itk watershed segmentation code
For streamed segmentation of images in the watershed framework, the documentation refers to the complete data set at the "image volume." The image volume is assumed to be partitioned into pieces referred to as image chunks. Each chunk is processed in sequence through the pipeline. The "face" of an image chunk is an N-1 dimensional boundary region of an N dimensional chunk (the planar faces of a cube, for example).
Input
The input to this filter is a pair of itk::watershed::Boundary pointers (BoundaryA and BoundaryB). The algorithm assumes that these Boundaries come from facing chunks in the image volume. The faces that align need to be specified in the parameters of the filter.
Output
This filter outputs a table of equivalencies among labels. See itk::EquivalencyTable for more information.
Parameters
The only parameters to set on this filter are the indices of the faces that align in the boundary object inputs. See itk::Boundary for a description of how boundary faces are indexed.
See also
itk::watershed::Boundary
Definition at line 65 of file itkWatershedBoundaryResolver.h.
Member Typedef Documentation
BoundaryType
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::BoundaryType = Boundary<PixelType, TDimension>
Definition at line 84 of file itkWatershedBoundaryResolver.h.
ConstPointer
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::ConstPointer = SmartPointer<const Self>
Set up smart pointer and object factory definitions.
Definition at line 74 of file itkWatershedBoundaryResolver.h.
DataObjectPointer
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::DataObjectPointer = DataObject::Pointer
Definition at line 87 of file itkWatershedBoundaryResolver.h.
DataObjectPointerArraySizeType
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::DataObjectPointerArraySizeType = ProcessObject::DataObjectPointerArraySizeType
Standard itk::ProcessObject subclass method.
Definition at line 141 of file itkWatershedBoundaryResolver.h.
EquivalencyTableType
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::EquivalencyTableType = EquivalencyTable
Definition at line 85 of file itkWatershedBoundaryResolver.h.
PixelType
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::PixelType = TPixelType
Some convenient type alias.
Definition at line 83 of file itkWatershedBoundaryResolver.h.
Pointer
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::Pointer = SmartPointer<Self>
Set up smart pointer and object factory definitions.
Definition at line 73 of file itkWatershedBoundaryResolver.h.
SegmenterType
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::SegmenterType = Segmenter<Image<TPixelType, TDimension> >
Definition at line 86 of file itkWatershedBoundaryResolver.h.
Self
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::Self = BoundaryResolver
Set up smart pointer and object factory definitions.
Definition at line 71 of file itkWatershedBoundaryResolver.h.
Superclass
template<typename TPixelType , unsigned int TDimension> using itk::watershed::BoundaryResolver< TPixelType, TDimension >::Superclass = ProcessObject
Set up smart pointer and object factory definitions.
Definition at line 72 of file itkWatershedBoundaryResolver.h.
Constructor & Destructor Documentation
BoundaryResolver()
template<typename TPixelType , unsigned int TDimension> itk::watershed::BoundaryResolver< TPixelType, TDimension >::BoundaryResolver () inline protected
Definition at line 147 of file itkWatershedBoundaryResolver.h.
References itk::SmartPointer< TObjectType >::GetPointer(), and itk::ProcessObject::SetNthOutput().
~BoundaryResolver()
template<typename TPixelType , unsigned int TDimension> itk::watershed::BoundaryResolver< TPixelType, TDimension >::~BoundaryResolver () override protected default
Member Function Documentation
GenerateData()
template<typename TPixelType , unsigned int TDimension> void itk::watershed::BoundaryResolver< TPixelType, TDimension >::GenerateData () override virtual
Standard non-threaded pipeline method
Reimplemented from itk::ProcessObject.
GenerateOutputRequestedRegion()
template<typename TPixelType , unsigned int TDimension> void itk::watershed::BoundaryResolver< TPixelType, TDimension >::GenerateOutputRequestedRegion (DataObject * output) override protected virtual
Given one output whose requested region has been set, how should the requested regions for the remaining outputs of the process object be set? By default, all the outputs are set to the same requested region. If a filter needs to produce different requested regions for each output, for instance an image processing filter producing several outputs at different resolutions, then that filter may override this method and set the requested regions appropriately.
Note that a filter producing multiple outputs of different types is required to override this method. The default implementation can only correctly handle multiple outputs of the same type.
Reimplemented from itk::ProcessObject.
GetBoundaryA()
template<typename TPixelType , unsigned int TDimension> BoundaryType::Pointer itk::watershed::BoundaryResolver< TPixelType, TDimension >::GetBoundaryA () inline
Set/Get the first of two boundaries that are to be resolved.
Definition at line 96 of file itkWatershedBoundaryResolver.h.
GetBoundaryB()
template<typename TPixelType , unsigned int TDimension> BoundaryType::Pointer itk::watershed::BoundaryResolver< TPixelType, TDimension >::GetBoundaryB () inline
Set/Get the second of two boundaries that are to be resolved.
Definition at line 109 of file itkWatershedBoundaryResolver.h.
GetEquivalencyTable()
template<typename TPixelType , unsigned int TDimension> EquivalencyTableType::Pointer itk::watershed::BoundaryResolver< TPixelType, TDimension >::GetEquivalencyTable () inline
This method sets/gets the equivalency table used to store equivalencies among segments that are generated from the boundary resolution algorithm.
Definition at line 130 of file itkWatershedBoundaryResolver.h.
References itk::ProcessObject::GetOutput().
GetFace()
template<typename TPixelType , unsigned int TDimension> virtual unsigned short itk::watershed::BoundaryResolver< TPixelType, TDimension >::GetFace () const virtual
Set/Get the face of the boundary object that we are going to resolve.
GetNameOfClass()
template<typename TPixelType , unsigned int TDimension> virtual const char* itk::watershed::BoundaryResolver< TPixelType, TDimension >::GetNameOfClass () const virtual
Set up smart pointer and object factory definitions.
Reimplemented from itk::ProcessObject.
MakeOutput()
template<typename TPixelType , unsigned int TDimension> DataObjectPointer itk::watershed::BoundaryResolver< TPixelType, TDimension >::MakeOutput (DataObjectPointerArraySizeType idx) override virtual
Make a DataObject of the correct type to used as the specified output.
Every ProcessObject subclass must be able to create a DataObject that can be used as a specified output. This method is automatically called when DataObject::DisconnectPipeline() is called. DataObject::DisconnectPipeline, disconnects a data object from being an output of its current source. When the data object is disconnected, the ProcessObject needs to construct a replacement output data object so that the ProcessObject is in a valid state. So DataObject::DisconnectPipeline eventually calls ProcessObject::MakeOutput. Note that MakeOutput always returns a itkSmartPointer to a DataObject. ImageSource and MeshSource override this method to create the correct type of image and mesh respectively. If a filter has multiple outputs of different types, then that filter must provide an implementation of MakeOutput().
Reimplemented from itk::ProcessObject.
New()
template<typename TPixelType , unsigned int TDimension> static Pointer itk::watershed::BoundaryResolver< TPixelType, TDimension >::New () static
Set up smart pointer and object factory definitions.
PrintSelf()
template<typename TPixelType , unsigned int TDimension> void itk::watershed::BoundaryResolver< TPixelType, TDimension >::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::ProcessObject.
SetBoundaryA()
template<typename TPixelType , unsigned int TDimension> void itk::watershed::BoundaryResolver< TPixelType, TDimension >::SetBoundaryA (BoundaryType * bd) inline
Set/Get the first of two boundaries that are to be resolved.
Definition at line 91 of file itkWatershedBoundaryResolver.h.
References itk::ProcessObject::SetNthInput().
SetBoundaryB()
template<typename TPixelType , unsigned int TDimension> void itk::watershed::BoundaryResolver< TPixelType, TDimension >::SetBoundaryB (BoundaryType * bd) inline
Set/Get the second of two boundaries that are to be resolved.
Definition at line 104 of file itkWatershedBoundaryResolver.h.
References itk::ProcessObject::SetNthInput().
SetEquivalencyTable()
template<typename TPixelType , unsigned int TDimension> void itk::watershed::BoundaryResolver< TPixelType, TDimension >::SetEquivalencyTable (EquivalencyTableType::Pointer a) inline
This method sets/gets the equivalency table used to store equivalencies among segments that are generated from the boundary resolution algorithm.
Definition at line 125 of file itkWatershedBoundaryResolver.h.
References itk::SmartPointer< TObjectType >::GetPointer(), and itk::ProcessObject::SetNthOutput().
SetFace()
template<typename TPixelType , unsigned int TDimension> virtual void itk::watershed::BoundaryResolver< TPixelType, TDimension >::SetFace (unsigned short _arg) virtual
Set/Get the face of the boundary object that we are going to resolve.
Member Data Documentation
ImageDimension
template<typename TPixelType , unsigned int TDimension> constexpr unsigned int itk::watershed::BoundaryResolver< TPixelType, TDimension >::ImageDimension = TDimension static constexpr
Expose the image dimension at run time.
Definition at line 80 of file itkWatershedBoundaryResolver.h.
m_Face
template<typename TPixelType , unsigned int TDimension> unsigned short itk::watershed::BoundaryResolver< TPixelType, TDimension >::m_Face { 0 } protected
Definition at line 160 of file itkWatershedBoundaryResolver.h.
The documentation for this class was generated from the following file:
itkWatershedBoundaryResolver.h