ITK: itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor Class Reference
itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor Class Reference
Group Core » Module ITKMesh
#include <itkSimplexMeshAdaptTopologyFilter.h>
Public Member Functions
double ComputeArea (PointIdentifier p1, PointIdentifier p2, PointIdentifier p3)
DoubleValueMapType::Pointer GetAreaMap ()
DoubleValueMapType::Pointer GetCurvatureMap ()
double GetMaximumCellSize ()
double GetMaximumCurvature ()
double GetMinimumCellSize ()
double GetMinimumCurvature ()
double GetTotalMeanCurvature ()
double GetTotalMeshArea ()
SimplexCellVisitor ()
void Visit (CellIdentifier cellId, InputPolygonType *poly)
Public Attributes
DoubleValueMapType::Pointer areaMap
DoubleValueMapType::Pointer curvatureMap
double maxCellSize
double maxCurvature
InputMeshPointer mesh
double minCellSize
double minCurvature
double totalArea
double totalCurvature
Detailed Description
template<typename TInputMesh, typename TOutputMesh>
class itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor
class for visiting all polygonal cells. The visitor computes the area and curvature of each cell and stores them in the area map.
Definition at line 98 of file itkSimplexMeshAdaptTopologyFilter.h.
Constructor & Destructor Documentation
SimplexCellVisitor()
template<typename TInputMesh , typename TOutputMesh > itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::SimplexCellVisitor () inline
Definition at line 112 of file itkSimplexMeshAdaptTopologyFilter.h.
References itk::NumericTraits< T >::max(), and New().
Member Function Documentation
ComputeArea()
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::ComputeArea (PointIdentifier p1, PointIdentifier p2, PointIdentifier p3) inline
Definition at line 184 of file itkSimplexMeshAdaptTopologyFilter.h.
References itk::Math::abs().
GetAreaMap()
template<typename TInputMesh , typename TOutputMesh > DoubleValueMapType::Pointer itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetAreaMap () inline
Definition at line 199 of file itkSimplexMeshAdaptTopologyFilter.h.
GetCurvatureMap()
template<typename TInputMesh , typename TOutputMesh > DoubleValueMapType::Pointer itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetCurvatureMap () inline
Definition at line 205 of file itkSimplexMeshAdaptTopologyFilter.h.
GetMaximumCellSize()
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetMaximumCellSize () inline
Definition at line 223 of file itkSimplexMeshAdaptTopologyFilter.h.
GetMaximumCurvature()
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetMaximumCurvature () inline
Definition at line 235 of file itkSimplexMeshAdaptTopologyFilter.h.
GetMinimumCellSize()
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetMinimumCellSize () inline
Definition at line 229 of file itkSimplexMeshAdaptTopologyFilter.h.
GetMinimumCurvature()
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetMinimumCurvature () inline
Definition at line 241 of file itkSimplexMeshAdaptTopologyFilter.h.
GetTotalMeanCurvature()
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetTotalMeanCurvature () inline
Definition at line 217 of file itkSimplexMeshAdaptTopologyFilter.h.
GetTotalMeshArea()
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::GetTotalMeshArea () inline
Definition at line 211 of file itkSimplexMeshAdaptTopologyFilter.h.
Visit()
template<typename TInputMesh , typename TOutputMesh > void itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::Visit (CellIdentifier cellId, InputPolygonType * poly) inline
visits all polygon cells and computes the area, NOTE: works for convex polygons only!!!
Definition at line 128 of file itkSimplexMeshAdaptTopologyFilter.h.
References itk::Math::abs(), itk::PolygonCell< TCellInterface >::PointIdsBegin(), and itk::PolygonCell< TCellInterface >::PointIdsEnd().
Member Data Documentation
areaMap
template<typename TInputMesh , typename TOutputMesh > DoubleValueMapType::Pointer itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::areaMap
Definition at line 106 of file itkSimplexMeshAdaptTopologyFilter.h.
curvatureMap
template<typename TInputMesh , typename TOutputMesh > DoubleValueMapType::Pointer itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::curvatureMap
Definition at line 107 of file itkSimplexMeshAdaptTopologyFilter.h.
maxCellSize
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::maxCellSize
Definition at line 105 of file itkSimplexMeshAdaptTopologyFilter.h.
maxCurvature
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::maxCurvature
Definition at line 110 of file itkSimplexMeshAdaptTopologyFilter.h.
mesh
template<typename TInputMesh , typename TOutputMesh > InputMeshPointer itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::mesh
Definition at line 101 of file itkSimplexMeshAdaptTopologyFilter.h.
minCellSize
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::minCellSize
Definition at line 104 of file itkSimplexMeshAdaptTopologyFilter.h.
minCurvature
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::minCurvature
Definition at line 109 of file itkSimplexMeshAdaptTopologyFilter.h.
totalArea
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::totalArea
Definition at line 102 of file itkSimplexMeshAdaptTopologyFilter.h.
totalCurvature
template<typename TInputMesh , typename TOutputMesh > double itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::totalCurvature
Definition at line 103 of file itkSimplexMeshAdaptTopologyFilter.h.
The documentation for this class was generated from the following file:
itkSimplexMeshAdaptTopologyFilter.h