ITK: itk::Function::MorphologicalGradientHistogram< TInputPixel > Class Template Reference
itk::Function::MorphologicalGradientHistogram< TInputPixel > Class Template Reference
#include <itkMovingHistogramMorphologicalGradientImageFilter.h>
Public Types
using MapType = std::map< TInputPixel, SizeValueType >
Public Member Functions
void AddBoundary ()
void AddPixel (const TInputPixel &p)
TInputPixel GetValue ()
TInputPixel GetValue (const TInputPixel &)
MorphologicalGradientHistogram ()=default
void RemoveBoundary ()
void RemovePixel (const TInputPixel &p)
~MorphologicalGradientHistogram ()=default
Static Public Member Functions
static bool UseVectorBasedAlgorithm ()
Public Attributes
MapType m_Map
Detailed Description
template<typename TInputPixel>
class itk::Function::MorphologicalGradientHistogram< TInputPixel >
Definition at line 29 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Member Typedef Documentation
MapType
template<typename TInputPixel > using itk::Function::MorphologicalGradientHistogram< TInputPixel >::MapType = std::map<TInputPixel, SizeValueType>
Definition at line 44 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Constructor & Destructor Documentation
MorphologicalGradientHistogram()
template<typename TInputPixel > itk::Function::MorphologicalGradientHistogram< TInputPixel >::MorphologicalGradientHistogram () default
~MorphologicalGradientHistogram()
template<typename TInputPixel > itk::Function::MorphologicalGradientHistogram< TInputPixel >::~MorphologicalGradientHistogram () default
Member Function Documentation
AddBoundary()
template<typename TInputPixel > void itk::Function::MorphologicalGradientHistogram< TInputPixel >::AddBoundary () inline
Definition at line 37 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
AddPixel()
template<typename TInputPixel > void itk::Function::MorphologicalGradientHistogram< TInputPixel >::AddPixel (const TInputPixel & p) inline
Definition at line 47 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::MorphologicalGradientHistogram< TInputPixel >::m_Map.
GetValue() [1/2]
template<typename TInputPixel > TInputPixel itk::Function::MorphologicalGradientHistogram< TInputPixel >::GetValue () inline
Definition at line 65 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::MorphologicalGradientHistogram< TInputPixel >::m_Map.
Referenced by itk::Function::MorphologicalGradientHistogram< TInputPixel >::GetValue().
GetValue() [2/2]
template<typename TInputPixel > TInputPixel itk::Function::MorphologicalGradientHistogram< TInputPixel >::GetValue (const TInputPixel &) inline
Definition at line 59 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::MorphologicalGradientHistogram< TInputPixel >::GetValue().
RemoveBoundary()
template<typename TInputPixel > void itk::Function::MorphologicalGradientHistogram< TInputPixel >::RemoveBoundary () inline
Definition at line 41 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
RemovePixel()
template<typename TInputPixel > void itk::Function::MorphologicalGradientHistogram< TInputPixel >::RemovePixel (const TInputPixel & p) inline
Definition at line 53 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
References itk::Function::MorphologicalGradientHistogram< TInputPixel >::m_Map.
UseVectorBasedAlgorithm()
template<typename TInputPixel > static bool itk::Function::MorphologicalGradientHistogram< TInputPixel >::UseVectorBasedAlgorithm () inline static
Definition at line 96 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Referenced by itk::MovingHistogramMorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >::GetUseVectorBasedAlgorithm().
Member Data Documentation
m_Map
template<typename TInputPixel > MapType itk::Function::MorphologicalGradientHistogram< TInputPixel >::m_Map
Definition at line 101 of file itkMovingHistogramMorphologicalGradientImageFilter.h.
Referenced by itk::Function::MorphologicalGradientHistogram< TInputPixel >::AddPixel(), itk::Function::MorphologicalGradientHistogram< TInputPixel >::GetValue(), and itk::Function::MorphologicalGradientHistogram< TInputPixel >::RemovePixel().
The documentation for this class was generated from the following file:
itkMovingHistogramMorphologicalGradientImageFilter.h