ITK: itk::IOTestHelper Class Reference
itk::IOTestHelper Class Reference
#include <itkIOTestHelper.h>
Static Public Member Functions
template<typename ImageType >
static ImageType::Pointer AllocateImageFromRegionAndSpacing (const typename ImageType::RegionType &region, const typename ImageType::SpacingType &spacing)
template<typename ImageType >
static ImageType::Pointer AllocateImageFromRegionAndSpacing (const typename ImageType::RegionType &region, const typename ImageType::SpacingType &spacing, int vecLength)
static void RandomPix (vnl_random &randgen, double &pix)
static void RandomPix (vnl_random &randgen, float &pix)
static void RandomPix (vnl_random &randgen, itk::RGBPixel< unsigned char > &pix)
static void RandomPix (vnl_random &randgen, long long &pix)
template<typename TPixel >
static void RandomPix (vnl_random &randgen, TPixel &pix)
static void RandomPix (vnl_random &randgen, unsigned long long &pix)
template<typename TImage >
static TImage::Pointer ReadImage (const std::string &fileName, const bool zeroOrigin=false, typename ImageIOBase::Pointer imageio=nullptr)
static int Remove (const char *fname)
template<typename ImageType >
static void SetIdentityDirection (typename ImageType::Pointer &im)
template<typename ImageType , typename ImageIOType >
static void WriteImage (typename ImageType::Pointer &image, const std::string &filename, typename ImageIOType::Pointer imageio=nullptr)
Detailed Description
Definition at line 29 of file itkIOTestHelper.h.
Member Function Documentation
AllocateImageFromRegionAndSpacing() [1/2]
template<typename ImageType > static ImageType::Pointer itk::IOTestHelper::AllocateImageFromRegionAndSpacing (const typename ImageType::RegionType & region, const typename ImageType::SpacingType & spacing) inline static
Definition at line 169 of file itkIOTestHelper.h.
References New().
AllocateImageFromRegionAndSpacing() [2/2]
template<typename ImageType > static ImageType::Pointer itk::IOTestHelper::AllocateImageFromRegionAndSpacing (const typename ImageType::RegionType & region, const typename ImageType::SpacingType & spacing, int vecLength) inline static
Definition at line 181 of file itkIOTestHelper.h.
References New().
RandomPix() [1/6]
static void itk::IOTestHelper::RandomPix (vnl_random & randgen, double & pix) inline static
Definition at line 141 of file itkIOTestHelper.h.
RandomPix() [2/6]
static void itk::IOTestHelper::RandomPix (vnl_random & randgen, float & pix) inline static
Definition at line 147 of file itkIOTestHelper.h.
RandomPix() [3/6]
static void itk::IOTestHelper::RandomPix (vnl_random & randgen, itk::RGBPixel< unsigned char > & pix) inline static
Definition at line 111 of file itkIOTestHelper.h.
RandomPix() [4/6]
static void itk::IOTestHelper::RandomPix (vnl_random & randgen, long long & pix) inline static
Definition at line 127 of file itkIOTestHelper.h.
RandomPix() [5/6]
template<typename TPixel > static void itk::IOTestHelper::RandomPix (vnl_random & randgen, TPixel & pix) inline static
Definition at line 121 of file itkIOTestHelper.h.
RandomPix() [6/6]
static void itk::IOTestHelper::RandomPix (vnl_random & randgen, unsigned long long & pix) inline static
Definition at line 134 of file itkIOTestHelper.h.
ReadImage()
template<typename TImage > static TImage::Pointer itk::IOTestHelper::ReadImage (const std::string & fileName, const bool zeroOrigin = false, typename ImageIOBase::Pointer imageio = nullptr) inline static
Definition at line 34 of file itkIOTestHelper.h.
References New().
Remove()
static int itk::IOTestHelper::Remove (const char * fname) inline static
Definition at line 153 of file itkIOTestHelper.h.
SetIdentityDirection()
template<typename ImageType > static void itk::IOTestHelper::SetIdentityDirection (typename ImageType::Pointer & im) inline static
Definition at line 160 of file itkIOTestHelper.h.
References itk::Matrix< T, VRows, VColumns >::SetIdentity().
WriteImage()
template<typename ImageType , typename ImageIOType > static void itk::IOTestHelper::WriteImage (typename ImageType::Pointer & image, const std::string & filename, typename ImageIOType::Pointer imageio = nullptr) inline static
Definition at line 78 of file itkIOTestHelper.h.
References New().
The documentation for this class was generated from the following file:
itkIOTestHelper.h