ITK: itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy > Class Template Reference
itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy > Class Template Reference final
Data Access Objects » Iterators » Image IteratorsGroup Core » | Module ITKCommon
#include <itkShapedImageNeighborhoodRange.h>
Classes
class CheckPolicy
struct EmptyPixelAccessParameter
struct OptionalPixelAccessParameter
struct OptionalPixelAccessParameter< TPolicy, false >
class PixelProxy
class PixelProxy< false, TDummy >
class PixelProxy< true, TDummy >
class QualifiedIterator
struct RegionData
Public Types
using const_iterator = QualifiedIterator< true >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using iterator = QualifiedIterator< IsImageTypeConst >
using reverse_iterator = std::reverse_iterator< iterator >
Public Member Functions
iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
bool empty () const noexcept
iterator end () const noexcept
reverse_iterator rbegin () const noexcept
reverse_iterator rend () const noexcept
ShapedImageNeighborhoodRange ()=default
vcl_size_t size () const noexcept
ShapedImageNeighborhoodRange (ImageType &image, const IndexType &location, const OffsetType *const shapeOffsets, const vcl_size_t numberOfNeigborhoodPixels, const OptionalPixelAccessParameterType optionalPixelAccessParameter={})
template<typename TContainerOfOffsets >
ShapedImageNeighborhoodRange (ImageType &image, const IndexType &location, const TContainerOfOffsets &shapeOffsets, const OptionalPixelAccessParameterType optionalPixelAccessParameter={})
QualifiedIterator< false >::reference operator[] (const vcl_size_t n) const noexcept
void SetLocation (const IndexType &location) noexcept
Private Types
using ImageDimensionType = typename TImage::ImageDimensionType
using ImageRegionType = typename TImage::RegionType
using ImageSizeType = typename TImage::SizeType
using ImageSizeValueType = typename TImage::SizeValueType
using ImageType = TImage
using IndexType = typename TImage::IndexType
using IndexValueType = typename TImage::IndexValueType
using InternalPixelType = typename TImage::InternalPixelType
using NeighborhoodAccessorFunctorType = typename TImage::NeighborhoodAccessorFunctorType
using OffsetType = Offset< ImageDimension >
using OptionalPixelAccessParameterType = typename OptionalPixelAccessParameter< TImageNeighborhoodPixelAccessPolicy >::Type
using PixelType = typename TImage::PixelType
using QualifiedInternalPixelType = std::conditional_t< IsImageTypeConst, const InternalPixelType, InternalPixelType >
Private Member Functions
void SubtractIndex (IndexType &index1, const IndexType &index2)
Private Attributes
RegionData m_BufferedRegionData {}
QualifiedInternalPixelType * m_ImageBufferPointer { nullptr }
NeighborhoodAccessorFunctorType m_NeighborhoodAccessor {}
vcl_size_t m_NumberOfNeighborhoodPixels { 0 }
OffsetType m_OffsetTable { {} }
OptionalPixelAccessParameterType m_OptionalPixelAccessParameter {}
IndexType m_RelativeLocation { {} }
const OffsetType * m_ShapeOffsets { nullptr }
Static Private Attributes
static constexpr ImageDimensionType ImageDimension = TImage::ImageDimension
static constexpr bool IsImageTypeConst = std::is_const<TImage>::value
Detailed Description
template<typename TImage, typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>>
class itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >
Modern C++11 range to iterate over a neighborhood of pixels. Designed to conform to Standard C++ Iterator requirements, so that it can be used in range-based for loop, and passed to Standard C++ algorithms.
The following example creates a 3 x 5 neighborhood around pixel [10, 20] and adds 42 to each neighborhood pixel, using a range-based for loop:
const ImageType::IndexType location = {10, 20};
const itk::Size<ImageType::ImageDimension> radius = { { 1, 2 } };
const std::vector<OffsetType> offsets = itk::GenerateRectangularImageNeighborhoodOffsets(radius)
itk::ShapedImageNeighborhoodRange<ImageType> neighborhoodRange{ *image, location, offsets };
for (auto&& neighborhoodPixel : neighborhoodRange)
{
  neighborhoodPixel = neighborhoodPixel + 42;
}
The following example prints the values of the neighborhood pixels:
for (const PixelType neighborhoodPixel : neighborhoodRange)
{
  std::cout << neighborhoodPixel << std::endl;
}
The inner product of the neighborhood with a kernel can be produced with std::inner_product (from the Standard C++ header "numeric"), as follows:
double result = std::inner_product(
  kernel.begin(),
  kernel.end(),
  neighborhoodRange.begin(),
  0.0);
Note
Strictly speaking, the itk::ShapedImageNeighborhoodRange iterator classes do not fully comply with the C++11 random access iterator requirements, because their operator*() returns a proxy to the pixel, instead of a reference. Which implies that ShapedImageNeighborhoodRange iterators are not guaranteed to work well as argument to a C++ Standard Library function that requires a standard compliant iterator. However, this "pixel proxy" very much behaves like a reference to the pixel, and in practice, passing such an iterator to an std function usually just works!
Author
Niels Dekker, LKEB, Leiden University Medical Center
See also
ShapedNeighborhoodIterator
Definition at line 92 of file itkShapedImageNeighborhoodRange.h.
Member Typedef Documentation
const_iterator
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::const_iterator = QualifiedIterator<true>
Definition at line 646 of file itkShapedImageNeighborhoodRange.h.
const_reverse_iterator
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 649 of file itkShapedImageNeighborhoodRange.h.
ImageDimensionType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ImageDimensionType = typename TImage::ImageDimensionType private
Definition at line 139 of file itkShapedImageNeighborhoodRange.h.
ImageRegionType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ImageRegionType = typename TImage::RegionType private
Definition at line 142 of file itkShapedImageNeighborhoodRange.h.
ImageSizeType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ImageSizeType = typename TImage::SizeType private
Definition at line 140 of file itkShapedImageNeighborhoodRange.h.
ImageSizeValueType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ImageSizeValueType = typename TImage::SizeValueType private
Definition at line 141 of file itkShapedImageNeighborhoodRange.h.
ImageType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ImageType = TImage private
Definition at line 138 of file itkShapedImageNeighborhoodRange.h.
IndexType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::IndexType = typename TImage::IndexType private
Definition at line 147 of file itkShapedImageNeighborhoodRange.h.
IndexValueType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::IndexValueType = typename TImage::IndexValueType private
Definition at line 148 of file itkShapedImageNeighborhoodRange.h.
InternalPixelType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::InternalPixelType = typename TImage::InternalPixelType private
Definition at line 144 of file itkShapedImageNeighborhoodRange.h.
iterator
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::iterator = QualifiedIterator<IsImageTypeConst>
Definition at line 647 of file itkShapedImageNeighborhoodRange.h.
NeighborhoodAccessorFunctorType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::NeighborhoodAccessorFunctorType = typename TImage::NeighborhoodAccessorFunctorType private
Definition at line 145 of file itkShapedImageNeighborhoodRange.h.
OffsetType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::OffsetType = Offset<ImageDimension> private
Definition at line 149 of file itkShapedImageNeighborhoodRange.h.
OptionalPixelAccessParameterType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::OptionalPixelAccessParameterType = typename OptionalPixelAccessParameter<TImageNeighborhoodPixelAccessPolicy>::Type private
Definition at line 151 of file itkShapedImageNeighborhoodRange.h.
PixelType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::PixelType = typename TImage::PixelType private
Definition at line 143 of file itkShapedImageNeighborhoodRange.h.
QualifiedInternalPixelType
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::QualifiedInternalPixelType = std::conditional_t<IsImageTypeConst, const InternalPixelType, InternalPixelType> private
Definition at line 592 of file itkShapedImageNeighborhoodRange.h.
reverse_iterator
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> using itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 648 of file itkShapedImageNeighborhoodRange.h.
Constructor & Destructor Documentation
ShapedImageNeighborhoodRange() [1/3]
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ShapedImageNeighborhoodRange () default
Explicitly-defaulted default-constructor. Constructs an empty range.
Note
The other five "special member functions" (copy-constructor, copy-assignment operator, move-constructor, move-assignment operator, and destructor) are defaulted implicitly, following the C++ "Rule of Zero".
ShapedImageNeighborhoodRange() [2/3]
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ShapedImageNeighborhoodRange (ImageType & image, const IndexType & location, const OffsetType *const shapeOffsets, const vcl_size_t numberOfNeigborhoodPixels, const OptionalPixelAccessParameterType optionalPixelAccessParameter = {}) inline
Specifies a range for the neighborhood of a pixel at the specified location. The shape of the neighborhood is specified by a pointer to a contiguous sequence of offsets, relative to the location index.
Note
The caller (the client code) should ensure that both the specified image and the specified shape offsets remain alive while the range (or one of its iterators) is being used.
Definition at line 665 of file itkShapedImageNeighborhoodRange.h.
ShapedImageNeighborhoodRange() [3/3]
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> template<typename TContainerOfOffsets > itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ShapedImageNeighborhoodRange (ImageType & image, const IndexType & location, const TContainerOfOffsets & shapeOffsets, const OptionalPixelAccessParameterType optionalPixelAccessParameter = {}) inline
Specifies a range for the neighborhood of a pixel at the specified location. The shape of the neighborhood is specified by a container of offsets, relative to the location index. This container of offsets must be a contiguous container, for example std::vector<OffsetType> or std::array<OffsetType>.
Note
The caller (the client code) should ensure that both the specified image and the specified shape offsets remain alive while the range (or one of its iterators) is being used.
Definition at line 702 of file itkShapedImageNeighborhoodRange.h.
Member Function Documentation
begin()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin () const inline noexcept
Returns an iterator to the first neighborhood pixel.
Definition at line 716 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_BufferedRegionData, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_ImageBufferPointer, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_NeighborhoodAccessor, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_OffsetTable, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_OptionalPixelAccessParameter, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_RelativeLocation, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_ShapeOffsets, and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::RegionData::m_Size.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::cbegin(), itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::operator[](), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::rend().
cbegin()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> const_iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::cbegin () const inline noexcept
Returns a const iterator to the first neighborhood pixel. Provides only read-only access to the pixel data.
Definition at line 738 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin().
cend()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> const_iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::cend () const inline noexcept
Returns a const 'end iterator' for this range.
Definition at line 745 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end().
crbegin()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> const_reverse_iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::crbegin () const inline noexcept
Returns a const reverse 'begin iterator' for this range.
Definition at line 766 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::rbegin().
crend()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> const_reverse_iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::crend () const inline noexcept
Returns a const reverse 'end iterator' for this range.
Definition at line 773 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::rend().
empty()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> bool itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::empty () const inline noexcept
Tells whether the range is empty.
Definition at line 789 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_NumberOfNeighborhoodPixels.
end()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end () const inline noexcept
Returns an 'end iterator' for this range.
Definition at line 724 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_BufferedRegionData, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_ImageBufferPointer, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_NeighborhoodAccessor, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_NumberOfNeighborhoodPixels, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_OffsetTable, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_OptionalPixelAccessParameter, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_RelativeLocation, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_ShapeOffsets, and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::RegionData::m_Size.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::cend(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::rbegin().
operator[]()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> QualifiedIterator<false>::reference itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::operator[] (const vcl_size_t n) const inline noexcept
Subscript operator. Allows random access, to the nth neighbor pixel.
Note
The return type QualifiedIterator<false>::reference is equivalent to iterator::reference. The return value is a proxy object that behaves like a reference to the pixel.
Definition at line 800 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::size().
rbegin()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> reverse_iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::rbegin () const inline noexcept
Returns a reverse 'begin iterator' for this range.
Definition at line 752 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end().
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::crbegin().
rend()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> reverse_iterator itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::rend () const inline noexcept
Returns a reverse 'end iterator' for this range.
Definition at line 759 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin().
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::crend().
SetLocation()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> void itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::SetLocation (const IndexType & location) inline noexcept
Sets the location of this neighborhood by specifying its pixel index. Typically, this is the index of the center pixel of the neighborhood.
Definition at line 814 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_BufferedRegionData, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::RegionData::m_Index, itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_RelativeLocation, and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::SubtractIndex().
size()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> vcl_size_t itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::size () const inline noexcept
Returns the size of the range, that is the number of neighborhood pixels.
Definition at line 781 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_NumberOfNeighborhoodPixels.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::operator[]().
SubtractIndex()
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> void itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::SubtractIndex (IndexType & index1, const IndexType & index2) inline private
Definition at line 611 of file itkShapedImageNeighborhoodRange.h.
References itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ImageDimension.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::SetLocation().
Member Data Documentation
ImageDimension
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> constexpr ImageDimensionType itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::ImageDimension = TImage::ImageDimension static constexpr private
Definition at line 146 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::SubtractIndex().
IsImageTypeConst
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> constexpr bool itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::IsImageTypeConst = std::is_const<TImage>::value static constexpr private
Definition at line 590 of file itkShapedImageNeighborhoodRange.h.
m_BufferedRegionData
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> RegionData itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_BufferedRegionData {} private
Definition at line 625 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::SetLocation().
m_ImageBufferPointer
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> QualifiedInternalPixelType* itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_ImageBufferPointer { nullptr } private
Definition at line 622 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end(), itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::PixelProxy< true, TDummy >::operator PixelType(), itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::PixelProxy< false, TDummy >::operator PixelType(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::PixelProxy< false, TDummy >::operator=().
m_NeighborhoodAccessor
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> NeighborhoodAccessorFunctorType itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_NeighborhoodAccessor {} private
Definition at line 630 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end().
m_NumberOfNeighborhoodPixels
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> vcl_size_t itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_NumberOfNeighborhoodPixels { 0 } private
Definition at line 641 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::empty(), itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::size().
m_OffsetTable
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> OffsetType itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_OffsetTable { {} } private
Definition at line 628 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end().
m_OptionalPixelAccessParameter
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> OptionalPixelAccessParameterType itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_OptionalPixelAccessParameter {} private
Definition at line 643 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end().
m_RelativeLocation
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> IndexType itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_RelativeLocation { {} } private
Definition at line 635 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::SetLocation().
m_ShapeOffsets
template<typename TImage , typename TImageNeighborhoodPixelAccessPolicy = ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<TImage>> const OffsetType* itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::m_ShapeOffsets { nullptr } private
Definition at line 638 of file itkShapedImageNeighborhoodRange.h.
Referenced by itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::begin(), and itk::ShapedImageNeighborhoodRange< TImage, TImageNeighborhoodPixelAccessPolicy >::end().
The documentation for this class was generated from the following file:
itkShapedImageNeighborhoodRange.h