ITK: itk::NumericTraits< Array< T > > Class Template Reference
itk::NumericTraits< Array< T > > Class Template Reference
#include <itkNumericTraitsArrayPixel.h>
Public Types
using AbsType = Array< ElementAbsType >
using AccumulateType = Array< ElementAccumulateType >
using FloatType = Array< ElementFloatType >
using MeasurementVectorType = Self
using PrintType = Array< ElementPrintType >
using RealType = Array< ElementRealType >
using ScalarRealType = ElementRealType
using Self = Array< T >
using ValueType = T
Static Public Member Functions
static void AssignToArray (const Self &v, MeasurementVectorType &mv)
template<typename TArray >
static void AssignToArray (const Self &v, TArray &mv)
static vcl_size_t GetLength (const Array< T > &m)
static const Self max (const Self &a)
static const Self min (const Self &a)
static const Self NonpositiveMin (const Self &a)
static const Self OneValue (const Self &a)
static const Self ZeroValue (const Self &a)
static void SetLength (Array< T > &m, const unsigned int s)
Static Public Attributes
static constexpr bool IsComplex = NumericTraits<ValueType>::IsComplex
static constexpr bool IsInteger = std::is_integral<ValueType>::value
static constexpr bool IsSigned = std::is_signed<ValueType>::value
Private Types
using ElementAbsType = typename NumericTraits< T >::AbsType
using ElementAccumulateType = typename NumericTraits< T >::AccumulateType
using ElementFloatType = typename NumericTraits< T >::FloatType
using ElementPrintType = typename NumericTraits< T >::PrintType
using ElementRealType = typename NumericTraits< T >::RealType
Detailed Description
template<typename T>
class itk::NumericTraits< Array< T > >
NumericTraits for Array.
Template Parameters
T type of the array component
Definition at line 30 of file itkNumericTraitsArrayPixel.h.
Member Typedef Documentation
AbsType
template<typename T > using itk::NumericTraits< Array< T > >::AbsType = Array<ElementAbsType>
Unsigned component type
Definition at line 45 of file itkNumericTraitsArrayPixel.h.
AccumulateType
template<typename T > using itk::NumericTraits< Array< T > >::AccumulateType = Array<ElementAccumulateType>
Accumulation of addition and multiplication.
Definition at line 48 of file itkNumericTraitsArrayPixel.h.
ElementAbsType
template<typename T > using itk::NumericTraits< Array< T > >::ElementAbsType = typename NumericTraits<T>::AbsType private
Definition at line 33 of file itkNumericTraitsArrayPixel.h.
ElementAccumulateType
template<typename T > using itk::NumericTraits< Array< T > >::ElementAccumulateType = typename NumericTraits<T>::AccumulateType private
Definition at line 34 of file itkNumericTraitsArrayPixel.h.
ElementFloatType
template<typename T > using itk::NumericTraits< Array< T > >::ElementFloatType = typename NumericTraits<T>::FloatType private
Definition at line 35 of file itkNumericTraitsArrayPixel.h.
ElementPrintType
template<typename T > using itk::NumericTraits< Array< T > >::ElementPrintType = typename NumericTraits<T>::PrintType private
Definition at line 36 of file itkNumericTraitsArrayPixel.h.
ElementRealType
template<typename T > using itk::NumericTraits< Array< T > >::ElementRealType = typename NumericTraits<T>::RealType private
Definition at line 37 of file itkNumericTraitsArrayPixel.h.
FloatType
template<typename T > using itk::NumericTraits< Array< T > >::FloatType = Array<ElementFloatType>
Typedef for operations that use floating point instead of real precision
Definition at line 52 of file itkNumericTraitsArrayPixel.h.
MeasurementVectorType
template<typename T > using itk::NumericTraits< Array< T > >::MeasurementVectorType = Self
Measurement vector type
Definition at line 64 of file itkNumericTraitsArrayPixel.h.
PrintType
template<typename T > using itk::NumericTraits< Array< T > >::PrintType = Array<ElementPrintType>
Return the type that can be printed.
Definition at line 55 of file itkNumericTraitsArrayPixel.h.
RealType
template<typename T > using itk::NumericTraits< Array< T > >::RealType = Array<ElementRealType>
Type for real-valued scalar operations.
Definition at line 58 of file itkNumericTraitsArrayPixel.h.
ScalarRealType
template<typename T > using itk::NumericTraits< Array< T > >::ScalarRealType = ElementRealType
Type for real-valued scalar operations.
Definition at line 61 of file itkNumericTraitsArrayPixel.h.
Self
template<typename T > using itk::NumericTraits< Array< T > >::Self = Array<T>
Definition at line 42 of file itkNumericTraitsArrayPixel.h.
ValueType
template<typename T > using itk::NumericTraits< Array< T > >::ValueType = T
Return the type of the native component type.
Definition at line 41 of file itkNumericTraitsArrayPixel.h.
Member Function Documentation
AssignToArray() [1/2]
template<typename T > static void itk::NumericTraits< Array< T > >::AssignToArray (const Self & v, MeasurementVectorType & mv) inline static
Definition at line 136 of file itkNumericTraitsArrayPixel.h.
AssignToArray() [2/2]
template<typename T > template<typename TArray > static void itk::NumericTraits< Array< T > >::AssignToArray (const Self & v, TArray & mv) inline static
Definition at line 143 of file itkNumericTraitsArrayPixel.h.
References itk::NumericTraits< T >::GetLength().
GetLength()
template<typename T > static vcl_size_t itk::NumericTraits< Array< T > >::GetLength (const Array< T > & m) inline static
Get the length of the input array.
Definition at line 130 of file itkNumericTraitsArrayPixel.h.
References itk::Array< TValue >::GetSize().
max()
template<typename T > static const Self itk::NumericTraits< Array< T > >::max (const Self & a) inline static
Component wise defined element
Note
minimum value for floating pointer types is defined as minimum positive normalize value.
Definition at line 72 of file itkNumericTraitsArrayPixel.h.
References itk::Array< TValue >::Fill(), and itk::Array< TValue >::Size().
min()
template<typename T > static const Self itk::NumericTraits< Array< T > >::min (const Self & a) inline static
Definition at line 81 of file itkNumericTraitsArrayPixel.h.
References itk::Array< TValue >::Fill(), and itk::Array< TValue >::Size().
NonpositiveMin()
template<typename T > static const Self itk::NumericTraits< Array< T > >::NonpositiveMin (const Self & a) inline static
Definition at line 108 of file itkNumericTraitsArrayPixel.h.
References itk::Array< TValue >::Fill(), and itk::Array< TValue >::Size().
OneValue()
template<typename T > static const Self itk::NumericTraits< Array< T > >::OneValue (const Self & a) inline static
Definition at line 99 of file itkNumericTraitsArrayPixel.h.
References itk::Array< TValue >::Fill(), and itk::Array< TValue >::Size().
SetLength()
template<typename T > static void itk::NumericTraits< Array< T > >::SetLength (Array< T > & m, const unsigned int s) inline static
Set the length of the input array and fill it with zeros.
Definition at line 121 of file itkNumericTraitsArrayPixel.h.
References itk::Array< TValue >::Fill(), and itk::Array< TValue >::SetSize().
ZeroValue()
template<typename T > static const Self itk::NumericTraits< Array< T > >::ZeroValue (const Self & a) inline static
Definition at line 90 of file itkNumericTraitsArrayPixel.h.
References itk::Array< TValue >::Fill(), and itk::Array< TValue >::Size().
Member Data Documentation
IsComplex
template<typename T > constexpr bool itk::NumericTraits< Array< T > >::IsComplex = NumericTraits<ValueType>::IsComplex static constexpr
Definition at line 117 of file itkNumericTraitsArrayPixel.h.
IsInteger
template<typename T > constexpr bool itk::NumericTraits< Array< T > >::IsInteger = std::is_integral<ValueType>::value static constexpr
Definition at line 116 of file itkNumericTraitsArrayPixel.h.
IsSigned
template<typename T > constexpr bool itk::NumericTraits< Array< T > >::IsSigned = std::is_signed<ValueType>::value static constexpr
Definition at line 115 of file itkNumericTraitsArrayPixel.h.
The documentation for this class was generated from the following file:
itkNumericTraitsArrayPixel.h