ITK: itk::NumericTraits< T > Class Template Reference
itk::NumericTraits< T > Class Template Reference
Data Representation ObjectsGroup Core » | Module ITKCommon
#include <itkNumericTraits.h>
Public Types
using AbsType = T
using AccumulateType = double
using FloatType = float
using MeasurementVectorType = FixedArray< ValueType, 1 >
using PrintType = T
using RealType = double
using ScalarRealType = RealType
using TraitsType = std::numeric_limits< T >
using ValueType = T
Static Public Member Functions
template<typename TArray >
static void AssignToArray (const T &v, TArray &mv)
static unsigned int GetLength ()
static unsigned int GetLength (const T &)
static bool IsNegative (T val)
static bool IsNonnegative (T val)
static bool IsNonpositive (T val)
static bool IsPositive (T val)
static constexpr T max (const T &)
static constexpr T min (const T &)
static constexpr T NonpositiveMin ()
static T NonpositiveMin (const T &)
static T OneValue ()
static T OneValue (const T &)
static void SetLength (T &m, const unsigned int s)
static T ZeroValue ()
static T ZeroValue (const T &)
Static Public Attributes
static constexpr bool IsComplex = false
static constexpr bool IsInteger = false
static constexpr bool IsSigned = false
static const T ITKCommon_EXPORT One
static const T ITKCommon_EXPORT Zero
Detailed Description
template<typename T>
class itk::NumericTraits< T >
Define additional traits for native types such as int or float.
Define numeric traits for std::vector.
NumericTraits is used to extend the traits associated with native types such as float, char, int, and so on. These traits are extensions of the standard numeric_limits defined by the C++ compilers. Some of the added traits include minimum and maximum value; accumulation type; etc.
ITK Sphinx Examples:
All ITK Sphinx Examples
Get Type Basic Information
Template Parameters
T Component type of std::vector
We provide here a generic implementation based on creating types of std::vector whose components are the types of the NumericTraits from the original std::vector components. This implementation require support for partial specializations, since it is based on the concept that: NumericTraits<std::vector< T > > is defined piecewise by std::vector< NumericTraits< T > >
Note
The Zero(), One(), min() and max() methods here take references to a pixel as input. This is due to the fact that the length of the std::vector is not known until run-time. Since the most common use of Zero and One is for comparison purposes or initialization of sums etc, this might just as easily be re-written with a pixel passed in as a reference and the length is inferred from this pixel.
See also
NumericTraits
Definition at line 58 of file itkNumericTraits.h.
Member Typedef Documentation
AbsType
template<typename T > using itk::NumericTraits< T >::AbsType = T
Return value of itk::Math::abs().
Definition at line 71 of file itkNumericTraits.h.
AccumulateType
template<typename T > using itk::NumericTraits< T >::AccumulateType = double
Accumulation of addition and multiplication.
Definition at line 74 of file itkNumericTraits.h.
FloatType
template<typename T > using itk::NumericTraits< T >::FloatType = float
Typedef for operations that use floating point instead of real precision to save memory
Definition at line 81 of file itkNumericTraits.h.
MeasurementVectorType
template<typename T > using itk::NumericTraits< T >::MeasurementVectorType = FixedArray<ValueType, 1>
Measurement vector type
Definition at line 77 of file itkNumericTraits.h.
PrintType
template<typename T > using itk::NumericTraits< T >::PrintType = T
Return the type that can be printed.
Definition at line 68 of file itkNumericTraits.h.
RealType
template<typename T > using itk::NumericTraits< T >::RealType = double
Type for real-valued scalar operations.
Definition at line 84 of file itkNumericTraits.h.
ScalarRealType
template<typename T > using itk::NumericTraits< T >::ScalarRealType = RealType
Type for real-valued scalar operations.
Definition at line 87 of file itkNumericTraits.h.
TraitsType
template<typename T > using itk::NumericTraits< T >::TraitsType = std::numeric_limits<T>
The type of this limits trait object.
Definition at line 62 of file itkNumericTraits.h.
ValueType
template<typename T > using itk::NumericTraits< T >::ValueType = T
Return the type of this native type.
Definition at line 65 of file itkNumericTraits.h.
Member Function Documentation
AssignToArray()
template<typename T > template<typename TArray > static void itk::NumericTraits< T >::AssignToArray (const T & v, TArray & mv) inline static
assign the value to an array
Definition at line 243 of file itkNumericTraits.h.
GetLength() [1/2]
template<typename T > static unsigned int itk::NumericTraits< T >::GetLength () inline static
Return the length of the scalar: 1. Array types can return a different value
Definition at line 208 of file itkNumericTraits.h.
Referenced by itk::NumericTraits< Array< T > >::AssignToArray(), itk::NumericTraits< std::vector< T > >::AssignToArray(), itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::AssignToArray(), itk::NumericTraits< VariableLengthVector< T > >::AssignToArray(), itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::GetLength(), itk::NumericTraits< InputImagePixelType >::GetLength(), itk::NumericTraits< Vector< T, D > >::IsNegative(), itk::NumericTraits< VariableLengthVector< T > >::IsNegative(), itk::NumericTraits< Vector< T, D > >::IsNonnegative(), itk::NumericTraits< VariableLengthVector< T > >::IsNonnegative(), itk::NumericTraits< Vector< T, D > >::IsNonpositive(), itk::NumericTraits< VariableLengthVector< T > >::IsNonpositive(), itk::NumericTraits< Vector< T, D > >::IsPositive(), itk::NumericTraits< VariableLengthVector< T > >::IsPositive(), itk::Statistics::MeasurementVectorTraits::IsResizable(), itk::Statistics::MembershipFunctionBase< TMeasurementVector >::MembershipFunctionBase(), itk::Statistics::Sample< ImageJointDomainTraits< TImage >::MeasurementVectorType >::Sample(), itk::Statistics::KdTreeBasedKmeansEstimator< TKdTree >::CandidateVector::SetCentroids(), itk::Statistics::MembershipFunctionBase< TMeasurementVector >::SetMeasurementVectorSize(), itk::Statistics::DistanceMetric< Array< double > >::SetMeasurementVectorSize(), itk::Statistics::Sample< ImageJointDomainTraits< TImage >::MeasurementVectorType >::SetMeasurementVectorSize(), itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >::TransformOutputPixel(), and itk::GTest::Predicate::VectorDoubleRMSPredFormat().
GetLength() [2/2]
template<typename T > static unsigned int itk::NumericTraits< T >::GetLength (const T &) inline static
Return the length of the scalar. This API is needed for VariableLengthVector because its length is only known at run-time. Specializations of the VariableLengthVector will provide a different implementation where a vector of the correct size is built.
Definition at line 201 of file itkNumericTraits.h.
IsNegative()
template<typename T > static bool itk::NumericTraits< T >::IsNegative (T val) inline static
Is a given value negative?
Definition at line 118 of file itkNumericTraits.h.
Referenced by itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::NumericTraits< RGBPixel< T > >::IsNegative(), and itk::NumericTraits< RGBAPixel< T > >::IsNegative().
IsNonnegative()
template<typename T > static bool itk::NumericTraits< T >::IsNonnegative (T val) inline static
Is a given value nonnegative?
Definition at line 125 of file itkNumericTraits.h.
Referenced by itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::NumericTraits< RGBPixel< T > >::IsNonnegative(), and itk::NumericTraits< RGBAPixel< T > >::IsNonnegative().
IsNonpositive()
template<typename T > static bool itk::NumericTraits< T >::IsNonpositive (T val) inline static
Is a given value nonpositive?
Definition at line 111 of file itkNumericTraits.h.
Referenced by itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::NumericTraits< RGBPixel< T > >::IsNonpositive(), and itk::NumericTraits< RGBAPixel< T > >::IsNonpositive().
IsPositive()
template<typename T > static bool itk::NumericTraits< T >::IsPositive (T val) inline static
Is a given value positive?
Definition at line 104 of file itkNumericTraits.h.
Referenced by itk::Math::CastWithRangeCheck(), itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::NumericTraits< RGBAPixel< T > >::IsPositive(), and itk::NumericTraits< RGBPixel< T > >::IsPositive().
max()
template<typename T > static constexpr T itk::NumericTraits< T >::max (const T &) inline static constexpr
Definition at line 167 of file itkNumericTraits.h.
Referenced by itk::AdaptiveHistogramEqualizationImageFilter< TImageType, TKernel >::AdaptiveHistogramEqualizationImageFilter(), itk::Functor::LabelToRGBFunctor< TLabelImage::PixelType, TOutputImage::PixelType >::AddColor(), itk::AnchorCloseImageFilter< TImage, TKernel >::AnchorCloseImageFilter(), itk::AnchorErodeImageFilter< TImage, TKernel >::AnchorErodeImageFilter(), itk::AnchorOpenImageFilter< TImage, TKernel >::AnchorOpenImageFilter(), itk::BinaryNotImageFilter< TImage >::BinaryNotImageFilter(), itk::BinaryProjectionImageFilter< TInputImage, TOutputImage >::BinaryProjectionImageFilter(), itk::Functor::BinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >::BinaryThreshold(), itk::BinaryThresholdProjectionImageFilter< TInputImage, TOutputImage >::BinaryThresholdProjectionImageFilter(), itk::Function::ColormapFunction< TScalar, TRGBPixel >::ColormapFunction(), itk::Function::RankHistogram< TInputPixel >::GetValueBruteForce(), itk::Function::VectorRankHistogram< TInputPixel >::GetValueBruteForce(), itk::Functor::GPUBinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >::GPUBinaryThreshold(), itk::HexahedronCell< TCellInterface >::HexahedronCell(), itk::Functor::MinimumAccumulator< TInputPixel >::Initialize(), itk::Functor::IntensityLinearTransform< TInputImage::PixelType, TInputImage ::PixelType >::IntensityLinearTransform(), itk::Functor::InvertIntensityTransform< TInputImage::PixelType, TInputImage ::PixelType >::InvertIntensityTransform(), itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >::LabelStatistics::LabelStatistics(), itk::LineCell< TCellInterface >::LineCell(), itk::MovingHistogramErodeImageFilter< TInputImage, TOutputImage, TKernel >::MovingHistogramErodeImageFilter(), itk::Functor::ConstrainedValueAddition< TInput1, TInput2, TOutput >::operator()(), itk::Functor::Div< TInput1, TInput2, TOutput >::operator()(), itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >::UnsharpMaskingFunctor< InPixelType, FunctorRealType, OutPixelType >::operator()(), itk::Functor::Modulus< TInput1, TInput2, TOutput >::operator()(), itk::Functor::DivFloor< TInput1, TInput2, TOutput >::operator()(), itk::QuadraticEdgeCell< TCellInterface >::QuadraticEdgeCell(), itk::QuadraticTriangleCell< TCellInterface >::QuadraticTriangleCell(), itk::QuadrilateralCell< TCellInterface >::QuadrilateralCell(), itk::Function::RankHistogram< TInputPixel >::RankHistogram(), itk::ReconstructionByErosionImageFilter< TInputImage, TOutputImage >::ReconstructionByErosionImageFilter(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemovePixel(), itk::Functor::Sigmoid< TInputImage::PixelType, TOutputImage::PixelType >::Sigmoid(), itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::SimplexCellVisitor(), itk::STAPLEImageFilter< TInputImage, TOutputImage >::STAPLEImageFilter(), itk::TetrahedronCell< TCellInterface >::TetrahedronCell(), itk::ThresholdSegmentationLevelSetFunction< TImageType, TFeatureImageType >::ThresholdSegmentationLevelSetFunction(), itk::VanHerkGilWermanErodeImageFilter< TImage, TKernel >::VanHerkGilWermanErodeImageFilter(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::VectorMorphologicalGradientHistogram(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram(), itk::Function::VectorRankHistogram< TInputPixel >::VectorRankHistogram(), and itk::VertexCell< TCellInterface >::VertexCell().
min()
template<typename T > static constexpr T itk::NumericTraits< T >::min (const T &) inline static constexpr
Definition at line 172 of file itkNumericTraits.h.
Referenced by itk::AdaptiveHistogramEqualizationImageFilter< TImageType, TKernel >::AdaptiveHistogramEqualizationImageFilter(), itk::Function::ColormapFunction< TScalar, TRGBPixel >::ColormapFunction(), itk::Statistics::KdTree< TSample >::NearestNeighbors::ReplaceFarthestNeighbor(), and itk::Functor::Sigmoid< TInputImage::PixelType, TOutputImage::PixelType >::Sigmoid().
NonpositiveMin() [1/2]
template<typename T > static constexpr T itk::NumericTraits< T >::NonpositiveMin () inline static constexpr
Smallest (most nonpositive) value
Definition at line 97 of file itkNumericTraits.h.
Referenced by itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::AddPixel(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::AddPixel(), itk::AnchorCloseImageFilter< TImage, TKernel >::AnchorCloseImageFilter(), itk::AnchorDilateImageFilter< TImage, TKernel >::AnchorDilateImageFilter(), itk::AnchorOpenImageFilter< TImage, TKernel >::AnchorOpenImageFilter(), itk::BinaryNotImageFilter< TImage >::BinaryNotImageFilter(), itk::BinaryProjectionImageFilter< TInputImage, TOutputImage >::BinaryProjectionImageFilter(), itk::Functor::BinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >::BinaryThreshold(), itk::BinaryThresholdProjectionImageFilter< TInputImage, TOutputImage >::BinaryThresholdProjectionImageFilter(), itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::LevelSetMotionRegistrationFunction< TFixedImage, TMovingImage, TDisplacementField >::GetGlobalDataPointer(), itk::Function::VectorRankHistogram< TInputPixel >::GetValueBruteForce(), itk::Functor::GPUBinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >::GPUBinaryThreshold(), itk::Functor::MaximumAccumulator< TInputPixel >::Initialize(), itk::Functor::IntensityLinearTransform< TInputImage::PixelType, TInputImage ::PixelType >::IntensityLinearTransform(), itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >::LabelStatistics::LabelStatistics(), itk::MovingHistogramDilateImageFilter< TInputImage, TOutputImage, TKernel >::MovingHistogramDilateImageFilter(), itk::NumericTraits< Vector< T, D > >::NonpositiveMin(), itk::NumericTraits< Point< T, D > >::NonpositiveMin(), itk::NumericTraits< RGBAPixel< T > >::NonpositiveMin(), itk::NumericTraits< RGBPixel< T > >::NonpositiveMin(), itk::NumericTraits< FixedArray< T, D > >::NonpositiveMin(), itk::NumericTraits< CovariantVector< T, D > >::NonpositiveMin(), itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::NonpositiveMin(), itk::NumericTraits< DiffusionTensor3D< T > >::NonpositiveMin(), itk::NumericTraits< InputImagePixelType >::NonpositiveMin(), itk::Functor::Maximum1< TInputImage::PixelType, TInputImage::PixelType >::operator()(), itk::Functor::ConstrainedValueAddition< TInput1, TInput2, TOutput >::operator()(), itk::Functor::ConstrainedValueDifference< TInput1, TInput2, TOutput >::operator()(), itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >::UnsharpMaskingFunctor< InPixelType, FunctorRealType, OutPixelType >::operator()(), itk::Functor::DivFloor< TInput1, TInput2, TOutput >::operator()(), itk::Function::RankHistogram< TInputPixel >::RankHistogram(), itk::ReconstructionByDilationImageFilter< TInputImage, TOutputImage >::ReconstructionByDilationImageFilter(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::RemovePixel(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::RemovePixel(), itk::ThresholdSegmentationLevelSetFunction< TImageType, TFeatureImageType >::ThresholdSegmentationLevelSetFunction(), itk::VanHerkGilWermanDilateImageFilter< TImage, TKernel >::VanHerkGilWermanDilateImageFilter(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::VectorMorphologicalGradientHistogram(), itk::Function::VectorMorphologyHistogram< TInputPixel, TCompare >::VectorMorphologyHistogram(), and itk::Function::VectorRankHistogram< TInputPixel >::VectorRankHistogram().
NonpositiveMin() [2/2]
template<typename T > static T itk::NumericTraits< T >::NonpositiveMin (const T &) inline static
Smallest (most nonpositive) value. This API is needed for VariableLengthVector because its length is only known at run-time.
Definition at line 217 of file itkNumericTraits.h.
OneValue() [1/2]
template<typename T > static T itk::NumericTraits< T >::OneValue () inline static
Return one value. This function should be used to support RGBPixel type and standard types (not vectors)
Definition at line 156 of file itkNumericTraits.h.
Referenced by itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::LevelSetFunction< TImageType >::CurvatureSpeed(), itk::Functor::DivideOrZeroOut< typename TInputImage1::PixelType, typename TInputImage1 ::PixelType, typename TInputImage1 ::PixelType >::DivideOrZeroOut(), itk::Path< unsigned int, Offset< VDimension >, VDimension >::EndOfInput(), itk::NormalVectorDiffusionFunction< TSparseImageType >::FluxStopFunction(), itk::LevelSetFunction< TImageType >::LaplacianSmoothingSpeed(), itk::Functor::LogicOpBase< TInput1, TInput1, TInput1 >::LogicOpBase(), itk::NumericTraits< Vector< T, D > >::OneValue(), itk::NumericTraits< Point< T, D > >::OneValue(), itk::NumericTraits< RGBAPixel< T > >::OneValue(), itk::NumericTraits< RGBPixel< T > >::OneValue(), itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::OneValue(), itk::NumericTraits< CovariantVector< T, D > >::OneValue(), itk::NumericTraits< FixedArray< T, D > >::OneValue(), itk::NumericTraits< DiffusionTensor3D< T > >::OneValue(), itk::NumericTraits< InputImagePixelType >::OneValue(), itk::Functor::InvertIntensityFunctor< InputPixelType >::operator()(), itk::Functor::LandweberMethod< TInput1, TInput2, TInput3, TOutput >::operator()(), itk::Functor::WeightedAdd2< typename TInputImage1::PixelType, typename TInputImage2::PixelType, typename TOutputImage::PixelType >::SetAlpha(), itk::STAPLEImageFilter< TInputImage, TOutputImage >::STAPLEImageFilter(), and itk::Functor::ThresholdLabeler< TInputImage::PixelType, TOutputImage::PixelType >::ThresholdLabeler().
OneValue() [2/2]
template<typename T > static T itk::NumericTraits< T >::OneValue (const T &) inline static
One value. This API is needed for VariableLengthVector because its length is only known at run-time.
Definition at line 235 of file itkNumericTraits.h.
SetLength()
template<typename T > static void itk::NumericTraits< T >::SetLength (T & m, const unsigned int s) inline static
Scalars cannot be resized, so an exception will be thrown if the input size is not 1. If the size is valid the will be zeros. This API is needed for VariableLengthVector because its length is only known at run-time. Specializations of the VariableLengthVector will provide a different implementation where a vector of the correct size is built.
Definition at line 185 of file itkNumericTraits.h.
Referenced by itk::Functor::LabelToRGBFunctor< TLabelImage::PixelType, TOutputImage::PixelType >::AddColor(), itk::Functor::LabelToRGBFunctor< TLabelImage::PixelType, TOutputImage::PixelType >::LabelToRGBFunctor(), itk::Functor::LabelOverlayFunctor< FeatureImagePixelType, LabelMapPixelType, OutputImagePixelType >::operator()(), and itk::Statistics::KdTreeBasedKmeansEstimator< TKdTree >::CandidateVector::SetCentroids().
ZeroValue() [1/2]
template<typename T > static T itk::NumericTraits< T >::ZeroValue () inline static
Return zero value. This function should be used to support RGBPixel type and standard types (not vectors)
Definition at line 148 of file itkNumericTraits.h.
Referenced by itk::Functor::BinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >::BinaryThreshold(), itk::BinaryThresholdProjectionImageFilter< TInputImage, TOutputImage >::BinaryThresholdProjectionImageFilter(), itk::ParallelSparseFieldLevelSetImageFilter< TInputImage, TOutputImage >::CalculateChange(), itk::CannySegmentationLevelSetFunction< TImageType, TFeatureImageType >::CannySegmentationLevelSetFunction(), itk::GPUFiniteDifferenceFunction< TDisplacementField >::ComputeUpdate(), itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::Concept::HasZero< T >::Constraints::constraints(), itk::Functor::DivideOrZeroOut< typename TInputImage1::PixelType, typename TInputImage1 ::PixelType, typename TInputImage1 ::PixelType >::DivideOrZeroOut(), itk::ExtractOrthogonalSwath2DImageFilter< TImage >::ExtractOrthogonalSwath2DImageFilter(), itk::Accessor::AbsPixelAccessor< TImage::PixelType, TOutputPixelType >::Get(), itk::CellInterface< TPixelType, TCellTraits >::GetBoundingBoxDiagonalLength2(), itk::QuadEdgeMesh< TPixel, VDimension, TTraits >::GetCellBoundaryFeatureNeighbors(), itk::QuadEdgeMesh< TPixel, VDimension, TTraits >::GetCellNeighbors(), itk::CurvatureFlowFunction< TImage >::GetGlobalDataPointer(), itk::ShapePriorSegmentationLevelSetFunction< TImageType, TImageType >::GetGlobalDataPointer(), itk::LevelSetFunction< TImageType >::GetGlobalDataPointer(), itk::Functor::StandardDeviationAccumulator< TInputPixel, TAccumulate >::GetValue(), itk::Function::VectorMorphologicalGradientHistogram< TInputPixel >::GetValue(), itk::Functor::GPUBinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >::GPUBinaryThreshold(), itk::Functor::SumAccumulator< TInputPixel, TOutputPixel >::Initialize(), itk::Functor::MeanAccumulator< TInputPixel, TAccumulate >::Initialize(), itk::Functor::StandardDeviationAccumulator< TInputPixel, TAccumulate >::Initialize(), itk::Functor::MaskInput< typename TInputImage::PixelType, typename TMaskImage::PixelType, typename TInputImage ::PixelType >::InitializeOutsideValue(), itk::NeighborhoodOperator< ScalarType, VDimension, NeighborhoodAllocator< ScalarType > >::InitializeToZero(), itk::Functor::LabelOverlayFunctor< FeatureImagePixelType, LabelMapPixelType, OutputImagePixelType >::LabelOverlayFunctor(), itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >::LabelStatistics::LabelStatistics(), itk::Functor::LabelToRGBFunctor< TLabelImage::PixelType, TOutputImage::PixelType >::LabelToRGBFunctor(), itk::LevelSetBase< TInput, VDimension, TOutput, TDomain >::LevelSetDataType::LevelSetDataType(), itk::Functor::LogicOpBase< TInput1, TInput1, TInput1 >::LogicOpBase(), itk::LinearInterpolateImageFunction< TInputImage, TCoordRep >::MakeZeroInitializer(), itk::Functor::MaskInput< typename TInputImage::PixelType, typename TMaskImage::PixelType, typename TInputImage ::PixelType >::MaskInput(), itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >::NonPCEvaluateAtNeighborhood(), itk::Functor::InvertIntensityFunctor< InputPixelType >::operator()(), itk::Functor::Add1< TInputImage::PixelType, TInputImage::PixelType >::operator()(), itk::Functor::SimilarVectorsFunctor< TInputImage::ValueType >::operator()(), itk::Functor::InverseDeconvolutionFunctor< TInput1, TInput2, TOutput >::operator()(), itk::Functor::TikhonovDeconvolutionFunctor< TInput1, TInput2, TOutput >::operator()(), itk::Functor::WienerDeconvolutionFunctor< TPixel >::operator()(), itk::AuthalicMatrixCoefficients< TInputMesh >::operator()(), itk::LevelSetFunctionWithRefitTerm< TImageType, TSparseImageType >::OtherPropagationSpeed(), itk::LevelSetFunction< TImageType >::PropagationSpeed(), itk::QuadEdgeMeshDecimationCriterion< TMesh, TElement, TMeasure, TPriorityQueueWrapper >::QuadEdgeMeshDecimationCriterion(), itk::MeshIOBase::ReadCellsBuffer(), itk::FastMarchingNumberOfElementsStoppingCriterion< TInput, TOutput >::Reset(), itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >::SetBinaryMask(), itk::NumericTraits< InputImagePixelType >::SetLength(), itk::Functor::SimilarPixelsFunctor< TInputImage::ValueType >::SimilarPixelsFunctor(), itk::Functor::SimilarVectorsFunctor< TInputImage::ValueType >::SimilarVectorsFunctor(), itk::Point< double, Self::ImageDimension >::SquaredEuclideanDistanceTo(), itk::Path< unsigned int, Offset< VDimension >, VDimension >::StartOfInput(), itk::ShapeRelabelLabelMapFilter< TImage >::TemplatedGenerateData(), itk::ImageBase< 2 >::TransformContinuousIndexToPhysicalPoint(), itk::ImageBase< 2 >::TransformLocalVectorToPhysicalVector(), itk::ImageBase< 2 >::TransformPhysicalPointToIndex(), itk::ImageBase< 2 >::TransformPhysicalVectorToLocalVector(), itk::OBJMeshIO::WriteCells(), itk::BYUMeshIO::WriteCells(), itk::MeshIOBase::WriteCellsBuffer(), itk::OBJMeshIO::WritePointData(), itk::OBJMeshIO::WritePoints(), itk::BYUMeshIO::WritePoints(), itk::NumericTraits< Vector< T, D > >::ZeroValue(), itk::NumericTraits< Point< T, D > >::ZeroValue(), itk::NumericTraits< RGBPixel< T > >::ZeroValue(), itk::NumericTraits< RGBAPixel< T > >::ZeroValue(), itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ZeroValue(), itk::NumericTraits< FixedArray< T, D > >::ZeroValue(), itk::NumericTraits< CovariantVector< T, D > >::ZeroValue(), itk::NumericTraits< DiffusionTensor3D< T > >::ZeroValue(), itk::NumericTraits< InputImagePixelType >::ZeroValue(), and itk::Functor::MeanAccumulator< TInputPixel, TAccumulate >::~MeanAccumulator().
ZeroValue() [2/2]
template<typename T > static T itk::NumericTraits< T >::ZeroValue (const T &) inline static
Zero value. This API is needed for VariableLengthVector because its length is only known at run-time.
Definition at line 226 of file itkNumericTraits.h.
Member Data Documentation
IsComplex
template<typename T > constexpr bool itk::NumericTraits< T >::IsComplex = false static constexpr
Is a given type complex? – default is no. For uniform array data types in ITK, the value of IsComplex is determined by the component elements of the array.
Definition at line 143 of file itkNumericTraits.h.
IsInteger
template<typename T > constexpr bool itk::NumericTraits< T >::IsInteger = false static constexpr
Is a given type an integer? – default is no. For uniform array data types in ITK, the value of IsInteger is determined by the component elements of the array.
Definition at line 138 of file itkNumericTraits.h.
IsSigned
template<typename T > constexpr bool itk::NumericTraits< T >::IsSigned = false static constexpr
Is a given type signed? – default is no. For uniform array data types in ITK, the value of IsSigned is determined by the component elements of the array.
Definition at line 133 of file itkNumericTraits.h.
One
template<typename T > const T ITKCommon_EXPORT itk::NumericTraits< T >::One static
Multiplicative identity.
Definition at line 93 of file itkNumericTraits.h.
Referenced by itk::NumericTraits< InputImagePixelType >::OneValue().
Zero
template<typename T > const T ITKCommon_EXPORT itk::NumericTraits< T >::Zero static
Additive identity.
Definition at line 90 of file itkNumericTraits.h.
Referenced by itk::NumericTraits< InputImagePixelType >::IsNegative(), itk::NumericTraits< InputImagePixelType >::IsNonnegative(), itk::NumericTraits< InputImagePixelType >::IsNonpositive(), itk::NumericTraits< InputImagePixelType >::IsPositive(), and itk::NumericTraits< InputImagePixelType >::ZeroValue().
The documentation for this class was generated from the following file:
itkNumericTraits.h