ITK: itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage > Class Template Reference
itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage > Class Template Reference final
Data Access Objects » Iterators » Image IteratorsGroup Core » | Module ITKCommon
#include <itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h>
Public Member Functions
PixelType GetPixelValue (const InternalPixelType *const imageBufferPointer) const noexcept
ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy & operator= (const ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy &)=delete
ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy ()=delete
ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy (const ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy &) noexcept=default
~ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy ()=default
ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy (const ImageSizeType &imageSize, const OffsetType &offsetTable, const NeighborhoodAccessorFunctorType &neighborhoodAccessor, const IndexType &pixelIndex) noexcept
void SetPixelValue (InternalPixelType *const imageBufferPointer, const PixelType &pixelValue) const noexcept
Private Types
using ImageDimensionType = typename TImage::ImageDimensionType
using ImageSizeType = Size< ImageDimension >
using ImageSizeValueType = SizeValueType
using IndexType = Index< ImageDimension >
using InternalPixelType = typename TImage::InternalPixelType
using NeighborhoodAccessorFunctorType = typename TImage::NeighborhoodAccessorFunctorType
using OffsetType = Offset< ImageDimension >
using PixelType = typename TImage::PixelType
Static Private Member Functions
static IndexValueType CalculatePixelIndexValue (const ImageSizeType &imageSize, const OffsetType &offsetTable, const IndexType &pixelIndex) noexcept
static IndexValueType GetClampedIndexValue (const IndexValueType indexValue, const ImageSizeValueType imageSizeValue) noexcept
Private Attributes
const NeighborhoodAccessorFunctorType & m_NeighborhoodAccessor
const IndexValueType m_PixelIndexValue
Static Private Attributes
static constexpr ImageDimensionType ImageDimension = TImage::ImageDimension
Detailed Description
template<typename TImage>
class itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >
ImageNeighborhoodPixelAccessPolicy class for ShapedImageNeighborhoodRange. Allows getting and setting the value of a pixel, located in a specified neighborhood location, at a specified offset. Uses "border replication" as extrapolation method for pixels outside the image border.
See also
ShapedNeighborhoodIterator
ZeroFluxNeumannBoundaryCondition
Definition at line 42 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
Member Typedef Documentation
ImageDimensionType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ImageDimensionType = typename TImage::ImageDimensionType private
Definition at line 49 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
ImageSizeType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ImageSizeType = Size<ImageDimension> private
Definition at line 54 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
ImageSizeValueType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ImageSizeValueType = SizeValueType private
Definition at line 55 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
IndexType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::IndexType = Index<ImageDimension> private
Definition at line 52 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
InternalPixelType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::InternalPixelType = typename TImage::InternalPixelType private
Definition at line 47 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
NeighborhoodAccessorFunctorType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::NeighborhoodAccessorFunctorType = typename TImage::NeighborhoodAccessorFunctorType private
Definition at line 45 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
OffsetType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::OffsetType = Offset<ImageDimension> private
Definition at line 53 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
PixelType
template<typename TImage > using itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::PixelType = typename TImage::PixelType private
Definition at line 46 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
Constructor & Destructor Documentation
ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy() [1/3]
template<typename TImage > itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy () delete
~ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy()
template<typename TImage > itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::~ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy () default
ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy() [2/3]
template<typename TImage > itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy (const ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage > &) default noexcept
ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy() [3/3]
template<typename TImage > itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy (const ImageSizeType & imageSize, const OffsetType & offsetTable, const NeighborhoodAccessorFunctorType & neighborhoodAccessor, const IndexType & pixelIndex) inline noexcept
Constructor called directly by the pixel proxy of ShapedImageNeighborhoodRange.
Definition at line 104 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
References itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::CalculatePixelIndexValue().
Member Function Documentation
CalculatePixelIndexValue()
template<typename TImage > static IndexValueType itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::CalculatePixelIndexValue (const ImageSizeType & imageSize, const OffsetType & offsetTable, const IndexType & pixelIndex) inline static private noexcept
Definition at line 78 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
References itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::GetClampedIndexValue(), and itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ImageDimension.
Referenced by itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy().
GetClampedIndexValue()
template<typename TImage > static IndexValueType itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::GetClampedIndexValue (const IndexValueType indexValue, const ImageSizeValueType imageSizeValue) inline static private noexcept
Definition at line 67 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
Referenced by itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::CalculatePixelIndexValue().
GetPixelValue()
template<typename TImage > PixelType itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::GetPixelValue (const InternalPixelType *const imageBufferPointer) const inline noexcept
Retrieves the pixel value from the image buffer, at the current index value.
Definition at line 116 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
References itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::m_NeighborhoodAccessor, and itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::m_PixelIndexValue.
operator=()
template<typename TImage > ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy& itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::operator= (const ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage > &) delete
SetPixelValue()
template<typename TImage > void itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::SetPixelValue (InternalPixelType *const imageBufferPointer, const PixelType & pixelValue) const inline noexcept
Sets the value of the image buffer at the current index value to the specified value.
Definition at line 124 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
References itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::m_NeighborhoodAccessor, and itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::m_PixelIndexValue.
Member Data Documentation
ImageDimension
template<typename TImage > constexpr ImageDimensionType itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::ImageDimension = TImage::ImageDimension static constexpr private
Definition at line 50 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
Referenced by itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::CalculatePixelIndexValue().
m_NeighborhoodAccessor
template<typename TImage > const NeighborhoodAccessorFunctorType& itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::m_NeighborhoodAccessor private
Definition at line 61 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
Referenced by itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::GetPixelValue(), and itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::SetPixelValue().
m_PixelIndexValue
template<typename TImage > const IndexValueType itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::m_PixelIndexValue private
Definition at line 58 of file itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h.
Referenced by itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::GetPixelValue(), and itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy< TImage >::SetPixelValue().
The documentation for this class was generated from the following file:
itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h