ITK: itk::DefaultVectorPixelAccessor< TType > Class Template Reference
itk::DefaultVectorPixelAccessor< TType > Class Template Reference
Data Processing Objects » Image AdaptorsGroup Core » | Module ITKCommon
#include <itkDefaultVectorPixelAccessor.h>
Public Types
using ExternalType = VariableLengthVector< TType >
using InternalType = TType
using VectorLengthType = unsigned int
Public Member Functions
DefaultVectorPixelAccessor ()=default
DefaultVectorPixelAccessor (VectorLengthType l)
ExternalType Get (const InternalType &input, const SizeValueType offset) const
VectorLengthType GetVectorLength () const
void Set (InternalType &output, const ExternalType &input, const unsigned long offset) const
~DefaultVectorPixelAccessor ()=default
void SetVectorLength (VectorLengthType l)
Private Attributes
VectorLengthType m_OffsetMultiplier { 0 }
VectorLengthType m_VectorLength { 0 }
Detailed Description
template<typename TType>
class itk::DefaultVectorPixelAccessor< TType >
Give access to partial aspects of a type.
DefaultVectorPixelAccessor is specifically meant to provide VectorImage with the same DefaultPixelAccessor interface that DefaultPixelAccessor provides to Image.
The template parameters is the type that is contained in by the elements of a vector.
The class also contains a m_VectorLength parameter, set with the SetVectorLength method to set the length of the vectors. This must be set before the accessor can be used. This is the length of each of the vector containers.
Note
This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.
Definition at line 50 of file itkDefaultVectorPixelAccessor.h.
Member Typedef Documentation
ExternalType
template<typename TType > using itk::DefaultVectorPixelAccessor< TType >::ExternalType = VariableLengthVector<TType>
External type alias. It defines the external aspect that this class will exhibit. Here it is an VariableLengthVector. The container does not manage the memory. In other words it is an array reference with the contents pointing to the actual data in the image.
Definition at line 59 of file itkDefaultVectorPixelAccessor.h.
InternalType
template<typename TType > using itk::DefaultVectorPixelAccessor< TType >::InternalType = TType
Internal type alias. It defines the internal real representation of data.
Definition at line 62 of file itkDefaultVectorPixelAccessor.h.
VectorLengthType
template<typename TType > using itk::DefaultVectorPixelAccessor< TType >::VectorLengthType = unsigned int
Definition at line 53 of file itkDefaultVectorPixelAccessor.h.
Constructor & Destructor Documentation
DefaultVectorPixelAccessor() [1/2]
template<typename TType > itk::DefaultVectorPixelAccessor< TType >::DefaultVectorPixelAccessor () default
DefaultVectorPixelAccessor() [2/2]
template<typename TType > itk::DefaultVectorPixelAccessor< TType >::DefaultVectorPixelAccessor (VectorLengthType l) inline
Constructor to initialize VectorLength at construction time
Definition at line 104 of file itkDefaultVectorPixelAccessor.h.
~DefaultVectorPixelAccessor()
template<typename TType > itk::DefaultVectorPixelAccessor< TType >::~DefaultVectorPixelAccessor () default
Member Function Documentation
Get()
template<typename TType > ExternalType itk::DefaultVectorPixelAccessor< TType >::Get (const InternalType & input, const SizeValueType offset) const inline
Get the value from input
Definition at line 78 of file itkDefaultVectorPixelAccessor.h.
Referenced by itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::Get(), and itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::Set().
GetVectorLength()
template<typename TType > VectorLengthType itk::DefaultVectorPixelAccessor< TType >::GetVectorLength () const inline
Get Vector lengths
Definition at line 96 of file itkDefaultVectorPixelAccessor.h.
Referenced by itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::GetVectorLength().
Set()
template<typename TType > void itk::DefaultVectorPixelAccessor< TType >::Set (InternalType & output, const ExternalType & input, const unsigned long offset) const inline
Set output using the value in input
Definition at line 66 of file itkDefaultVectorPixelAccessor.h.
SetVectorLength()
template<typename TType > void itk::DefaultVectorPixelAccessor< TType >::SetVectorLength (VectorLengthType l) inline
Set the length of each vector in the VectorImage
Definition at line 87 of file itkDefaultVectorPixelAccessor.h.
Referenced by itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::SetVectorLength(), and itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::VectorImageToImagePixelAccessor().
Member Data Documentation
m_OffsetMultiplier
template<typename TType > VectorLengthType itk::DefaultVectorPixelAccessor< TType >::m_OffsetMultiplier { 0 } private
Definition at line 114 of file itkDefaultVectorPixelAccessor.h.
m_VectorLength
template<typename TType > VectorLengthType itk::DefaultVectorPixelAccessor< TType >::m_VectorLength { 0 } private
Definition at line 113 of file itkDefaultVectorPixelAccessor.h.
The documentation for this class was generated from the following file:
itkDefaultVectorPixelAccessor.h