ITK: itk::Statistics::MeasurementVectorTraits Class Reference
itk::Statistics::MeasurementVectorTraits Class Reference
Group Numerics » Module ITKStatistics
#include <itkMeasurementVectorTraits.h>
Public Types
using AbsoluteFrequencyType = InstanceIdentifier
using InstanceIdentifier = IdentifierType
using MeasurementVectorLength = vcl_size_t
using RelativeFrequencyType = NumericTraits< AbsoluteFrequencyType >::RealType
using TotalAbsoluteFrequencyType = NumericTraits< AbsoluteFrequencyType >::AccumulateType
using TotalRelativeFrequencyType = NumericTraits< RelativeFrequencyType >::AccumulateType
Static Public Member Functions
template<typename TValue >
static MeasurementVectorLength Assert (const Array< TValue > &a, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue >
static MeasurementVectorLength Assert (const Array< TValue > *a, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue1 , typename TValue2 >
static MeasurementVectorLength Assert (const Array< TValue1 > &a, const Array< TValue2 > &b, const char *errMsg="Length Mismatch")
template<typename TValue1 , typename TValue2 >
static MeasurementVectorLength Assert (const Array< TValue1 > *a, const Array< TValue2 > *b, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 >
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > &, const Array< TValue2 > &b, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 , unsigned int VLength2>
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > &, const FixedArray< TValue2, VLength2 > &, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength>
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > &, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 >
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > &, const std::vector< TValue2 > &b, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 >
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > &, const VariableLengthVector< TValue2 > &b, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 >
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > *, const Array< TValue2 > *b, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 , unsigned int VLength2>
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > *, const FixedArray< TValue2, VLength2 > *, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength>
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > *, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 >
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > *, const std::vector< TValue2 > *b, const char *errMsg="Length Mismatch")
template<typename TValue1 , unsigned int VLength, typename TValue2 >
static MeasurementVectorLength Assert (const FixedArray< TValue1, VLength > *, const VariableLengthVector< TValue2 > *b, const char *errMsg="Length Mismatch")
template<typename TValue >
static MeasurementVectorLength Assert (const std::vector< TValue > &a, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue >
static MeasurementVectorLength Assert (const std::vector< TValue > *a, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue1 , typename TValue2 >
static MeasurementVectorLength Assert (const std::vector< TValue1 > &a, const std::vector< TValue2 > &b, const char *errMsg="Length Mismatch")
template<typename TValue1 , typename TValue2 >
static MeasurementVectorLength Assert (const std::vector< TValue1 > *a, const std::vector< TValue2 > *b, const char *errMsg="Length Mismatch")
template<typename TValue >
static MeasurementVectorLength Assert (const VariableLengthVector< TValue > &a, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue >
static MeasurementVectorLength Assert (const VariableLengthVector< TValue > *a, const MeasurementVectorLength l, const char *errMsg="Length Mismatch")
template<typename TValue1 , typename TValue2 >
static MeasurementVectorLength Assert (const VariableLengthVector< TValue1 > &a, const VariableLengthVector< TValue2 > &b, const char *errMsg="Length Mismatch")
template<typename TValue1 , typename TValue2 >
static MeasurementVectorLength Assert (const VariableLengthVector< TValue1 > *a, const VariableLengthVector< TValue2 > *b, const char *errMsg="Length Mismatch")
template<typename TValue , unsigned int VLength>
static void Assign (FixedArray< TValue, VLength > &m, const TValue &v)
template<typename TArrayType >
static void Assign (TArrayType &m, const TArrayType &v)
template<typename TVectorType >
static bool IsResizable (const TVectorType &)
Detailed Description
Definition at line 41 of file itkMeasurementVectorTraits.h.
Member Typedef Documentation
AbsoluteFrequencyType
using itk::Statistics::MeasurementVectorTraits::AbsoluteFrequencyType = InstanceIdentifier
Type defined for representing the frequency of measurement vectors
Definition at line 53 of file itkMeasurementVectorTraits.h.
InstanceIdentifier
using itk::Statistics::MeasurementVectorTraits::InstanceIdentifier = IdentifierType
In the old framework, the FrequencyType is set to float. The problem is for large histograms the total frequency can be more than 1e+7, than increasing the frequency by one does not change the total frequency (because of lack of precision). Using double type will also ultimately fall into the same problem. Hence in the new statistics framework, InstanceIdentifier/FrequencyTypes are set to the the largest possible integer on the machine
Definition at line 50 of file itkMeasurementVectorTraits.h.
MeasurementVectorLength
using itk::Statistics::MeasurementVectorTraits::MeasurementVectorLength = vcl_size_t
Definition at line 58 of file itkMeasurementVectorTraits.h.
RelativeFrequencyType
using itk::Statistics::MeasurementVectorTraits::RelativeFrequencyType = NumericTraits<AbsoluteFrequencyType>::RealType
Definition at line 54 of file itkMeasurementVectorTraits.h.
TotalAbsoluteFrequencyType
using itk::Statistics::MeasurementVectorTraits::TotalAbsoluteFrequencyType = NumericTraits<AbsoluteFrequencyType>::AccumulateType
Definition at line 55 of file itkMeasurementVectorTraits.h.
TotalRelativeFrequencyType
using itk::Statistics::MeasurementVectorTraits::TotalRelativeFrequencyType = NumericTraits<RelativeFrequencyType>::AccumulateType
Definition at line 56 of file itkMeasurementVectorTraits.h.
Member Function Documentation
Assert() [1/22]
template<typename TValue > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const Array< TValue > & a, const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 306 of file itkMeasurementVectorTraits.h.
References itk::Array< TValue >::Size().
Assert() [2/22]
template<typename TValue > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const Array< TValue > * a, const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 321 of file itkMeasurementVectorTraits.h.
References itk::Array< TValue >::Size().
Assert() [3/22]
template<typename TValue1 , typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const Array< TValue1 > & a, const Array< TValue2 > & b, const char * errMsg = "Length Mismatch") inline static
Definition at line 103 of file itkMeasurementVectorTraits.h.
References itk::Array< TValue >::Size().
Assert() [4/22]
template<typename TValue1 , typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const Array< TValue1 > * a, const Array< TValue2 > * b, const char * errMsg = "Length Mismatch") inline static
Definition at line 114 of file itkMeasurementVectorTraits.h.
References itk::Array< TValue >::Size().
Assert() [5/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > & , const Array< TValue2 > & b, const char * errMsg = "Length Mismatch") inline static
Definition at line 173 of file itkMeasurementVectorTraits.h.
References itk::Array< TValue >::Size().
Assert() [6/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 , unsigned int VLength2> static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > & , const FixedArray< TValue2, VLength2 > & , const char * errMsg = "Length Mismatch") inline static
Definition at line 77 of file itkMeasurementVectorTraits.h.
Assert() [7/22]
template<typename TValue1 , unsigned int VLength> static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > & , const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 276 of file itkMeasurementVectorTraits.h.
Assert() [8/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > & , const std::vector< TValue2 > & b, const char * errMsg = "Length Mismatch") inline static
Definition at line 243 of file itkMeasurementVectorTraits.h.
Assert() [9/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > & , const VariableLengthVector< TValue2 > & b, const char * errMsg = "Length Mismatch") inline static
Definition at line 206 of file itkMeasurementVectorTraits.h.
References itk::VariableLengthVector::Size().
Assert() [10/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > * , const Array< TValue2 > * b, const char * errMsg = "Length Mismatch") inline static
Definition at line 191 of file itkMeasurementVectorTraits.h.
References itk::Array< TValue >::Size().
Assert() [11/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 , unsigned int VLength2> static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > * , const FixedArray< TValue2, VLength2 > * , const char * errMsg = "Length Mismatch") inline static
Definition at line 90 of file itkMeasurementVectorTraits.h.
Assert() [12/22]
template<typename TValue1 , unsigned int VLength> static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > * , const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 291 of file itkMeasurementVectorTraits.h.
Assert() [13/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > * , const std::vector< TValue2 > * b, const char * errMsg = "Length Mismatch") inline static
Definition at line 261 of file itkMeasurementVectorTraits.h.
Assert() [14/22]
template<typename TValue1 , unsigned int VLength, typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const FixedArray< TValue1, VLength > * , const VariableLengthVector< TValue2 > * b, const char * errMsg = "Length Mismatch") inline static
Definition at line 226 of file itkMeasurementVectorTraits.h.
References itk::VariableLengthVector::Size().
Assert() [15/22]
template<typename TValue > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const std::vector< TValue > & a, const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 370 of file itkMeasurementVectorTraits.h.
Assert() [16/22]
template<typename TValue > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const std::vector< TValue > * a, const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 385 of file itkMeasurementVectorTraits.h.
Assert() [17/22]
template<typename TValue1 , typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const std::vector< TValue1 > & a, const std::vector< TValue2 > & b, const char * errMsg = "Length Mismatch") inline static
Definition at line 151 of file itkMeasurementVectorTraits.h.
Assert() [18/22]
template<typename TValue1 , typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const std::vector< TValue1 > * a, const std::vector< TValue2 > * b, const char * errMsg = "Length Mismatch") inline static
Definition at line 162 of file itkMeasurementVectorTraits.h.
Assert() [19/22]
template<typename TValue > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const VariableLengthVector< TValue > & a, const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 336 of file itkMeasurementVectorTraits.h.
References itk::VariableLengthVector::Size().
Assert() [20/22]
template<typename TValue > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const VariableLengthVector< TValue > * a, const MeasurementVectorLength l, const char * errMsg = "Length Mismatch") inline static
Definition at line 353 of file itkMeasurementVectorTraits.h.
References itk::VariableLengthVector::Size().
Assert() [21/22]
template<typename TValue1 , typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const VariableLengthVector< TValue1 > & a, const VariableLengthVector< TValue2 > & b, const char * errMsg = "Length Mismatch") inline static
Definition at line 125 of file itkMeasurementVectorTraits.h.
References itk::VariableLengthVector::Size().
Assert() [22/22]
template<typename TValue1 , typename TValue2 > static MeasurementVectorLength itk::Statistics::MeasurementVectorTraits::Assert (const VariableLengthVector< TValue1 > * a, const VariableLengthVector< TValue2 > * b, const char * errMsg = "Length Mismatch") inline static
Definition at line 138 of file itkMeasurementVectorTraits.h.
References itk::VariableLengthVector::Size().
Assign() [1/2]
template<typename TValue , unsigned int VLength> static void itk::Statistics::MeasurementVectorTraits::Assign (FixedArray< TValue, VLength > & m, const TValue & v) inline static
Definition at line 407 of file itkMeasurementVectorTraits.h.
Assign() [2/2]
template<typename TArrayType > static void itk::Statistics::MeasurementVectorTraits::Assign (TArrayType & m, const TArrayType & v) inline static
Definition at line 400 of file itkMeasurementVectorTraits.h.
Referenced by itk::Statistics::ImageToListSampleAdaptor< TImage >::ConstIterator::GetMeasurementVector().
IsResizable()
template<typename TVectorType > static bool itk::Statistics::MeasurementVectorTraits::IsResizable (const TVectorType &) inline static
Definition at line 62 of file itkMeasurementVectorTraits.h.
References itk::NumericTraits< T >::GetLength().
Referenced by itk::Statistics::MembershipFunctionBase< TMeasurementVector >::SetMeasurementVectorSize(), itk::Statistics::DistanceMetric< Array< double > >::SetMeasurementVectorSize(), and itk::Statistics::Sample< ImageJointDomainTraits< TImage >::MeasurementVectorType >::SetMeasurementVectorSize().
The documentation for this class was generated from the following file:
itkMeasurementVectorTraits.h