ITK: itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint > Class Template Reference
itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint > Class Template Reference
#include <itkQuadEdgeMeshDecimationQuadricElementHelper.h>
Public Types
using CoefficientVectorType = vnl_vector_fixed< CoordType, Self::NumberOfCoefficients >
using CoordType = typename PointType::CoordRepType
using PointType = TPoint
using Self = QuadEdgeMeshDecimationQuadricElementHelper
using TriangleType = TriangleHelper< PointType >
using VectorType = typename PointType::VectorType
using VNLMatrixType = vnl_matrix< CoordType >
using VNLVectorType = vnl_vector_fixed< CoordType, Self::PointDimension >
Public Member Functions
void AddPoint (const PointType &iP, const VectorType &iN, const CoordType &iWeight=static_cast< CoordType >(1.))
void AddTriangle (const PointType &iP1, const PointType &iP2, const PointType &iP3, const CoordType &iWeight=static_cast< CoordType >(1.))
CoordType ComputeError (const PointType &iP) const
CoordType ComputeErrorAtOptimalLocation (const PointType &iP)
PointType ComputeOptimalLocation (const PointType &iP)
PointType ComputeOptimalLocation (const unsigned int &)
VNLMatrixType GetAMatrix ()
VNLVectorType GetBVector ()
CoefficientVectorType GetCoefficients () const
unsigned int GetRank () const
Self operator* (const CoordType &iV) const
Self & operator*= (const CoordType &iV)
Self operator+ (const Self &iRight) const
Self & operator+= (const Self &iRight)
Self operator- (const Self &iRight) const
Self & operator-= (const Self &iRight)
Self & operator= (const Self &iRight)
QuadEdgeMeshDecimationQuadricElementHelper ()
QuadEdgeMeshDecimationQuadricElementHelper (const CoefficientVectorType &iCoefficients)
~QuadEdgeMeshDecimationQuadricElementHelper ()=default
Static Public Attributes
static constexpr unsigned int NumberOfCoefficients = PointDimension * (PointDimension + 1 / 2 + PointDimension + 1)
static constexpr unsigned int PointDimension = PointType::PointDimension
Protected Member Functions
void ComputeAMatrixAndBVector ()
Protected Attributes
VNLMatrixType m_A
VNLVectorType m_B
CoefficientVectorType m_Coefficients
unsigned int m_Rank
CoordType m_SVDAbsoluteThreshold
CoordType m_SVDRelativeThreshold
Detailed Description
template<typename TPoint>
class itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >
TODO explicit specification for VDimension=3!!!
Definition at line 32 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Member Typedef Documentation
CoefficientVectorType
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::CoefficientVectorType = vnl_vector_fixed<CoordType, Self::NumberOfCoefficients>
Definition at line 45 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
CoordType
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::CoordType = typename PointType::CoordRepType
Definition at line 37 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
PointType
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::PointType = TPoint
Definition at line 36 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Self
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::Self = QuadEdgeMeshDecimationQuadricElementHelper
Definition at line 35 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
TriangleType
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::TriangleType = TriangleHelper<PointType>
Definition at line 46 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
VectorType
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::VectorType = typename PointType::VectorType
Definition at line 42 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
VNLMatrixType
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::VNLMatrixType = vnl_matrix<CoordType>
Definition at line 43 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
VNLVectorType
template<typename TPoint > using itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::VNLVectorType = vnl_vector_fixed<CoordType, Self::PointDimension>
Definition at line 44 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Constructor & Destructor Documentation
QuadEdgeMeshDecimationQuadricElementHelper() [1/2]
template<typename TPoint > itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::QuadEdgeMeshDecimationQuadricElementHelper () inline
Definition at line 49 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Rank, and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::PointDimension.
QuadEdgeMeshDecimationQuadricElementHelper() [2/2]
template<typename TPoint > itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::QuadEdgeMeshDecimationQuadricElementHelper (const CoefficientVectorType & iCoefficients) inline
Definition at line 59 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Rank, and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::PointDimension.
~QuadEdgeMeshDecimationQuadricElementHelper()
template<typename TPoint > itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::~QuadEdgeMeshDecimationQuadricElementHelper () default
Member Function Documentation
AddPoint()
template<typename TPoint > void itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::AddPoint (const PointType & iP, const VectorType & iN, const CoordType & iWeight = static_cast<CoordType>(1.)) inline
Definition at line 183 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients, and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::PointDimension.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::AddTriangle().
AddTriangle()
template<typename TPoint > void itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::AddTriangle (const PointType & iP1, const PointType & iP2, const PointType & iP3, const CoordType & iWeight = static_cast<CoordType>(1.)) inline
Definition at line 172 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::AddPoint(), and itk::TriangleHelper< TPoint >::ComputeNormal().
Referenced by itk::QuadricDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >::QuadricAtOrigin().
ComputeAMatrixAndBVector()
template<typename TPoint > void itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector () inline protected
Definition at line 263 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_A, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_B, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients, and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::PointDimension.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetAMatrix(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetBVector(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::QuadEdgeMeshDecimationQuadricElementHelper().
ComputeError()
template<typename TPoint > CoordType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeError (const PointType & iP) const inline
TODO this method should be really optimized!!!
Definition at line 100 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_A, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_SVDAbsoluteThreshold, and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_SVDRelativeThreshold.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeErrorAtOptimalLocation(), and itk::QuadricDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >::MeasureEdge().
ComputeErrorAtOptimalLocation()
template<typename TPoint > CoordType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeErrorAtOptimalLocation (const PointType & iP) inline
TODO this method should be really optimized!!!
Definition at line 137 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeError(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation().
ComputeOptimalLocation() [1/2]
template<typename TPoint > PointType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation (const PointType & iP) inline
Definition at line 145 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_A, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_B, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Rank, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_SVDAbsoluteThreshold, itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_SVDRelativeThreshold, and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::PointDimension.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeErrorAtOptimalLocation(), and itk::QuadricDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >::MeasureEdge().
ComputeOptimalLocation() [2/2]
template<typename TPoint > PointType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation (const unsigned int &) inline
TODO to be implemented!!!
Definition at line 168 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
GetAMatrix()
template<typename TPoint > VNLMatrixType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetAMatrix () inline
Definition at line 79 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_A.
GetBVector()
template<typename TPoint > VNLVectorType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetBVector () inline
Definition at line 86 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_B.
GetCoefficients()
template<typename TPoint > CoefficientVectorType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetCoefficients () const inline
Definition at line 73 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
GetRank()
template<typename TPoint > unsigned int itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetRank () const inline
Definition at line 93 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Rank.
operator*()
template<typename TPoint > Self itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator* (const CoordType & iV) const inline
Definition at line 239 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
operator*=()
template<typename TPoint > Self& itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator*= (const CoordType & iV) inline
Definition at line 247 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
operator+()
template<typename TPoint > Self itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator+ (const Self & iRight) const inline
Definition at line 214 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
operator+=()
template<typename TPoint > Self& itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator+= (const Self & iRight) inline
Definition at line 220 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
operator-()
template<typename TPoint > Self itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator- (const Self & iRight) const inline
Definition at line 227 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
operator-=()
template<typename TPoint > Self& itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator-= (const Self & iRight) inline
Definition at line 233 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
operator=()
template<typename TPoint > Self& itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator= (const Self & iRight) inline
Definition at line 204 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
References itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients.
Member Data Documentation
m_A
template<typename TPoint > VNLMatrixType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_A protected
Definition at line 255 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeError(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetAMatrix().
m_B
template<typename TPoint > VNLVectorType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_B protected
Definition at line 256 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetBVector().
m_Coefficients
template<typename TPoint > CoefficientVectorType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Coefficients protected
Definition at line 254 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::AddPoint(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeError(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetCoefficients(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator*(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator*=(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator+(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator+=(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator-(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator-=(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::operator=().
m_Rank
template<typename TPoint > unsigned int itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_Rank protected
Definition at line 257 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::GetRank(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::QuadEdgeMeshDecimationQuadricElementHelper().
m_SVDAbsoluteThreshold
template<typename TPoint > CoordType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_SVDAbsoluteThreshold protected
Definition at line 258 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeError(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation().
m_SVDRelativeThreshold
template<typename TPoint > CoordType itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::m_SVDRelativeThreshold protected
Definition at line 259 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeError(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation().
NumberOfCoefficients
template<typename TPoint > constexpr unsigned int itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::NumberOfCoefficients = PointDimension * (PointDimension + 1 / 2 + PointDimension + 1) static constexpr
Definition at line 40 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
PointDimension
template<typename TPoint > constexpr unsigned int itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::PointDimension = PointType::PointDimension static constexpr
Definition at line 39 of file itkQuadEdgeMeshDecimationQuadricElementHelper.h.
Referenced by itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::AddPoint(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeAMatrixAndBVector(), itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::ComputeOptimalLocation(), and itk::QuadEdgeMeshDecimationQuadricElementHelper< TPoint >::QuadEdgeMeshDecimationQuadricElementHelper().
The documentation for this class was generated from the following file:
itkQuadEdgeMeshDecimationQuadricElementHelper.h