ITK: itk::Accessor::VectorImageToImagePixelAccessor< TType > Class Template Reference
itk::Accessor::VectorImageToImagePixelAccessor< TType > Class Template Reference
Data Processing Objects » Image AdaptorsGroup Core » | Module ITKImageAdaptors
#include <itkVectorImageToImageAdaptor.h>
Public Types
using ActualPixelType = VariableLengthVector< TType >
using ExternalType = TType
using InternalType = TType
using VectorLengthType = unsigned int
Public Member Functions
ExternalType Get (const ActualPixelType &input) const
ExternalType Get (const InternalType &input, const SizeValueType offset) const
VectorLengthType GetExtractComponentIdx () const
VectorLengthType GetVectorLength () const
void Set (ActualPixelType output, const ExternalType &input) const
void Set (InternalType &output, const ExternalType &input, const unsigned long offset) const
void SetExtractComponentIdx (VectorLengthType idx)
void SetVectorLength (VectorLengthType l)
VectorImageToImagePixelAccessor (unsigned int length=1)
Protected Types
using Superclass = DefaultVectorPixelAccessor< TType >
Private Attributes
VectorLengthType m_ComponentIdx { 0 }
Additional Inherited Members
Private Types inherited from itk::DefaultVectorPixelAccessor< TType >
using ExternalType = VariableLengthVector< TType >
using InternalType = TType
using VectorLengthType = unsigned int
Private Member Functions inherited from itk::DefaultVectorPixelAccessor< TType >
DefaultVectorPixelAccessor ()=default
DefaultVectorPixelAccessor (VectorLengthType l)
ExternalType Get (const InternalType &input, const SizeValueType offset) const
VectorLengthType GetVectorLength () const
void Set (InternalType &output, const ExternalType &input, const unsigned long offset) const
~DefaultVectorPixelAccessor ()=default
void SetVectorLength (VectorLengthType l)
Detailed Description
template<typename TType>
class itk::Accessor::VectorImageToImagePixelAccessor< TType >
Extract components from a VectorImage.
This accessor is used to extract components from a VectorImage. It is used from VectorImageComponentExtractAdaptor. The component to extract is set using SetExtractComponentIdx.
Note
This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.
Deprecated:
Please use the more generic NthElementImageAdaptor.
See also
NthElementImageAdaptor
Definition at line 48 of file itkVectorImageToImageAdaptor.h.
Member Typedef Documentation
ActualPixelType
template<typename TType > using itk::Accessor::VectorImageToImagePixelAccessor< TType >::ActualPixelType = VariableLengthVector<TType>
Definition at line 60 of file itkVectorImageToImageAdaptor.h.
ExternalType
template<typename TType > using itk::Accessor::VectorImageToImagePixelAccessor< TType >::ExternalType = TType
External type alias. It defines the external aspect that this class will exhibit.
Definition at line 55 of file itkVectorImageToImageAdaptor.h.
InternalType
template<typename TType > using itk::Accessor::VectorImageToImagePixelAccessor< TType >::InternalType = TType
Internal type alias used by the ImageAdaptor for the buffer pointer
Definition at line 58 of file itkVectorImageToImageAdaptor.h.
Superclass
template<typename TType > using itk::Accessor::VectorImageToImagePixelAccessor< TType >::Superclass = DefaultVectorPixelAccessor<TType> protected
Definition at line 118 of file itkVectorImageToImageAdaptor.h.
VectorLengthType
template<typename TType > using itk::Accessor::VectorImageToImagePixelAccessor< TType >::VectorLengthType = unsigned int
Definition at line 51 of file itkVectorImageToImageAdaptor.h.
Constructor & Destructor Documentation
VectorImageToImagePixelAccessor()
template<typename TType > itk::Accessor::VectorImageToImagePixelAccessor< TType >::VectorImageToImagePixelAccessor (unsigned int length = 1) inline
Definition at line 115 of file itkVectorImageToImageAdaptor.h.
Member Function Documentation
Get() [1/2]
template<typename TType > ExternalType itk::Accessor::VectorImageToImagePixelAccessor< TType >::Get (const ActualPixelType & input) const inline
Definition at line 75 of file itkVectorImageToImageAdaptor.h.
Referenced by itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::Get().
Get() [2/2]
template<typename TType > ExternalType itk::Accessor::VectorImageToImagePixelAccessor< TType >::Get (const InternalType & input, const SizeValueType offset) const inline
Definition at line 84 of file itkVectorImageToImageAdaptor.h.
GetExtractComponentIdx()
template<typename TType > VectorLengthType itk::Accessor::VectorImageToImagePixelAccessor< TType >::GetExtractComponentIdx () const inline
Definition at line 96 of file itkVectorImageToImageAdaptor.h.
Referenced by itk::VectorImageToImageAdaptor< TPixelType, Dimension >::GetExtractComponentIndex().
GetVectorLength()
template<typename TType > VectorLengthType itk::Accessor::VectorImageToImagePixelAccessor< TType >::GetVectorLength () const inline
Get Vector lengths
Definition at line 110 of file itkVectorImageToImageAdaptor.h.
Set() [1/2]
template<typename TType > void itk::Accessor::VectorImageToImagePixelAccessor< TType >::Set (ActualPixelType output, const ExternalType & input) const inline
Definition at line 63 of file itkVectorImageToImageAdaptor.h.
Referenced by itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::Set().
Set() [2/2]
template<typename TType > void itk::Accessor::VectorImageToImagePixelAccessor< TType >::Set (InternalType & output, const ExternalType & input, const unsigned long offset) const inline
Definition at line 69 of file itkVectorImageToImageAdaptor.h.
SetExtractComponentIdx()
template<typename TType > void itk::Accessor::VectorImageToImagePixelAccessor< TType >::SetExtractComponentIdx (VectorLengthType idx) inline
Definition at line 90 of file itkVectorImageToImageAdaptor.h.
Referenced by itk::VectorImageToImageAdaptor< TPixelType, Dimension >::SetExtractComponentIndex().
SetVectorLength()
template<typename TType > void itk::Accessor::VectorImageToImagePixelAccessor< TType >::SetVectorLength (VectorLengthType l) inline
Set the length of each vector in the VectorImage
Definition at line 103 of file itkVectorImageToImageAdaptor.h.
Member Data Documentation
m_ComponentIdx
template<typename TType > VectorLengthType itk::Accessor::VectorImageToImagePixelAccessor< TType >::m_ComponentIdx { 0 } private
Definition at line 121 of file itkVectorImageToImageAdaptor.h.
Referenced by itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::Get(), itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::GetExtractComponentIdx(), itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::Set(), and itk::Accessor::VectorImageToImagePixelAccessor< TPixelType >::SetExtractComponentIdx().
The documentation for this class was generated from the following file:
itkVectorImageToImageAdaptor.h