ITK: itk::fftw::ComplexToComplexProxy< float > Class Reference
itk::fftw::ComplexToComplexProxy< float > Class Reference
#include <itkFFTWCommonExtended.h>
Public Types
using ComplexType = fftwf_complex
using PixelType = float
using PlanType = fftwf_plan
using Self = ComplexToComplexProxy< float >
Static Public Member Functions
static void DestroyPlan (PlanType p)
static void Execute (PlanType p)
static PlanType Plan_dft_1d (const int n, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r (int rank, const int *n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r_1d (int n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r_2d (int nx, int ny, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType *in, PixelType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c (int rank, const int *n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c_1d (int n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c_2d (int nx, int ny, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
static PlanType Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType *in, ComplexType *out, unsigned int flags, int threads=1)
Detailed Description
Definition at line 57 of file itkFFTWCommonExtended.h.
Member Typedef Documentation
ComplexType
using itk::fftw::ComplexToComplexProxy< float >::ComplexType = fftwf_complex
Definition at line 61 of file itkFFTWCommonExtended.h.
PixelType
using itk::fftw::ComplexToComplexProxy< float >::PixelType = float
Definition at line 60 of file itkFFTWCommonExtended.h.
PlanType
using itk::fftw::ComplexToComplexProxy< float >::PlanType = fftwf_plan
Definition at line 62 of file itkFFTWCommonExtended.h.
Self
using itk::fftw::ComplexToComplexProxy< float >::Self = ComplexToComplexProxy<float>
Definition at line 63 of file itkFFTWCommonExtended.h.
Member Function Documentation
DestroyPlan()
static void itk::fftw::ComplexToComplexProxy< float >::DestroyPlan (PlanType p) inline static
Definition at line 182 of file itkFFTWCommonExtended.h.
Execute()
static void itk::fftw::ComplexToComplexProxy< float >::Execute (PlanType p) inline static
Definition at line 177 of file itkFFTWCommonExtended.h.
Plan_dft_1d()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_1d (const int n, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1) inline static
Definition at line 163 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_c2r (int rank, const int * n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 102 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r_1d()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_c2r_1d (int n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 66 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r_2d()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_c2r_2d (int nx, int ny, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 78 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_c2r_3d()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1) inline static
Definition at line 90 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_r2c (int rank, const int * n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 151 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c_1d()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_r2c_1d (int n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 115 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c_2d()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_r2c_2d (int nx, int ny, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 127 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Plan_dft_r2c_3d()
static PlanType itk::fftw::ComplexToComplexProxy< float >::Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1) inline static
Definition at line 139 of file itkFFTWCommonExtended.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
The documentation for this class was generated from the following file:
itkFFTWCommonExtended.h