ITK: itk::DTITubeSpatialObjectPoint< TPointDimension > Class Template Reference
itk::DTITubeSpatialObjectPoint< TPointDimension > Class Template Reference
Group Core » Module ITKSpatialObjects
#include <itkDTITubeSpatialObjectPoint.h>
Public Types
using CovariantVectorType = CovariantVector< double, TPointDimension >
using DTITubeSpatialObjectPointFieldEnum = DTITubeSpatialObjectPointEnums::DTITubeSpatialObjectPointField
using FieldListType = std::vector< FieldType >
using FieldType = std::pair< std::string, float >
using PointType = Point< double, TPointDimension >
using Self = DTITubeSpatialObjectPoint
using Superclass = TubeSpatialObjectPoint< TPointDimension >
using VectorType = Vector< double, TPointDimension >
Public Types inherited from itk::TubeSpatialObjectPoint< 3 >
using CovariantVectorType = CovariantVector< double, TPointDimension >
using PointType = Point< double, TPointDimension >
using Self = TubeSpatialObjectPoint
using Superclass = SpatialObjectPoint< TPointDimension >
using VectorType = Vector< double, TPointDimension >
Public Types inherited from itk::SpatialObjectPoint< TPointDimension >
using ColorType = RGBAPixel< double >
using PointDimensionType = unsigned int
using PointType = Point< double, TPointDimension >
using Self = SpatialObjectPoint
using SpatialObjectType = SpatialObject< TPointDimension >
using VectorType = vnl_vector< double >
Public Member Functions
void AddField (const char *name, float value)
void AddField (DTITubeSpatialObjectPointFieldEnum name, float value)
DTITubeSpatialObjectPoint ()
DTITubeSpatialObjectPoint (const DTITubeSpatialObjectPoint &other)
float GetField (const char *name) const
float GetField (DTITubeSpatialObjectPointFieldEnum name) const
const FieldListType & GetFields () const
const float * GetTensorMatrix () const
Self & operator= (const DTITubeSpatialObjectPoint &rhs)
void SetField (const char *name, float value)
void SetField (DTITubeSpatialObjectPointFieldEnum name, float value)
void SetTensorMatrix (const DiffusionTensor3D< double > &matrix)
void SetTensorMatrix (const DiffusionTensor3D< float > &matrix)
void SetTensorMatrix (const float *matrix)
~DTITubeSpatialObjectPoint () override=default
Public Member Functions inherited from itk::TubeSpatialObjectPoint< 3 >
double GetAlpha1 () const
double GetAlpha2 () const
double GetAlpha3 () const
double GetBranchness () const
double GetCurvature () const
double GetIntensity () const
double GetLevelness () const
double GetMedialness () const
const CovariantVectorType & GetNormal1InObjectSpace () const
const CovariantVectorType GetNormal1InWorldSpace () const
const CovariantVectorType & GetNormal2InObjectSpace () const
const CovariantVectorType GetNormal2InWorldSpace () const
double GetRadiusInObjectSpace () const
double GetRadiusInWorldSpace () const
double GetRidgeness () const
double GetRoundness () const
const VectorType & GetTangentInObjectSpace () const
const VectorType GetTangentInWorldSpace () const
Self & operator= (const TubeSpatialObjectPoint &rhs)
void SetAlpha1 (double alpha1)
void SetAlpha2 (double alpha2)
void SetAlpha3 (double alpha3)
void SetBranchness (double branchness)
void SetCurvature (double curvature)
void SetIntensity (double intensity)
void SetLevelness (double levelness)
void SetMedialness (double medialness)
void SetNormal1InObjectSpace (const CovariantVectorType &newV1)
void SetNormal1InWorldSpace (const CovariantVectorType &newV1)
void SetNormal2InObjectSpace (const CovariantVectorType &newV2)
void SetNormal2InWorldSpace (const CovariantVectorType &newV2)
void SetRadiusInObjectSpace (double newR)
void SetRadiusInWorldSpace (double newR)
void SetRidgeness (double ridgeness)
void SetRoundness (double roundness)
void SetTangentInObjectSpace (const VectorType &newT)
void SetTangentInWorldSpace (const VectorType &newT)
TubeSpatialObjectPoint ()
TubeSpatialObjectPoint (const TubeSpatialObjectPoint &other)
~TubeSpatialObjectPoint () override=default
Public Member Functions inherited from itk::SpatialObjectPoint< TPointDimension >
double GetAlpha () const
double GetBlue () const
ColorType GetColor () const
double GetGreen () const
int GetId () const
virtual const char * GetNameOfClass () const
const PointType & GetPositionInObjectSpace () const
PointType GetPositionInWorldSpace () const
double GetRed () const
SpatialObjectType * GetSpatialObject () const
std::map< std::string, double > & GetTagScalarDictionary ()
const std::map< std::string, double > & GetTagScalarDictionary () const
double GetTagScalarValue (const std::string &tag) const
bool GetTagScalarValue (const std::string &tag, double &value) const
Self & operator= (const SpatialObjectPoint &rhs)
void Print (std::ostream &os) const
void SetAlpha (double a)
void SetBlue (double b)
void SetColor (ColorType color)
void SetColor (double r, double g, double b, double a=1)
void SetGreen (double g)
void SetId (int id)
template<typename... TCoordinate>
void SetPositionInObjectSpace (const double firstCoordinate, const TCoordinate... otherCoordinate)
void SetPositionInObjectSpace (const PointType &newPositionInObjectSpace)
void SetPositionInWorldSpace (const PointType &point)
void SetRed (double r)
void SetSpatialObject (SpatialObjectType *so)
void SetTagScalarDictionary (const std::map< std::string, double > &dict)
void SetTagScalarValue (const std::string &tag, double value)
SpatialObjectPoint ()
SpatialObjectPoint (const SpatialObjectPoint &other)
virtual ~SpatialObjectPoint ()=default
Protected Member Functions
void PrintSelf (std::ostream &os, Indent indent) const override
std::string TranslateEnumToChar (DTITubeSpatialObjectPointFieldEnum name) const
Protected Member Functions inherited from itk::TubeSpatialObjectPoint< 3 >
void PrintSelf (std::ostream &os, Indent indent) const override
Protected Attributes
FieldListType m_Fields
float m_TensorMatrix [6]
Protected Attributes inherited from itk::TubeSpatialObjectPoint< 3 >
double m_Alpha1
double m_Alpha2
double m_Alpha3
double m_Branchness
double m_Curvature
double m_Intensity
double m_Levelness
double m_Medialness
CovariantVectorType m_Normal1InObjectSpace
CovariantVectorType m_Normal2InObjectSpace
double m_RadiusInObjectSpace
double m_Ridgeness
double m_Roundness
VectorType m_TangentInObjectSpace
Protected Attributes inherited from itk::SpatialObjectPoint< TPointDimension >
ColorType m_Color
int m_Id
PointType m_PositionInObjectSpace
std::map< std::string, double > m_ScalarDictionary
WeakPointer< SpatialObjectType > m_SpatialObject
Additional Inherited Members
Static Public Attributes inherited from itk::SpatialObjectPoint< TPointDimension >
static constexpr PointDimensionType PointDimension = TPointDimension
Detailed Description
template<unsigned int TPointDimension = 3>
class itk::DTITubeSpatialObjectPoint< TPointDimension >
Point used for a tube definition.
This class contains all the functions necessary to define a point that can be used to build tubes.
See also
DTITubeSpatialObject
Definition at line 61 of file itkDTITubeSpatialObjectPoint.h.
Member Typedef Documentation
CovariantVectorType
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::CovariantVectorType = CovariantVector<double, TPointDimension>
Definition at line 68 of file itkDTITubeSpatialObjectPoint.h.
DTITubeSpatialObjectPointFieldEnum
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::DTITubeSpatialObjectPointFieldEnum = DTITubeSpatialObjectPointEnums::DTITubeSpatialObjectPointField
Definition at line 72 of file itkDTITubeSpatialObjectPoint.h.
FieldListType
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::FieldListType = std::vector<FieldType>
Definition at line 70 of file itkDTITubeSpatialObjectPoint.h.
FieldType
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::FieldType = std::pair<std::string, float>
Definition at line 69 of file itkDTITubeSpatialObjectPoint.h.
PointType
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::PointType = Point<double, TPointDimension>
Definition at line 66 of file itkDTITubeSpatialObjectPoint.h.
Self
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::Self = DTITubeSpatialObjectPoint
Definition at line 64 of file itkDTITubeSpatialObjectPoint.h.
Superclass
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::Superclass = TubeSpatialObjectPoint<TPointDimension>
Definition at line 65 of file itkDTITubeSpatialObjectPoint.h.
VectorType
template<unsigned int TPointDimension = 3> using itk::DTITubeSpatialObjectPoint< TPointDimension >::VectorType = Vector<double, TPointDimension>
Definition at line 67 of file itkDTITubeSpatialObjectPoint.h.
Constructor & Destructor Documentation
DTITubeSpatialObjectPoint() [1/2]
template<unsigned int TPointDimension = 3> itk::DTITubeSpatialObjectPoint< TPointDimension >::DTITubeSpatialObjectPoint ()
Constructor. This one defines the number of dimensions in the DTITubeSpatialObjectPoint
DTITubeSpatialObjectPoint() [2/2]
template<unsigned int TPointDimension = 3> itk::DTITubeSpatialObjectPoint< TPointDimension >::DTITubeSpatialObjectPoint (const DTITubeSpatialObjectPoint< TPointDimension > & other)
Copy Constructor
~DTITubeSpatialObjectPoint()
template<unsigned int TPointDimension = 3> itk::DTITubeSpatialObjectPoint< TPointDimension >::~DTITubeSpatialObjectPoint () override default
Default destructor.
Member Function Documentation
AddField() [1/2]
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::AddField (const char * name, float value)
Add a field to the point list
AddField() [2/2]
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::AddField (DTITubeSpatialObjectPointFieldEnum name, float value)
Add a field to the point list
GetField() [1/2]
template<unsigned int TPointDimension = 3> float itk::DTITubeSpatialObjectPoint< TPointDimension >::GetField (const char * name) const
Return the value of the specific fields
GetField() [2/2]
template<unsigned int TPointDimension = 3> float itk::DTITubeSpatialObjectPoint< TPointDimension >::GetField (DTITubeSpatialObjectPointFieldEnum name) const
GetFields()
template<unsigned int TPointDimension = 3> const FieldListType& itk::DTITubeSpatialObjectPoint< TPointDimension >::GetFields () const inline
Return the list of extra fields
Definition at line 142 of file itkDTITubeSpatialObjectPoint.h.
GetTensorMatrix()
template<unsigned int TPointDimension = 3> const float* itk::DTITubeSpatialObjectPoint< TPointDimension >::GetTensorMatrix () const inline
Definition at line 116 of file itkDTITubeSpatialObjectPoint.h.
operator=()
template<unsigned int TPointDimension = 3> Self& itk::DTITubeSpatialObjectPoint< TPointDimension >::operator= (const DTITubeSpatialObjectPoint< TPointDimension > & rhs)
Copy one DTITubeSpatialObjectPoint to another
PrintSelf()
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Print the object
Reimplemented from itk::SpatialObjectPoint< TPointDimension >.
SetField() [1/2]
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::SetField (const char * name, float value)
SetField() [2/2]
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::SetField (DTITubeSpatialObjectPointFieldEnum name, float value)
Set a field value
SetTensorMatrix() [1/3]
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::SetTensorMatrix (const DiffusionTensor3D< double > & matrix) inline
Set/Get the tensor matrix
Definition at line 95 of file itkDTITubeSpatialObjectPoint.h.
References itk::FixedArray< TComponent, VDimension *(VDimension+1)/2 >::Begin(), and itk::FixedArray< TComponent, VDimension *(VDimension+1)/2 >::End().
SetTensorMatrix() [2/3]
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::SetTensorMatrix (const DiffusionTensor3D< float > & matrix) inline
Definition at line 101 of file itkDTITubeSpatialObjectPoint.h.
References itk::FixedArray< TComponent, VDimension *(VDimension+1)/2 >::Begin(), and itk::FixedArray< TComponent, VDimension *(VDimension+1)/2 >::End().
SetTensorMatrix() [3/3]
template<unsigned int TPointDimension = 3> void itk::DTITubeSpatialObjectPoint< TPointDimension >::SetTensorMatrix (const float * matrix) inline
Definition at line 107 of file itkDTITubeSpatialObjectPoint.h.
TranslateEnumToChar()
template<unsigned int TPointDimension = 3> std::string itk::DTITubeSpatialObjectPoint< TPointDimension >::TranslateEnumToChar (DTITubeSpatialObjectPointFieldEnum name) const protected
Translate the enum to char
Member Data Documentation
m_Fields
template<unsigned int TPointDimension = 3> FieldListType itk::DTITubeSpatialObjectPoint< TPointDimension >::m_Fields protected
Definition at line 156 of file itkDTITubeSpatialObjectPoint.h.
m_TensorMatrix
template<unsigned int TPointDimension = 3> float itk::DTITubeSpatialObjectPoint< TPointDimension >::m_TensorMatrix[6] protected
Definition at line 155 of file itkDTITubeSpatialObjectPoint.h.
The documentation for this class was generated from the following file:
itkDTITubeSpatialObjectPoint.h