ITK: itk::NumericTraits< SymmetricSecondRankTensor< T, D > > Class Template Reference
itk::NumericTraits< SymmetricSecondRankTensor< T, D > > Class Template Reference
Data Representation ObjectsGroup Core » | Module ITKCommon
#include <itkNumericTraitsTensorPixel.h>
Public Types
using AbsType = SymmetricSecondRankTensor< ElementAbsType, D >
using AccumulateType = SymmetricSecondRankTensor< ElementAccumulateType, D >
using FloatType = SymmetricSecondRankTensor< ElementFloatType, D >
using MeasurementVectorType = Self
using PrintType = SymmetricSecondRankTensor< ElementPrintType, D >
using RealType = SymmetricSecondRankTensor< ElementRealType, D >
using ScalarRealType = ElementRealType
using Self = SymmetricSecondRankTensor< T, D >
using ValueType = T
Static Public Member Functions
static void AssignToArray (const Self &v, MeasurementVectorType &mv)
template<typename TArray >
static void AssignToArray (const Self &v, TArray &mv)
static unsigned int GetLength ()
static unsigned int GetLength (const SymmetricSecondRankTensor< T, D > &)
static const Self max ()
static const Self max (const Self &)
static const Self min ()
static const Self min (const Self &)
static const Self NonpositiveMin ()
static const Self NonpositiveMin (const Self &)
static const Self OneValue ()
static const Self OneValue (const Self &)
static const Self ZeroValue ()
static const Self ZeroValue (const Self &)
static void SetLength (SymmetricSecondRankTensor< T, D > &m, const unsigned int s)
Static Public Attributes
static constexpr bool IsComplex = NumericTraits<ValueType>::IsComplex
static constexpr bool IsInteger = std::is_integral<ValueType>::value
static constexpr bool IsSigned = std::is_signed<ValueType>::value
static const Self ITKCommon_EXPORT One
static const Self ITKCommon_EXPORT Zero
Private Types
using ElementAbsType = typename NumericTraits< T >::AbsType
using ElementAccumulateType = typename NumericTraits< T >::AccumulateType
using ElementFloatType = typename NumericTraits< T >::FloatType
using ElementPrintType = typename NumericTraits< T >::PrintType
using ElementRealType = typename NumericTraits< T >::RealType
Detailed Description
template<typename T, unsigned int D>
class itk::NumericTraits< SymmetricSecondRankTensor< T, D > >
Define numeric traits for SymmetricSecondRankTensor.
Template Parameters
T Component type of SymmetricSecondRankTensor
D Dimension of the SymmetricSecondRankTensor
We provide here a generic implementation based on creating types of SymmetricSecondRankTensor whose components are the types of the NumericTraits from the original SymmetricSecondRankTensor components. This implementation require support for partial specializations, since it is based on the concept that: NumericTraits<SymmetricSecondRankTensor< T, D > > is defined piecewise by SymmetricSecondRankTensor< NumericTraits< T, D > >
See also
NumericTraits
Definition at line 44 of file itkNumericTraitsTensorPixel.h.
Member Typedef Documentation
AbsType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::AbsType = SymmetricSecondRankTensor<ElementAbsType, D>
Unsigned component type
Definition at line 60 of file itkNumericTraitsTensorPixel.h.
AccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::AccumulateType = SymmetricSecondRankTensor<ElementAccumulateType, D>
Accumulation of addition and multiplication.
Definition at line 63 of file itkNumericTraitsTensorPixel.h.
ElementAbsType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ElementAbsType = typename NumericTraits<T>::AbsType private
Definition at line 47 of file itkNumericTraitsTensorPixel.h.
ElementAccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ElementAccumulateType = typename NumericTraits<T>::AccumulateType private
Definition at line 48 of file itkNumericTraitsTensorPixel.h.
ElementFloatType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ElementFloatType = typename NumericTraits<T>::FloatType private
Definition at line 49 of file itkNumericTraitsTensorPixel.h.
ElementPrintType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ElementPrintType = typename NumericTraits<T>::PrintType private
Definition at line 50 of file itkNumericTraitsTensorPixel.h.
ElementRealType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ElementRealType = typename NumericTraits<T>::RealType private
Definition at line 51 of file itkNumericTraitsTensorPixel.h.
FloatType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::FloatType = SymmetricSecondRankTensor<ElementFloatType, D>
Typedef for operations that use floating point instead of real precision
Definition at line 67 of file itkNumericTraitsTensorPixel.h.
MeasurementVectorType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::MeasurementVectorType = Self
Measurement vector type
Definition at line 79 of file itkNumericTraitsTensorPixel.h.
PrintType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::PrintType = SymmetricSecondRankTensor<ElementPrintType, D>
Return the type that can be printed.
Definition at line 70 of file itkNumericTraitsTensorPixel.h.
RealType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::RealType = SymmetricSecondRankTensor<ElementRealType, D>
Type for real-valued scalar operations.
Definition at line 73 of file itkNumericTraitsTensorPixel.h.
ScalarRealType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ScalarRealType = ElementRealType
Type for real-valued scalar operations.
Definition at line 76 of file itkNumericTraitsTensorPixel.h.
Self
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::Self = SymmetricSecondRankTensor<T, D>
Definition at line 57 of file itkNumericTraitsTensorPixel.h.
ValueType
template<typename T , unsigned int D> using itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ValueType = T
Return the type of the native component type.
Definition at line 55 of file itkNumericTraitsTensorPixel.h.
Member Function Documentation
AssignToArray() [1/2]
template<typename T , unsigned int D> static void itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::AssignToArray (const Self & v, MeasurementVectorType & mv) inline static
Definition at line 182 of file itkNumericTraitsTensorPixel.h.
AssignToArray() [2/2]
template<typename T , unsigned int D> template<typename TArray > static void itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::AssignToArray (const Self & v, TArray & mv) inline static
Definition at line 189 of file itkNumericTraitsTensorPixel.h.
References itk::NumericTraits< T >::GetLength().
GetLength() [1/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::GetLength () inline static
Return the size of the underlying FixedArray.
Definition at line 176 of file itkNumericTraitsTensorPixel.h.
GetLength() [2/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::GetLength (const SymmetricSecondRankTensor< T, D > &) inline static
Return the size of the underlying FixedArray.
Definition at line 169 of file itkNumericTraitsTensorPixel.h.
References itk::NumericTraits< T >::GetLength().
max() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::max () inline static
Definition at line 99 of file itkNumericTraitsTensorPixel.h.
max() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::max (const Self &) inline static
Component wise defined element
Note
minimum value for floating pointer types is defined as minimum positive normalize value.
Definition at line 87 of file itkNumericTraitsTensorPixel.h.
min() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::min () inline static
Definition at line 105 of file itkNumericTraitsTensorPixel.h.
min() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::min (const Self &) inline static
Definition at line 93 of file itkNumericTraitsTensorPixel.h.
NonpositiveMin() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::NonpositiveMin () inline static
Definition at line 111 of file itkNumericTraitsTensorPixel.h.
NonpositiveMin() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::NonpositiveMin (const Self &) inline static
Definition at line 129 of file itkNumericTraitsTensorPixel.h.
References itk::NumericTraits< T >::NonpositiveMin().
OneValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::OneValue () inline static
Definition at line 123 of file itkNumericTraitsTensorPixel.h.
OneValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::OneValue (const Self &) inline static
Definition at line 141 of file itkNumericTraitsTensorPixel.h.
References itk::NumericTraits< T >::OneValue().
SetLength()
template<typename T , unsigned int D> static void itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::SetLength (SymmetricSecondRankTensor< T, D > & m, const unsigned int s) inline static
Fixed length vectors cannot be resized, so an exception will be thrown if the input size is not valid. Here, the size refers to the dimensionality of the underlying FixedArray, not the tensor dimensionality.
Definition at line 155 of file itkNumericTraitsTensorPixel.h.
References itk::FixedArray< TComponent, 3 *(3+1)/2 >::Fill().
ZeroValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ZeroValue () inline static
Definition at line 117 of file itkNumericTraitsTensorPixel.h.
ZeroValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::ZeroValue (const Self &) inline static
Definition at line 135 of file itkNumericTraitsTensorPixel.h.
References itk::NumericTraits< T >::ZeroValue().
Member Data Documentation
IsComplex
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::IsComplex = NumericTraits<ValueType>::IsComplex static constexpr
Definition at line 148 of file itkNumericTraitsTensorPixel.h.
IsInteger
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::IsInteger = std::is_integral<ValueType>::value static constexpr
Definition at line 147 of file itkNumericTraitsTensorPixel.h.
IsSigned
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::IsSigned = std::is_signed<ValueType>::value static constexpr
Definition at line 146 of file itkNumericTraitsTensorPixel.h.
One
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::One static
Definition at line 201 of file itkNumericTraitsTensorPixel.h.
Zero
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< SymmetricSecondRankTensor< T, D > >::Zero static
Note
: the functions are preferred over the member variables as they are defined for all partial specialization
Definition at line 200 of file itkNumericTraitsTensorPixel.h.
The documentation for this class was generated from the following file:
itkNumericTraitsTensorPixel.h