ITK: itk::NumericTraits< Vector< T, D > > Class Template Reference
itk::NumericTraits< Vector< T, D > > Class Template Reference
#include <itkNumericTraitsVectorPixel.h>
Public Types
using AbsType = Vector< ElementAbsType, D >
using AccumulateType = Vector< ElementAccumulateType, D >
using FloatType = Vector< ElementFloatType, D >
using MeasurementVectorType = Self
using PrintType = Vector< ElementPrintType, D >
using RealType = Vector< ElementRealType, D >
using ScalarRealType = ElementRealType
using Self = Vector< T, D >
using ValueType = T
Static Public Member Functions
static void AssignToArray (const Self &v, MeasurementVectorType &mv)
template<typename TArray >
static void AssignToArray (const Self &v, TArray &mv)
static unsigned int GetLength ()
static unsigned int GetLength (const Vector< T, D > &)
static bool IsNegative (const Self &a)
static bool IsNonnegative (const Self &a)
static bool IsNonpositive (const Self &a)
static bool IsPositive (const Self &a)
static const Self max ()
static const Self max (const Self &)
static const Self min ()
static const Self min (const Self &)
static const Self NonpositiveMin ()
static const Self NonpositiveMin (const Self &)
static const Self OneValue ()
static const Self OneValue (const Self &)
static const Self ZeroValue ()
static const Self ZeroValue (const Self &)
static void SetLength (Vector< T, D > &m, const unsigned int s)
Static Public Attributes
static constexpr bool IsComplex = NumericTraits<ValueType>::IsComplex
static constexpr bool IsInteger = std::is_integral<ValueType>::value
static constexpr bool IsSigned = std::is_signed<ValueType>::value
static const Self ITKCommon_EXPORT One
static const Self ITKCommon_EXPORT Zero
Private Types
using ElementAbsType = typename NumericTraits< T >::AbsType
using ElementAccumulateType = typename NumericTraits< T >::AccumulateType
using ElementFloatType = typename NumericTraits< T >::FloatType
using ElementPrintType = typename NumericTraits< T >::PrintType
using ElementRealType = typename NumericTraits< T >::RealType
Detailed Description
template<typename T, unsigned int D>
class itk::NumericTraits< Vector< T, D > >
NumericTraits for Vector.
Template Parameters
T Component type for Vector
D Space dimension (Dimension of Vector)
Definition at line 31 of file itkNumericTraitsVectorPixel.h.
Member Typedef Documentation
AbsType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::AbsType = Vector<ElementAbsType, D>
Unsigned component type
Definition at line 46 of file itkNumericTraitsVectorPixel.h.
AccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::AccumulateType = Vector<ElementAccumulateType, D>
Accumulation of addition and multiplication.
Definition at line 49 of file itkNumericTraitsVectorPixel.h.
ElementAbsType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::ElementAbsType = typename NumericTraits<T>::AbsType private
Definition at line 34 of file itkNumericTraitsVectorPixel.h.
ElementAccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::ElementAccumulateType = typename NumericTraits<T>::AccumulateType private
Definition at line 35 of file itkNumericTraitsVectorPixel.h.
ElementFloatType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::ElementFloatType = typename NumericTraits<T>::FloatType private
Definition at line 36 of file itkNumericTraitsVectorPixel.h.
ElementPrintType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::ElementPrintType = typename NumericTraits<T>::PrintType private
Definition at line 37 of file itkNumericTraitsVectorPixel.h.
ElementRealType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::ElementRealType = typename NumericTraits<T>::RealType private
Definition at line 38 of file itkNumericTraitsVectorPixel.h.
FloatType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::FloatType = Vector<ElementFloatType, D>
Typedef for operations that use floating point instead of real precision
Definition at line 53 of file itkNumericTraitsVectorPixel.h.
MeasurementVectorType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::MeasurementVectorType = Self
Measurement vector type
Definition at line 65 of file itkNumericTraitsVectorPixel.h.
PrintType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::PrintType = Vector<ElementPrintType, D>
Return the type that can be printed.
Definition at line 56 of file itkNumericTraitsVectorPixel.h.
RealType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::RealType = Vector<ElementRealType, D>
Type for real-valued scalar operations.
Definition at line 59 of file itkNumericTraitsVectorPixel.h.
ScalarRealType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::ScalarRealType = ElementRealType
Type for real-valued scalar operations.
Definition at line 62 of file itkNumericTraitsVectorPixel.h.
Self
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::Self = Vector<T, D>
Definition at line 43 of file itkNumericTraitsVectorPixel.h.
ValueType
template<typename T , unsigned int D> using itk::NumericTraits< Vector< T, D > >::ValueType = T
Return the type of the native component type.
Definition at line 42 of file itkNumericTraitsVectorPixel.h.
Member Function Documentation
AssignToArray() [1/2]
template<typename T , unsigned int D> static void itk::NumericTraits< Vector< T, D > >::AssignToArray (const Self & v, MeasurementVectorType & mv) inline static
Definition at line 221 of file itkNumericTraitsVectorPixel.h.
AssignToArray() [2/2]
template<typename T , unsigned int D> template<typename TArray > static void itk::NumericTraits< Vector< T, D > >::AssignToArray (const Self & v, TArray & mv) inline static
Definition at line 228 of file itkNumericTraitsVectorPixel.h.
GetLength() [1/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< Vector< T, D > >::GetLength () inline static
Return the size of the vector.
Definition at line 215 of file itkNumericTraitsVectorPixel.h.
GetLength() [2/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< Vector< T, D > >::GetLength (const Vector< T, D > &) inline static
Return the size of the vector.
Definition at line 208 of file itkNumericTraitsVectorPixel.h.
IsNegative()
template<typename T , unsigned int D> static bool itk::NumericTraits< Vector< T, D > >::IsNegative (const Self & a) inline static
Definition at line 161 of file itkNumericTraitsVectorPixel.h.
References itk::NumericTraits< T >::GetLength().
IsNonnegative()
template<typename T , unsigned int D> static bool itk::NumericTraits< Vector< T, D > >::IsNonnegative (const Self & a) inline static
Definition at line 175 of file itkNumericTraitsVectorPixel.h.
References itk::NumericTraits< T >::GetLength().
IsNonpositive()
template<typename T , unsigned int D> static bool itk::NumericTraits< Vector< T, D > >::IsNonpositive (const Self & a) inline static
Definition at line 147 of file itkNumericTraitsVectorPixel.h.
References itk::NumericTraits< T >::GetLength().
IsPositive()
template<typename T , unsigned int D> static bool itk::NumericTraits< Vector< T, D > >::IsPositive (const Self & a) inline static
Definition at line 133 of file itkNumericTraitsVectorPixel.h.
References itk::NumericTraits< T >::GetLength().
max() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::max () inline static
Definition at line 85 of file itkNumericTraitsVectorPixel.h.
max() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::max (const Self &) inline static
Component wise defined element
Note
minimum value for floating pointer types is defined as minimum positive normalize value.
Definition at line 73 of file itkNumericTraitsVectorPixel.h.
min() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::min () inline static
Definition at line 91 of file itkNumericTraitsVectorPixel.h.
min() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::min (const Self &) inline static
Definition at line 79 of file itkNumericTraitsVectorPixel.h.
NonpositiveMin() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::NonpositiveMin () inline static
Definition at line 97 of file itkNumericTraitsVectorPixel.h.
NonpositiveMin() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::NonpositiveMin (const Self &) inline static
Definition at line 115 of file itkNumericTraitsVectorPixel.h.
References itk::NumericTraits< T >::NonpositiveMin().
OneValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::OneValue () inline static
Definition at line 109 of file itkNumericTraitsVectorPixel.h.
OneValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::OneValue (const Self &) inline static
Definition at line 127 of file itkNumericTraitsVectorPixel.h.
References itk::NumericTraits< T >::OneValue().
SetLength()
template<typename T , unsigned int D> static void itk::NumericTraits< Vector< T, D > >::SetLength (Vector< T, D > & m, const unsigned int s) inline static
Fixed length vectors cannot be resized, so an exception will be thrown if the input size is not valid. If the size is valid the vector will be filled with zeros.
Definition at line 196 of file itkNumericTraitsVectorPixel.h.
References itk::FixedArray< T, 3 >::Fill().
ZeroValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::ZeroValue () inline static
Definition at line 103 of file itkNumericTraitsVectorPixel.h.
ZeroValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< Vector< T, D > >::ZeroValue (const Self &) inline static
Definition at line 121 of file itkNumericTraitsVectorPixel.h.
References itk::NumericTraits< T >::ZeroValue().
Member Data Documentation
IsComplex
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< Vector< T, D > >::IsComplex = NumericTraits<ValueType>::IsComplex static constexpr
Definition at line 190 of file itkNumericTraitsVectorPixel.h.
IsInteger
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< Vector< T, D > >::IsInteger = std::is_integral<ValueType>::value static constexpr
Definition at line 189 of file itkNumericTraitsVectorPixel.h.
IsSigned
template<typename T , unsigned int D> constexpr bool itk::NumericTraits< Vector< T, D > >::IsSigned = std::is_signed<ValueType>::value static constexpr
Definition at line 188 of file itkNumericTraitsVectorPixel.h.
One
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< Vector< T, D > >::One static
Definition at line 240 of file itkNumericTraitsVectorPixel.h.
Zero
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< Vector< T, D > >::Zero static
Note
: the functions are preferred over the member variables as they are defined for all partial specialization
Definition at line 239 of file itkNumericTraitsVectorPixel.h.
The documentation for this class was generated from the following file:
itkNumericTraitsVectorPixel.h