ITK: itk::NumericTraits< FixedArray< T, D > > Class Template Reference
itk::NumericTraits< FixedArray< T, D > > Class Template Reference
Data Representation ObjectsGroup Core » | Module ITKCommon
#include <itkNumericTraitsFixedArrayPixel.h>
Public Types
using AbsType = FixedArray< ElementAbsType, D >
using AccumulateType = FixedArray< ElementAccumulateType, D >
using FloatType = FixedArray< ElementFloatType, D >
using MeasurementVectorType = Self
using PrintType = FixedArray< ElementPrintType, D >
using RealType = FixedArray< ElementRealType, D >
using ScalarRealType = ElementRealType
using Self = FixedArray< T, D >
using ValueType = T
Static Public Member Functions
static void AssignToArray (const Self &v, MeasurementVectorType &mv)
template<typename TArray >
static void AssignToArray (const Self &v, TArray &mv)
static unsigned int GetLength ()
static unsigned int GetLength (const FixedArray< T, D > &)
static const Self max ()
static const Self max (const Self &)
static const Self min ()
static const Self min (const Self &)
static const Self NonpositiveMin ()
static const Self NonpositiveMin (const Self &)
static const Self OneValue ()
static const Self OneValue (const Self &)
static const Self ZeroValue ()
static const Self ZeroValue (const Self &)
static void SetLength (FixedArray< T, D > &m, const unsigned int s)
Static Public Attributes
static const Self ITKCommon_EXPORT One
static const Self ITKCommon_EXPORT Zero
Private Types
using ElementAbsType = typename NumericTraits< T >::AbsType
using ElementAccumulateType = typename NumericTraits< T >::AccumulateType
using ElementFloatType = typename NumericTraits< T >::FloatType
using ElementPrintType = typename NumericTraits< T >::PrintType
using ElementRealType = typename NumericTraits< T >::RealType
Detailed Description
template<typename T, unsigned int D>
class itk::NumericTraits< FixedArray< T, D > >
Define numeric traits for FixedArray.
Template Parameters
T Component type of the FixedArray
D Dimension of the FixedArray
We provide here a generic implementation based on creating types of FixedArray whose components are the types of the NumericTraits from the original FixedArray components. This implementation require support for partial specializations, since it is based on the concept that: NumericTraits<FixedArray< T, D > > is defined piecewise by FixedArray< NumericTraits< T > >
See also
NumericTraits
Definition at line 44 of file itkNumericTraitsFixedArrayPixel.h.
Member Typedef Documentation
AbsType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::AbsType = FixedArray<ElementAbsType, D>
Unsigned component type
Definition at line 60 of file itkNumericTraitsFixedArrayPixel.h.
AccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::AccumulateType = FixedArray<ElementAccumulateType, D>
Accumulation of addition and multiplication.
Definition at line 63 of file itkNumericTraitsFixedArrayPixel.h.
ElementAbsType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::ElementAbsType = typename NumericTraits<T>::AbsType private
Definition at line 47 of file itkNumericTraitsFixedArrayPixel.h.
ElementAccumulateType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::ElementAccumulateType = typename NumericTraits<T>::AccumulateType private
Definition at line 48 of file itkNumericTraitsFixedArrayPixel.h.
ElementFloatType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::ElementFloatType = typename NumericTraits<T>::FloatType private
Definition at line 49 of file itkNumericTraitsFixedArrayPixel.h.
ElementPrintType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::ElementPrintType = typename NumericTraits<T>::PrintType private
Definition at line 50 of file itkNumericTraitsFixedArrayPixel.h.
ElementRealType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::ElementRealType = typename NumericTraits<T>::RealType private
Definition at line 51 of file itkNumericTraitsFixedArrayPixel.h.
FloatType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::FloatType = FixedArray<ElementFloatType, D>
Typedef for operations that use floating point instead of real precision
Definition at line 67 of file itkNumericTraitsFixedArrayPixel.h.
MeasurementVectorType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::MeasurementVectorType = Self
Measurement vector type
Definition at line 79 of file itkNumericTraitsFixedArrayPixel.h.
PrintType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::PrintType = FixedArray<ElementPrintType, D>
Return the type that can be printed.
Definition at line 70 of file itkNumericTraitsFixedArrayPixel.h.
RealType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::RealType = FixedArray<ElementRealType, D>
Type for real-valued scalar operations.
Definition at line 73 of file itkNumericTraitsFixedArrayPixel.h.
ScalarRealType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::ScalarRealType = ElementRealType
Type for real-valued scalar operations.
Definition at line 76 of file itkNumericTraitsFixedArrayPixel.h.
Self
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::Self = FixedArray<T, D>
Definition at line 57 of file itkNumericTraitsFixedArrayPixel.h.
ValueType
template<typename T , unsigned int D> using itk::NumericTraits< FixedArray< T, D > >::ValueType = T
Return the type of the native component type.
Definition at line 55 of file itkNumericTraitsFixedArrayPixel.h.
Member Function Documentation
AssignToArray() [1/2]
template<typename T , unsigned int D> static void itk::NumericTraits< FixedArray< T, D > >::AssignToArray (const Self & v, MeasurementVectorType & mv) inline static
Definition at line 175 of file itkNumericTraitsFixedArrayPixel.h.
AssignToArray() [2/2]
template<typename T , unsigned int D> template<typename TArray > static void itk::NumericTraits< FixedArray< T, D > >::AssignToArray (const Self & v, TArray & mv) inline static
Definition at line 182 of file itkNumericTraitsFixedArrayPixel.h.
GetLength() [1/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< FixedArray< T, D > >::GetLength () inline static
Return the length of the array.
Definition at line 169 of file itkNumericTraitsFixedArrayPixel.h.
GetLength() [2/2]
template<typename T , unsigned int D> static unsigned int itk::NumericTraits< FixedArray< T, D > >::GetLength (const FixedArray< T, D > &) inline static
Return the length of the array.
Definition at line 162 of file itkNumericTraitsFixedArrayPixel.h.
max() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::max () inline static
Definition at line 99 of file itkNumericTraitsFixedArrayPixel.h.
max() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::max (const Self &) inline static
Component wise defined element
Note
minimum value for floating pointer types is defined as minimum positive normalize value.
Definition at line 87 of file itkNumericTraitsFixedArrayPixel.h.
min() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::min () inline static
Definition at line 105 of file itkNumericTraitsFixedArrayPixel.h.
min() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::min (const Self &) inline static
Definition at line 93 of file itkNumericTraitsFixedArrayPixel.h.
NonpositiveMin() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::NonpositiveMin () inline static
Definition at line 111 of file itkNumericTraitsFixedArrayPixel.h.
NonpositiveMin() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::NonpositiveMin (const Self &) inline static
Definition at line 129 of file itkNumericTraitsFixedArrayPixel.h.
References itk::NumericTraits< T >::NonpositiveMin().
OneValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::OneValue () inline static
Definition at line 123 of file itkNumericTraitsFixedArrayPixel.h.
OneValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::OneValue (const Self &) inline static
Definition at line 141 of file itkNumericTraitsFixedArrayPixel.h.
References itk::NumericTraits< T >::OneValue().
SetLength()
template<typename T , unsigned int D> static void itk::NumericTraits< FixedArray< T, D > >::SetLength (FixedArray< T, D > & m, const unsigned int s) inline static
Fixed length vectors cannot be resized, so an exception will be thrown if the input size is not valid. If the size is valid the vector will be filled with zeros.
Definition at line 150 of file itkNumericTraitsFixedArrayPixel.h.
References itk::FixedArray< TValue, VLength >::Fill().
ZeroValue() [1/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::ZeroValue () inline static
Definition at line 117 of file itkNumericTraitsFixedArrayPixel.h.
ZeroValue() [2/2]
template<typename T , unsigned int D> static const Self itk::NumericTraits< FixedArray< T, D > >::ZeroValue (const Self &) inline static
Definition at line 135 of file itkNumericTraitsFixedArrayPixel.h.
References itk::NumericTraits< T >::ZeroValue().
Member Data Documentation
One
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< FixedArray< T, D > >::One static
Definition at line 194 of file itkNumericTraitsFixedArrayPixel.h.
Zero
template<typename T , unsigned int D> const Self ITKCommon_EXPORT itk::NumericTraits< FixedArray< T, D > >::Zero static
Note
: the functions are preferred over the member variables as they are defined for all partial specialization
Definition at line 193 of file itkNumericTraitsFixedArrayPixel.h.
The documentation for this class was generated from the following file:
itkNumericTraitsFixedArrayPixel.h