ITK: itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > > Class Template Reference
itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > > Class Template Reference
#include <itkDefaultConvertPixelTraits.h>
Public Types
using ComponentType = VComponent
using TargetType = VariableSizeMatrix< VComponent >
Static Public Member Functions
static ComponentType GetNthComponent (int i, const TargetType &pixel)
static unsigned int GetNumberOfComponents ()
static unsigned int GetNumberOfComponents (const TargetType pixel)
static ComponentType GetScalarValue (const TargetType &)
static void SetNthComponent (int i, TargetType &pixel, const ComponentType &v)
Detailed Description
template<typename VComponent>
class itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >
Definition at line 250 of file itkDefaultConvertPixelTraits.h.
Member Typedef Documentation
ComponentType
template<typename VComponent > using itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >::ComponentType = VComponent
Definition at line 254 of file itkDefaultConvertPixelTraits.h.
TargetType
template<typename VComponent > using itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >::TargetType = VariableSizeMatrix<VComponent>
Definition at line 253 of file itkDefaultConvertPixelTraits.h.
Member Function Documentation
GetNthComponent()
template<typename VComponent > static ComponentType itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >::GetNthComponent (int i, const TargetType & pixel) inline static
Definition at line 273 of file itkDefaultConvertPixelTraits.h.
References itk::VariableSizeMatrix< T >::Cols().
GetNumberOfComponents() [1/2]
template<typename VComponent > static unsigned int itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >::GetNumberOfComponents () inline static
Definition at line 256 of file itkDefaultConvertPixelTraits.h.
GetNumberOfComponents() [2/2]
template<typename VComponent > static unsigned int itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >::GetNumberOfComponents (const TargetType pixel) inline static
Definition at line 261 of file itkDefaultConvertPixelTraits.h.
References itk::VariableSizeMatrix< T >::Cols(), and itk::VariableSizeMatrix< T >::Rows().
GetScalarValue()
template<typename VComponent > static ComponentType itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >::GetScalarValue (const TargetType &) inline static
Definition at line 280 of file itkDefaultConvertPixelTraits.h.
SetNthComponent()
template<typename VComponent > static void itk::DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >::SetNthComponent (int i, TargetType & pixel, const ComponentType & v) inline static
Definition at line 266 of file itkDefaultConvertPixelTraits.h.
References itk::VariableSizeMatrix< T >::Cols().
The documentation for this class was generated from the following file:
itkDefaultConvertPixelTraits.h