ITK: itk::fftw::Proxy< double > Class Reference
itk::fftw::Proxy< double > Class Reference
#include <itkFFTWCommon.h>
Public Types
using ComplexType = fftw_complex
using PixelType = double
using PlanType = fftw_plan
using Self = Proxy< double >
Static Public Member Functions
static void DestroyPlan (PlanType p)
static void Execute (PlanType p)
static PlanType Plan_dft (int rank, const int *n, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_1d (int n, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_2d (int nx, int ny, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_3d (int nx, int ny, int nz, ComplexType *in, ComplexType *out, int sign, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r (int rank, const int *n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r_1d (int n, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r_2d (int nx, int ny, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType *in, PixelType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c (int rank, const int *n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c_1d (int n, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c_2d (int nx, int ny, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
static PlanType Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType *in, ComplexType *out, unsigned int flags, int threads=1, bool canDestroyInput=false)
Static Public Attributes
static constexpr SizeValueType GREATEST_PRIME_FACTOR = 13
Detailed Description
Definition at line 408 of file itkFFTWCommon.h.
Member Typedef Documentation
ComplexType
using itk::fftw::Proxy< double >::ComplexType = fftw_complex
Definition at line 412 of file itkFFTWCommon.h.
PixelType
using itk::fftw::Proxy< double >::PixelType = double
Definition at line 411 of file itkFFTWCommon.h.
PlanType
using itk::fftw::Proxy< double >::PlanType = fftw_plan
Definition at line 413 of file itkFFTWCommon.h.
Self
using itk::fftw::Proxy< double >::Self = Proxy<double>
Definition at line 414 of file itkFFTWCommon.h.
Member Function Documentation
DestroyPlan()
static void itk::fftw::Proxy< double >::DestroyPlan (PlanType p) inline static
Definition at line 735 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex().
Execute()
static void itk::fftw::Proxy< double >::Execute (PlanType p) inline static
Definition at line 730 of file itkFFTWCommon.h.
Plan_dft()
static PlanType itk::fftw::Proxy< double >::Plan_dft (int rank, const int * n, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 675 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex(), and itk::FFTWGlobalConfiguration::SetNewWisdomAvailable().
Plan_dft_1d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_1d (int n, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 625 of file itkFFTWCommon.h.
Plan_dft_2d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_2d (int nx, int ny, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 637 of file itkFFTWCommon.h.
Plan_dft_3d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_3d (int nx, int ny, int nz, ComplexType * in, ComplexType * out, int sign, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 655 of file itkFFTWCommon.h.
Plan_dft_c2r()
static PlanType itk::fftw::Proxy< double >::Plan_dft_c2r (int rank, const int * n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 471 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex(), and itk::FFTWGlobalConfiguration::SetNewWisdomAvailable().
Plan_dft_c2r_1d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_c2r_1d (int n, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 424 of file itkFFTWCommon.h.
Plan_dft_c2r_2d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_c2r_2d (int nx, int ny, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 435 of file itkFFTWCommon.h.
Plan_dft_c2r_3d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_c2r_3d (int nx, int ny, int nz, ComplexType * in, PixelType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 452 of file itkFFTWCommon.h.
Plan_dft_r2c()
static PlanType itk::fftw::Proxy< double >::Plan_dft_r2c (int rank, const int * n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 572 of file itkFFTWCommon.h.
References itk::FFTWGlobalConfiguration::GetLockMutex(), and itk::FFTWGlobalConfiguration::SetNewWisdomAvailable().
Plan_dft_r2c_1d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_r2c_1d (int n, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 525 of file itkFFTWCommon.h.
Plan_dft_r2c_2d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_r2c_2d (int nx, int ny, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 536 of file itkFFTWCommon.h.
Plan_dft_r2c_3d()
static PlanType itk::fftw::Proxy< double >::Plan_dft_r2c_3d (int nx, int ny, int nz, PixelType * in, ComplexType * out, unsigned int flags, int threads = 1, bool canDestroyInput = false) inline static
Definition at line 553 of file itkFFTWCommon.h.
Member Data Documentation
GREATEST_PRIME_FACTOR
constexpr SizeValueType itk::fftw::Proxy< double >::GREATEST_PRIME_FACTOR = 13 static constexpr
Definition at line 420 of file itkFFTWCommon.h.
The documentation for this class was generated from the following file:
itkFFTWCommon.h