ITK: itk::Functor::LogicOpBase< TInput1, TInput2, TOutput > Class Template Reference
itk::Functor::LogicOpBase< TInput1, TInput2, TOutput > Class Template Reference
Group Filtering » Module ITKImageIntensity
#include <itkLogicOpsFunctors.h>
Public Types
using Self = LogicOpBase
Public Member Functions
TOutput GetBackgroundValue () const
TOutput GetForegroundValue () const
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
LogicOpBase ()
bool operator== (const Self &) const
void SetBackgroundValue (const TOutput &BG)
void SetForegroundValue (const TOutput &FG)
~LogicOpBase ()=default
Protected Attributes
TOutput m_BackgroundValue
TOutput m_ForegroundValue
Detailed Description
template<typename TInput1, typename TInput2 = TInput1, typename TOutput = TInput1>
class itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >
Base class for some logic functors. Provides the Foreground and background setting methods.
The derived classes can be used as follows:
using myFilterType = itk::BinaryFunctorImageFilter< myImageType1, myImageType2, myImageType3, itk::Functor::Equal2<myImageType1::PixelType, myImageType2::PixelType, myImageType3::PixelType> >;
using myFilterTypePointer = myFilterType::Pointer;
myFilterTypePointer filter = myFilterType::New();
filter->SetInput1(inputImageA); filter->SetInput2(inputImageB);
filter->SetConstant1(3.0); filter->SetInput2(inputImageB);
Definition at line 59 of file itkLogicOpsFunctors.h.
Member Typedef Documentation
Self
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> using itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::Self = LogicOpBase
Definition at line 62 of file itkLogicOpsFunctors.h.
Constructor & Destructor Documentation
LogicOpBase()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::LogicOpBase () inline
Definition at line 63 of file itkLogicOpsFunctors.h.
~LogicOpBase()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::~LogicOpBase () default
Member Function Documentation
GetBackgroundValue()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> TOutput itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::GetBackgroundValue () const inline
Definition at line 97 of file itkLogicOpsFunctors.h.
Referenced by itk::NotImageFilter< TInputImage, TOutputImage >::GetBackgroundValue().
GetForegroundValue()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> TOutput itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::GetForegroundValue () const inline
Definition at line 92 of file itkLogicOpsFunctors.h.
Referenced by itk::NotImageFilter< TInputImage, TOutputImage >::GetForegroundValue().
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
operator==()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> bool itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::operator== (const Self &) const inline
Definition at line 73 of file itkLogicOpsFunctors.h.
SetBackgroundValue()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> void itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::SetBackgroundValue (const TOutput & BG) inline
Definition at line 86 of file itkLogicOpsFunctors.h.
Referenced by itk::NotImageFilter< TInputImage, TOutputImage >::NotImageFilter(), and itk::NotImageFilter< TInputImage, TOutputImage >::SetBackgroundValue().
SetForegroundValue()
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> void itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::SetForegroundValue (const TOutput & FG) inline
Definition at line 81 of file itkLogicOpsFunctors.h.
Referenced by itk::NotImageFilter< TInputImage, TOutputImage >::NotImageFilter(), and itk::NotImageFilter< TInputImage, TOutputImage >::SetForegroundValue().
Member Data Documentation
m_BackgroundValue
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> TOutput itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::m_BackgroundValue protected
Definition at line 104 of file itkLogicOpsFunctors.h.
m_ForegroundValue
template<typename TInput1 , typename TInput2 = TInput1, typename TOutput = TInput1> TOutput itk::Functor::LogicOpBase< TInput1, TInput2, TOutput >::m_ForegroundValue protected
Definition at line 103 of file itkLogicOpsFunctors.h.
The documentation for this class was generated from the following file:
itkLogicOpsFunctors.h