ITK: itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor Class Reference
itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor Class Reference
Group Core » Module ITKMesh
#include <itkSimplexMeshVolumeCalculator.h>
Public Member Functions
PointMapPointer GetCenterMap ()
void SetMesh (InputMeshPointer mesh)
SimplexCellVisitor ()
virtual ~SimplexCellVisitor ()=default
void Visit (IdentifierType cellId, SimplexPolygonType *poly)
Protected Attributes
PointMapPointer m_CenterMap
InputMeshPointer m_Mesh
Detailed Description
template<typename TInputMesh>
class itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor
This class provides methods for visiting each simplex cell of a simplex mesh It computes the center of each visited cell.
Definition at line 107 of file itkSimplexMeshVolumeCalculator.h.
Constructor & Destructor Documentation
SimplexCellVisitor()
template<typename TInputMesh > itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::SimplexCellVisitor () inline
default constructor
Definition at line 114 of file itkSimplexMeshVolumeCalculator.h.
References New().
~SimplexCellVisitor()
template<typename TInputMesh > virtual itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::~SimplexCellVisitor () virtual default
default constructor
Member Function Documentation
GetCenterMap()
template<typename TInputMesh > PointMapPointer itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::GetCenterMap () inline
Definition at line 146 of file itkSimplexMeshVolumeCalculator.h.
SetMesh()
template<typename TInputMesh > void itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::SetMesh (InputMeshPointer mesh) inline
Definition at line 152 of file itkSimplexMeshVolumeCalculator.h.
Visit()
template<typename TInputMesh > void itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::Visit (IdentifierType cellId, SimplexPolygonType * poly) inline
visits all polygon cells and compute the cell centers
Definition at line 122 of file itkSimplexMeshVolumeCalculator.h.
References itk::PolygonCell< TCellInterface >::GetNumberOfPoints(), itk::PolygonCell< TCellInterface >::PointIdsBegin(), and itk::PolygonCell< TCellInterface >::PointIdsEnd().
Member Data Documentation
m_CenterMap
template<typename TInputMesh > PointMapPointer itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::m_CenterMap protected
Definition at line 159 of file itkSimplexMeshVolumeCalculator.h.
m_Mesh
template<typename TInputMesh > InputMeshPointer itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::m_Mesh protected
Definition at line 158 of file itkSimplexMeshVolumeCalculator.h.
The documentation for this class was generated from the following file:
itkSimplexMeshVolumeCalculator.h