ITK: itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition > Class Template Reference
itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition > Class Template Reference
Data Access Objects » Iterators » Image IteratorsGroup Core » | Module ITKCommon
#include <itkConstNeighborhoodIterator.h>
Public Types
using BoundaryConditionType = TBoundaryCondition
using ConstIterator = typename AllocatorType::const_iterator
using DimensionValueType = unsigned int
using ImageBoundaryConditionConstPointerType = const ImageBoundaryCondition< ImageType, OutputImageType > *
using ImageBoundaryConditionPointerType = ImageBoundaryCondition< ImageType, OutputImageType > *
using ImageType = TImage
using IndexType = Index< Self::Dimension >
using InternalPixelType = typename TImage::InternalPixelType
using Iterator = typename AllocatorType::iterator
using NeighborhoodAccessorFunctorType = typename ImageType::NeighborhoodAccessorFunctorType
using NeighborhoodType = Neighborhood< PixelType, Self::Dimension >
using NeighborIndexType = typename NeighborhoodType::NeighborIndexType
using OffsetType = Offset< VDimension >
using OutputImageType = typename BoundaryConditionType::OutputImageType
using PixelType = typename TImage::PixelType
using RadiusType = itk::Size< VDimension >
using RegionType = typename TImage::RegionType
using Self = ConstNeighborhoodIterator
using SizeType = itk::Size< VDimension >
using Superclass = Neighborhood< InternalPixelType *, Self::Dimension >
Public Types inherited from itk::Neighborhood< TImage::InternalPixelType *, TImage::ImageDimension >
using AllocatorType = NeighborhoodAllocator< TImage::InternalPixelType * >
using ConstIterator = typename AllocatorType::const_iterator
using DimensionValueType = unsigned int
using Iterator = typename AllocatorType::iterator
using NeighborIndexType = SizeValueType
using OffsetType = Offset< VDimension >
using PixelType = TImage::InternalPixelType *
using RadiusType = itk::Size< VDimension >
using Self = Neighborhood
using SizeType = itk::Size< VDimension >
using SizeValueType = typename SizeType::SizeValueType
using SliceIteratorType = SliceIterator< TImage::InternalPixelType *, Self >
Public Member Functions
OffsetType ComputeInternalIndex (const NeighborIndexType n) const
ConstNeighborhoodIterator ()
ConstNeighborhoodIterator (const ConstNeighborhoodIterator &)
IndexType GetBeginIndex () const
IndexType GetBound () const
IndexValueType GetBound (NeighborIndexType n) const
ImageBoundaryConditionPointerType GetBoundaryCondition () const
RegionType GetBoundingBoxAsImageRegion () const
PixelType GetCenterPixel () const
const InternalPixelType * GetCenterPointer () const
IndexType GetFastIndexPlusOffset (const OffsetType &o) const
const ImageType * GetImagePointer () const
ITK_ITERATOR_VIRTUAL IndexType GetIndex () const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL IndexType GetIndex (const OffsetType &o) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL IndexType GetIndex (NeighborIndexType i) const ITK_ITERATOR_FINAL
bool GetNeedToUseBoundaryCondition () const
ITK_ITERATOR_VIRTUAL NeighborhoodType GetNeighborhood () const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetNext (const unsigned int axis) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetNext (const unsigned int axis, NeighborIndexType i) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetPixel (const NeighborIndexType i) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetPixel (const OffsetType &o) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetPixel (const OffsetType &o, bool &IsInBounds) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetPixel (NeighborIndexType i, bool &IsInBounds) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetPrevious (const unsigned int axis) const ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL PixelType GetPrevious (const unsigned int axis, NeighborIndexType i) const ITK_ITERATOR_FINAL
RegionType GetRegion () const
OffsetType GetWrapOffset () const
OffsetValueType GetWrapOffset (NeighborIndexType n) const
ITK_ITERATOR_VIRTUAL void GoToBegin () ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL void GoToEnd () ITK_ITERATOR_FINAL
bool InBounds () const
bool IndexInBounds (const NeighborIndexType n) const
bool IndexInBounds (const NeighborIndexType n, OffsetType &internalIndex, OffsetType &offset) const
ITK_ITERATOR_VIRTUAL void Initialize (const SizeType &radius, const ImageType *ptr, const RegionType &region) ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL bool IsAtBegin () const ITK_ITERATOR_FINAL
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
void NeedToUseBoundaryConditionOff ()
void NeedToUseBoundaryConditionOn ()
Self & operator++ ()
Self & operator+= (const OffsetType &)
OffsetType operator- (const Self &b)
Self & operator-- ()
Self & operator-= (const OffsetType &)
bool operator< (const Self &it) const
bool operator<= (const Self &it) const
Self & operator= (const Self &orig)
bool operator== (const Self &it) const
bool operator> (const Self &it) const
bool operator>= (const Self &it) const
ITK_ITERATOR_VIRTUAL void OverrideBoundaryCondition (const ImageBoundaryConditionPointerType i) ITK_ITERATOR_FINAL
void PrintSelf (std::ostream &, Indent) const override
ITK_ITERATOR_VIRTUAL void ResetBoundaryCondition () ITK_ITERATOR_FINAL
void SetBoundaryCondition (const TBoundaryCondition &c)
void SetNeedToUseBoundaryCondition (bool b)
ITK_ITERATOR_VIRTUAL void SetRegion (const RegionType &region) ITK_ITERATOR_FINAL
~ConstNeighborhoodIterator () override=default
ConstNeighborhoodIterator (const SizeType &radius, const ImageType *ptr, const RegionType &region)
ITK_ITERATOR_VIRTUAL bool IsAtEnd () const ITK_ITERATOR_FINAL
void SetLocation (const IndexType &position)
Public Member Functions inherited from itk::Neighborhood< TImage::InternalPixelType *, TImage::ImageDimension >
NeighborIndexType GetCenterNeighborhoodIndex () const
TImage::InternalPixelType * GetCenterValue () const
virtual NeighborIndexType GetNeighborhoodIndex (const OffsetType &) const
OffsetType GetOffset (NeighborIndexType i) const
const SizeType GetRadius () const
SizeValueType GetRadius (DimensionValueType n) const
SizeType GetSize () const
SizeValueType GetSize (DimensionValueType n) const
std::slice GetSlice (unsigned int) const
OffsetValueType GetStride (DimensionValueType axis) const
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
itkTypeMacroNoParent (Neighborhood)
Neighborhood ()=default
Neighborhood (const Self &)=default
Neighborhood (Self &&)=default
Self & operator= (const Self &)=default
Self & operator= (Self &&)=default
bool operator== (const Self &other) const
void Print (std::ostream &os) const
void SetRadius (const SizeType &)
void SetRadius (const SizeValueType)
NeighborIndexType Size () const
virtual ~Neighborhood ()=default
Iterator End ()
ConstIterator End () const
Iterator Begin ()
ConstIterator Begin () const
TImage::InternalPixelType * & operator[] (NeighborIndexType i)
const TImage::InternalPixelType * & operator[] (NeighborIndexType i) const
TImage::InternalPixelType * & GetElement (NeighborIndexType i)
TImage::InternalPixelType * & operator[] (const OffsetType &o)
const TImage::InternalPixelType * & operator[] (const OffsetType &o) const
void SetRadius (const SizeValueType *rad)
AllocatorType & GetBufferReference ()
const AllocatorType & GetBufferReference () const
Static Public Attributes
static constexpr DimensionValueType Dimension = TImage::ImageDimension
Static Public Attributes inherited from itk::Neighborhood< TImage::InternalPixelType *, TImage::ImageDimension >
static constexpr unsigned int NeighborhoodDimension
Protected Member Functions
ITK_ITERATOR_VIRTUAL void SetBeginIndex (const IndexType &start) ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL void SetBound (const SizeType &) ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL void SetEndIndex () ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL void SetLoop (const IndexType &p) ITK_ITERATOR_FINAL
ITK_ITERATOR_VIRTUAL void SetPixelPointers (const IndexType &) ITK_ITERATOR_FINAL
Protected Member Functions inherited from itk::Neighborhood< TImage::InternalPixelType *, TImage::ImageDimension >
virtual void Allocate (NeighborIndexType i)
virtual void ComputeNeighborhoodOffsetTable ()
virtual void ComputeNeighborhoodStrideTable ()
void SetSize ()
Protected Attributes
const InternalPixelType * m_Begin { nullptr }
IndexType m_BeginIndex { { 0 } }
IndexType m_Bound { { 0 } }
ImageBoundaryConditionPointerType m_BoundaryCondition
ImageType::ConstWeakPointer m_ConstImage
const InternalPixelType * m_End { nullptr }
IndexType m_EndIndex { { 0 } }
bool m_InBounds [Dimension] { false }
IndexType m_InnerBoundsHigh
IndexType m_InnerBoundsLow
TBoundaryCondition m_InternalBoundaryCondition
bool m_IsInBounds { false }
bool m_IsInBoundsValid { false }
IndexType m_Loop { { 0 } }
bool m_NeedToUseBoundaryCondition { false }
NeighborhoodAccessorFunctorType m_NeighborhoodAccessorFunctor
RegionType m_Region
OffsetType m_WrapOffset { { 0 } }
Detailed Description
template<typename TImage, typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>>
class itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >
Const version of NeighborhoodIterator, defining iteration of a local N-dimensional neighborhood of pixels across an itk::Image.
ConstNeighborhoodIterator implements the read-only methods of NeighborhoodIterator. It serves as a base class from which other iterators are derived. See NeighborhoodIterator for more complete information.
See also
Neighborhood
ImageIterator
NeighborhoodIterator
ShapedImageNeighborhoodRange
ITK Sphinx Examples:
All ITK Sphinx Examples
Iterate Region In Image With Neighborhood Without Write Access
Definition at line 51 of file itkConstNeighborhoodIterator.h.
Member Typedef Documentation
BoundaryConditionType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::BoundaryConditionType = TBoundaryCondition
Typedef for boundary condition type.
Definition at line 84 of file itkConstNeighborhoodIterator.h.
ConstIterator
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::ConstIterator = typename AllocatorType::const_iterator
Definition at line 76 of file itkNeighborhood.h.
DimensionValueType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::DimensionValueType = unsigned int
Type used to refer to space dimensions
Definition at line 60 of file itkConstNeighborhoodIterator.h.
ImageBoundaryConditionConstPointerType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ImageBoundaryConditionConstPointerType = const ImageBoundaryCondition<ImageType, OutputImageType> *
Definition at line 98 of file itkConstNeighborhoodIterator.h.
ImageBoundaryConditionPointerType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ImageBoundaryConditionPointerType = ImageBoundaryCondition<ImageType, OutputImageType> *
Typedef for generic boundary condition pointer
Definition at line 97 of file itkConstNeighborhoodIterator.h.
ImageType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ImageType = TImage
Typedef support for common objects
Definition at line 77 of file itkConstNeighborhoodIterator.h.
IndexType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::IndexType = Index<Self::Dimension>
Definition at line 79 of file itkConstNeighborhoodIterator.h.
InternalPixelType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::InternalPixelType = typename TImage::InternalPixelType
Extract image type information.
Definition at line 56 of file itkConstNeighborhoodIterator.h.
Iterator
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::Iterator = typename AllocatorType::iterator
Iterator type alias support Note the naming is intentional, i.e., AllocatorType::iterator and AllocatorType::const_iterator, because the allocator may be a vnl object or other type, which uses this form.
Definition at line 75 of file itkNeighborhood.h.
NeighborhoodAccessorFunctorType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::NeighborhoodAccessorFunctorType = typename ImageType::NeighborhoodAccessorFunctorType
Typedef for the functor used to access neighborhoods of pixel pointers. This is obtained as a trait from the image and is different for Image and VectorImage.
Definition at line 94 of file itkConstNeighborhoodIterator.h.
NeighborhoodType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::NeighborhoodType = Neighborhood<PixelType, Self::Dimension>
Definition at line 80 of file itkConstNeighborhoodIterator.h.
NeighborIndexType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::NeighborIndexType = typename NeighborhoodType::NeighborIndexType
Type used to refer to the elements in the list of neighbor pixels.
Definition at line 89 of file itkConstNeighborhoodIterator.h.
OffsetType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::OffsetType = Offset<VDimension>
Offset type used to reference neighbor locations
Definition at line 86 of file itkNeighborhood.h.
OutputImageType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::OutputImageType = typename BoundaryConditionType::OutputImageType
Definition at line 86 of file itkConstNeighborhoodIterator.h.
PixelType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::PixelType = typename TImage::PixelType
Definition at line 57 of file itkConstNeighborhoodIterator.h.
RadiusType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::RadiusType = itk::Size<VDimension>
Radius type alias support
Definition at line 83 of file itkNeighborhood.h.
RegionType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::RegionType = typename TImage::RegionType
Definition at line 78 of file itkConstNeighborhoodIterator.h.
Self
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::Self = ConstNeighborhoodIterator
Standard class type aliases.
Definition at line 66 of file itkConstNeighborhoodIterator.h.
SizeType
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::Neighborhood< TPixel, VDimension, TAllocator >::SizeType = itk::Size<VDimension>
Size and value type alias support
Definition at line 79 of file itkNeighborhood.h.
Superclass
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> using itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::Superclass = Neighborhood<InternalPixelType *, Self::Dimension>
Definition at line 67 of file itkConstNeighborhoodIterator.h.
Constructor & Destructor Documentation
ConstNeighborhoodIterator() [1/3]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ConstNeighborhoodIterator ()
Default constructor
~ConstNeighborhoodIterator()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::~ConstNeighborhoodIterator () override default
Virtual destructor
ConstNeighborhoodIterator() [2/3]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ConstNeighborhoodIterator (const ConstNeighborhoodIterator< TImage, TBoundaryCondition > &)
Copy constructor
ConstNeighborhoodIterator() [3/3]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ConstNeighborhoodIterator (const SizeType & radius, const ImageType * ptr, const RegionType & region) inline
Constructor which establishes the region size, neighborhood, and image over which to walk.
Definition at line 111 of file itkConstNeighborhoodIterator.h.
Member Function Documentation
ComputeInternalIndex()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> OffsetType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ComputeInternalIndex (const NeighborIndexType n) const
Computes the internal, N-d offset of a pixel array position n from (0,0, ..., 0) in the "upper-left" corner of the neighborhood.
GetBeginIndex()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetBeginIndex () const inline
Returns the N-dimensional starting index of the iterator's position on the image.
Definition at line 301 of file itkConstNeighborhoodIterator.h.
GetBound() [1/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetBound () const inline
Returns the array of upper loop bounds used during iteration.
Definition at line 139 of file itkConstNeighborhoodIterator.h.
GetBound() [2/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexValueType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetBound (NeighborIndexType n) const inline
Returns the loop bound used to define the edge of a single dimension in the itk::Image region.
Definition at line 147 of file itkConstNeighborhoodIterator.h.
GetBoundaryCondition()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ImageBoundaryConditionPointerType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetBoundaryCondition () const inline
Definition at line 515 of file itkConstNeighborhoodIterator.h.
GetBoundingBoxAsImageRegion()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> RegionType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetBoundingBoxAsImageRegion () const
Returns a bounding box for the region spanned by this neighborhood represented by an itk::ImageRegion
GetCenterPixel()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetCenterPixel () const inline
Returns the pixel referenced at the center of the ConstNeighborhoodIterator.
Definition at line 162 of file itkConstNeighborhoodIterator.h.
GetCenterPointer()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> const InternalPixelType* itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetCenterPointer () const inline
Returns the pointer to the center pixel of the neighborhood.
Definition at line 154 of file itkConstNeighborhoodIterator.h.
Referenced by itk::ConstNeighborhoodIterator< TSparseImageType >::operator<(), itk::ConstNeighborhoodIterator< TSparseImageType >::operator<=(), itk::ConstNeighborhoodIterator< TSparseImageType >::operator==(), itk::ConstNeighborhoodIterator< TSparseImageType >::operator>(), and itk::ConstNeighborhoodIterator< TSparseImageType >::operator>=().
GetFastIndexPlusOffset()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetFastIndexPlusOffset (const OffsetType & o) const inline
Definition at line 183 of file itkConstNeighborhoodIterator.h.
GetImagePointer()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> const ImageType* itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetImagePointer () const inline
Returns a smartpointer to the image on which this iterator operates.
Definition at line 169 of file itkConstNeighborhoodIterator.h.
GetIndex() [1/3]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetIndex () const inline
Returns the N-dimensional index of the iterator's position in the image.
Definition at line 177 of file itkConstNeighborhoodIterator.h.
GetIndex() [2/3]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetIndex (const OffsetType & o) const inline
Returns the image index for neighbor pixel at offset o from the center of the neighborhood.
Definition at line 278 of file itkConstNeighborhoodIterator.h.
GetIndex() [3/3]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetIndex (NeighborIndexType i) const inline
Returns the image index for neighbor pixel at index i in the neighborhood.
Definition at line 286 of file itkConstNeighborhoodIterator.h.
GetNeedToUseBoundaryCondition()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetNeedToUseBoundaryCondition () const inline
Definition at line 540 of file itkConstNeighborhoodIterator.h.
GetNeighborhood()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL NeighborhoodType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetNeighborhood () const
Function that "dereferences" a ConstNeighborhoodIterator, returning a Neighborhood of pixel values.
GetNext() [1/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetNext (const unsigned int axis) const inline
Returns the pixel value located one pixel distant from the neighborhood center in the specified positive axis direction. No bounds checking is done on the size of the neighborhood.
Definition at line 252 of file itkConstNeighborhoodIterator.h.
GetNext() [2/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetNext (const unsigned int axis, NeighborIndexType i) const inline
Returns the pixel value located i pixels distant from the neighborhood center in the positive specified "axis" direction. No bounds checking is done on the size of the neighborhood.
Definition at line 243 of file itkConstNeighborhoodIterator.h.
Referenced by itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >::EvaluateAtNeighborhood(), itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >::EvaluateAtNeighborhood3D(), and itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >::NonPCEvaluateAtNeighborhood().
GetPixel() [1/4]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetPixel (const NeighborIndexType i) const inline
Returns the pixel value located at a linear array location i.
Definition at line 195 of file itkConstNeighborhoodIterator.h.
GetPixel() [2/4]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetPixel (const OffsetType & o) const inline
Returns the pixel value located at the itk::Offset o from the center of the neighborhood.
Definition at line 221 of file itkConstNeighborhoodIterator.h.
GetPixel() [3/4]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetPixel (const OffsetType & o, bool & IsInBounds) const inline
Returns the pixel value located at the itk::Offset o from the center of the neighborhood. Sets "IsInBounds" to true if the offset is inside the image and the pixel value returned is an actual pixel in the image. Sets "IsInBounds" to false if the offset is outside the image and the pixel value returned is a boundary condition.
Definition at line 234 of file itkConstNeighborhoodIterator.h.
GetPixel() [4/4]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetPixel (NeighborIndexType i, bool & IsInBounds) const
Return the pixel value located at a linear array location i. Sets "IsInBounds" to true if the location is inside the image and the pixel value returned is an actual pixel in the image. Sets "IsInBounds" to false if the location is outside the image and the pixel value returned is a boundary condition.
GetPrevious() [1/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetPrevious (const unsigned int axis) const inline
Returns the pixel value located one pixel distant from the neighborhood center in the specified negative axis direction. No bounds checking is done on the size of the neighborhood.
Definition at line 270 of file itkConstNeighborhoodIterator.h.
GetPrevious() [2/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL PixelType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetPrevious (const unsigned int axis, NeighborIndexType i) const inline
Returns the pixel value located i pixels distant from the neighborhood center in the negative specified "axis" direction. No bounds checking is done on the size of the neighborhood.
Definition at line 261 of file itkConstNeighborhoodIterator.h.
Referenced by itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >::EvaluateAtNeighborhood(), itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >::EvaluateAtNeighborhood3D(), and itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >::NonPCEvaluateAtNeighborhood().
GetRegion()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> RegionType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetRegion () const inline
Returns the region of iteration.
Definition at line 293 of file itkConstNeighborhoodIterator.h.
GetWrapOffset() [1/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> OffsetType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetWrapOffset () const inline
Returns the offsets used to wrap across dimensional boundaries.
Definition at line 313 of file itkConstNeighborhoodIterator.h.
GetWrapOffset() [2/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> OffsetValueType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GetWrapOffset (NeighborIndexType n) const inline
Returns the internal offset associated with wrapping around a single dimension's region boundary in the itk::Image. An offset for each dimension is necessary to shift pointers when wrapping around region edges because region memory is not necessarily contiguous within the buffer.
Definition at line 324 of file itkConstNeighborhoodIterator.h.
GoToBegin()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GoToBegin ()
Method for rewinding the iterator to its beginning pixel.
Referenced by itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::Begin().
GoToEnd()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GoToEnd ()
Method for sending the iterator to one past the last pixel in its region.
Referenced by itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::End().
InBounds()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::InBounds () const
Returns false if the iterator overlaps region boundaries, true otherwise. Also updates an internal boolean array indicating which of the iterator's faces are out of bounds.
IndexInBounds() [1/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::IndexInBounds (const NeighborIndexType n) const
Returns true if the neighborhood index is within region boundaries, false otherwise.
IndexInBounds() [2/2]
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::IndexInBounds (const NeighborIndexType n, OffsetType & internalIndex, OffsetType & offset) const
Returns true if the neighborhood index is within region boundaries, false otherwise. If false, then internalIndex and offset are calculated. Otherwise their values are left unchanged. Also updates an internal boolean array indicating which of the iterator's faces are out of bounds.
Parameters
n - linear neighborhood index.
internalIndex - calculated for index n only when the neighborhood is not completely within region boundaries.
offset - per-dimension offsets for index n to nearest boundary index, calculate only when the neighborhood is not completely within region boundaries.
Initialize()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::Initialize (const SizeType & radius, const ImageType * ptr, const RegionType & region)
Initializes the iterator to walk a particular image and a particular region of that image.
IsAtBegin()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::IsAtBegin () const inline
Method for determining whether the iterator is at the beginning of its iteration region.
Definition at line 346 of file itkConstNeighborhoodIterator.h.
IsAtEnd()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::IsAtEnd () const inline
Method for determining whether the iterator has reached the end of its iteration region.
Definition at line 354 of file itkConstNeighborhoodIterator.h.
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
NeedToUseBoundaryConditionOff()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::NeedToUseBoundaryConditionOff () inline
Definition at line 528 of file itkConstNeighborhoodIterator.h.
NeedToUseBoundaryConditionOn()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::NeedToUseBoundaryConditionOn () inline
Definition at line 522 of file itkConstNeighborhoodIterator.h.
operator++()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> Self& itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator++ ()
Increments the pointers in the ConstNeighborhoodIterator, wraps across boundaries automatically, accounting for the disparity in the buffer size and the region size of the image.
operator+=()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> Self& itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator+= (const OffsetType &)
Addition of an itk::Offset. Note that this method does not do any bounds checking. Adding an offset that moves the iterator out of its assigned region will produce undefined results.
operator-()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> OffsetType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator- (const Self & b) inline
Distance between two iterators
Definition at line 457 of file itkConstNeighborhoodIterator.h.
operator--()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> Self& itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator-- ()
Decrements the pointers in the ConstNeighborhoodIterator, wraps across boundaries automatically, accounting for the disparity in the buffer size and the region size of the image.
operator-=()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> Self& itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator-= (const OffsetType &)
Subtraction of an itk::Offset. Note that this method does not do any bounds checking. Subtracting an offset that moves the iterator out of its assigned region will produce undefined results.
operator<()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator< (const Self & it) const inline
Returns a boolean < comparison of the memory addresses of the center elements of two ConstNeighborhoodIterators of like pixel type and dimensionality. The radii of the iterators are ignored.
Definition at line 399 of file itkConstNeighborhoodIterator.h.
operator<=()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator<= (const Self & it) const inline
Returns a boolean < comparison of the memory addresses of the center elements of two ConstNeighborhoodIterators of like pixel type and dimensionality. The radii of the iterators are ignored.
Definition at line 408 of file itkConstNeighborhoodIterator.h.
operator=()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> Self& itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator= (const Self & orig)
Assignment operator
operator==()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator== (const Self & it) const inline
Returns a boolean == comparison of the memory addresses of the center elements of two ConstNeighborhoodIterators of like pixel type and dimensionality. The radii of the iterators are ignored.
Definition at line 388 of file itkConstNeighborhoodIterator.h.
operator>()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator> (const Self & it) const inline
Returns a boolean > comparison of the memory addresses of the center elements of two ConstNeighborhoodIterators of like pixel type and dimensionality. The radii of the iterators are ignored.
Definition at line 417 of file itkConstNeighborhoodIterator.h.
operator>=()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::operator>= (const Self & it) const inline
Returns a boolean >= comparison of the memory addresses of the center elements of two ConstNeighborhoodIterators of like pixel type and dimensionality. The radii of the iterators are ignored.
Definition at line 426 of file itkConstNeighborhoodIterator.h.
OverrideBoundaryCondition()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::OverrideBoundaryCondition (const ImageBoundaryConditionPointerType i) inline
Allows a user to override the internal boundary condition. Care should be taken to ensure that the overriding boundary condition is a persistent object during the time it is referenced. The overriding condition can be of a different type than the default type as long as it is a subclass of ImageBoundaryCondition.
Definition at line 493 of file itkConstNeighborhoodIterator.h.
PrintSelf()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::PrintSelf (std::ostream & , Indent) const override virtual
Standard itk print method
Reimplemented from itk::Neighborhood< TImage::InternalPixelType *, TImage::ImageDimension >.
Reimplemented in itk::ConstShapedNeighborhoodIterator< TImage, ZeroFluxNeumannBoundaryCondition< TImage > >, itk::ConstShapedNeighborhoodIterator< ImageType, ZeroFluxNeumannBoundaryCondition< ImageType > >, itk::NeighborhoodIterator< TImage, ZeroFluxNeumannBoundaryCondition< TImage > >, itk::NeighborhoodIterator< ImageType, ZeroFluxNeumannBoundaryCondition< ImageType > >, and itk::ShapedNeighborhoodIterator< ImageType >.
ResetBoundaryCondition()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::ResetBoundaryCondition () inline
Resets the boundary condition to the internal, default conditions specified by the template parameter.
Definition at line 501 of file itkConstNeighborhoodIterator.h.
SetBeginIndex()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetBeginIndex (const IndexType & start) inline protected
Default method for setting the index of the first pixel in the iteration region.
Definition at line 575 of file itkConstNeighborhoodIterator.h.
SetBound()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetBound (const SizeType &) protected
Method for setting internal loop boundaries. This method must be defined in each subclass because each subclass may handle loop boundaries differently.
SetBoundaryCondition()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetBoundaryCondition (const TBoundaryCondition & c) inline
Sets the internal, default boundary condition.
Definition at line 508 of file itkConstNeighborhoodIterator.h.
SetEndIndex()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetEndIndex () protected
Default method for setting the index of the first pixel in the iteration region.
SetLocation()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetLocation (const IndexType & position) inline
This method positions the iterator at an indexed location in the image. SetLocation should NOT be used to update the position of the iterator during iteration, only for initializing it to a position prior to iteration. This method is not optimized for speed.
Definition at line 436 of file itkConstNeighborhoodIterator.h.
SetLoop()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetLoop (const IndexType & p) inline protected
Default method for setting the coordinate location of the iterator. Loop indices correspond to the actual Image region index.
Definition at line 553 of file itkConstNeighborhoodIterator.h.
SetNeedToUseBoundaryCondition()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetNeedToUseBoundaryCondition (bool b) inline
Definition at line 534 of file itkConstNeighborhoodIterator.h.
SetPixelPointers()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetPixelPointers (const IndexType &) protected
Default method for setting the values of the internal pointers to itk::Image memory buffer locations. This method should generally only be called when the iterator is initialized.
See also
SetLocation
SetRegion()
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ITK_ITERATOR_VIRTUAL void itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::SetRegion (const RegionType & region)
Set the region to iterate over.
Member Data Documentation
Dimension
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> constexpr DimensionValueType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::Dimension = TImage::ImageDimension static constexpr
Save the image dimension.
Definition at line 63 of file itkConstNeighborhoodIterator.h.
m_Begin
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> const InternalPixelType* itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_Begin { nullptr } protected
A pointer to the first pixel in the iteration region.
Definition at line 593 of file itkConstNeighborhoodIterator.h.
m_BeginIndex
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_BeginIndex { { 0 } } protected
The starting index for iteration within the itk::Image region on which this ConstNeighborhoodIterator is defined.
Definition at line 587 of file itkConstNeighborhoodIterator.h.
m_Bound
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_Bound { { 0 } } protected
An array of upper looping boundaries used during iteration.
Definition at line 590 of file itkConstNeighborhoodIterator.h.
m_BoundaryCondition
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ImageBoundaryConditionPointerType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_BoundaryCondition protected
Pointer to the actual boundary condition that will be used. By default this points to m_BoundaryCondition, but OverrideBoundaryCondition allows a user to point this variable an external boundary condition.
Definition at line 622 of file itkConstNeighborhoodIterator.h.
m_ConstImage
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> ImageType::ConstWeakPointer itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_ConstImage protected
The image on which iteration is defined.
Definition at line 596 of file itkConstNeighborhoodIterator.h.
m_End
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> const InternalPixelType* itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_End { nullptr } protected
A pointer to one past the last pixel in the iteration region.
Definition at line 599 of file itkConstNeighborhoodIterator.h.
m_EndIndex
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_EndIndex { { 0 } } protected
The end index for iteration within the itk::Image region on which this ConstNeighborhoodIterator is defined.
Definition at line 603 of file itkConstNeighborhoodIterator.h.
m_InBounds
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_InBounds[Dimension] { false } mutable protected
Denotes which of the iterators dimensional sides spill outside region of interest boundaries. By default false for each dimension.
Definition at line 626 of file itkConstNeighborhoodIterator.h.
m_InnerBoundsHigh
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_InnerBoundsHigh protected
Upper threshold of in-bounds loop counter values.
Definition at line 640 of file itkConstNeighborhoodIterator.h.
m_InnerBoundsLow
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_InnerBoundsLow protected
Lower threshold of in-bounds loop counter values.
Definition at line 637 of file itkConstNeighborhoodIterator.h.
m_InternalBoundaryCondition
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> TBoundaryCondition itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_InternalBoundaryCondition protected
Default boundary condition.
Definition at line 643 of file itkConstNeighborhoodIterator.h.
m_IsInBounds
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_IsInBounds { false } mutable protected
Denotes if iterator is entirely within bounds
Definition at line 629 of file itkConstNeighborhoodIterator.h.
m_IsInBoundsValid
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_IsInBoundsValid { false } mutable protected
Is the m_InBounds and m_IsInBounds variables up to date? Set to false whenever the iterator is repositioned. Set to true within InBounds().
Definition at line 634 of file itkConstNeighborhoodIterator.h.
m_Loop
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> IndexType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_Loop { { 0 } } protected
Array of loop counters used during iteration.
Definition at line 606 of file itkConstNeighborhoodIterator.h.
Referenced by itk::ConstNeighborhoodIterator< TSparseImageType >::operator-().
m_NeedToUseBoundaryCondition
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> bool itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_NeedToUseBoundaryCondition { false } protected
Does the specified region need to worry about boundary conditions?
Definition at line 646 of file itkConstNeighborhoodIterator.h.
m_NeighborhoodAccessorFunctor
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> NeighborhoodAccessorFunctorType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_NeighborhoodAccessorFunctor protected
Functor type used to access neighborhoods of pixel pointers
Definition at line 649 of file itkConstNeighborhoodIterator.h.
m_Region
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> RegionType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_Region protected
The region over which iteration is defined.
Definition at line 609 of file itkConstNeighborhoodIterator.h.
m_WrapOffset
template<typename TImage , typename TBoundaryCondition = ZeroFluxNeumannBoundaryCondition<TImage>> OffsetType itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::m_WrapOffset { { 0 } } protected
The internal array of offsets that provide support for regions of interest. An offset for each dimension is necessary to shift pointers when wrapping around region edges because region memory is not necessarily contiguous within the buffer.
Definition at line 616 of file itkConstNeighborhoodIterator.h.
The documentation for this class was generated from the following file:
itkConstNeighborhoodIterator.h