ITK: itk::MetaArrayReader Class Reference
itk::MetaArrayReader Class Reference
#include <itkMetaArrayReader.h>
Public Types
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = MetaArrayReader
using Superclass = LightProcessObject
Public Types inherited from itk::LightProcessObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightProcessObject
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
int GetCovariantVectorDimension () const
MET_ValueEnumType GetDataType () const
template<typename TValue >
void GetElement (TValue &value, unsigned int i, unsigned int channel=0) const
virtual const char * GetFileName () const
MetaArray * GetMetaArrayPointer ()
virtual const char * GetNameOfClass () const
int GetNumberOfComponents () const
int GetNumberOfElements () const
int GetVectorDimension () const
void SetBuffer (void *_buffer)
virtual void SetFileName (const char *_arg)
int Size () const
void Update ()
template<typename TValue >
void GetOutput (MET_ValueEnumType _metaElementType, Array< TValue > *_array, bool _letArrayManageData=true)
template<typename TValue , unsigned int VLength>
bool GetOutput (MET_ValueEnumType, FixedArray< TValue, VLength > *_array)
template<typename TValue , unsigned int VLength>
bool GetOutput (MET_ValueEnumType, Vector< TValue, VLength > *_vector)
template<typename TValue , unsigned int VLength>
bool GetOutput (MET_ValueEnumType, CovariantVector< TValue, VLength > *_vector)
template<typename TValue >
void GetOutput (MET_ValueEnumType _metaElementType, VariableLengthVector< TValue > *_vector, bool _letVectorManageData=true)
template<typename TValue >
void GetMultiChannelOutput (MET_ValueEnumType _metaElementType, Array< TValue > *_array)
Public Member Functions inherited from itk::LightProcessObject
virtual void AbortGenerateDataOn ()
virtual const bool & GetAbortGenerateData () const
virtual void SetAbortGenerateData (bool _arg)
virtual void UpdateOutputData ()
void UpdateProgress (float amount)
virtual void SetProgress (float _arg)
virtual const float & GetProgress () const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual void Delete ()
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::LightProcessObject
static Pointer New ()
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
MetaArrayReader ()
void PrintSelf (std::ostream &os, Indent indent) const override
~MetaArrayReader () override
Protected Member Functions inherited from itk::LightProcessObject
virtual void GenerateData ()
LightProcessObject ()
~LightProcessObject () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Private Attributes
void * m_Buffer { nullptr }
std::string m_FileName
MetaArray m_MetaArray
Additional Inherited Members
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Detailed Description
Definition at line 30 of file itkMetaArrayReader.h.
Member Typedef Documentation
ConstPointer
using itk::MetaArrayReader::ConstPointer = SmartPointer<const Self>
Definition at line 37 of file itkMetaArrayReader.h.
Pointer
using itk::MetaArrayReader::Pointer = SmartPointer<Self>
Definition at line 36 of file itkMetaArrayReader.h.
Self
using itk::MetaArrayReader::Self = MetaArrayReader
SmartPointer type alias support
Definition at line 34 of file itkMetaArrayReader.h.
Superclass
using itk::MetaArrayReader::Superclass = LightProcessObject
Definition at line 35 of file itkMetaArrayReader.h.
Constructor & Destructor Documentation
MetaArrayReader()
itk::MetaArrayReader::MetaArrayReader () protected
~MetaArrayReader()
itk::MetaArrayReader::~MetaArrayReader () override protected
Member Function Documentation
GetCovariantVectorDimension()
int itk::MetaArrayReader::GetCovariantVectorDimension () const inline
GetCovariantVectorDimension is used by itkVector.
Definition at line 101 of file itkMetaArrayReader.h.
GetDataType()
MET_ValueEnumType itk::MetaArrayReader::GetDataType () const inline
Return the MetaIO type that corresponds to the element type.
Definition at line 66 of file itkMetaArrayReader.h.
GetElement()
template<typename TValue > void itk::MetaArrayReader::GetElement (TValue & value, unsigned int i, unsigned int channel = 0) const inline
GetElement is used by itkArray, itkFixedArray, and VariableLengthVector.
Definition at line 109 of file itkMetaArrayReader.h.
GetFileName()
virtual const char* itk::MetaArrayReader::GetFileName () const virtual
Get the filename.
GetMetaArrayPointer()
MetaArray* itk::MetaArrayReader::GetMetaArrayPointer ()
Get a pointer to the MetaArray so that its options, such as adding comments and user-defined fields, can be changed.
GetMultiChannelOutput()
template<typename TValue > void itk::MetaArrayReader::GetMultiChannelOutput (MET_ValueEnumType _metaElementType, Array< TValue > * _array) inline
Get an itkArray of Arrays, itk::Array< itk::Array<short> >. Assumes all sub-arrays have the same length. Specify the MetaType of the elements of the Array< Array< * > > and provide a pointer to the Array of arrays. Elements are copied into the array of arrays.
Definition at line 231 of file itkMetaArrayReader.h.
References itk::Array< TValue >::SetSize().
GetNameOfClass()
virtual const char* itk::MetaArrayReader::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::LightProcessObject.
GetNumberOfComponents()
int itk::MetaArrayReader::GetNumberOfComponents () const inline
GetNumberOfComponents is used by itkVector and itkCovariantVector.
Definition at line 94 of file itkMetaArrayReader.h.
GetNumberOfElements()
int itk::MetaArrayReader::GetNumberOfElements () const inline
GetNumberOfElements is used by itkArray and VariableLengthVector.
Definition at line 80 of file itkMetaArrayReader.h.
GetOutput() [1/5]
template<typename TValue > void itk::MetaArrayReader::GetOutput (MET_ValueEnumType _metaElementType, Array< TValue > * _array, bool _letArrayManageData = true) inline
Get an itkArray. Specify the MetaType of the elements of the Array and provide a pointer to the Array. The buffer of the Array is replaced by the buffer into which the data was directly read (a copy does not occur). If _letVectorManageData is true, the buffer persists even after this MetaArrayReader is destroyed. Otherwise, the buffer (and therefore the validity of the dat ain the Array) is destroyed when the MetaArrayReader is dstroyed.
Definition at line 124 of file itkMetaArrayReader.h.
References itk::Array< TValue >::SetData().
GetOutput() [2/5]
template<typename TValue > void itk::MetaArrayReader::GetOutput (MET_ValueEnumType _metaElementType, VariableLengthVector< TValue > * _vector, bool _letVectorManageData = true) inline
Get it VariableLengthVector. Specify the MetaType of the elements of the VariableLengthVector and provide a pointer to the VariableLengthVector. The buffer of the VariableLengthVector is replaced by the buffer into which the data was directly read (a copy does not occur). If _letVectorManageData is true, the buffer persists even after this MetaArrayReader is destroyed. Otherwise, the buffer (and therefore the validity of the dat ain the VariableLengthVector) is destroyed when the MetaArrayReader is dstroyed.
Definition at line 208 of file itkMetaArrayReader.h.
References itk::VariableLengthVector::SetData().
GetOutput() [3/5]
template<typename TValue , unsigned int VLength> bool itk::MetaArrayReader::GetOutput (MET_ValueEnumType , CovariantVector< TValue, VLength > * _vector) inline
Get an itkCovariantVector. Specify the MetaType of the elements of the itkCovariantVector and provide a pointer to the itkCovariantVector into which the data should be copied.
Definition at line 182 of file itkMetaArrayReader.h.
GetOutput() [4/5]
template<typename TValue , unsigned int VLength> bool itk::MetaArrayReader::GetOutput (MET_ValueEnumType , FixedArray< TValue, VLength > * _array) inline
Get an itkFixedArray.
Definition at line 141 of file itkMetaArrayReader.h.
GetOutput() [5/5]
template<typename TValue , unsigned int VLength> bool itk::MetaArrayReader::GetOutput (MET_ValueEnumType , Vector< TValue, VLength > * _vector) inline
Get an itkVectort. Specify the MetaType of the elements of the itkVector and provide a pointer to the itkVector into which the data should be copied.
Definition at line 161 of file itkMetaArrayReader.h.
GetVectorDimension()
int itk::MetaArrayReader::GetVectorDimension () const inline
GetVectorDimension is used by itkVector.
Definition at line 87 of file itkMetaArrayReader.h.
New()
static Pointer itk::MetaArrayReader::New () static
Method for creation through the object factory.
PrintSelf()
void itk::MetaArrayReader::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::LightProcessObject.
SetBuffer()
void itk::MetaArrayReader::SetBuffer (void * _buffer)
Specify the buffer (already allocated) into which data should be read.
SetFileName()
virtual void itk::MetaArrayReader::SetFileName (const char * _arg) virtual
Set the filename.
Size()
int itk::MetaArrayReader::Size () const inline
Size is used by itkArray and VariableLengthVector.
Definition at line 73 of file itkMetaArrayReader.h.
Update()
void itk::MetaArrayReader::Update ()
Read the Array in MetaIO format.
Member Data Documentation
m_Buffer
void* itk::MetaArrayReader::m_Buffer { nullptr } private
Definition at line 262 of file itkMetaArrayReader.h.
m_FileName
std::string itk::MetaArrayReader::m_FileName private
Definition at line 260 of file itkMetaArrayReader.h.
m_MetaArray
MetaArray itk::MetaArrayReader::m_MetaArray private
Definition at line 258 of file itkMetaArrayReader.h.
The documentation for this class was generated from the following file:
itkMetaArrayReader.h