ITK: itkMeshFileTestHelper.h File Reference
itkMeshFileTestHelper.h File Reference
#include "itkMeshFileReader.h"
#include "itkMeshFileWriter.h"
#include "itksys/SystemTools.hxx"
Functions
template<typename TMesh >
int test (char *inputFileName, char *outputFileName, bool isBinary)
template<typename TMesh >
int TestCellDataContainer (typename TMesh::CellDataContainerPointer cellData0, typename TMesh::CellDataContainerPointer cellData1)
template<typename TMesh >
int TestCellsContainer (typename TMesh::CellsContainerPointer cells0, typename TMesh::CellsContainerPointer cells1)
template<typename TMesh >
int TestPointDataContainer (typename TMesh::PointDataContainerPointer pointData0, typename TMesh::PointDataContainerPointer pointData1)
template<typename TMesh >
int TestPointsContainer (typename TMesh::PointsContainerPointer points0, typename TMesh::PointsContainerPointer points1)
Function Documentation
test()
template<typename TMesh > int test (char * inputFileName, char * outputFileName, bool isBinary)
Definition at line 250 of file itkMeshFileTestHelper.h.
References New().
Referenced by itk::TransformFactoryBase::RegisterTransform().
TestCellDataContainer()
template<typename TMesh > int TestCellDataContainer (typename TMesh::CellDataContainerPointer cellData0, typename TMesh::CellDataContainerPointer cellData1)
Definition at line 199 of file itkMeshFileTestHelper.h.
References itk::Math::NotExactlyEquals().
TestCellsContainer()
template<typename TMesh > int TestCellsContainer (typename TMesh::CellsContainerPointer cells0, typename TMesh::CellsContainerPointer cells1)
Definition at line 86 of file itkMeshFileTestHelper.h.
TestPointDataContainer()
template<typename TMesh > int TestPointDataContainer (typename TMesh::PointDataContainerPointer pointData0, typename TMesh::PointDataContainerPointer pointData1)
Definition at line 148 of file itkMeshFileTestHelper.h.
References itk::Math::NotExactlyEquals().
TestPointsContainer()
template<typename TMesh > int TestPointsContainer (typename TMesh::PointsContainerPointer points0, typename TMesh::PointsContainerPointer points1)
Definition at line 33 of file itkMeshFileTestHelper.h.
References itk::Math::e.