ITK: itkMeshIOTestHelper.h File Reference
itkMeshIOTestHelper.h File Reference
#include "itkArray.h"
#include "itkCommonEnums.h"
#include "itkCovariantVector.h"
#include "itkFixedArray.h"
#include "itkDiffusionTensor3D.h"
#include "itkMacro.h"
#include "itkMatrix.h"
#include "itkMeshIOBase.h"
#include "itkRGBAPixel.h"
#include "itkRGBPixel.h"
#include "itkSymmetricSecondRankTensor.h"
#include "itkVariableLengthVector.h"
#include "itkVariableSizeMatrix.h"
#include "itkVector.h"
#include <complex>
#include <iostream>
Macros
#define LOCAL_ITK_TEST_SET_GET_VALUE(variable, command)
Functions
void AllocateBuffer (void **data, itk::IOComponentEnum componentType, itk::SizeValueType bufferSize)
template<typename TMeshIO >
int TestBaseClassMethodsMeshIO (typename TMeshIO::Pointer meshIO)
Macro Definition Documentation
LOCAL_ITK_TEST_SET_GET_VALUE
#define LOCAL_ITK_TEST_SET_GET_VALUE (variable, command)
Value:
  CLANG_PRAGMA_PUSH                                                     \
  CLANG_SUPPRESS_Wfloat_equal if (variable != command) CLANG_PRAGMA_POP \
  {                                                                     \
    std::cerr << "Error in " << #command << std::endl;                  \
    std::cerr << "  In " __FILE__ ", line " << __LINE__ << std::endl;   \
    std::cerr << "Expected " << variable << std::endl;                  \
    std::cerr << "but got  " << command << std::endl;                   \
    return EXIT_FAILURE;                                                \
  }                                                                     \
  ITK_MACROEND_NOOP_STATEMENT
Definition at line 42 of file itkMeshIOTestHelper.h.
Function Documentation
AllocateBuffer()
void AllocateBuffer (void ** data, itk::IOComponentEnum componentType, itk::SizeValueType bufferSize)
Definition at line 379 of file itkMeshIOTestHelper.h.
References itk::CommonEnums::CHAR, itk::CommonEnums::DOUBLE, itk::CommonEnums::FLOAT, itk::CommonEnums::INT, itk::CommonEnums::LDOUBLE, itk::CommonEnums::LONG, itk::CommonEnums::LONGLONG, itk::CommonEnums::SHORT, itk::CommonEnums::UCHAR, itk::CommonEnums::UINT, itk::CommonEnums::ULONG, itk::CommonEnums::ULONGLONG, itk::CommonEnums::UNKNOWNCOMPONENTTYPE, and itk::CommonEnums::USHORT.
TestBaseClassMethodsMeshIO()
template<typename TMeshIO > int TestBaseClassMethodsMeshIO (typename TMeshIO::Pointer meshIO)
Definition at line 57 of file itkMeshIOTestHelper.h.
References itk::CommonEnums::ARRAY, itk::CommonEnums::ASCII, itk::CommonEnums::BigEndian, itk::CommonEnums::COMPLEX, itk::CommonEnums::COVARIANTVECTOR, itk::CommonEnums::DIFFUSIONTENSOR3D, itk::Array< TValue >::Fill(), itk::VariableSizeMatrix< T >::Fill(), itk::Matrix< T, VRows, VColumns >::Fill(), itk::FixedArray< TValue, VLength >::Fill(), itk::VariableLengthVector::Fill(), itk::CommonEnums::FIXEDARRAY, itk::CommonEnums::FLOAT, LOCAL_ITK_TEST_SET_GET_VALUE, itk::CommonEnums::MATRIX, itk::CommonEnums::RGB, itk::CommonEnums::RGBA, itk::CommonEnums::SCALAR, itk::CommonEnums::SYMMETRICSECONDRANKTENSOR, itk::CommonEnums::VARIABLELENGTHVECTOR, itk::CommonEnums::VARIABLESIZEMATRIX, and itk::CommonEnums::VECTOR.