ITK: itk::i18n Namespace Reference
itk::i18n Namespace Reference
Typedefs
using I18nIfstream = std::ifstream
using I18nOfstream = std::ofstream
Functions
FILE * I18nFopen (const std::string &str, const std::string &mode)
int I18nOpen (const std::string &str, const int &flags)
int I18nOpen (const std::string &str, const int &flags, const int &mode)
int I18nOpenForReading (const std::string &str)
int I18nOpenForWriting (const std::string &str, const bool append=false)
bool IsStringEncodingValid (const std::string &)
Typedef Documentation
I18nIfstream
using itk::i18n::I18nIfstream = typedef std::ifstream
Definition at line 294 of file itkInternationalizationIOHelpers.h.
I18nOfstream
using itk::i18n::I18nOfstream = typedef std::ofstream
Definition at line 293 of file itkInternationalizationIOHelpers.h.
Function Documentation
I18nFopen()
FILE* itk::i18n::I18nFopen (const std::string & str, const std::string & mode) inline
Definition at line 193 of file itkInternationalizationIOHelpers.h.
I18nOpen() [1/2]
int itk::i18n::I18nOpen (const std::string & str, const int & flags) inline
Definition at line 118 of file itkInternationalizationIOHelpers.h.
Referenced by I18nOpenForReading(), and I18nOpenForWriting().
I18nOpen() [2/2]
int itk::i18n::I18nOpen (const std::string & str, const int & flags, const int & mode) inline
Definition at line 133 of file itkInternationalizationIOHelpers.h.
I18nOpenForReading()
int itk::i18n::I18nOpenForReading (const std::string & str) inline
Definition at line 147 of file itkInternationalizationIOHelpers.h.
References I18nOpen().
I18nOpenForWriting()
int itk::i18n::I18nOpenForWriting (const std::string & str, const bool append = false) inline
Definition at line 158 of file itkInternationalizationIOHelpers.h.
References I18nOpen().
IsStringEncodingValid()
bool itk::i18n::IsStringEncodingValid (const std::string &) inline
Definition at line 85 of file itkInternationalizationIOHelpers.h.