ITK: itk::Concept::Detail Namespace Reference
itk::Concept::Detail Namespace Reference
Classes
struct UniqueType
struct UniqueType_bool
struct UniqueType_int
struct UniqueType_unsigned_int
Functions
template<typename T >
void IgnoreUnusedVariable (T)
template<typename T >
void RequireBooleanExpression (const T &t)
Detailed Description
Some concept implementation details are adapted from the BOOST C++ libraries (www.boost.org). These are marked with "(BOOST)" in the corresponding comment. Namespace containing concept check implementation details.
Function Documentation
IgnoreUnusedVariable()
template<typename T > void itk::Concept::Detail::IgnoreUnusedVariable (T) inline
Concept checks may require a variable to be declared but not used. This function can be called with the variable to prevent the compiler warning. (BOOST)
Definition at line 145 of file itkConceptChecking.h.
Referenced by itk::Concept::CopyConstructible< T >::Constraints::const_constraints(), itk::Concept::DefaultConstructible< T >::Constraints::constraints(), itk::Concept::CopyConstructible< T >::Constraints::constraints(), itk::Concept::Convertible< T1, T2 >::Constraints::constraints(), itk::Concept::Signed< T >::Constraints::constraints(), itk::Concept::SameType< T1, T2 >::Constraints::constraints(), itk::Concept::SameDimension< D1, D2 >::Constraints::constraints(), itk::Concept::HasNumericTraits< T >::Constraints::constraints(), itk::Concept::HasPixelTraits< T >::Constraints::constraints(), itk::Concept::HasZero< T >::Constraints::constraints(), itk::Concept::IsInteger< T >::Constraints::constraints(), itk::Concept::IsUnsignedInteger< T >::Constraints::constraints(), itk::Concept::IsNonInteger< T >::Constraints::constraints(), itk::Concept::IsFloatingPoint< T >::Constraints::constraints(), itk::Concept::IsFixedPoint< T >::Constraints::constraints(), and RequireBooleanExpression().
RequireBooleanExpression()
template<typename T > void itk::Concept::Detail::RequireBooleanExpression (const T & t)
Concept checks may require that an expression be convertible to bool. Passing the expression to this function will enforce this requirement. (BOOST)
Definition at line 155 of file itkConceptChecking.h.
References IgnoreUnusedVariable().
Referenced by itk::Concept::LessThanComparable< T1, T2 >::Constraints::constraints(), itk::Concept::GreaterThanComparable< T1, T2 >::Constraints::constraints(), itk::Concept::EqualityComparable< T1, T2 >::Constraints::constraints(), and itk::Concept::Comparable< T1, T2 >::Constraints::constraints().