ITK: itk::Math Namespace Reference
itk::Math Namespace Reference
Namespaces
Detail
Functions
bool abs (bool x)
unsigned char abs (char x)
unsigned short abs (short x)
unsigned char abs (signed char x)
unsigned char abs (unsigned char x)
unsigned int abs (unsigned int x)
unsigned long long abs (unsigned long long x)
unsigned long abs (unsigned long x)
unsigned short abs (unsigned short x)
template<typename T1 , typename T2 >
bool AlmostEquals (T1 x1, T2 x2)
template<typename TReturn , typename TInput >
TReturn CastWithRangeCheck (TInput x)
template<TReturn , typename TInput >
Ceil (TInput x)
template<typename TInput1 , typename TInput2 >
bool ExactlyEquals (const TInput1 &x1, const TInput2 &x2)
template<typename T >
T FloatAddULP (T x, typename Detail::FloatIEEE< T >::IntType ulps)
template<typename T >
bool FloatAlmostEqual (T x1, T x2, typename Detail::FloatIEEE< T >::IntType maxUlps=4, typename Detail::FloatIEEE< T >::FloatType maxAbsoluteDifference=0.1 *itk::NumericTraits< T >::epsilon())
template<typename T >
Detail::FloatIEEE< T >::IntType FloatDifferenceULP (T x1, T x2)
template<TReturn , typename TInput >
Floor (TInput x)
template<typename T1 , typename T2 >
bool NotAlmostEquals (T1 x1, T2 x2)
template<typename TInput1 , typename TInput2 >
bool NotExactlyEquals (const TInput1 &x1, const TInput2 &x2)
template<typename TReturn , typename TInput >
TReturn Round (TInput x)
template<TReturn , typename TInput >
RoundHalfIntegerToEven (TInput x)
template<TReturn , typename TInput >
RoundHalfIntegerUp (TInput x)
template<typename TReturnType = uintmax_t>
constexpr TReturnType UnsignedPower (const uintmax_t base, const uintmax_t exponent) noexcept
template<typename TReturnType = uintmax_t>
constexpr TReturnType UnsignedProduct (const uintmax_t a, const uintmax_t b) noexcept
Variables
static constexpr double deg_per_rad = vnl_math::deg_per_rad
static constexpr double e = vnl_math::e
static constexpr double eps = vnl_math::eps
static constexpr double euler = vnl_math::euler
static constexpr float float_eps = vnl_math::float_eps
static constexpr float float_sqrteps = vnl_math::float_sqrteps
static constexpr double ln10 = vnl_math::ln10
static constexpr double ln2 = vnl_math::ln2
static constexpr double log10e = vnl_math::log10e
static constexpr double log2e = vnl_math::log2e
static constexpr double one_over_pi = vnl_math::one_over_pi
static constexpr double one_over_sqrt2pi = vnl_math::one_over_sqrt2pi
static constexpr double pi = vnl_math::pi
static constexpr double pi_over_180 = vnl_math::pi_over_180
static constexpr double pi_over_2 = vnl_math::pi_over_2
static constexpr double pi_over_4 = vnl_math::pi_over_4
static constexpr double sqrt1_2 = vnl_math::sqrt1_2
static constexpr double sqrt1_3 = vnl_math::sqrt1_3
static constexpr double sqrt2 = vnl_math::sqrt2
static constexpr double sqrt2pi = vnl_math::sqrt2pi
static constexpr double sqrteps = vnl_math::sqrteps
static constexpr double two_over_pi = vnl_math::two_over_pi
static constexpr double two_over_sqrtpi = vnl_math::two_over_sqrtpi
static constexpr double twopi = vnl_math::twopi
Function Documentation
abs() [1/9]
bool itk::Math::abs (bool x) inline
Definition at line 851 of file itkMath.h.
Referenced by itk::ScanlineFilterCommon< TInputImage, TOutputImage >::CheckNeighbors(), itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::ComputeArea(), itk::Function::AdaptiveEqualizationHistogram< TInputPixel, TOutputPixel >::CumulativeFunction(), itk::BSplineKernelFunction< VSplineOrder, TRealValueType >::Evaluate(), itk::Function::Max3(), itk::Functor::Abs< TInput, TOutput >::operator()(), itk::Functor::SimilarVectorsFunctor< TInputImage::ValueType >::operator()(), itk::Functor::SimilarPixelsFunctor< TInputImage::ValueType >::operator()(), itk::Functor::InverseDeconvolutionFunctor< TInput1, TInput2, TOutput >::operator()(), itk::HessianToObjectnessMeasureImageFilter< TInputImage, TOutputImage >::AbsLessCompare::operator()(), itk::Functor::WienerDeconvolutionFunctor< TPixel >::operator()(), itk::detail::sortEigenValuesByMagnitude(), and itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::Visit().
abs() [2/9]
unsigned char itk::Math::abs (char x) inline
Definition at line 866 of file itkMath.h.
abs() [3/9]
unsigned short itk::Math::abs (short x) inline
Definition at line 871 of file itkMath.h.
abs() [4/9]
unsigned char itk::Math::abs (signed char x) inline
Definition at line 861 of file itkMath.h.
abs() [5/9]
unsigned char itk::Math::abs (unsigned char x) inline
Definition at line 856 of file itkMath.h.
abs() [6/9]
unsigned int itk::Math::abs (unsigned int x) inline
Definition at line 881 of file itkMath.h.
abs() [7/9]
unsigned long long itk::Math::abs (unsigned long long x) inline
Definition at line 892 of file itkMath.h.
Referenced by FloatAlmostEqual().
abs() [8/9]
unsigned long itk::Math::abs (unsigned long x) inline
Definition at line 886 of file itkMath.h.
abs() [9/9]
unsigned short itk::Math::abs (unsigned short x) inline
Definition at line 876 of file itkMath.h.
AlmostEquals()
template<typename T1 , typename T2 > bool itk::Math::AlmostEquals (T1 x1, T2 x2) inline
Provide consistent equality checks between values of potentially different scalar or complex types.
template< typename T1, typename T2 > AlmostEquals(T1 x1, T2 x2)
template< typename T1, typename T2 > NotAlmostEquals(T1 x1, T2 x2)
This function compares two scalar or complex values of potentially different types. For maximum extensibility the function is implemented through a series of templated structs which direct the AlmostEquals() call to the correct function by evaluating the parameter's types.
Overall algorithm: If both values are complex... separate values into real and imaginary components and compare them separately
If one of the values is complex.. see if the imaginary part of the complex value is approximately 0 ... compare real part of complex value with scalar value
If both values are scalars...
To compare two floating point types... use FloatAlmostEqual.
To compare a floating point and an integer type... Use static_cast<FloatingPointType>(integerValue) and call FloatAlmostEqual
To compare signed and unsigned integers... Check for negative value or overflow, then cast and use ==
To compare two signed or two unsigned integers ... Use ==
To compare anything else ... Use ==
Parameters
x1 first scalar value to compare
x2 second scalar value to compare
Definition at line 685 of file itkMath.h.
Referenced by itk::AnchorErodeDilateLine< TInputPix, TCompare >::Compare(), NotAlmostEquals(), and itk::DivideImageFilter< TInputImage1, TInputImage2, TOutputImage >::VerifyPreconditions().
CastWithRangeCheck()
template<typename TReturn , typename TInput > TReturn itk::Math::CastWithRangeCheck (TInput x) inline
Definition at line 213 of file itkMath.h.
References itk::NumericTraits< T >::IsPositive(), and itkConceptMacro.
Ceil()
template<TReturn , typename TInput > itk::Math::Ceil (TInput x)
Round towards plus infinity.
The behavior of overflow is undefined due to numerous implementations.
Warning
argument absolute value must be less than INT_MAX/2 for vnl_math_ceil to be guaranteed to work.
We also assume that the rounding mode is not changed from the default one (or at least that it is always restored to the default one).
ExactlyEquals()
template<typename TInput1 , typename TInput2 > bool itk::Math::ExactlyEquals (const TInput1 & x1, const TInput2 & x2) inline
Return the result of an exact comparison between two scalar values of potentially different types.
template <typename TInput1, typename TInput2> inline bool ExactlyEquals(const TInput & x1, const TInput & x2)
template <typename TInput1, typename TInput2> inline bool NotExactlyEquals(const TInput & x1, const TInput & x2)
These functions complement the EqualsComparison functions and determine if two scalar values are exactly equal using the compilers casting rules when comparing two different types. While this is also easily accomplished by using the equality operators, use of this function demonstrates the intent of an exact equality check and thus improves readability and clarity of code. In addition, this function suppresses float-equal warnings produced when using Clang.
Parameters
x1 first floating point value to compare
x2 second floating point value to compare
Definition at line 723 of file itkMath.h.
Referenced by itk::BSplineKernelFunction< VSplineOrder, TRealValueType >::Evaluate(), itk::BSplineDerivativeKernelFunction< VSplineOrder, TRealValueType >::Evaluate(), NotExactlyEquals(), itk::Functor::Equal< TInput1, TInput2, TOutput >::operator()(), itk::Functor::ExpNegative< TInputImage::PixelType, TOutputImage::PixelType >::operator==(), itk::Functor::IntensityWindowingTransform< TInputImage::PixelType, TInputImage ::PixelType >::operator==(), itk::Functor::VectorMagnitudeLinearTransform< TInputImage::PixelType, TInputImage ::PixelType >::operator==(), itk::Functor::WeightedAdd2< typename TInputImage1::PixelType, typename TInputImage2::PixelType, typename TOutputImage::PixelType >::operator==(), itk::Functor::Sigmoid< TInputImage::PixelType, TOutputImage::PixelType >::operator==(), itk::Functor::IntensityLinearTransform< TInputImage::PixelType, TInputImage ::PixelType >::operator==(), itk::Functor::LabelOverlayFunctor< FeatureImagePixelType, LabelMapPixelType, OutputImagePixelType >::operator==(), itk::Functor::BinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >::operator==(), itk::Point< double, Self::ImageDimension >::operator==(), itk::KLMDynamicBorderArray< TBorder >::operator>(), itk::LaplacianSegmentationLevelSetFunction< TImageType, TFeatureImageType >::SetAdvectionWeight(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetAlpha(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetBeta(), itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >::SetBinaryMask(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetOutputMaximum(), itk::SigmoidImageFilter< TInputImage, TOutputImage >::SetOutputMinimum(), and itk::ShapeUniqueLabelMapFilter< TImage >::TemplatedGenerateData().
FloatAddULP()
template<typename T > T itk::Math::FloatAddULP (T x, typename Detail::FloatIEEE< T >::IntType ulps) inline
Add the given ULPs (units in the last place) to a float.
If the given ULPs can are negative, they are subtracted.
See also
FloatAlmostEqual
FloatDifferenceULP
Definition at line 270 of file itkMath.h.
References itk::Math::Detail::FloatIEEE< T >::asFloat, and itk::Math::Detail::FloatIEEE< T >::asInt.
FloatAlmostEqual()
template<typename T > bool itk::Math::FloatAlmostEqual (T x1, T x2, typename Detail::FloatIEEE< T >::IntType maxUlps = 4, typename Detail::FloatIEEE< T >::FloatType maxAbsoluteDifference = 0.1 * itk::NumericTraits<T>::epsilon()) inline
Compare two floats and return if they are effectively equal.
Determining when floats are almost equal is difficult because of their IEEE bit representation. This function uses the integer representation of the float to determine if they are almost equal.
The implementation is based off the explanation in the white papers:
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
https://randomascii.wordpress.com/category/floating-point/
This function is not a cure-all, and reading those articles is important to understand its appropriate use in the context of ULPs, zeros, subnormals, infinities, and NANs. For example, it is preferable to use this function on two floats directly instead of subtracting them and comparing them to zero.
The tolerance is specified in ULPs (units in the last place), i.e. how many floats there are in between the numbers. Therefore, the tolerance depends on the magnitude of the values that are being compared. A second tolerance is a maximum difference allowed, which is important when comparing numbers close to zero.
A NAN compares as not equal to a number, but two NAN's may compare as equal to each other.
Parameters
x1 first floating value to compare
x2 second floating values to compare
maxUlps maximum units in the last place to be considered equal
maxAbsoluteDifference maximum absolute difference to be considered equal
Definition at line 309 of file itkMath.h.
References abs(), and FloatDifferenceULP().
FloatDifferenceULP()
template<typename T > Detail::FloatIEEE<T>::IntType itk::Math::FloatDifferenceULP (T x1, T x2) inline
Return the signed distance in ULPs (units in the last place) between two floats.
This is the signed distance, i.e., if x1 > x2, then the result is positive.
See also
FloatAlmostEqual
FloatAddULP
Definition at line 254 of file itkMath.h.
References itk::Math::Detail::FloatIEEE< T >::AsULP().
Referenced by FloatAlmostEqual().
Floor()
template<TReturn , typename TInput > itk::Math::Floor (TInput x)
Round towards minus infinity.
The behavior of overflow is undefined due to numerous implementations.
Warning
argument absolute value must be less than NumbericTraits<TReturn>::max()/2 for vnl_math_floor to be guaranteed to work.
We also assume that the rounding mode is not changed from the default one (or at least that it is always restored to the default one).
GreatestPrimeFactor() [1/4]
ITKCommon_EXPORT unsigned int itk::Math::GreatestPrimeFactor (unsigned int n)
Return the greatest factor of the decomposition in prime numbers.
GreatestPrimeFactor() [2/4]
ITKCommon_EXPORT unsigned long long itk::Math::GreatestPrimeFactor (unsigned long long n)
Return the greatest factor of the decomposition in prime numbers.
GreatestPrimeFactor() [3/4]
ITKCommon_EXPORT unsigned long itk::Math::GreatestPrimeFactor (unsigned long n)
Return the greatest factor of the decomposition in prime numbers.
GreatestPrimeFactor() [4/4]
ITKCommon_EXPORT unsigned short itk::Math::GreatestPrimeFactor (unsigned short n)
Return the greatest factor of the decomposition in prime numbers.
IsPrime() [1/4]
ITKCommon_EXPORT bool itk::Math::IsPrime (unsigned int n)
Return whether the number is a prime number or not.
Note
Negative numbers cannot be prime.
IsPrime() [2/4]
ITKCommon_EXPORT bool itk::Math::IsPrime (unsigned long long n)
Return whether the number is a prime number or not.
Note
Negative numbers cannot be prime.
IsPrime() [3/4]
ITKCommon_EXPORT bool itk::Math::IsPrime (unsigned long n)
Return whether the number is a prime number or not.
Note
Negative numbers cannot be prime.
IsPrime() [4/4]
ITKCommon_EXPORT bool itk::Math::IsPrime (unsigned short n)
Return whether the number is a prime number or not.
Note
Negative numbers cannot be prime.
NotAlmostEquals()
template<typename T1 , typename T2 > bool itk::Math::NotAlmostEquals (T1 x1, T2 x2) inline
Definition at line 693 of file itkMath.h.
References AlmostEquals().
Referenced by itk::Functor::Div< TInput1, TInput2, TOutput >::operator()().
NotExactlyEquals()
template<typename TInput1 , typename TInput2 > bool itk::Math::NotExactlyEquals (const TInput1 & x1, const TInput2 & x2) inline
Definition at line 733 of file itkMath.h.
References ExactlyEquals().
Referenced by itk::Functor::NotEqual< TInput1, TInput2, TOutput >::operator()(), itk::VariableSizeMatrix< double >::operator==(), itk::Matrix< double, Self::InputSpaceDimension, Self::OutputSpaceDimension >::operator==(), itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, float, Image< float, TInputImage::ImageDimension > >::SetAdvectionScaling(), itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >::SetAdvectionScaling(), itk::GaussianInterpolateImageFunction< TInputImage, double >::SetAlpha(), itk::NotImageFilter< TInputImage, TOutputImage >::SetBackgroundValue(), itk::ConstantPadImageFilter< TInputImage, TOutputImage >::SetConstant(), itk::DivideOrZeroOutImageFilter< TInputImage1, TInputImage2, TOutputImage >::SetConstant(), itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, float, Image< float, TInputImage::ImageDimension > >::SetCurvatureScaling(), itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >::SetCurvatureScaling(), itk::GeodesicActiveContourLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >::SetDerivativeSigma(), itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >::SetFeatureScaling(), itk::NotImageFilter< TInputImage, TOutputImage >::SetForegroundValue(), itk::CannyEdgeDetectionImageFilter< ImageType, ImageType >::SetMaximumError(), itk::MaskNegatedImageFilter< TInputImage, TMaskImage, TOutputImage >::SetOutsideValue(), itk::MaskImageFilter< TInputImage, TMaskImage, TOutputImage >::SetOutsideValue(), itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, float, Image< float, TInputImage::ImageDimension > >::SetPropagationScaling(), itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >::SetPropagationScaling(), itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >::SetShapePriorScaling(), itk::DivideOrZeroOutImageFilter< TInputImage1, TInputImage2, TOutputImage >::SetThreshold(), itk::CannyEdgeDetectionImageFilter< ImageType, ImageType >::SetVariance(), TestCellDataContainer(), and TestPointDataContainer().
Round()
template<typename TReturn , typename TInput > TReturn itk::Math::Round (TInput x) inline
Round towards nearest integer (This is a synonym for RoundHalfIntegerUp)
Template Parameters
TReturn must be an integer type
TInput must be float or double
See also
RoundHalfIntegerUp<TReturn, TInput>()
Definition at line 178 of file itkMath.h.
RoundHalfIntegerToEven()
template<TReturn , typename TInput > itk::Math::RoundHalfIntegerToEven (TInput x)
Round towards nearest integer.
Template Parameters
TReturn must be an integer type
TInput must be float or double
    halfway cases are rounded towards the nearest even
    integer, e.g.
RoundHalfIntegerToEven(1.5) ==  2
RoundHalfIntegerToEven(-1.5) == -2
RoundHalfIntegerToEven(2.5) ==  2
RoundHalfIntegerToEven(3.5) ==  4
The behavior of overflow is undefined due to numerous implementations.
Warning
We assume that the rounding mode is not changed from the default one (or at least that it is always restored to the default one).
RoundHalfIntegerUp()
template<TReturn , typename TInput > itk::Math::RoundHalfIntegerUp (TInput x)
Round towards nearest integer.
Template Parameters
TReturn must be an integer type
TInput must be float or double
    halfway cases are rounded upward, e.g.
RoundHalfIntegerUp(1.5) ==  2
RoundHalfIntegerUp(-1.5) == -1
RoundHalfIntegerUp(2.5) ==  3
The behavior of overflow is undefined due to numerous implementations.
Warning
The argument absolute value must be less than NumbericTraits<TReturn>::max()/2 for RoundHalfIntegerUp to be guaranteed to work.
We also assume that the rounding mode is not changed from the default one (or at least that it is always restored to the default one).
UnsignedPower()
template<typename TReturnType = uintmax_t> constexpr TReturnType itk::Math::UnsignedPower (const uintmax_t base, const uintmax_t exponent) constexpr noexcept
Calculates base ^ exponent. Numeric overflow triggers a compilation error in "constexpr context" and a debug assert failure at run-time. Otherwise equivalent to C++11 static_cast<uintmax_t>(std::pow(base, exponent))
Note
UnsignedPower(0, 0) is not supported, as zero to the power of zero has no agreed-upon value: https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero
Definition at line 802 of file itkMath.h.
References ITK_X_ASSERT.
Referenced by itk::ConnectedImageNeighborhoodShape< VImageDimension >::CalculateNumberOfConnectedNeighbors().
UnsignedProduct()
template<typename TReturnType = uintmax_t> constexpr TReturnType itk::Math::UnsignedProduct (const uintmax_t a, const uintmax_t b) constexpr noexcept
Returns a * b. Numeric overflow triggers a compilation error in "constexpr context" and a debug assert failure at run-time.
Definition at line 780 of file itkMath.h.
References ITK_X_ASSERT.
Referenced by itk::ConnectedImageNeighborhoodShape< VImageDimension >::CalculateBinomialCoefficient(), and itk::ConnectedImageNeighborhoodShape< VImageDimension >::CalculateNumberOfHypercubesOnBoundaryOfCube().
Variable Documentation
deg_per_rad
constexpr double itk::Math::deg_per_rad = vnl_math::deg_per_rad static constexpr
\[ \frac{180}{\pi} \]
Definition at line 78 of file itkMath.h.
e
constexpr double itk::Math::e = vnl_math::e static constexpr
\[e\]
The base of the natural logarithm or Euler's number
Definition at line 54 of file itkMath.h.
Referenced by itk::TotalProgressReporter::CheckAbortGenerateData(), itk::ProgressReporter::CheckAbortGenerateData(), itk::DiscretePrincipalCurvaturesQuadEdgeMeshFilter< TInputMesh, TInputMesh >::ComputeMeanAndGaussianCurvatures(), itk::Concept::AdditiveOperators< T1, T2, T3 >::Constraints::const_constraints(), itk::Concept::MultiplyOperator< T1, T2, T3 >::Constraints::const_constraints(), itk::Concept::DivisionOperators< T1, T2, T3 >::Constraints::const_constraints(), itk::Concept::BitwiseOperators< T1, T2, T3 >::Constraints::const_constraints(), itk::Concept::BracketOperator< T1, T2, T3 >::Constraints::const_constraints(), itk::Functor::DivideOrZeroOut< typename TInputImage1::PixelType, typename TInputImage1 ::PixelType, typename TInputImage1 ::PixelType >::DivideOrZeroOut(), itk::Versor< double >::Epsilon(), itk::DiscreteMeanCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >::EstimateCurvature(), itk::QuadEdgeMeshEulerOperatorSplitEdgeFunction< TMesh, TQEType >::Evaluate(), itk::MatrixOrthogonalityTolerance< double >::GetTolerance(), itk::MatrixOrthogonalityTolerance< float >::GetTolerance(), itk::ConstNeighborhoodIterator< TSparseImageType >::IsAtEnd(), itk::Functor::Sigmoid< TInputImage::PixelType, TOutputImage::PixelType >::operator()(), itk::operator<<(), itk::PDEDeformableRegistrationFunction< TFixedImage, TMovingImage, TDisplacementField >::SetEnergy(), itk::GPUPDEDeformableRegistrationFunction< TFixedImage, TMovingImage, TDisplacementField >::SetEnergy(), itk::LevelSetFunction< TImageType >::SetEpsilonMagnitude(), itk::PDEDeformableRegistrationFunction< TFixedImage, TMovingImage, TDisplacementField >::SetGradientStep(), itk::GPUPDEDeformableRegistrationFunction< TFixedImage, TMovingImage, TDisplacementField >::SetGradientStep(), itk::PDEDeformableRegistrationFunction< TFixedImage, TMovingImage, TDisplacementField >::SetNormalizeGradient(), itk::GPUPDEDeformableRegistrationFunction< TFixedImage, TMovingImage, TDisplacementField >::SetNormalizeGradient(), and TestPointsContainer().
eps
constexpr double itk::Math::eps = vnl_math::eps static constexpr
Definition at line 95 of file itkMath.h.
euler
constexpr double itk::Math::euler = vnl_math::euler static constexpr
euler constant
Definition at line 92 of file itkMath.h.
float_eps
constexpr float itk::Math::float_eps = vnl_math::float_eps static constexpr
Definition at line 98 of file itkMath.h.
float_sqrteps
constexpr float itk::Math::float_sqrteps = vnl_math::float_sqrteps static constexpr
Definition at line 99 of file itkMath.h.
ln10
constexpr double itk::Math::ln10 = vnl_math::ln10 static constexpr
\[ \log_e 10 \]
Definition at line 62 of file itkMath.h.
ln2
constexpr double itk::Math::ln2 = vnl_math::ln2 static constexpr
\[ \log_e 2 \]
Definition at line 60 of file itkMath.h.
log10e
constexpr double itk::Math::log10e = vnl_math::log10e static constexpr
\[ \log_{10} e \]
Definition at line 58 of file itkMath.h.
log2e
constexpr double itk::Math::log2e = vnl_math::log2e static constexpr
\[ \log_2 e \]
Definition at line 56 of file itkMath.h.
one_over_pi
constexpr double itk::Math::one_over_pi = vnl_math::one_over_pi static constexpr
\[ \frac{1}{\pi} \]
Definition at line 74 of file itkMath.h.
one_over_sqrt2pi
constexpr double itk::Math::one_over_sqrt2pi = vnl_math::one_over_sqrt2pi static constexpr
\[ \frac{2}{\sqrt{2\pi}} \]
Definition at line 84 of file itkMath.h.
pi
constexpr double itk::Math::pi = vnl_math::pi static constexpr
\[ \pi \]
Definition at line 64 of file itkMath.h.
Referenced by itk::DiscretePrincipalCurvaturesQuadEdgeMeshFilter< TInputMesh, TInputMesh >::ComputeMeanAndGaussianCurvatures(), itk::DelaunayConformingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >::Dyer07Criterion(), itk::DiscreteGaussianCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >::EstimateCurvature(), itk::GaborKernelFunction< TRealValueType >::Evaluate(), itk::Statistics::MersenneTwisterRandomVariateGenerator::GetNormalVariate(), itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::PhasedArray3DSpecialCoordinatesImage(), and itk::WindowedSincInterpolateImageFunction< TInputImage, VRadius, TWindowFunction, TBoundaryCondition, TCoordRep >::Sinc().
pi_over_180
constexpr double itk::Math::pi_over_180 = vnl_math::pi_over_180 static constexpr
\[ \frac{\pi}{180} \]
Definition at line 72 of file itkMath.h.
pi_over_2
constexpr double itk::Math::pi_over_2 = vnl_math::pi_over_2 static constexpr
\[ \frac{\pi}{2} \]
Definition at line 68 of file itkMath.h.
Referenced by itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToContinuousIndex(), and itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToIndex().
pi_over_4
constexpr double itk::Math::pi_over_4 = vnl_math::pi_over_4 static constexpr
\[ \frac{\pi}{4} \]
Definition at line 70 of file itkMath.h.
sqrt1_2
constexpr double itk::Math::sqrt1_2 = vnl_math::sqrt1_2 static constexpr
\[ \sqrt{ \frac{1}{2}} \]
Definition at line 88 of file itkMath.h.
sqrt1_3
constexpr double itk::Math::sqrt1_3 = vnl_math::sqrt1_3 static constexpr
\[ \sqrt{ \frac{1}{3}} \]
Definition at line 90 of file itkMath.h.
sqrt2
constexpr double itk::Math::sqrt2 = vnl_math::sqrt2 static constexpr
\[ \sqrt{2} \]
Definition at line 86 of file itkMath.h.
sqrt2pi
constexpr double itk::Math::sqrt2pi = vnl_math::sqrt2pi static constexpr
\[ \sqrt{2\pi} \]
Definition at line 80 of file itkMath.h.
sqrteps
constexpr double itk::Math::sqrteps = vnl_math::sqrteps static constexpr
Definition at line 96 of file itkMath.h.
two_over_pi
constexpr double itk::Math::two_over_pi = vnl_math::two_over_pi static constexpr
\[ \frac{2}{\pi} \]
Definition at line 76 of file itkMath.h.
two_over_sqrtpi
constexpr double itk::Math::two_over_sqrtpi = vnl_math::two_over_sqrtpi static constexpr
\[ \frac{2}{\sqrt{\pi}} \]
Definition at line 82 of file itkMath.h.
twopi
constexpr double itk::Math::twopi = vnl_math::twopi static constexpr
\[ 2\pi \]
Definition at line 66 of file itkMath.h.