ITK: itk::Concept::CopyConstructible< T >::Constraints Struct Reference
itk::Concept::CopyConstructible< T >::Constraints Struct Reference
#include <itkConceptChecking.h>
Public Member Functions
void const_constraints (const T &a)
void constraints ()
Public Attributes
T b
Detailed Description
template<typename T>
struct itk::Concept::CopyConstructible< T >::Constraints
Definition at line 185 of file itkConceptChecking.h.
Member Function Documentation
const_constraints()
template<typename T > void itk::Concept::CopyConstructible< T >::Constraints::const_constraints (const T & a) inline
Definition at line 199 of file itkConceptChecking.h.
References itk::Concept::Detail::IgnoreUnusedVariable().
Referenced by itk::Concept::CopyConstructible< T >::Constraints::constraints().
constraints()
template<typename T > void itk::Concept::CopyConstructible< T >::Constraints::constraints () inline
Definition at line 188 of file itkConceptChecking.h.
References itk::Concept::CopyConstructible< T >::Constraints::b, itk::Concept::CopyConstructible< T >::Constraints::const_constraints(), and itk::Concept::Detail::IgnoreUnusedVariable().
Member Data Documentation
b
template<typename T > T itk::Concept::CopyConstructible< T >::Constraints::b
Definition at line 208 of file itkConceptChecking.h.
Referenced by itk::Concept::CopyConstructible< T >::Constraints::constraints().
The documentation for this struct was generated from the following file:
itkConceptChecking.h