ITK: itk::Index< VDimension > Struct Template Reference
itk::Index< VDimension > Struct Template Reference final
Data Access Objects » Image Access ObjectsData Representation Objects » | Image Representation ObjectsGroup Core » | Module ITKCommon
#include <itkIndex.h>
Public Types
using const_iterator = const value_type *
using const_reference = const value_type &
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using difference_type = ptrdiff_t
using IndexType = Index< VDimension >
using IndexValueType = itk::IndexValueType
using iterator = value_type *
using OffsetType = Offset< VDimension >
using OffsetValueType = itk::OffsetValueType
using reference = value_type &
using reverse_iterator = std::reverse_iterator< iterator >
using Self = Index
using size_type = unsigned int
using SizeType = Size< VDimension >
using value_type = itk::IndexValueType
Public Member Functions
void assign (const value_type &newValue)
reference at (size_type pos)
const_reference at (size_type pos) const
reference back ()
const_reference back () const
constexpr iterator begin ()
constexpr const_iterator begin () const
constexpr const_iterator cbegin () const
constexpr const_iterator cend () const
IndexValueType * data ()
const IndexValueType * data () const
constexpr bool empty () const
constexpr iterator end ()
constexpr const_iterator end () const
void Fill (IndexValueType value)
reference front ()
const_reference front () const
IndexValueType GetElement (unsigned long element) const
const IndexValueType * GetIndex () const
constexpr size_type max_size () const
const Self operator* (const SizeType &vec) const
const Self operator+ (const OffsetType &offset) const
const Self operator+ (const SizeType &sz) const
const Self operator- (const OffsetType &off) const
const OffsetType operator- (const Self &vec) const
const Self operator- (const SizeType &sz) const
constexpr reference operator[] (size_type pos)
constexpr const_reference operator[] (size_type pos) const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
void SetElement (unsigned long element, IndexValueType val)
void SetIndex (const IndexValueType val[VDimension])
constexpr size_type size () const
void swap (Index &other)
const Self & operator+= (const SizeType &sz)
const Self & operator-= (const SizeType &sz)
const Self & operator+= (const OffsetType &offset)
const Self & operator-= (const OffsetType &offset)
template<typename TCoordRep >
void CopyWithRound (const FixedArray< TCoordRep, VDimension > &point)
template<typename TCoordRep >
void CopyWithCast (const FixedArray< TCoordRep, VDimension > &point)
Static Public Member Functions
static constexpr Self Filled (const IndexValueType value)
static Self GetBasisIndex (unsigned int dim)
static constexpr unsigned int GetIndexDimension ()
Public Attributes
IndexValueType m_InternalArray [VDimension]
Static Public Attributes
static constexpr unsigned int Dimension = VDimension
Private Member Functions
void ExceptionThrowingBoundsCheck (size_type pos) const
Detailed Description
template<unsigned int VDimension = 2>
struct itk::Index< VDimension >
Represent a n-dimensional index in a n-dimensional image.
Index is a templated class to represent a multi-dimensional index, i.e. (i,j,k,...). Index is templated over the dimension of the index. ITK assumes the first element of an index is the fastest moving index.
For efficiency sake, Index does not define a default constructor, a copy constructor, or an operator=. We rely on the compiler to provide efficient bitwise copies.
Index is an "aggregate" class. Its data is public (m_InternalArray) allowing for fast and convenient instantiations/assignments.
The following syntax for assigning an aggregate type like this is allowed/suggested:
Index<3> var{{ 256, 256, 20 }}; // Also prevent narrowing conversions Index<3> var = {{ 256, 256, 20 }};
The doubled braces {{ and }} are required to prevent ‘gcc -Wall’ (and perhaps other compilers) from complaining about a partly bracketed initializer.
As an aggregate type that is intended to provide highest performance characteristics, this class is not appropriate to inherit from, so setting this struct as final.
ITK Sphinx Examples:
All ITK Sphinx Examples
Distance between two indices
Create A Index
Definition at line 70 of file itkIndex.h.
Member Typedef Documentation
const_iterator
template<unsigned int VDimension = 2> using itk::Index< VDimension >::const_iterator = const value_type *
Definition at line 338 of file itkIndex.h.
const_reference
template<unsigned int VDimension = 2> using itk::Index< VDimension >::const_reference = const value_type &
Definition at line 336 of file itkIndex.h.
const_reverse_iterator
template<unsigned int VDimension = 2> using itk::Index< VDimension >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 342 of file itkIndex.h.
difference_type
template<unsigned int VDimension = 2> using itk::Index< VDimension >::difference_type = ptrdiff_t
Definition at line 340 of file itkIndex.h.
IndexType
template<unsigned int VDimension = 2> using itk::Index< VDimension >::IndexType = Index<VDimension>
Compatible Index and value type alias
Definition at line 80 of file itkIndex.h.
IndexValueType
template<unsigned int VDimension = 2> using itk::Index< VDimension >::IndexValueType = itk::IndexValueType
Definition at line 81 of file itkIndex.h.
iterator
template<unsigned int VDimension = 2> using itk::Index< VDimension >::iterator = value_type *
Definition at line 337 of file itkIndex.h.
OffsetType
template<unsigned int VDimension = 2> using itk::Index< VDimension >::OffsetType = Offset<VDimension>
Compatible Offset and Offset value type alias.
Definition at line 87 of file itkIndex.h.
OffsetValueType
template<unsigned int VDimension = 2> using itk::Index< VDimension >::OffsetValueType = itk::OffsetValueType
Definition at line 88 of file itkIndex.h.
reference
template<unsigned int VDimension = 2> using itk::Index< VDimension >::reference = value_type &
Definition at line 335 of file itkIndex.h.
reverse_iterator
template<unsigned int VDimension = 2> using itk::Index< VDimension >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 341 of file itkIndex.h.
Self
template<unsigned int VDimension = 2> using itk::Index< VDimension >::Self = Index
Standard class type aliases.
Definition at line 77 of file itkIndex.h.
size_type
template<unsigned int VDimension = 2> using itk::Index< VDimension >::size_type = unsigned int
Definition at line 339 of file itkIndex.h.
SizeType
template<unsigned int VDimension = 2> using itk::Index< VDimension >::SizeType = Size<VDimension>
Compatible Size type alias.
Definition at line 84 of file itkIndex.h.
value_type
template<unsigned int VDimension = 2> using itk::Index< VDimension >::value_type = itk::IndexValueType
Mirror the std::array type aliases and member function so that the Index class can be treated as a container class in a way that is similar to the std::array.
Definition at line 334 of file itkIndex.h.
Member Function Documentation
assign()
template<unsigned int VDimension = 2> void itk::Index< VDimension >::assign (const value_type & newValue) inline
Mirror behavior of the std::array manipulations See std::array for documentation on these methods
Definition at line 349 of file itkIndex.h.
at() [1/2]
template<unsigned int VDimension = 2> reference itk::Index< VDimension >::at (size_type pos) inline
Definition at line 443 of file itkIndex.h.
at() [2/2]
template<unsigned int VDimension = 2> const_reference itk::Index< VDimension >::at (size_type pos) const inline
Definition at line 450 of file itkIndex.h.
back() [1/2]
template<unsigned int VDimension = 2> reference itk::Index< VDimension >::back () inline
Definition at line 469 of file itkIndex.h.
Referenced by itk::IndexRange< VDimension, VBeginAtZero >::end(), itk::IndexRange< VDimension, VBeginAtZero >::const_iterator::operator++(), and itk::IndexRange< VDimension, VBeginAtZero >::const_iterator::operator--().
back() [2/2]
template<unsigned int VDimension = 2> const_reference itk::Index< VDimension >::back () const inline
Definition at line 475 of file itkIndex.h.
begin() [1/2]
template<unsigned int VDimension = 2> constexpr iterator itk::Index< VDimension >::begin () inline constexpr
Definition at line 367 of file itkIndex.h.
Referenced by itk::operator<(), and itk::operator==().
begin() [2/2]
template<unsigned int VDimension = 2> constexpr const_iterator itk::Index< VDimension >::begin () const inline constexpr
Definition at line 373 of file itkIndex.h.
cbegin()
template<unsigned int VDimension = 2> constexpr const_iterator itk::Index< VDimension >::cbegin () const inline constexpr
Definition at line 361 of file itkIndex.h.
cend()
template<unsigned int VDimension = 2> constexpr const_iterator itk::Index< VDimension >::cend () const inline constexpr
Definition at line 379 of file itkIndex.h.
CopyWithCast()
template<unsigned int VDimension = 2> template<typename TCoordRep > void itk::Index< VDimension >::CopyWithCast (const FixedArray< TCoordRep, VDimension > & point) inline
Copy values from a FixedArray by casting each one of the components
Definition at line 312 of file itkIndex.h.
CopyWithRound()
template<unsigned int VDimension = 2> template<typename TCoordRep > void itk::Index< VDimension >::CopyWithRound (const FixedArray< TCoordRep, VDimension > & point) inline
Copy values from a FixedArray by rounding each one of the components
Definition at line 300 of file itkIndex.h.
data() [1/2]
template<unsigned int VDimension = 2> IndexValueType* itk::Index< VDimension >::data () inline
Definition at line 481 of file itkIndex.h.
data() [2/2]
template<unsigned int VDimension = 2> const IndexValueType* itk::Index< VDimension >::data () const inline
Definition at line 487 of file itkIndex.h.
empty()
template<unsigned int VDimension = 2> constexpr bool itk::Index< VDimension >::empty () const inline constexpr
Definition at line 433 of file itkIndex.h.
end() [1/2]
template<unsigned int VDimension = 2> constexpr iterator itk::Index< VDimension >::end () inline constexpr
Definition at line 385 of file itkIndex.h.
Referenced by itk::operator<(), and itk::operator==().
end() [2/2]
template<unsigned int VDimension = 2> constexpr const_iterator itk::Index< VDimension >::end () const inline constexpr
Definition at line 391 of file itkIndex.h.
ExceptionThrowingBoundsCheck()
template<unsigned int VDimension = 2> void itk::Index< VDimension >::ExceptionThrowingBoundsCheck (size_type pos) const inline private
Definition at line 504 of file itkIndex.h.
Fill()
template<unsigned int VDimension = 2> void itk::Index< VDimension >::Fill (IndexValueType value) inline
Set one value for the index in all dimensions. Useful for initializing an offset to zero.
Definition at line 274 of file itkIndex.h.
Referenced by itk::FrequencyFFTLayoutImageRegionConstIteratorWithIndex< TImage >::GetFrequencyBin(), and itk::LevelSetNode< TPixel, VSetDimension >::LevelSetNode().
Filled()
template<unsigned int VDimension = 2> static constexpr Self itk::Index< VDimension >::Filled (const IndexValueType value) inline static constexpr
Returns an Index object, filled with the specified value for each element.
Definition at line 496 of file itkIndex.h.
front() [1/2]
template<unsigned int VDimension = 2> reference itk::Index< VDimension >::front () inline
Definition at line 457 of file itkIndex.h.
front() [2/2]
template<unsigned int VDimension = 2> const_reference itk::Index< VDimension >::front () const inline
Definition at line 463 of file itkIndex.h.
GetBasisIndex()
template<unsigned int VDimension> Index< VDimension > itk::Index< VDimension >::GetBasisIndex (unsigned int dim) static
Return a basis vector of the form [0, ..., 0, 1, 0, ... 0] where the "1" is positioned in the location specified by the parameter "dim". Valid values of "dim" are 0, ..., VDimension-1.
Definition at line 516 of file itkIndex.h.
GetElement()
template<unsigned int VDimension = 2> IndexValueType itk::Index< VDimension >::GetElement (unsigned long element) const inline
Gets the value of one of the elements. This method is mainly intended to facilitate the access to elements from Tcl and Python where C++ notation is not very convenient.
Warning
No bound checking is performed
See also
GetIndex()
SetElement()
Definition at line 266 of file itkIndex.h.
GetIndex()
template<unsigned int VDimension = 2> const IndexValueType* itk::Index< VDimension >::GetIndex () const inline
Get the index. This provides a read only pointer to the index.
See also
SetIndex()
Definition at line 232 of file itkIndex.h.
Referenced by itk::BoxMeanCalculatorFunction(), itk::BoxSigmaCalculatorFunction(), itk::ImageBase< 2 >::ComputeIndex(), itk::ImageBase< 2 >::FastComputeIndex(), and itk::Functor::LabelObjectLineComparator< TLabelObjectLine >::operator()().
GetIndexDimension()
template<unsigned int VDimension = 2> static constexpr unsigned int itk::Index< VDimension >::GetIndexDimension () inline static constexpr
Get the dimension.
Definition at line 95 of file itkIndex.h.
max_size()
template<unsigned int VDimension = 2> constexpr size_type itk::Index< VDimension >::max_size () const inline constexpr
Definition at line 427 of file itkIndex.h.
operator*()
template<unsigned int VDimension = 2> const Self itk::Index< VDimension >::operator* (const SizeType & vec) const inline
Multiply an index by a size (elementwise product).
Definition at line 218 of file itkIndex.h.
operator+() [1/2]
template<unsigned int VDimension = 2> const Self itk::Index< VDimension >::operator+ (const OffsetType & offset) const inline
Add an offset to an index.
Definition at line 154 of file itkIndex.h.
operator+() [2/2]
template<unsigned int VDimension = 2> const Self itk::Index< VDimension >::operator+ (const SizeType & sz) const inline
Add a size to an index.
Definition at line 103 of file itkIndex.h.
operator+=() [1/2]
template<unsigned int VDimension = 2> const Self& itk::Index< VDimension >::operator+= (const OffsetType & offset) inline
Increment index by an offset.
Definition at line 167 of file itkIndex.h.
operator+=() [2/2]
template<unsigned int VDimension = 2> const Self& itk::Index< VDimension >::operator+= (const SizeType & sz) inline
Increment index by a size.
Definition at line 116 of file itkIndex.h.
operator-() [1/3]
template<unsigned int VDimension = 2> const Self itk::Index< VDimension >::operator- (const OffsetType & off) const inline
Subtract an offset from an index.
Definition at line 191 of file itkIndex.h.
operator-() [2/3]
template<unsigned int VDimension = 2> const OffsetType itk::Index< VDimension >::operator- (const Self & vec) const inline
Subtract two indices.
Definition at line 204 of file itkIndex.h.
operator-() [3/3]
template<unsigned int VDimension = 2> const Self itk::Index< VDimension >::operator- (const SizeType & sz) const inline
Subtract a size from an index.
Definition at line 129 of file itkIndex.h.
operator-=() [1/2]
template<unsigned int VDimension = 2> const Self& itk::Index< VDimension >::operator-= (const OffsetType & offset) inline
Decrement index by an offset.
Definition at line 179 of file itkIndex.h.
operator-=() [2/2]
template<unsigned int VDimension = 2> const Self& itk::Index< VDimension >::operator-= (const SizeType & sz) inline
Decrement index by a size.
Definition at line 142 of file itkIndex.h.
operator[]() [1/2]
template<unsigned int VDimension = 2> constexpr reference itk::Index< VDimension >::operator[] (size_type pos) inline constexpr
Definition at line 438 of file itkIndex.h.
operator[]() [2/2]
template<unsigned int VDimension = 2> constexpr const_reference itk::Index< VDimension >::operator[] (size_type pos) const inline constexpr
Definition at line 440 of file itkIndex.h.
rbegin() [1/2]
template<unsigned int VDimension = 2> reverse_iterator itk::Index< VDimension >::rbegin () inline
Definition at line 397 of file itkIndex.h.
rbegin() [2/2]
template<unsigned int VDimension = 2> const_reverse_iterator itk::Index< VDimension >::rbegin () const inline
Definition at line 403 of file itkIndex.h.
rend() [1/2]
template<unsigned int VDimension = 2> reverse_iterator itk::Index< VDimension >::rend () inline
Definition at line 409 of file itkIndex.h.
rend() [2/2]
template<unsigned int VDimension = 2> const_reverse_iterator itk::Index< VDimension >::rend () const inline
Definition at line 415 of file itkIndex.h.
SetElement()
template<unsigned int VDimension = 2> void itk::Index< VDimension >::SetElement (unsigned long element, IndexValueType val) inline
Sets the value of one of the elements. This method is mainly intended to facilitate the access to elements from Tcl and Python where C++ notation is not very convenient.
Warning
No bound checking is performed.
See also
SetIndex()
GetElement()
Definition at line 254 of file itkIndex.h.
SetIndex()
template<unsigned int VDimension = 2> void itk::Index< VDimension >::SetIndex (const IndexValueType val[VDimension]) inline
Set the index. Try to prototype this function so that val has to point to a block of memory that is the appropriate size.
See also
GetIndex()
Definition at line 242 of file itkIndex.h.
Referenced by itk::BoxMeanCalculatorFunction(), and itk::BoxSigmaCalculatorFunction().
size()
template<unsigned int VDimension = 2> constexpr size_type itk::Index< VDimension >::size () const inline constexpr
Definition at line 421 of file itkIndex.h.
swap()
template<unsigned int VDimension = 2> void itk::Index< VDimension >::swap (Index< VDimension > & other) inline
Definition at line 355 of file itkIndex.h.
Member Data Documentation
Dimension
template<unsigned int VDimension> constexpr unsigned int itk::Index< VDimension >::Dimension = VDimension static constexpr
Dimension constant
Definition at line 91 of file itkIndex.h.
m_InternalArray
template<unsigned int VDimension = 2> IndexValueType itk::Index< VDimension >::m_InternalArray[VDimension]
Index is an "aggregate" class. Its data is public (m_InternalArray) allowing for fast and convenient instantiations/assignments. (See main class documentation for an example of initialization)
Definition at line 293 of file itkIndex.h.
Referenced by itk::Index< Self::ImageDimension >::GetBasisIndex(), itk::Index< Self::ImageDimension >::operator-(), itk::MultiThreaderBase::ParallelizeImageRegion(), itk::Index< Self::ImageDimension >::swap(), and itk::swap().
The documentation for this struct was generated from the following file:
itkIndex.h