ITK: itk::Math::Detail::FloatIEEE< T > Union Template Reference
itk::Math::Detail::FloatIEEE< T > Union Template Reference
#include <itkMathDetail.h>
Public Types
using FloatType = T
using IntType = typename FloatIEEETraits< T >::IntType
using UIntType = typename FloatIEEETraits< T >::UIntType
Public Member Functions
IntType AsULP () const
FloatIEEE (FloatType f)
FloatIEEE (IntType i)
bool Sign () const
Public Attributes
FloatType asFloat
IntType asInt
UIntType asUInt
Detailed Description
template<typename T>
union itk::Math::Detail::FloatIEEE< T >
Definition at line 490 of file itkMathDetail.h.
Member Typedef Documentation
FloatType
template<typename T > using itk::Math::Detail::FloatIEEE< T >::FloatType = T
Definition at line 492 of file itkMathDetail.h.
IntType
template<typename T > using itk::Math::Detail::FloatIEEE< T >::IntType = typename FloatIEEETraits<T>::IntType
Definition at line 493 of file itkMathDetail.h.
UIntType
template<typename T > using itk::Math::Detail::FloatIEEE< T >::UIntType = typename FloatIEEETraits<T>::UIntType
Definition at line 494 of file itkMathDetail.h.
Constructor & Destructor Documentation
FloatIEEE() [1/2]
template<typename T > itk::Math::Detail::FloatIEEE< T >::FloatIEEE (FloatType f) inline
Definition at line 500 of file itkMathDetail.h.
FloatIEEE() [2/2]
template<typename T > itk::Math::Detail::FloatIEEE< T >::FloatIEEE (IntType i) inline
Definition at line 503 of file itkMathDetail.h.
Member Function Documentation
AsULP()
template<typename T > IntType itk::Math::Detail::FloatIEEE< T >::AsULP () const inline
Definition at line 512 of file itkMathDetail.h.
References itk::Math::Detail::FloatIEEE< T >::asInt, and itk::Math::Detail::FloatIEEE< T >::Sign().
Referenced by itk::Math::FloatDifferenceULP().
Sign()
template<typename T > bool itk::Math::Detail::FloatIEEE< T >::Sign () const inline
Definition at line 507 of file itkMathDetail.h.
References itk::Math::Detail::FloatIEEE< T >::asUInt.
Referenced by itk::Math::Detail::FloatIEEE< T >::AsULP().
Member Data Documentation
asFloat
template<typename T > FloatType itk::Math::Detail::FloatIEEE< T >::asFloat
Definition at line 496 of file itkMathDetail.h.
Referenced by itk::Math::FloatAddULP().
asInt
template<typename T > IntType itk::Math::Detail::FloatIEEE< T >::asInt
Definition at line 497 of file itkMathDetail.h.
Referenced by itk::Math::Detail::FloatIEEE< T >::AsULP(), and itk::Math::FloatAddULP().
asUInt
template<typename T > UIntType itk::Math::Detail::FloatIEEE< T >::asUInt
Definition at line 498 of file itkMathDetail.h.
Referenced by itk::Math::Detail::FloatIEEE< T >::Sign().
The documentation for this union was generated from the following file:
itkMathDetail.h